import type{PlatformModule,PlatformRole}from"./permissions";
import{currentRole}from"./permissions";

export type AuditAction="create"|"update"|"status"|"approval"|"signature"|"payment"|"document"|"export"|"access"|"security"|"system";
export type AuditEntityType="client"|"deal"|"property"|"contract"|"payment"|"approval"|"poa"|"registration"|"handover"|"warranty"|"template"|"role"|"system";
export type AuditSeverity="info"|"warning"|"critical";
export interface AuditEvent{
 id:string;at:string;actor:string;actorRole:PlatformRole;module:PlatformModule;action:AuditAction;entityType:AuditEntityType;entityId:string;entityLabel:string;route?:string;field?:string;oldValue?:string;newValue?:string;note:string;source:"user"|"system";severity:AuditSeverity;integrityRef:string;
}
export interface AuditInput{module:PlatformModule;action:AuditAction;entityType:AuditEntityType;entityId:string;entityLabel?:string;route?:string;field?:string;oldValue?:unknown;newValue?:unknown;note?:string;source?:"user"|"system";severity?:AuditSeverity;actor?:string;actorRole?:PlatformRole;at?:string}
const STORAGE="estateflowAuditTrailV55";
const ACTOR="Անի Հակոբյան";
const seed:Omit<AuditEvent,"integrityRef">[]=[
{id:"AUD-550001",at:"2026-09-23T08:58:00+04:00",actor:"Անի Հակոբյան",actorRole:"Sales Manager",module:"deals",action:"update",entityType:"deal",entityId:"DL-2026-00481",entityLabel:"DL-2026-00481 · Արման Պետրոսյան",route:"deal/DL-2026-00481",field:"Discount",oldValue:"2%",newValue:"3%",note:"Commercial terms updated before approval.",source:"user",severity:"info"},
{id:"AUD-550002",at:"2026-09-23T08:41:00+04:00",actor:"Լուսինե Մկրտչյան",actorRole:"Finance",module:"payments",action:"payment",entityType:"payment",entityId:"BNK-55021",entityLabel:"BNK-55021 · 25,000 USD",route:"reconciliation",field:"Accounting status",oldValue:"Unreviewed",newValue:"Confirmed",note:"Bank receipt matched to DL-2026-00488 and confirmed.",source:"user",severity:"info"},
{id:"AUD-550003",at:"2026-09-23T08:24:00+04:00",actor:"Անահիտ Մարտիրոսյան",actorRole:"Legal",module:"registration",action:"document",entityType:"registration",entityId:"RG-0251",entityLabel:"RG-0251 · Մարիամ Սարգսյան",route:"registration/RG-0251",field:"Additional documents",oldValue:"No active request",newValue:"Open request",note:"Registrar request for updated cadastral certificate and spouse consent is being processed.",source:"user",severity:"warning"},
{id:"AUD-550004",at:"2026-09-23T08:03:00+04:00",actor:"System",actorRole:"System Administrator",module:"tasks",action:"system",entityType:"system",entityId:"SLA",entityLabel:"SLA monitoring",route:"tasks?tab=overdue",field:"Escalation",oldValue:"L1",newValue:"L2",note:"Warranty task exceeded the configured SLA threshold.",source:"system",severity:"critical"},
{id:"AUD-550005",at:"2026-09-22T17:46:00+04:00",actor:"Վահե Խաչատրյան",actorRole:"Legal",module:"contracts",action:"update",entityType:"contract",entityId:"CT-2026-0184",entityLabel:"CT-2026-0184 · Արման Պետրոսյան",route:"contract/CT-2026-0184",field:"Handover clause",oldValue:"Standard wording",newValue:"Deviation under legal review",note:"Buyer-requested handover clause submitted for legal approval before signing.",source:"user",severity:"warning"},
{id:"AUD-550006",at:"2026-09-22T17:21:00+04:00",actor:"Անի Հակոբյան",actorRole:"Sales Manager",module:"clients",action:"update",entityType:"client",entityId:"CL-1001",entityLabel:"CL-1001 · Արման Պետրոսյան",route:"client/CL-1001",field:"KYC decision",oldValue:"Review",newValue:"Clear",note:"KYC review finalized after mandatory checks.",source:"user",severity:"info"},
{id:"AUD-550007",at:"2026-09-22T16:52:00+04:00",actor:"Commercial Office",actorRole:"Commercial Director",module:"properties",action:"status",entityType:"property",entityId:"PR-B1204",entityLabel:"Norq Residence · B-1204",route:"property/PR-B1204",field:"Property status",oldValue:"Approval",newValue:"Contract",note:"Status advanced after commercial approval.",source:"user",severity:"info"},
{id:"AUD-550008",at:"2026-09-22T16:31:00+04:00",actor:"Անի Հակոբյան",actorRole:"Sales Manager",module:"approvals",action:"approval",entityType:"approval",entityId:"AP-1001",entityLabel:"Discount approval · DL-2026-00481",route:"approvals?tab=inbox",field:"Decision",oldValue:"Pending",newValue:"Approved",note:"Approval completed within SLA.",source:"user",severity:"info"},
{id:"AUD-550009",at:"2026-09-22T15:58:00+04:00",actor:"Անահիտ Մարտիրոսյան",actorRole:"Legal",module:"legal",action:"status",entityType:"poa",entityId:"POA-2026-032",entityLabel:"POA-2026-032 · Դավիթ Գրիգորյան",route:"poa/POA-2026-032",field:"POA status",oldValue:"Active",newValue:"Suspended",note:"Authority suspended pending written confirmation from principal.",source:"user",severity:"warning"},
{id:"AUD-550010",at:"2026-09-22T15:34:00+04:00",actor:"Finance",actorRole:"Finance",module:"finance",action:"update",entityType:"payment",entityId:"SCH-469-01",entityLabel:"DL-2026-00469 · Package initial contribution",route:"payments",field:"Paid amount",oldValue:"0 AMD",newValue:"12,000,000 AMD",note:"Payment allocated across package assets.",source:"user",severity:"info"},
{id:"AUD-550011",at:"2026-09-22T14:48:00+04:00",actor:"Անահիտ Մարտիրոսյան",actorRole:"Legal",module:"registration",action:"status",entityType:"registration",entityId:"RG-0244",entityLabel:"RG-0244 · Մարիամ Սարգսյան",route:"registration/RG-0244",field:"Registration status",oldValue:"Submitted",newValue:"Registered",note:"Final state registration extract CERT-0244-2026 received.",source:"user",severity:"info"},
{id:"AUD-550012",at:"2026-09-22T14:16:00+04:00",actor:"System Administrator",actorRole:"System Administrator",module:"administration",action:"security",entityType:"role",entityId:"Sales Manager",entityLabel:"Role · Sales Manager",route:"admin/roles?role=Sales%20Manager",field:"Discount limit",oldValue:"2%",newValue:"3%",note:"Role policy updated. Previous value retained in audit trail.",source:"user",severity:"warning"},
{id:"AUD-550013",at:"2026-09-22T13:40:00+04:00",actor:"Անի Հակոբյան",actorRole:"Sales Manager",module:"contracts",action:"document",entityType:"contract",entityId:"CT-2026-0184",entityLabel:"CT-2026-0184 · Արման Պետրոսյան",route:"contract/CT-2026-0184",field:"Contract version",oldValue:"v1.0",newValue:"v1.1",note:"New working version created with change reason.",source:"user",severity:"info"},
{id:"AUD-550014",at:"2026-09-22T12:57:00+04:00",actor:"Auditor",actorRole:"Auditor",module:"reports",action:"export",entityType:"system",entityId:"REPORT-SALES",entityLabel:"Sales report",route:"reports",field:"Export",oldValue:"—",newValue:"CSV",note:"Report exported from the demo workspace.",source:"user",severity:"warning"},
{id:"AUD-550015",at:"2026-09-21T18:10:00+04:00",actor:"System",actorRole:"System Administrator",module:"legal",action:"system",entityType:"poa",entityId:"POA-2026-039",entityLabel:"POA-2026-039 · Արարատ Դեվելոփմենթ ՍՊԸ",route:"poa/POA-2026-039",field:"Validity",oldValue:"Active",newValue:"Expiring",note:"Automatic expiry warning created.",source:"system",severity:"warning"},
{id:"AUD-550016",at:"2026-09-21T16:44:00+04:00",actor:"Անի Հակոբյան",actorRole:"Sales Manager",module:"deals",action:"create",entityType:"deal",entityId:"DL-2026-00488",entityLabel:"DL-2026-00488 · Caspian Holdings LLC",route:"deal/DL-2026-00488",field:"Deal",oldValue:"—",newValue:"Created",note:"USD installment transaction created.",source:"user",severity:"info"}
];
function text(v:unknown){if(v===undefined||v===null||v==="")return undefined;return typeof v==="string"?v:JSON.stringify(v)}
function checksum(raw:string){let h=2166136261;for(let i=0;i<raw.length;i++){h^=raw.charCodeAt(i);h=Math.imul(h,16777619)}return (h>>>0).toString(16).toUpperCase().padStart(8,"0")}
function seal(e:Omit<AuditEvent,"integrityRef">):AuditEvent{return{...e,integrityRef:`EF-${checksum([e.id,e.at,e.actor,e.module,e.action,e.entityType,e.entityId,e.field,e.oldValue,e.newValue,e.note].join("|"))}`}}
function load():AuditEvent[]{try{const raw=localStorage.getItem(STORAGE);if(raw){const parsed=JSON.parse(raw) as AuditEvent[];if(Array.isArray(parsed))return parsed}}catch{}const data=seed.map(seal);localStorage.setItem(STORAGE,JSON.stringify(data));return data}
function save(events:AuditEvent[]){localStorage.setItem(STORAGE,JSON.stringify(events))}
export function ensureAuditInitialized(){load()}
export function auditEvents(){return load().slice().sort((a,b)=>Date.parse(b.at)-Date.parse(a.at))}
export function auditForEntity(entityType:AuditEntityType,entityId:string){return auditEvents().filter(e=>e.entityType===entityType&&e.entityId===entityId)}
export function auditForRoute(route:string){return auditEvents().filter(e=>e.route===route)}
export function recordAudit(input:AuditInput){const at=input.at??new Date().toISOString(),role=input.actorRole??currentRole();const id=`AUD-${Date.now()}-${Math.floor(Math.random()*900+100)}`;const e=seal({id,at,actor:input.actor??ACTOR,actorRole:role,module:input.module,action:input.action,entityType:input.entityType,entityId:input.entityId,entityLabel:input.entityLabel??input.entityId,route:input.route,field:input.field,oldValue:text(input.oldValue),newValue:text(input.newValue),note:input.note??"",source:input.source??"user",severity:input.severity??"info"});const all=load();all.push(e);save(all);return e}
export function auditStats(){const all=auditEvents(),today="2026-09-23";return{total:all.length,today:all.filter(e=>e.at.startsWith(today)).length,critical:all.filter(e=>e.severity==="critical").length,changes:all.filter(e=>e.oldValue!==undefined||e.newValue!==undefined).length,exports:all.filter(e=>e.action==="export").length,system:all.filter(e=>e.source==="system").length}}
export function auditActors(){return[...new Set(auditEvents().map(e=>e.actor))].sort()}
