import type{NotificationCategory,NotificationSeverity,PlatformNotification}from"../models/types";
import{approvals,deals,handoverCases,legalCases,paymentSchedule,powersOfAttorney,registrationCases,warrantyCases}from"../data/mock";
import{ensureTasksInitialized,tasks}from"./tasks";
import{t}from"../i18n";

export const NOTIFICATION_REFERENCE_NOW="2026-09-23T09:14:00+04:00";
export const notifications:PlatformNotification[]=[];
let initialized=false;
const now=()=>new Date(NOTIFICATION_REFERENCE_NOW);
const stamp=()=>NOTIFICATION_REFERENCE_NOW;
const iso=(hour:number,minute=0)=>`2026-09-23T${String(hour).padStart(2,"0")}:${String(minute).padStart(2,"0")}:00+04:00`;
const localRoles=(roles:string[])=>[...new Set(roles.map(x=>["Handover","Service","Mortgage"].includes(x)?"Sales Manager":x))];
const amount=(v:number,currency="AMD")=>`${new Intl.NumberFormat("ru-RU",{maximumFractionDigits:currency==="AMD"?0:2}).format(v)} ${currency}`;

function upsert(sourceKey:string,data:Omit<PlatformNotification,"id"|"sourceKey">){
 const existing=notifications.find(x=>x.sourceKey===sourceKey);
 if(existing){const state={readAt:existing.readAt,snoozedUntil:existing.snoozedUntil,archivedAt:existing.archivedAt};Object.assign(existing,data,state,{resolvedAt:undefined});return existing}
 const item:PlatformNotification={id:`NT-${String(notifications.length+1).padStart(4,"0")}`,sourceKey,...data};notifications.push(item);return item
}
function touch(active:Set<string>,key:string,data:Omit<PlatformNotification,"id"|"sourceKey">){active.add(key);upsert(key,data)}

export function syncNotifications(){
 ensureTasksInitialized();const active=new Set<string>();
 approvals.filter(a=>a.status==="pending").forEach((a,i)=>{const overdue=Boolean(a.slaDueAt&&new Date(a.slaDueAt).getTime()<now().getTime());touch(active,`approval:${a.id}`,{category:"approval",severity:overdue||a.priority==="critical"?"critical":"warning",title:t("v53.generated.approvalTitle",{id:a.id}),description:t("v53.generated.approvalBody",{client:a.clientName,role:a.requiredRole??"Sales Head",value:a.requestedValue}),createdAt:iso(10+i,12+i*7),targetRoles:localRoles([a.requiredRole??"Sales Head","CEO"]),sourceRoute:"approvals?tab=inbox",sourceLabel:a.id,dealId:a.dealId,clientName:a.clientName,propertyLabel:a.propertyLabel,meta:[a.reason,a.triggerSummary??""] .filter(Boolean)})});
 paymentSchedule.filter(p=>p.status==="overdue"||p.status==="partial").forEach((p,i)=>{const d=deals.find(x=>x.id===p.dealId),outstanding=Math.max(0,p.amount-p.paid);touch(active,`payment:${p.id}`,{category:"payment",severity:p.status==="overdue"?"critical":"warning",title:t(p.status==="overdue"?"v53.generated.paymentOverdueTitle":"v53.generated.paymentPartialTitle",{deal:p.dealId}),description:t("v53.generated.paymentBody",{client:d?.clientName??p.dealId,amount:amount(outstanding,p.currency??d?.currency??"AMD"),date:p.dueDate}),createdAt:iso(9+i,5+i*11),targetRoles:["Finance","Financial Director","Sales Manager","CEO"],sourceRoute:`deal/${p.dealId}`,sourceLabel:p.id,dealId:p.dealId,clientName:d?.clientName,propertyLabel:d?.propertyLabel,meta:[p.title]})});
 powersOfAttorney.filter(p=>p.status==="expiring"||p.status==="suspended").forEach((p,i)=>touch(active,`poa:${p.id}:${p.status}`,{category:"legal",severity:p.status==="suspended"?"critical":"warning",title:t(p.status==="suspended"?"v53.generated.poaSuspendedTitle":"v53.generated.poaExpiringTitle",{id:p.id}),description:t("v53.generated.poaBody",{principal:p.principal,representative:p.representative,date:p.expiresAt}),createdAt:iso(11+i,18+i*9),targetRoles:["Legal","Sales Manager","CEO"],sourceRoute:`poa/${p.id}`,sourceLabel:p.id,dealId:p.relatedDeal,clientName:p.principal,meta:[p.scope]}));
 legalCases.filter(c=>c.status!=="clear").forEach((c,i)=>touch(active,`legal:${c.id}:${c.status}`,{category:"legal",severity:c.status==="blocked"||String(c.risk).toLowerCase()==="high"?"critical":"warning",title:t(c.status==="blocked"?"v53.generated.legalBlockedTitle":"v53.generated.legalReviewTitle",{id:c.id}),description:t("v53.generated.legalBody",{client:c.clientName,risk:c.risk}),createdAt:iso(12+i,8+i*6),targetRoles:["Legal","Sales Manager","CEO"],sourceRoute:"legal",sourceLabel:c.id,dealId:c.dealId,clientName:c.clientName,meta:[c.type,c.decisionNote??""] .filter(Boolean)}));
 registrationCases.filter(r=>r.status==="additional-documents"||r.status==="rejected").forEach((r,i)=>touch(active,`registration:${r.id}:${r.status}`,{category:"registration",severity:"critical",title:t(r.status==="rejected"?"v53.generated.registrationRejectedTitle":"v53.generated.registrationDocsTitle",{id:r.id}),description:t("v53.generated.registrationBody",{client:r.clientName,property:r.propertyLabel}),createdAt:iso(13+i,22+i*4),targetRoles:["Legal","Sales Manager","CEO"],sourceRoute:`registration/${r.id}`,sourceLabel:r.id,dealId:r.dealId,clientName:r.clientName,propertyLabel:r.propertyLabel,meta:[r.rejectionReason??"",r.additionalRequests?.find(x=>x.status==="open")?.items.join(", ")??""] .filter(Boolean)}));
 handoverCases.filter(h=>h.status==="defects"||h.clientAcceptance==="declined").forEach((h,i)=>touch(active,`handover:${h.id}:${h.status}:${h.clientAcceptance??"pending"}`,{category:"handover",severity:h.clientAcceptance==="declined"?"critical":"warning",title:t(h.clientAcceptance==="declined"?"v53.generated.handoverRejectedTitle":"v53.generated.handoverDefectsTitle",{id:h.id}),description:t("v53.generated.handoverBody",{client:h.clientName,property:h.propertyLabel}),createdAt:iso(14+i,10+i*5),targetRoles:["Sales Manager","CEO"],sourceRoute:`handover-case/${h.id}`,sourceLabel:h.id,dealId:h.dealId,clientName:h.clientName,propertyLabel:h.propertyLabel,meta:[`${h.technicalReadiness}%`] }));
 warrantyCases.filter(w=>w.status==="waiting-client").forEach((w,i)=>touch(active,`service:${w.id}:waiting-client`,{category:"service",severity:"warning",title:t("v53.generated.serviceWaitingTitle",{id:w.id}),description:t("v53.generated.serviceWaitingBody",{client:w.clientName,property:w.propertyLabel}),createdAt:iso(15+i,4+i*5),targetRoles:["Sales Manager","CEO"],sourceRoute:`warranty/${w.id}`,sourceLabel:w.id,clientName:w.clientName,propertyLabel:w.propertyLabel,meta:[w.title,w.contractor]}));
 warrantyCases.filter(w=>(w.escalationLevel??0)>0).forEach((w,i)=>touch(active,`sla:warranty:${w.id}`,{category:"sla",severity:"critical",title:t("v53.generated.slaWarrantyTitle",{id:w.id,level:String(w.escalationLevel??1)}),description:t("v53.generated.slaWarrantyBody",{client:w.clientName,due:w.dueAt}),createdAt:iso(16+i,2+i*3),targetRoles:["Sales Manager","CEO"],sourceRoute:`warranty/${w.id}`,sourceLabel:w.id,clientName:w.clientName,propertyLabel:w.propertyLabel,meta:[w.escalationReason??w.title]}));
 tasks.filter(x=>x.escalated&&!['warranty','registration'].includes(x.sourceType)&&!["done","cancelled"].includes(x.status)).slice(0,4).forEach((x,i)=>touch(active,`sla:task:${x.id}`,{category:"sla",severity:x.priority==="critical"?"critical":"warning",title:t("v53.generated.slaTaskTitle",{id:x.id}),description:t("v53.generated.slaTaskBody",{title:x.title,owner:x.assignedTo}),createdAt:iso(16,20+i*6),targetRoles:localRoles([x.assignedRole,"CEO"]),sourceRoute:x.sourceRoute??"tasks?tab=overdue",sourceLabel:x.id,dealId:x.dealId,clientName:x.clientName,propertyLabel:x.propertyLabel,meta:[x.description]}));
 notifications.forEach(n=>{if(!active.has(n.sourceKey)&&!n.resolvedAt){n.resolvedAt=stamp();n.readAt=n.readAt??stamp();n.archivedAt=n.archivedAt??stamp()}});
 notifications.sort((a,b)=>new Date(b.createdAt).getTime()-new Date(a.createdAt).getTime());
}
export function ensureNotificationsInitialized(){if(!initialized)initialized=true;syncNotifications()}
export function isNotificationSnoozed(n:PlatformNotification){return Boolean(n.snoozedUntil&&new Date(n.snoozedUntil).getTime()>now().getTime())}
export function notificationsForRole(role:string,includeArchived=true){ensureNotificationsInitialized();return notifications.filter(n=>(!n.targetRoles.length||n.targetRoles.includes(role)||role==="CEO")&&(includeArchived||!n.archivedAt))}
export function markNotificationRead(id:string,read=true){const n=notifications.find(x=>x.id===id);if(!n)return;n.readAt=read?stamp():undefined;return n}
export function markAllNotificationsRead(role:string){notificationsForRole(role,false).filter(n=>!isNotificationSnoozed(n)).forEach(n=>n.readAt=n.readAt??stamp())}
export function archiveNotification(id:string){const n=notifications.find(x=>x.id===id);if(!n)return;n.archivedAt=stamp();n.readAt=n.readAt??stamp();return n}
export function restoreNotification(id:string){const n=notifications.find(x=>x.id===id);if(!n)return;n.archivedAt=undefined;return n}
export function snoozeNotification(id:string,until:string){const n=notifications.find(x=>x.id===id);if(!n)return;n.snoozedUntil=until;n.readAt=n.readAt??stamp();return n}
export function clearNotificationSnooze(id:string){const n=notifications.find(x=>x.id===id);if(!n)return;n.snoozedUntil=undefined;return n}
export function notificationStats(role:string){const rows=notificationsForRole(role,true),active=rows.filter(n=>!n.archivedAt&&!n.resolvedAt),unsnoozed=active.filter(n=>!isNotificationSnoozed(n));return{total:active.length,unread:unsnoozed.filter(n=>!n.readAt).length,critical:unsnoozed.filter(n=>n.severity==="critical").length,snoozed:active.filter(isNotificationSnoozed).length,archived:rows.filter(n=>n.archivedAt).length}}
export function notificationCategoryStats(role:string){const rows=notificationsForRole(role,false).filter(n=>!n.resolvedAt&&!isNotificationSnoozed(n));return(["approval","payment","legal","registration","handover","service","sla"] as NotificationCategory[]).map(category=>({category,count:rows.filter(n=>n.category===category).length,unread:rows.filter(n=>n.category===category&&!n.readAt).length,critical:rows.filter(n=>n.category===category&&n.severity==="critical").length}))}
