import {approvals,contracts,deals,handoverCases,legalCases,paymentSchedule,registrationCases,warrantyCases} from "../data/mock";
import type{TaskCategory,TaskPriority,TaskStatus,WorkTask}from"../models/types";
import {ensureWorkflowInitialized}from"./workflow";

export const TASK_REFERENCE_NOW="2026-09-23T09:14:00+04:00";
export const taskNow=()=>new Date(TASK_REFERENCE_NOW);
const owners:Record<string,string>={
  "Sales Manager":"Անի Հակոբյան","Sales Head":"Արթուր Սարգսյան","Commercial Director":"Գագիկ Մանուկյան",Legal:"Անահիտ Մարտիրոսյան",Finance:"Լուսինե Մկրտչյան","Financial Director":"Վահե Խաչատրյան",CEO:"Տիգրան Հարությունյան",Handover:"Լուսինե Աբրահամյան",Service:"Սերվիս թիմ"
};
export const taskOwnerForRole=(role:string)=>owners[role]??role;
const event=(actor:string,action:WorkTask["history"][number]["action"],note:string,at=TASK_REFERENCE_NOW)=>({id:`TE-${Date.now()}-${Math.random().toString(36).slice(2,7)}`,at,actor,action,note});
const taskId=()=>`TSK-2026-${String(120+tasks.length+1).padStart(4,"0")}`;
const iso=(day:number,hour:number,minute=0)=>`2026-09-${String(day).padStart(2,"0")}T${String(hour).padStart(2,"0")}:${String(minute).padStart(2,"0")}:00+04:00`;

export const tasks:WorkTask[]=[
 {id:"TSK-2026-0118",title:"Подготовить пакет объектов для клиента",description:"Собрать 2–3 варианта недвижимости и подготовить сравнение условий для Narek Sahakyan.",category:"sales",sourceType:"lead",sourceId:"LD-26062",sourceLabel:"LD-26062 · Narek Sahakyan",sourceRoute:"lead/LD-26062",clientName:"Narek Sahakyan",assignedTo:"Անի Հակոբյան",assignedRole:"Sales Manager",backupOwner:"Նարեկ Կարապետյան",createdBy:"Անի Հակոբյան",createdAt:iso(22,9,10),dueAt:iso(22,17,30),priority:"high",status:"in-progress",slaHours:8,escalated:false,reminderAt:iso(22,17,0),tags:["Lead","Offer"],history:[event("Անի Հակոբյան","started","Задача взята в работу",iso(22,10,15)),event("System","created","Создано из следующего действия лида",iso(22,9,10))]},
 {id:"TSK-2026-0119",title:"Получить ответ по коммерческому предложению",description:"Связаться с клиентом, зафиксировать решение и при принятии перейти к бронированию.",category:"sales",sourceType:"lead",sourceId:"LD-26079",sourceLabel:"LD-26079 · Սամվել Ավետիսյան",sourceRoute:"lead/LD-26079",clientName:"Սամվել Ավետիսյան",assignedTo:"Անի Հակոբյան",assignedRole:"Sales Manager",backupOwner:"Մարի Հովհաննիսյան",createdBy:"System",createdAt:iso(21,16,10),dueAt:iso(23,11,0),priority:"normal",status:"open",slaHours:24,escalated:false,tags:["Lead","Follow-up"],history:[event("System","created","Создано по следующему действию лида",iso(21,16,10))]},
 {id:"TSK-2026-0120",title:"Подтвердить пакет документов по сделке",description:"Проверить комплект обязательных документов и закрыть замечания до подготовки договора.",category:"legal",sourceType:"deal",sourceId:"DL-2026-00481",sourceLabel:"DL-2026-00481",sourceRoute:"deal/DL-2026-00481",dealId:"DL-2026-00481",clientName:"Արման Պետրոսյան",propertyLabel:"B-1204",assignedTo:"Անահիտ Մարտիրոսյան",assignedRole:"Legal",backupOwner:"Վահե Խաչատրյան",createdBy:"System",createdAt:iso(22,8,30),dueAt:iso(22,15,30),priority:"high",status:"waiting",slaHours:7,escalated:true,escalationLevel:1,tags:["Deal","Documents"],history:[event("System","escalated","Срок выполнения превышен; руководитель юридического блока уведомлен",iso(22,15,35)),event("Անահիտ Մարտիրոսյան","comment","Ожидается подтверждение по нестандартному условию договора",iso(22,11,45)),event("System","created","Задача создана из контрольной точки сделки",iso(22,8,30))]},
 {id:"TSK-2026-0121",title:"Сверить поступление по пакетной сделке",description:"Проверить частичный платеж и распределение по квартире, парковке и кладовой.",category:"payment",sourceType:"payment",sourceId:"SCH-469-01",sourceLabel:"DL-2026-00469 · платеж",sourceRoute:"deal/DL-2026-00469",dealId:"DL-2026-00469",clientName:"Արարատ Դեվելոփմենթ ՍՊԸ",propertyLabel:"B-1206 + P-043 + S-118",assignedTo:"Լուսինե Մկրտչյան",assignedRole:"Finance",backupOwner:"Սիրանուշ Ավագյան",createdBy:"System",createdAt:iso(21,10,0),dueAt:iso(22,14,0),priority:"critical",status:"open",slaHours:28,escalated:true,escalationLevel:2,tags:["Payment","Package deal","source:payment:SCH-469-01"],history:[event("System","escalated","Вторая линия эскалации: задача просрочена",iso(22,15,0)),event("System","created","Создано по частично оплаченному этапу графика",iso(21,10,0))]}
];

let initialized=false;
function parseLegacyDate(value:string,fallbackHour=17){
 const m=value.match(/(\d{1,2})\.(\d{1,2})\.(\d{4})(?:\s*[· ]\s*(\d{1,2}):(\d{2}))?/);if(!m)return iso(23,fallbackHour);
 return `${m[3]}-${m[2].padStart(2,"0")}-${m[1].padStart(2,"0")}T${(m[4]??String(fallbackHour)).padStart(2,"0")}:${(m[5]??"00").padStart(2,"0")}:00`;
}
function addProcessTask(key:string,data:Omit<WorkTask,"id"|"history">&{createdNote?:string}){
 const found=tasks.find(t=>t.tags?.includes(`source:${key}`));if(found)return found;
 const created:WorkTask={...data,id:taskId(),tags:[...(data.tags??[]),`source:${key}`],history:[event("System","created",data.createdNote??"Создано автоматически из процесса",data.createdAt)]};tasks.push(created);return created;
}
function finishMissing(activeKeys:Set<string>){
 tasks.filter(t=>t.tags?.some(x=>x.startsWith("source:"))&&!activeKeys.has(t.tags!.find(x=>x.startsWith("source:"))!.slice(7))&&!['done','cancelled'].includes(t.status)).forEach(t=>{t.status="done";t.history.unshift(event("System","completed","Связанный процесс завершен"))});
}
export function syncProcessTasks(){
 ensureWorkflowInitialized();const active=new Set<string>();
 approvals.filter(a=>a.status==="pending").forEach(a=>{const key=`approval:${a.id}`;active.add(key);addProcessTask(key,{title:`Согласовать: ${a.clientName}`,description:`${a.reason}. ${a.requestedValue} · стандарт ${a.limitValue}.`,category:"approval",sourceType:"approval",sourceId:a.id,sourceLabel:`${a.id} · ${a.dealId}`,sourceRoute:"approvals?tab=inbox",dealId:a.dealId,clientName:a.clientName,propertyLabel:a.propertyLabel,assignedTo:taskOwnerForRole(a.requiredRole??"Sales Head"),assignedRole:a.requiredRole??"Sales Head",backupOwner:a.requiredRole==="Legal"?"Վահե Խաչատրյան":"Անի Հակոբյան",createdBy:a.requestedBy,createdAt:TASK_REFERENCE_NOW,dueAt:a.slaDueAt??iso(23,12),priority:a.priority??"normal",status:"open",slaHours:8,escalated:Boolean(a.slaDueAt&&new Date(a.slaDueAt).getTime()<taskNow().getTime()),escalationLevel:a.slaDueAt&&new Date(a.slaDueAt).getTime()<taskNow().getTime()?1:undefined,tags:["Approval",a.type],createdNote:`Создано из шага согласования ${a.id}`})});
 contracts.filter(c=>!["signed","registered"].includes(c.status)).forEach(c=>{const key=`contract:${c.id}:${c.status}`;active.add(key);const isLegal=c.status==="legal-review",isSignature=c.status==="signature";addProcessTask(key,{title:isLegal?`Проверить договор ${c.id}`:isSignature?`Организовать подписание ${c.id}`:`Продвинуть договор ${c.id}`,description:`${c.clientName} · ${c.propertyLabel} · текущий статус: ${c.status}.`,category:"contract",sourceType:"contract",sourceId:c.id,sourceLabel:`${c.id} · ${c.clientName}`,sourceRoute:`contract/${c.id}`,dealId:c.dealId,clientName:c.clientName,propertyLabel:c.propertyLabel,assignedTo:c.owner,assignedRole:isLegal?"Legal":"Sales Manager",backupOwner:isLegal?"Վահե Խաչատրյան":"Նարեկ Կարապետյան",createdBy:"System",createdAt:iso(22,9,0),dueAt:isLegal?iso(22,18,0):isSignature?iso(22,17,45):iso(23,12,0),priority:c.nonStandardClauses?"high":"normal",status:"open",slaHours:isLegal?9:24,escalated:false,tags:["Contract",c.status],createdNote:"Создано из текущей стадии договора"})});
 paymentSchedule.filter(p=>p.status==="overdue"||p.status==="partial").forEach(p=>{const d=deals.find(x=>x.id===p.dealId);const key=`payment:${p.id}`;active.add(key);addProcessTask(key,{title:p.status==="overdue"?`Отработать просроченный платеж ${p.dealId}`:`Сверить частичный платеж ${p.dealId}`,description:`${p.title}: ${Math.max(0,p.amount-p.paid).toLocaleString("ru-RU")} AMD остается к оплате.`,category:"payment",sourceType:"payment",sourceId:p.id,sourceLabel:`${p.id} · ${p.dealId}`,sourceRoute:`deal/${p.dealId}`,dealId:p.dealId,clientName:d?.clientName,propertyLabel:d?.propertyLabel,assignedTo:"Լուսինե Մկրտչյան",assignedRole:"Finance",backupOwner:"Սիրանուշ Ավագյան",createdBy:"System",createdAt:iso(22,8,0),dueAt:iso(22,13,30),priority:p.status==="overdue"?"critical":"high",status:"open",slaHours:6,escalated:p.status==="overdue",escalationLevel:p.status==="overdue"?1:undefined,tags:["Payment",p.status],createdNote:"Создано из контроля графика платежей"})});
 legalCases.filter(c=>c.status!=="clear").forEach(c=>{const key=`legal:${c.id}:${c.status}`;active.add(key);addProcessTask(key,{title:c.status==="blocked"?`Снять юридическую блокировку ${c.id}`:`Завершить юридическую проверку ${c.id}`,description:`${c.clientName} · ${c.type}. Риск: ${c.risk}.`,category:"legal",sourceType:"legal",sourceId:c.id,sourceLabel:`${c.id} · ${c.dealId}`,sourceRoute:"legal",dealId:c.dealId,clientName:c.clientName,assignedTo:c.owner,assignedRole:"Legal",backupOwner:"Վահե Խաչատրյան",createdBy:"System",createdAt:iso(22,9,0),dueAt:c.status==="blocked"?iso(22,14,30):iso(23,10,0),priority:c.status==="blocked"?"critical":"high",status:"open",slaHours:c.status==="blocked"?5:24,escalated:c.status==="blocked",escalationLevel:c.status==="blocked"?1:undefined,tags:["Legal",c.status],createdNote:"Создано из юридической проверки"})});
 registrationCases.filter(r=>r.status!=="registered").forEach(r=>{const key=`registration:${r.id}:${r.status}`;active.add(key);const due=parseLegacyDate(r.plannedAt,15);const title=r.status==="submitted"?`Проверить результат регистрации ${r.id}`:r.status==="notary"?`Провести нотариальный этап ${r.id}`:r.status==="additional-documents"?`Получить дополнительные документы ${r.id}`:r.status==="rejected"?`Подготовить повторную подачу ${r.id}`:`Подготовить пакет на регистрацию ${r.id}`;const critical=r.status==="rejected"||r.status==="additional-documents";addProcessTask(key,{title,description:`${r.clientName} · ${r.propertyLabel} · ${r.notary}.`,category:"registration",sourceType:"registration",sourceId:r.id,sourceLabel:`${r.id} · ${r.contractId}`,sourceRoute:`registration/${r.id}`,dealId:r.dealId,clientName:r.clientName,propertyLabel:r.propertyLabel,assignedTo:r.owner??"Անահիտ Մարտիրոսյան",assignedRole:"Legal",backupOwner:"Վահե Խաչատրյան",createdBy:"System",createdAt:iso(21,9,0),dueAt:due,priority:critical?"critical":r.status==="submitted"?"high":"normal",status:"open",slaHours:critical?8:24,escalated:critical||new Date(due).getTime()<taskNow().getTime(),escalationLevel:critical||new Date(due).getTime()<taskNow().getTime()?1:undefined,tags:["Registration",r.status],createdNote:"Создано из этапа государственной регистрации"})});
 handoverCases.filter(h=>h.status!=="handed-over").forEach(h=>{const key=`handover:${h.id}:${h.status}`;active.add(key);const due=parseLegacyDate(h.plannedAt,16);addProcessTask(key,{title:h.status==="defects"?`Координировать устранение дефектов ${h.id}`:`Подготовить объект к передаче ${h.id}`,description:`${h.clientName} · ${h.propertyLabel} · готовность ${h.technicalReadiness}%.`,category:"handover",sourceType:"handover",sourceId:h.id,sourceLabel:`${h.id} · ${h.propertyLabel}`,sourceRoute:`handover-case/${h.id}`,dealId:h.dealId,clientName:h.clientName,propertyLabel:h.propertyLabel,assignedTo:h.coordinator,assignedRole:"Handover",backupOwner:"Գոռ Մելիքյան",createdBy:"System",createdAt:iso(21,10,0),dueAt:due,priority:h.status==="defects"?"high":"normal",status:"open",slaHours:24,escalated:new Date(due).getTime()<taskNow().getTime(),escalationLevel:new Date(due).getTime()<taskNow().getTime()?1:undefined,tags:["Handover",h.status],createdNote:"Создано из процесса передачи объекта"})});
 warrantyCases.filter(w=>!["resolved","closed"].includes(w.status)).forEach(w=>{const key=`warranty:${w.id}:${w.status}`;active.add(key);const due=parseLegacyDate(w.dueAt,18);const overdue=new Date(due).getTime()<taskNow().getTime();const escalationLevel=Math.max(w.escalationLevel??0,overdue?1:0);addProcessTask(key,{title:`Сервисное обращение ${w.id}: ${w.title}`,description:`${w.clientName} · ${w.propertyLabel} · подрядчик ${w.contractor}.`,category:"service",sourceType:"warranty",sourceId:w.id,sourceLabel:`${w.id} · ${w.category}`,sourceRoute:`warranty/${w.id}`,clientName:w.clientName,propertyLabel:w.propertyLabel,assignedTo:w.owner,assignedRole:"Service",backupOwner:"Սերվիս թիմ",createdBy:"System",createdAt:parseLegacyDate(w.createdAt,9),dueAt:due,priority:w.priority==="urgent"?"critical":w.priority==="high"?"high":w.priority==="medium"?"normal":"low",status:w.status==="waiting-client"?"waiting":w.status==="in-progress"?"in-progress":"open",slaHours:w.slaHours,escalated:escalationLevel>0,escalationLevel:escalationLevel||undefined,tags:["Warranty",w.category],createdNote:"Создано из гарантийного обращения"})});
 finishMissing(active);
}
export function ensureTasksInitialized(){if(!initialized){initialized=true}syncProcessTasks()}
export function getTask(id:string){ensureTasksInitialized();return tasks.find(t=>t.id===id)}
export function setTaskStatus(id:string,status:TaskStatus,actor:string,note:string){const t=tasks.find(x=>x.id===id);if(!t)return;t.status=status;const action=status==="in-progress"?"started":status==="done"?"completed":status==="open"?"reopened":"comment";t.history.unshift(event(actor,action,note));return t}
export function reassignTask(id:string,assignedTo:string,assignedRole:string,actor:string,note:string,backupOwner?:string){const t=tasks.find(x=>x.id===id);if(!t)return;const old=`${t.assignedTo} / ${t.assignedRole}`;t.assignedTo=assignedTo;t.assignedRole=assignedRole;t.backupOwner=backupOwner||t.backupOwner;t.history.unshift(event(actor,"reassigned",`${old} → ${assignedTo} / ${assignedRole}${note?` · ${note}`:""}`));return t}
export function deferTask(id:string,dueAt:string,actor:string,note:string){const t=tasks.find(x=>x.id===id);if(!t)return;const old=t.dueAt;t.dueAt=dueAt;t.escalated=false;t.escalationLevel=undefined;t.history.unshift(event(actor,"deferred",`${old} → ${dueAt}${note?` · ${note}`:""}`));return t}
export function escalateTask(id:string,actor:string,note:string){const t=tasks.find(x=>x.id===id);if(!t)return;t.escalated=true;t.escalationLevel=(t.escalationLevel??0)+1;t.priority=t.escalationLevel>=2?"critical":t.priority==="low"?"normal":"high";t.history.unshift(event(actor,"escalated",note||`Эскалация уровня ${t.escalationLevel}`));return t}
export function setTaskReminder(id:string,reminderAt:string,actor:string){const t=tasks.find(x=>x.id===id);if(!t)return;t.reminderAt=reminderAt;t.history.unshift(event(actor,"reminder",`Напоминание: ${reminderAt}`));return t}
export function addTask(data:{title:string;description:string;category:TaskCategory;dueAt:string;priority:TaskPriority;assignedTo:string;assignedRole:string;backupOwner?:string;sourceRoute?:string;clientName?:string;dealId?:string}){const t:WorkTask={id:taskId(),title:data.title,description:data.description,category:data.category,sourceType:"manual",sourceLabel:"Manual task",sourceRoute:data.sourceRoute,dealId:data.dealId,clientName:data.clientName,assignedTo:data.assignedTo,assignedRole:data.assignedRole,backupOwner:data.backupOwner,createdBy:"Անի Հակոբյան",createdAt:TASK_REFERENCE_NOW,dueAt:data.dueAt,priority:data.priority,status:"open",escalated:false,tags:["Manual"],history:[event("Անի Հակոբյան","created","Задача создана вручную")]};tasks.unshift(t);return t}
export function taskStats(){ensureTasksInitialized();const active=tasks.filter(t=>!["done","cancelled"].includes(t.status)),now=taskNow(),day=TASK_REFERENCE_NOW.slice(0,10);return{active:active.length,today:active.filter(t=>t.dueAt.slice(0,10)===day).length,overdue:active.filter(t=>new Date(t.dueAt).getTime()<now.getTime()).length,escalated:active.filter(t=>t.escalated).length,done:tasks.filter(t=>t.status==="done").length}}
