import{closeModal,openLocalizedModal,toastLocalized}from"../components/layout";
import{currentRoute,navigate}from"../router";
import{t}from"../i18n";
import{actionLabelKey,canAction,currentRole,getRolePolicy,landingRoute,moduleLabelKey,moduleStats,permissionActions,platformModules,platformRoles,resetRolePolicy,roleLabelKey,setActionPermission,setCurrentRole,setDiscountLimit,setModuleAccess,type AccessLevel,type PermissionAction,type PlatformModule,type PlatformRole}from"../services/permissions";
import{recordAudit}from"../services/audit";

const levels:AccessLevel[]=["none","view","edit","manage"];
const selectedRole=():PlatformRole=>{const m=currentRoute().match(/[?&]role=([^&]+)/);const role=decodeURIComponent(m?.[1]??currentRole()) as PlatformRole;return platformRoles.includes(role)?role:currentRole()};
const label=(role:PlatformRole)=>t(roleLabelKey(role));
const levelLabel=(level:AccessLevel)=>t(`v54.access.${level}`);
const departmentLabel=(value:string)=>t(`v54.department.${value}`);
const actionGroups:[string,PermissionAction[]][]=[
  ["v54.group.client",["client.personal","client.financial","client.kyc","client.merge"]],
  ["v54.group.commercial",["property.price","property.status","deal.discount","deal.stage"]],
  ["v54.group.approvals",["approval.decide","approval.reassign","approval.rules"]],
  ["v54.group.contractLegal",["contract.edit","contract.templates","contract.sign","legal.review","legal.poa"]],
  ["v54.group.finance",["finance.payment","finance.bank-confirm","finance.fx","finance.security","finance.schedule","mortgage.manage"]],
  ["v54.group.operations",["registration.manage","handover.manage","service.manage","task.manage","task.reassign"]],
  ["v54.group.control",["report.export","admin.roles","data.export"]]
];

export function adminRolesPage(){
  const role=selectedRole(),p=getRolePolicy(role),stats=moduleStats(role),editable=canAction("admin.roles");
  const accessible=platformModules.filter(m=>p.modules[m]!=="none");
  return`<section class="page permissions-page">
    <div class="page-header"><div class="page-title"><div class="eyebrow">${t("v54.eyebrow")}</div><h1>${t("v54.title")}</h1><p>${t("v54.subtitle")}</p></div><div class="toolbar"><span class="permission-mode-chip ${editable?"manage":"readonly"}"><i>${editable?"✓":"◉"}</i><span><small>${t("v54.currentMode")}</small><strong>${editable?t("v54.manageMode"):t("v54.readonlyMode")}</strong></span></span><button class="btn" id="permissionExplain">${t("v54.howItWorks")}</button></div></div>
    <div class="permissions-kpis">${metric(t("v54.kpi.modules"),stats.accessible,t("v54.kpi.modulesSub"),"module")}${metric(t("v54.kpi.editable"),stats.editable,t("v54.kpi.editableSub"),"edit")}${metric(t("v54.kpi.managed"),stats.managed,t("v54.kpi.managedSub"),"manage")}${metric(t("v54.kpi.actions"),stats.elevated,t("v54.kpi.actionsSub"),"action")}</div>
    <div class="permissions-layout">
      <aside class="card role-catalog"><div class="role-catalog-head"><span>${t("v54.roles")}</span><small>${platformRoles.length}</small></div><div class="role-catalog-list">${platformRoles.map(r=>roleCard(r,role)).join("")}</div></aside>
      <div class="permissions-workspace">
        <div class="card role-hero"><div class="role-hero-main"><div class="role-avatar ${p.department}">${initials(label(role))}</div><div><span class="role-department">${departmentLabel(p.department)}</span><h2>${label(role)}</h2><p>${t(p.descriptionKey)}</p></div></div><div class="role-hero-actions"><button class="btn" id="previewRole">${t("v54.previewAsRole")}</button>${editable?`<button class="btn btn-danger-soft" id="resetRole">${t("v54.resetRole")}</button>`:""}</div></div>
        ${!editable?`<div class="permission-readonly-note"><span>🔒</span><div><strong>${t("v54.readonlyTitle")}</strong><p>${t("v54.readonlyText")}</p></div></div>`:""}
        <div class="card card-pad permission-section"><div class="section-title"><div><div class="eyebrow">${t("v54.moduleAccessEyebrow")}</div><h2>${t("v54.moduleAccess")}</h2><p>${t("v54.moduleAccessSub")}</p></div><div class="permission-legend">${levels.map(x=>`<span class="access-badge ${x}">${levelLabel(x)}</span>`).join("")}</div></div>
          <div class="module-access-table"><div class="module-access-head"><span>${t("v54.module")}</span><span>${t("v54.accessLevel")}</span><span>${t("v54.effect")}</span></div>${platformModules.map(m=>moduleRow(role,m,p.modules[m],editable)).join("")}</div>
        </div>
        <div class="card card-pad permission-section"><div class="section-title"><div><div class="eyebrow">${t("v54.actionRightsEyebrow")}</div><h2>${t("v54.actionRights")}</h2><p>${t("v54.actionRightsSub")}</p></div></div>
          <div class="action-rights-grid">${actionGroups.map(([title,actions])=>`<section class="permission-action-group"><h3>${t(title)}</h3>${actions.map(a=>actionRow(role,a,p.actions[a],editable)).join("")}</section>`).join("")}</div>
          <div class="discount-policy"><div><span>${t("v54.discountLimit")}</span><strong>${p.discountLimit==null?t("v54.unlimited"):p.discountLimit+"%"}</strong><small>${t("v54.discountLimitSub")}</small></div><div class="discount-policy-control"><input id="discountLimit" type="number" min="0" max="100" step="0.5" value="${p.discountLimit??100}" ${editable?"":"disabled"}><span>%</span><button class="btn btn-soft" id="saveDiscountLimit" ${editable?"":"disabled"}>${t("v54.saveLimit")}</button></div></div>
        </div>
        <div class="card card-pad permission-section"><div class="section-title"><div><div class="eyebrow">${t("v54.dataScopeEyebrow")}</div><h2>${t("v54.dataScope")}</h2><p>${t("v54.dataScopeSub")}</p></div></div><div class="data-scope-grid">
          ${scopeCard("personal",p.actions["client.personal"],t("v54.scope.personal"),t("v54.scope.personalSub"))}${scopeCard("financial",p.actions["client.financial"],t("v54.scope.financial"),t("v54.scope.financialSub"))}${scopeCard("export",p.actions["data.export"],t("v54.scope.export"),t("v54.scope.exportSub"))}${scopeCard("admin",p.actions["admin.roles"],t("v54.scope.admin"),t("v54.scope.adminSub"))}
        </div></div>
        <div class="card role-summary"><div><div class="eyebrow">${t("v54.summaryEyebrow")}</div><h2>${t("v54.summaryTitle")}</h2><p>${t("v54.summaryText",{role:label(role),count:accessible.length})}</p></div><div class="role-summary-modules">${accessible.map(m=>`<span>${t(moduleLabelKey(m))}<b class="${p.modules[m]}">${levelLabel(p.modules[m])}</b></span>`).join("")}</div></div>
      </div>
    </div>
  </section>`;
}
function metric(labelText:string,value:number,note:string,kind:string){return`<div class="card permission-kpi"><span class="permission-kpi-icon ${kind}">${kind==="module"?"▦":kind==="edit"?"✎":kind==="manage"?"⌘":"✓"}</span><div><small>${labelText}</small><strong>${value}</strong><span>${note}</span></div></div>`}
function initials(value:string){return value.split(/\s+/).slice(0,2).map(x=>x[0]??"").join("").toUpperCase()}
function roleCard(role:PlatformRole,active:PlatformRole){const p=getRolePolicy(role),s=moduleStats(role);return`<button class="role-catalog-item ${role===active?"active":""}" data-role-card="${role}"><span class="role-dot ${p.department}"></span><div><strong>${label(role)}</strong><small>${departmentLabel(p.department)}</small></div><em>${s.accessible}</em></button>`}
function moduleRow(role:PlatformRole,module:PlatformModule,level:AccessLevel,editable:boolean){return`<div class="module-access-row"><div class="module-name"><span class="module-icon-mini">${moduleIcon(module)}</span><div><strong>${t(moduleLabelKey(module))}</strong><small>${t(`v54.moduleNote.${module}`)}</small></div></div><div class="access-segments" role="group" aria-label="${t(moduleLabelKey(module))}">${levels.map(x=>`<button class="access-segment ${x} ${level===x?"active":""}" data-access-role="${role}" data-access-module="${module}" data-access-level="${x}" ${editable?"":"disabled"}>${levelLabel(x)}</button>`).join("")}</div><div class="access-effect"><span class="access-badge ${level}">${levelLabel(level)}</span><small>${t(`v54.accessEffect.${level}`)}</small></div></div>`}
function actionRow(role:PlatformRole,action:PermissionAction,value:boolean,editable:boolean){return`<label class="permission-action-row ${value?"enabled":""}"><span class="permission-switch"><input type="checkbox" data-action-role="${role}" data-action-permission="${action}" ${value?"checked":""} ${editable?"":"disabled"}><i></i></span><div><strong>${t(actionLabelKey(action))}</strong><small>${t(`${actionLabelKey(action)}.sub`)}</small></div><em>${value?t("v54.allowed"):t("v54.denied")}</em></label>`}
function scopeCard(kind:string,enabled:boolean,title:string,subtitle:string){return`<div class="data-scope-card ${enabled?"allowed":"blocked"}"><span>${enabled?"✓":"×"}</span><div><strong>${title}</strong><p>${subtitle}</p></div><em>${enabled?t("v54.allowed"):t("v54.denied")}</em></div>`}
function moduleIcon(module:PlatformModule){return({dashboard:"⌂",leads:"✦",clients:"◎",properties:"▦",deals:"◇",payments:"₳",approvals:"✓",tasks:"☑",notifications:"◌",contracts:"▤",legal:"⚖",finance:"↗",mortgages:"⌂",registration:"§",handover:"⌘",service:"⚙",reports:"▥",audit:"≡",administration:"⚙"}as Record<PlatformModule,string>)[module]}

export function bindAdminRoles(){
  document.querySelectorAll<HTMLElement>("[data-role-card]").forEach(el=>el.addEventListener("click",()=>navigate(`admin/roles?role=${encodeURIComponent(el.dataset.roleCard!)}`)));
  document.querySelectorAll<HTMLButtonElement>("[data-access-module]").forEach(el=>el.addEventListener("click",()=>{if(!canAction("admin.roles"))return;const role=el.dataset.accessRole as PlatformRole,module=el.dataset.accessModule as PlatformModule,level=el.dataset.accessLevel as AccessLevel,before=getRolePolicy(role).modules[module];setModuleAccess(role,module,level);recordAudit({module:"administration",action:"security",entityType:"role",entityId:role,entityLabel:`Role · ${role}`,route:`admin/roles?role=${encodeURIComponent(role)}`,field:`${module} access`,oldValue:before,newValue:level,note:"Module access level changed.",severity:"warning"});toastLocalized(t("v54.toast.accessSaved"));refresh()}));
  document.querySelectorAll<HTMLInputElement>("[data-action-permission]").forEach(el=>el.addEventListener("change",()=>{if(!canAction("admin.roles"))return;const role=el.dataset.actionRole as PlatformRole,action=el.dataset.actionPermission as PermissionAction,before=getRolePolicy(role).actions[action];setActionPermission(role,action,el.checked);recordAudit({module:"administration",action:"security",entityType:"role",entityId:role,entityLabel:`Role · ${role}`,route:`admin/roles?role=${encodeURIComponent(role)}`,field:action,oldValue:before?"Allowed":"Denied",newValue:el.checked?"Allowed":"Denied",note:"Special permission changed.",severity:"warning"});toastLocalized(t("v54.toast.actionSaved"));refresh()}));
  document.querySelector("#saveDiscountLimit")?.addEventListener("click",()=>{if(!canAction("admin.roles"))return;const input=document.querySelector<HTMLInputElement>("#discountLimit");if(!input)return;const role=selectedRole(),before=getRolePolicy(role).discountLimit,next=Math.max(0,Math.min(100,Number(input.value)||0));setDiscountLimit(role,next);recordAudit({module:"administration",action:"security",entityType:"role",entityId:role,entityLabel:`Role · ${role}`,route:`admin/roles?role=${encodeURIComponent(role)}`,field:"Discount limit",oldValue:before==null?"Unlimited":`${before}%`,newValue:`${next}%`,note:"Discount authority threshold changed.",severity:"warning"});toastLocalized(t("v54.toast.limitSaved"));refresh()});
  document.querySelector("#resetRole")?.addEventListener("click",()=>{if(!canAction("admin.roles"))return;openLocalizedModal(t("v54.resetTitle"),`<div class="permission-reset-warning"><span>↺</span><div><strong>${label(selectedRole())}</strong><p>${t("v54.resetText")}</p></div></div>`,`<button class="btn" data-modal-close>${t("common.cancel")}</button><button class="btn btn-danger" id="confirmResetRole">${t("v54.resetConfirm")}</button>`);setTimeout(()=>document.querySelector("#confirmResetRole")?.addEventListener("click",()=>{const role=selectedRole();resetRolePolicy(role);recordAudit({module:"administration",action:"security",entityType:"role",entityId:role,entityLabel:`Role · ${role}`,route:`admin/roles?role=${encodeURIComponent(role)}`,field:"Role policy",oldValue:"Customized",newValue:"Default",note:"Role policy reset to platform defaults.",severity:"critical"});closeModal();toastLocalized(t("v54.toast.reset"));refresh()}),0)});
  document.querySelector("#previewRole")?.addEventListener("click",()=>{const role=selectedRole(),before=currentRole();recordAudit({module:"administration",action:"access",entityType:"role",entityId:role,entityLabel:`Role · ${role}`,route:`admin/roles?role=${encodeURIComponent(role)}`,field:"Demo role",oldValue:before,newValue:role,note:"Role preview started from Administration.",severity:"info"});setCurrentRole(role);toastLocalized(t("toast.roleMode",{role:label(role)}));navigate(landingRoute(role))});
  document.querySelector("#permissionExplain")?.addEventListener("click",()=>openLocalizedModal(t("v54.howItWorks"),`<div class="permission-explain"><div><b>1</b><section><strong>${t("v54.explain.1title")}</strong><p>${t("v54.explain.1text")}</p></section></div><div><b>2</b><section><strong>${t("v54.explain.2title")}</strong><p>${t("v54.explain.2text")}</p></section></div><div><b>3</b><section><strong>${t("v54.explain.3title")}</strong><p>${t("v54.explain.3text")}</p></section></div><div><b>4</b><section><strong>${t("v54.explain.4title")}</strong><p>${t("v54.explain.4text")}</p></section></div></div>`,`<button class="btn" data-modal-close>${t("modal.close")}</button>`));
}
function refresh(){const role=selectedRole();navigate("dashboard");setTimeout(()=>navigate(`admin/roles?role=${encodeURIComponent(role)}`),15)}
