import { leads, properties } from "../data/mock";
import { amd,propertyTypeLabel } from "../utils";
import { currentRoute, navigate } from "../router";
import {closeModal,formValue,openLocalizedModal,toastLocalized} from "../components/layout";
import {locale,t} from "../i18n";
import {convertReservation,getSalesFlowState} from "../services/sales-flow";
import {createWorkflowRoute,getRuleById,getWorkflowRoute,previewWorkflow} from "../services/workflow";
import type{WorkflowContext,WorkflowRole}from"../models/types";

type ApplicationPartyRole="coBuyer"|"representative"|"coBorrower";
type ApplicationFinanceScheme="installment12"|"mortgage"|"full";
type ApplicationStatus="draft"|"incomplete"|"ready"|"approval"|"returned"|"approved"|"cancelled";
type ApplicationDocumentKey="passport"|"personalNumber"|"addressProof"|"assetPackage"|"purchaseApplication"|"fundingSource"|"representativePoa"|"mortgagePreApproval";
interface ApplicationParty{id:string;name:string;role:ApplicationPartyRole;phone:string}
interface ApplicationState{parties:ApplicationParty[];finance:{scheme:ApplicationFinanceScheme;downPayment:string;discount:string;currency:string};documents:Partial<Record<ApplicationDocumentKey,boolean>>;status:ApplicationStatus;createdAt:string;submittedAt?:string;history:{at:string;title:string;note:string}[]}
const applicationState=new Map<string,ApplicationState>();
const stateFor=(id:string)=>{if(!applicationState.has(id))applicationState.set(id,{parties:[],finance:{scheme:"installment12",downPayment:"20%",discount:"3%",currency:"AMD"},documents:{passport:true,personalNumber:true,addressProof:true,assetPackage:true,purchaseApplication:false,fundingSource:false},status:"draft",createdAt:new Date().toISOString(),history:[{at:new Date().toISOString(),title:"draft",note:"Purchase application created"}]});return applicationState.get(id)!};
const partyRoleLabel=(role:ApplicationPartyRole)=>role==="coBuyer"?t("application.coBuyer"):role==="representative"?t("application.representative"):t("application.coBorrower");
const financeSchemeLabel=(scheme:ApplicationFinanceScheme)=>scheme==="installment12"?t("application.installment12"):scheme==="mortgage"?t("application.mortgage"):t("application.fullPayment");
const discountValue=(s:string)=>Math.max(0,Math.min(100,Number.parseFloat(s.replace("%",""))||0));
const fmtDate=(iso?:string)=>iso?new Intl.DateTimeFormat(locale(),{day:"2-digit",month:"2-digit",year:"numeric",hour:"2-digit",minute:"2-digit"}).format(new Date(iso)):"—";
const statusLabel=(s:ApplicationStatus)=>t(`v46.application.status.${s}`);
const statusClass=(s:ApplicationStatus)=>s==="ready"||s==="approved"?"success":s==="approval"?"accent":s==="returned"||s==="cancelled"?"danger":"warning";
const workflowRoleLabel=(role:WorkflowRole)=>({"Sales Head":t("role.salesHead"),"Commercial Director":t("role.commercialDirector"),Legal:t("role.legal"),Finance:t("role.finance"),"Financial Director":t("role.financialDirector"),CEO:t("role.ceo")}[role]??role);
function applicationWorkflowContext(l:(typeof leads)[number],st:ApplicationState,rows:(typeof properties)[number][],dealTotal:number):WorkflowContext{return{sourceType:"application",subjectId:l.id,dealId:`APP-${l.id}`,title:`${t("application.title")} · ${l.id}`,clientName:l.name,propertyLabel:rows.map(p=>p.unit).join(" + "),requestedBy:l.manager,discountPercent:discountValue(st.finance.discount),amount:dealTotal,currency:(st.finance.currency||"AMD") as any,installmentMonths:st.finance.scheme==="installment12"?12:undefined,buyerType:/ՍՊԸ|LLC|LTD/i.test(l.name)?"company":"individual",hasRepresentative:st.parties.some(x=>x.role==="representative"),nonStandardClauses:0,riskLevel:"low",assetCount:rows.length}}
function applicationApprovalAction(status:ApplicationStatus){if(status==="approval")return`<button class="btn btn-accent" id="openApplicationWorkflow">${t("v47.application.openWorkflow")}</button>`;if(status==="approved")return`<button class="btn btn-success" disabled>✓ ${t("v47.application.workflowApproved")}</button>`;if(status==="returned")return`<button class="btn btn-accent" id="resumeApplication">${t("v47.application.resumeRevision")}</button>`;return`<button class="btn btn-accent" id="sendApproval" ${status!=="ready"?"disabled":""}>${t("application.sendApproval")}</button>`}

function docDefinitions(st:ApplicationState){
  const docs:{key:ApplicationDocumentKey;label:string;required:boolean;why:string}[]=[
    {key:"passport",label:t("application.passportId"),required:true,why:t("v46.application.doc.identityWhy")},
    {key:"personalNumber",label:t("client.publicServiceNumber"),required:true,why:t("v46.application.doc.personalWhy")},
    {key:"addressProof",label:t("application.addressProof"),required:true,why:t("v46.application.doc.addressWhy")},
    {key:"assetPackage",label:t("v45.package.assetPackageAttached"),required:true,why:t("v46.application.doc.assetsWhy")},
    {key:"purchaseApplication",label:t("application.purchaseApplication"),required:true,why:t("v46.application.doc.applicationWhy")},
    {key:"fundingSource",label:t("application.fundingSource"),required:true,why:t("v46.application.doc.fundingWhy")}
  ];
  if(st.parties.some(x=>x.role==="representative"))docs.push({key:"representativePoa",label:t("v46.application.doc.poa"),required:true,why:t("v46.application.doc.poaWhy")});
  if(st.finance.scheme==="mortgage")docs.push({key:"mortgagePreApproval",label:t("v46.application.doc.mortgage"),required:true,why:t("v46.application.doc.mortgageWhy")});
  return docs;
}
function readiness(st:ApplicationState){const docs=docDefinitions(st);const ready=docs.filter(d=>st.documents[d.key]===true).length;return {docs,ready,total:docs.length,missing:docs.filter(d=>st.documents[d.key]!==true)}}
function syncStatus(st:ApplicationState){if(["approval","approved","cancelled","returned"].includes(st.status))return st.status;const r=readiness(st);st.status=r.missing.length?"incomplete":"ready";return st.status}

export function applicationPage(leadId:string){
  const l=leads.find(x=>x.id===leadId);if(!l)return `<section class="page"><div class="card card-pad">${t("common.recordNotFound")}</div></section>`;
  const fallback=properties.find(x=>x.status==="available"),flow=getSalesFlowState(l.id,fallback?[fallback.id]:[],l.stage),rows=flow.selectedPropertyIds.map(id=>properties.find(x=>x.id===id)).filter(Boolean) as typeof properties,st=stateFor(l.id);if(!rows.length)return `<section class="page"><div class="card card-pad">${t("reservation.noProperty")}</div></section>`;
  if(flow.reservationStatus!=="active"&&!(["approval","approved","returned"] as ApplicationStatus[]).includes(st.status))return `<section class="page"><div class="sales-flow-alert danger"><b>!</b><div><strong>${t("v46.application.reservationRequiredTitle")}</strong><span>${t("v46.application.reservationRequiredText")}</span></div><button class="btn" id="applicationReturnReservation">${t("application.backReservation")}</button></div></section>`;
  syncStatus(st);const ready=readiness(st),listTotal=rows.reduce((s,p)=>s+p.totalPrice,0),discount=discountValue(st.finance.discount),dealTotal=Math.round(listTotal*(1-discount/100));const existingRoute=getWorkflowRoute("application",l.id);if(existingRoute?.status==="approved"&&st.status==="approval")st.status="approved";else if(existingRoute?.status==="returned"&&st.status==="approval")st.status="returned";else if(existingRoute?.status==="rejected"&&st.status==="approval")st.status="returned";const locked=st.status==="approval"||st.status==="approved",workflowContext=applicationWorkflowContext(l,st,rows,dealTotal),workflowPlan=previewWorkflow(workflowContext);
  return `<section class="page">
  <div class="breadcrumbs"><span>${t("nav.sales")}</span><span>›</span><span>${l.name}</span><span>›</span><span>${t("application.title")}</span></div>
  <div class="page-header"><div class="page-title"><div class="eyebrow">${t("application.eyebrow")}</div><h1>${t("application.title")}</h1><p>${rows.length>1?t("v45.package.applicationSubtitle",{count:rows.length}):t("application.subtitle")}</p></div><div class="toolbar"><button class="btn" id="backReservation">${t("application.backReservation")}</button>${!locked?`<button class="btn" id="reviewMissingDocs">${t("v46.application.reviewMissing")}</button>`:""}${applicationApprovalAction(st.status)}</div></div>

  <div class="application-statusbar"><div><span>${t("v46.application.number")}</span><strong>APP-${leadId.replace("LD-","")}</strong><small>${t("v46.application.created")}: ${fmtDate(st.createdAt)}</small></div><div class="application-readiness"><span>${t("v46.application.readiness")}</span><strong>${ready.ready}/${ready.total}</strong><div class="progress"><span style="width:${ready.total?Math.round(ready.ready/ready.total*100):0}%"></span></div></div><span class="status ${statusClass(st.status)}">${statusLabel(st.status)}</span></div>
  ${ready.missing.length&&!locked?`<div class="sales-flow-alert warning" id="applicationMissingAlert"><b>!</b><div><strong>${t("v46.application.missingTitle",{count:ready.missing.length})}</strong><span>${t("v46.application.missingText")}</span></div></div>`:""}
  ${locked?`<div class="sales-flow-alert"><b>✓</b><div><strong>${t("v46.application.lockedTitle")}</strong><span>${t("v46.application.lockedText")}</span></div></div>`:""}

  <div class="journey u-mb-16">${step("01",t("application.step.client"),true,false)}${step("02",t("application.step.property"),true,false)}${step("03",t("application.step.finance"),true,false)}${step("04",t("application.step.documents"),ready.missing.length===0,ready.missing.length>0)}${step("05",t("application.step.approval"),st.status==="approved",st.status==="approval")}</div>
  <div class="package-application-hero"><div><span>${t("v45.package.purchaseApplication")}</span><strong>${rows.map(p=>p.unit).join(" + ")}</strong><p>${t("v45.package.applicationRule")}</p></div><div><span>${t("v45.package.listValue")}</span><strong>${amd(listTotal)}</strong></div><div><span>${t("application.discount")}</span><strong>${st.finance.discount}</strong></div><div><span>${t("v45.package.packagePrice")}</span><strong>${amd(dealTotal)}</strong></div></div>

  <div class="grid grid-2"><div class="card card-pad"><div class="section-title"><div><h2>${t("application.partiesTitle")}</h2><p>${t("application.partiesSub")}</p></div>${!locked?`<button class="btn btn-soft" id="applicationAddParty">${t("application.addParty")}</button>`:""}</div><div class="person"><div class="avatar accent">${l.name.split(" ").map(x=>x[0]).slice(0,2).join("")}</div><div><strong>${l.name}</strong><span>${t("application.buyer")} · ${l.phone}</span></div></div>${st.parties.map(x=>`<div class="application-party-row"><div class="avatar">${x.name.slice(0,1)}</div><div><strong>${x.name}</strong><span>${partyRoleLabel(x.role)} · ${x.phone}</span></div>${!locked?`<button class="icon-btn" data-remove-party="${x.id}" aria-label="${t("v46.application.removeParty")}">×</button>`:""}</div>`).join("")}<div class="divider"></div><div class="info-list"><div class="info-box"><span>${t("application.buyerType")}</span><strong>${t("application.physicalPerson")}</strong></div><div class="info-box"><span>${t("application.documentLanguage")}</span><strong>${l.language}</strong></div><div class="info-box"><span>${t("application.participants")}</span><strong>${1+st.parties.length}</strong></div><div class="info-box"><span>KYC</span><strong>${t("application.preliminaryPassed")}</strong></div></div></div>
  <div class="card card-pad"><div class="section-title"><div><h2>${t("v45.package.assetsInApplication")}</h2><p>${t("v45.package.assetTermsSub")}</p></div><span class="chip accent">${rows.length}</span></div><div class="package-application-assets">${rows.map((p,i)=>`<div class="package-application-asset"><div><span>${String(i+1).padStart(2,"0")} · ${propertyTypeLabel(p.type)}</span><strong>${p.project} · ${p.unit}</strong><small>${p.area} m² · ${p.phase} · ${p.building}/${p.entrance}</small></div><div><span>${t("v45.package.listPrice")}</span><strong>${amd(p.totalPrice)}</strong><small>${t("v45.package.afterDiscount")}: ${amd(Math.round(p.totalPrice*(1-discount/100)))}</small></div></div>`).join("")}</div></div>
  <div class="card card-pad"><div class="section-title"><div><h2>${t("application.financeTitle")}</h2><p>${t("application.financeSub")}</p></div>${!locked?`<button class="btn btn-soft" id="applicationFinance">${t("application.edit")}</button>`:""}</div><div class="info-list"><div class="info-box"><span>${t("application.scheme")}</span><strong>${financeSchemeLabel(st.finance.scheme)}</strong></div><div class="info-box"><span>${t("application.downPayment")}</span><strong>${st.finance.downPayment}</strong></div><div class="info-box"><span>${t("application.discount")}</span><strong>${st.finance.discount}</strong></div><div class="info-box"><span>${t("application.contractCurrency")}</span><strong>${st.finance.currency}</strong></div></div><div class="package-rule-note u-mt-12"><b>i</b><span>${t("v45.package.paymentAllocationRule")}</span></div></div>
  <div class="card card-pad" id="applicationDocuments"><div class="section-title"><div><h2>${t("application.docsReady")}</h2><p>${t("application.beforeWorkflow")}</p></div><div class="document-readiness-pill"><strong>${ready.ready}/${ready.total}</strong><span>${t("v46.application.ready")}</span></div></div><div class="application-doc-list">${ready.docs.map(d=>documentRow(d,Boolean(st.documents[d.key]),locked)).join("")}</div></div></div>

  <div class="card card-pad u-mt-16 application-workflow-preview"><div class="section-title"><div><h2>${t("v47.application.routePreview")}</h2><p>${t("v47.application.routePreviewSub")}</p></div>${existingRoute?`<span class="status ${existingRoute.status==="approved"?"success":existingRoute.status==="active"?"warning":"danger"}">${existingRoute.id} · ${t(`status.${existingRoute.status}`)}</span>`:`<span class="chip accent">${workflowPlan.groups.length} ${t("v47.application.steps")}</span>`}</div><div class="workflow-preview-chain">${workflowPlan.groups.map((g,i)=>`<div class="workflow-preview-step"><span>${String(i+1).padStart(2,"0")}</span><div><small>${t("v47.application.approver")}</small><strong>${workflowRoleLabel(g.role)}</strong><p>${g.rules.map(r=>t(r.nameKey)).join(" · ")}</p></div><b>SLA ${g.slaHours}h</b></div>`).join("")||`<div class="workflow-auto-pass">✓ ${t("v47.application.noApprovalRequired")}</div>`}</div></div>

  <div class="grid grid-2 u-mt-16"><div class="card card-pad"><div class="section-title"><div><h2>${t("v46.application.transitionControl")}</h2><p>${t("v46.application.transitionControlSub")}</p></div></div>${gate(t("v46.application.gateReservation"),flow.reservationStatus==="active"&&flow.reservationPaid)}${gate(t("v46.application.gateAssets"),rows.every(p=>p.status==="reserved"||p.status==="approval"))}${gate(t("v46.application.gateDocuments"),ready.missing.length===0)}${gate(t("v46.application.gateFinance"),Boolean(st.finance.scheme&&st.finance.currency))}<div class="application-gate-result ${ready.missing.length?"blocked":"ready"}"><b>${ready.missing.length?"!":"✓"}</b><div><strong>${ready.missing.length?t("v46.application.blocked"):t("v46.application.canSubmit")}</strong><span>${ready.missing.length?t("v46.application.blockedText",{count:ready.missing.length}):t("v46.application.canSubmitText")}</span></div></div></div>
  <div class="card card-pad"><div class="section-title"><div><h2>${t("v46.application.history")}</h2><p>${t("v46.application.historySub")}</p></div></div><div class="sales-flow-history">${st.history.slice(0,7).map(h=>`<div class="sales-history-row"><i></i><div><span>${fmtDate(h.at)}</span><strong>${t(`v46.application.history.${h.title}`)}</strong><p>${h.note}</p></div></div>`).join("")}</div></div></div>
  </section>`;
}
function step(num:string,title:string,done:boolean,active:boolean){return `<div class="journey-step ${done?"done":""} ${active?"active":""}"><span>${num}</span><strong>${title}</strong></div>`}
function documentRow(d:{key:ApplicationDocumentKey;label:string;required:boolean;why:string},done:boolean,locked:boolean){return `<div class="application-doc-row ${done?"ready":"missing"}"><div class="application-doc-icon">${done?"✓":"!"}</div><div><div class="application-doc-title"><strong>${d.label}</strong>${d.required?`<span>${t("v46.application.required")}</span>`:""}</div><p>${d.why}</p></div><div class="application-doc-action"><span class="status ${done?"success":"warning"}">${done?t("v46.application.docReady"):t("v46.application.docMissing")}</span>${!locked?`<button class="btn btn-soft" data-app-doc="${d.key}">${done?t("v46.application.reopen"):t("v46.application.complete")}</button>`:""}</div></div>`}
function gate(label:string,done:boolean){return `<div class="application-gate"><span class="checkmark ${done?"":"pending"}">${done?"✓":"!"}</span><strong>${label}</strong></div>`}

export function bindApplication(){
  const id=currentRoute().split("/")[1],l=leads.find(x=>x.id===id);if(!l)return;const st=stateFor(l.id),flow=getSalesFlowState(id),rows=flow.selectedPropertyIds.map(pid=>properties.find(x=>x.id===pid)).filter(Boolean) as typeof properties;
  document.querySelector("#applicationReturnReservation")?.addEventListener("click",()=>navigate("reservation/"+id));
  document.querySelector("#backReservation")?.addEventListener("click",()=>navigate("reservation/"+id));
  document.querySelector("#reviewMissingDocs")?.addEventListener("click",()=>document.querySelector("#applicationDocuments")?.scrollIntoView({behavior:"smooth",block:"start"}));
  document.querySelector("#openApplicationWorkflow")?.addEventListener("click",()=>navigate("approvals?tab=routes"));
  document.querySelector("#resumeApplication")?.addEventListener("click",()=>{st.status="draft";syncStatus(st);st.history.unshift({at:new Date().toISOString(),title:"financeUpdated",note:t("v47.application.revisionResumed")});toastLocalized(t("v47.application.revisionResumed"));refresh(id)});
  document.querySelector("#sendApproval")?.addEventListener("click",()=>{
    syncStatus(st);const ready=readiness(st);if(flow.reservationStatus!=="active"||!flow.reservationPaid){toastLocalized(t("application.reservationPaymentRequired"));return}if(ready.missing.length){toastLocalized(t("v46.application.completeRequired",{count:ready.missing.length}));document.querySelector("#applicationDocuments")?.scrollIntoView({behavior:"smooth",block:"center"});return}
    const listTotal=rows.reduce((sum,p)=>sum+p.totalPrice,0),dealTotal=Math.round(listTotal*(1-discountValue(st.finance.discount)/100)),route=createWorkflowRoute(applicationWorkflowContext(l,st,rows,dealTotal));
    rows.forEach(p=>{if(["reserved","offered","pre-reserved"].includes(p.status))p.status="approval"});st.status=route.status==="approved"?"approved":"approval";st.submittedAt=new Date().toISOString();st.history.unshift({at:st.submittedAt,title:"submitted",note:t("v47.application.historyRouteCreated",{route:route.id,steps:route.approvalIds.length})});convertReservation(id);l.stage="reservation";l.lastActivity="i18n:leads.activity.now";l.nextAction=route.status==="approved"?"i18n:v47.application.nextApproved":"i18n:v46.application.nextApproval";
    toastLocalized(t("v47.application.routeCreated",{route:route.id,steps:route.approvalIds.length}));setTimeout(()=>navigate("approvals?tab=inbox"),250)
  });
  document.querySelector("#applicationAddParty")?.addEventListener("click",()=>openParty(id));
  document.querySelector("#applicationFinance")?.addEventListener("click",()=>openFinance(id));
  document.querySelectorAll<HTMLElement>("[data-remove-party]").forEach(btn=>btn.addEventListener("click",()=>{const partyId=btn.dataset.removeParty;const idx=st.parties.findIndex(x=>x.id===partyId);if(idx>=0){const [removed]=st.parties.splice(idx,1);st.history.unshift({at:new Date().toISOString(),title:"partyRemoved",note:removed.name});syncStatus(st);toastLocalized(t("v46.application.partyRemoved"));refresh(id)}}));
  document.querySelectorAll<HTMLElement>("[data-app-doc]").forEach(btn=>btn.addEventListener("click",()=>{const key=btn.dataset.appDoc as ApplicationDocumentKey;st.documents[key]=!st.documents[key];st.history.unshift({at:new Date().toISOString(),title:st.documents[key]?"documentCompleted":"documentReopened",note:docDefinitions(st).find(x=>x.key===key)?.label??key});syncStatus(st);toastLocalized(st.documents[key]?t("v46.application.documentCompleted"):t("v46.application.documentReopened"));refresh(id)}));
}
function openParty(id:string){openLocalizedModal(t("application.partyModal"),`<form id="applicationPartyForm" class="form-grid"><div class="form-field full"><label>${t("application.fullName")}</label><input name="name" required></div><div class="form-field"><label>${t("application.role")}</label><select name="role"><option value="coBuyer">${t("application.coBuyer")}</option><option value="representative">${t("application.representative")}</option><option value="coBorrower">${t("application.coBorrower")}</option></select></div><div class="form-field"><label>${t("application.phone")}</label><input name="phone" value="+374 "></div><div class="full sales-flow-modal-note">${t("v46.application.partyNote")}</div></form>`,`<button class="btn" data-modal-close>${t("application.cancel")}</button><button class="btn btn-accent" id="saveApplicationParty">${t("application.add")}</button>`);setTimeout(()=>document.querySelector("#saveApplicationParty")?.addEventListener("click",()=>{const f=document.querySelector<HTMLFormElement>("#applicationPartyForm")!;if(!f.reportValidity())return;const st=stateFor(id),role=formValue(f,"role") as ApplicationPartyRole;st.parties.push({id:`PTY-${Date.now()}`,name:formValue(f,"name"),role,phone:formValue(f,"phone")});if(role==="representative"&&st.documents.representativePoa===undefined)st.documents.representativePoa=false;st.history.unshift({at:new Date().toISOString(),title:"partyAdded",note:`${formValue(f,"name")} · ${partyRoleLabel(role)}`});syncStatus(st);closeModal();toastLocalized(t("application.partyAdded"));refresh(id)}),0)}
function openFinance(id:string){const st=stateFor(id);openLocalizedModal(t("application.financingTerms"),`<form id="applicationFinanceForm" class="form-grid"><div class="form-field"><label>${t("application.scheme")}</label><select name="scheme"><option value="installment12" ${st.finance.scheme==="installment12"?"selected":""}>${t("application.installment12")}</option><option value="mortgage" ${st.finance.scheme==="mortgage"?"selected":""}>${t("application.mortgage")}</option><option value="full" ${st.finance.scheme==="full"?"selected":""}>${t("application.fullPayment")}</option></select></div><div class="form-field"><label>${t("application.downPayment")}</label><input name="downPayment" value="${st.finance.downPayment}"></div><div class="form-field"><label>${t("application.discount")}</label><input name="discount" value="${st.finance.discount}"></div><div class="form-field"><label>${t("application.currency")}</label><select name="currency"><option ${st.finance.currency==="AMD"?"selected":""}>AMD</option><option ${st.finance.currency==="USD"?"selected":""}>USD</option><option ${st.finance.currency==="EUR"?"selected":""}>EUR</option></select></div><div class="full sales-flow-modal-note">${t("v46.application.financeNote")}</div></form>`,`<button class="btn" data-modal-close>${t("application.cancel")}</button><button class="btn btn-accent" id="saveApplicationFinance">${t("application.apply")}</button>`);setTimeout(()=>document.querySelector("#saveApplicationFinance")?.addEventListener("click",()=>{const f=document.querySelector<HTMLFormElement>("#applicationFinanceForm")!,oldScheme=st.finance.scheme;st.finance={scheme:formValue(f,"scheme") as ApplicationFinanceScheme,downPayment:formValue(f,"downPayment"),discount:formValue(f,"discount"),currency:formValue(f,"currency")};if(st.finance.scheme==="mortgage"&&st.documents.mortgagePreApproval===undefined)st.documents.mortgagePreApproval=false;if(oldScheme==="mortgage"&&st.finance.scheme!=="mortgage")delete st.documents.mortgagePreApproval;st.history.unshift({at:new Date().toISOString(),title:"financeUpdated",note:`${financeSchemeLabel(st.finance.scheme)} · ${st.finance.downPayment} · ${st.finance.discount}`});syncStatus(st);closeModal();toastLocalized(t("application.financeUpdated"));refresh(id)}),0)}
function refresh(id:string){navigate("reservation/"+id);setTimeout(()=>navigate("application/"+id),20)}
