import{auditActors,auditEvents,auditStats,recordAudit,type AuditAction,type AuditEntityType,type AuditEvent}from"../services/audit";
import{t}from"../i18n";import{currentRoute,navigate}from"../router";import{openLocalizedModal,toastLocalized}from"../components/layout";import{canAction,currentRole,platformModules,roleLabelKey,type PlatformModule}from"../services/permissions";
const actions:AuditAction[]=["create","update","status","approval","signature","payment","document","export","access","security","system"];
const entities:AuditEntityType[]=["client","deal","property","contract","payment","approval","poa","registration","handover","warranty","template","role","system"];
function params(){return new URLSearchParams(currentRoute().split("?")[1]??"")}
function fmt(iso:string){return new Intl.DateTimeFormat(undefined,{day:"2-digit",month:"short",year:"numeric",hour:"2-digit",minute:"2-digit"}).format(new Date(iso))}
function esc(v:string){return v.replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]!))}
function filtered(){const p=params(),q=(p.get("q")??"").toLowerCase(),module=p.get("module")??"",action=p.get("action")??"",actor=p.get("actor")??"",severity=p.get("severity")??"",entityType=p.get("entityType")??"",entityId=p.get("entityId")??"";return auditEvents().filter(e=>(!q||[e.actor,e.entityLabel,e.entityId,e.note,e.field,e.oldValue,e.newValue,e.integrityRef].join(" ").toLowerCase().includes(q))&&(!module||e.module===module)&&(!action||e.action===action)&&(!actor||e.actor===actor)&&(!severity||e.severity===severity)&&(!entityType||e.entityType===entityType)&&(!entityId||e.entityId===entityId))}
export function auditPage(){const s=auditStats(),rows=filtered(),p=params(),entityId=p.get("entityId");return`<section class="page audit-page"><div class="breadcrumbs"><span>${t("v55.audit.admin")}</span><span>›</span><span>${t("v55.audit.title")}</span></div><div class="page-header"><div><div class="eyebrow">${t("v55.audit.eyebrow")}</div><h1>${t("v55.audit.title")}</h1><p>${t("v55.audit.subtitle")}</p></div><div class="toolbar"><span class="audit-immutable-chip"><i>◆</i><span><small>${t("v55.audit.integrity")}</small><strong>${t("v55.audit.appendOnly")}</strong></span></span>${canAction("data.export")?`<button class="btn" id="auditExport">${t("v55.audit.export")}</button>`:""}</div></div>
<div class="audit-kpis">${kpi(t("v55.audit.kpi.today"),s.today,t("v55.audit.kpi.todaySub"),"today")}${kpi(t("v55.audit.kpi.changes"),s.changes,t("v55.audit.kpi.changesSub"),"changes")}${kpi(t("v55.audit.kpi.critical"),s.critical,t("v55.audit.kpi.criticalSub"),"critical")}${kpi(t("v55.audit.kpi.total"),s.total,t("v55.audit.kpi.totalSub"),"total")}</div>
${entityId?`<div class="audit-context-banner"><span>◎</span><div><small>${t("v55.audit.filteredEntity")}</small><strong>${esc(entityId)}</strong></div><button class="text-btn" id="clearAuditEntity">${t("v55.audit.clearEntityFilter")}</button></div>`:""}
<div class="card card-pad audit-filters"><div class="audit-filter-grid"><div class="form-field audit-search-wide"><label>${t("v55.audit.search")}</label><input id="auditSearch" value="${esc(p.get("q")??"")}" placeholder="${t("v55.audit.searchPlaceholder")}"></div>${select("auditModule",t("v55.audit.module"),"",platformModules.map(m=>[m,t(m==="administration"?"v54.module.administration":m)]),p.get("module")??"")}${select("auditAction",t("v55.audit.action"),"",actions.map(a=>[a,t(`v55.audit.action.${a}`)]),p.get("action")??"")}${select("auditSeverity",t("v55.audit.severity"),"",[["info",t("v55.audit.severity.info")],["warning",t("v55.audit.severity.warning")],["critical",t("v55.audit.severity.critical")]],p.get("severity")??"")}${select("auditActor",t("v55.audit.actor"),"",auditActors().map(a=>[a,a]),p.get("actor")??"")}</div><div class="toolbar audit-filter-actions"><button class="btn btn-primary" id="applyAuditFilters">${t("v55.audit.apply")}</button><button class="btn" id="resetAuditFilters">${t("v55.audit.reset")}</button><span class="subtle">${t("v55.audit.found",{count:rows.length})}</span></div></div>
<div class="card audit-table-card"><div class="table-wrap"><table class="table audit-table"><thead><tr><th>${t("v55.audit.time")}</th><th>${t("v55.audit.actor")}</th><th>${t("v55.audit.event")}</th><th>${t("v55.audit.object")}</th><th>${t("v55.audit.change")}</th><th>${t("v55.audit.integrityRef")}</th></tr></thead><tbody>${rows.map(row).join("")}</tbody></table></div>${rows.length?"":`<div class="empty">${t("v55.audit.empty")}</div>`}</div>
<div class="grid grid-2 u-mt-16"><div class="card card-pad audit-principle"><span class="audit-principle-icon">◇</span><div><h3>${t("v55.audit.principleTitle")}</h3><p>${t("v55.audit.principleText")}</p></div></div><div class="card card-pad audit-principle"><span class="audit-principle-icon">⌁</span><div><h3>${t("v55.audit.traceTitle")}</h3><p>${t("v55.audit.traceText")}</p></div></div></div></section>`}
function kpi(label:string,value:number,note:string,kind:string){return`<div class="card audit-kpi"><span class="audit-kpi-icon ${kind}">${kind==="today"?"◷":kind==="changes"?"↺":kind==="critical"?"!":"≡"}</span><div><small>${label}</small><strong>${value}</strong><span>${note}</span></div></div>`}
function select(id:string,label:string,first:string,opts:string[][],value:string){return`<div class="form-field"><label>${label}</label><select id="${id}"><option value="">${t("v55.audit.all")}</option>${opts.map(([v,l])=>`<option value="${esc(v)}" ${v===value?"selected":""}>${esc(l)}</option>`).join("")}</select></div>`}
function row(e:AuditEvent){return`<tr class="audit-event-row" data-audit-id="${e.id}"><td><strong>${fmt(e.at)}</strong><small>${e.source==="system"?t("v55.audit.systemSource"):t("v55.audit.userSource")}</small></td><td><div class="audit-actor"><span>${e.actor.slice(0,2).toUpperCase()}</span><div><strong>${esc(e.actor)}</strong><small>${t(roleLabelKey(e.actorRole))}</small></div></div></td><td><span class="audit-action-badge ${e.action}">${t(`v55.audit.action.${e.action}`)}</span><p>${esc(e.note)}</p></td><td><strong>${esc(e.entityLabel)}</strong><small>${t(`v55.audit.entity.${e.entityType}`)} · ${e.module}</small></td><td>${e.field?`<div class="audit-change"><b>${esc(e.field)}</b><span class="before">${esc(e.oldValue??"—")}</span><i>→</i><span class="after">${esc(e.newValue??"—")}</span></div>`:`<span class="subtle">—</span>`}</td><td><span class="audit-integrity-ref ${e.severity}">${e.integrityRef}</span></td></tr>`}
export function bindAudit(){document.querySelector("#applyAuditFilters")?.addEventListener("click",apply);document.querySelector("#resetAuditFilters")?.addEventListener("click",()=>navigate("audit"));document.querySelector("#clearAuditEntity")?.addEventListener("click",()=>navigate("audit"));document.querySelector<HTMLInputElement>("#auditSearch")?.addEventListener("keydown",e=>{if(e.key==="Enter")apply()});document.querySelectorAll<HTMLElement>("[data-audit-id]").forEach(el=>el.addEventListener("click",()=>showDetail(el.dataset.auditId!)));document.querySelector("#auditExport")?.addEventListener("click",exportCsv)}
function apply(){const p=new URLSearchParams();const fields:[[string,string]]|any=[["q","auditSearch"],["module","auditModule"],["action","auditAction"],["severity","auditSeverity"],["actor","auditActor"]];for(const[k,id]of fields){const v=(document.querySelector<HTMLInputElement|HTMLSelectElement>(`#${id}`)?.value??"").trim();if(v)p.set(k,v)}navigate("audit"+(p.toString()?`?${p}`:""))}
function showDetail(id:string){const e=auditEvents().find(x=>x.id===id);if(!e)return;openLocalizedModal(t("v55.audit.detailTitle"),`<div class="audit-detail"><div class="audit-detail-head"><span class="audit-event-icon ${e.severity}">${e.source==="system"?"⚙":"↺"}</span><div><span>${t(`v55.audit.action.${e.action}`)} · ${fmt(e.at)}</span><h3>${esc(e.entityLabel)}</h3><p>${esc(e.note)}</p></div></div><div class="audit-detail-grid"><div><span>${t("v55.audit.actor")}</span><strong>${esc(e.actor)}</strong><small>${t(roleLabelKey(e.actorRole))}</small></div><div><span>${t("v55.audit.module")}</span><strong>${esc(e.module)}</strong></div><div><span>${t("v55.audit.object")}</span><strong>${t(`v55.audit.entity.${e.entityType}`)} · ${esc(e.entityId)}</strong></div><div><span>${t("v55.audit.integrityRef")}</span><strong>${e.integrityRef}</strong></div></div>${e.field?`<div class="audit-detail-change"><span>${esc(e.field)}</span><div><section><small>${t("v55.audit.before")}</small><strong>${esc(e.oldValue??"—")}</strong></section><i>→</i><section><small>${t("v55.audit.after")}</small><strong>${esc(e.newValue??"—")}</strong></section></div></div>`:""}<div class="audit-detail-note"><strong>${t("v55.audit.immutableNoteTitle")}</strong><p>${t("v55.audit.immutableNote")}</p></div></div>`,`<button class="btn" data-modal-close>${t("common.close")}</button>${e.route?`<button class="btn btn-primary" id="auditOpenSource">${t("v55.audit.openSource")}</button>`:""}`);if(e.route)setTimeout(()=>document.querySelector("#auditOpenSource")?.addEventListener("click",()=>navigate(e.route!)),0)}
function exportCsv(){const rows=filtered(),csv=["Time,Actor,Role,Module,Action,Entity type,Entity ID,Field,Old value,New value,Note,Integrity ref",...rows.map(e=>[e.at,e.actor,e.actorRole,e.module,e.action,e.entityType,e.entityId,e.field??"",e.oldValue??"",e.newValue??"",e.note,e.integrityRef].map(v=>`"${String(v).replace(/"/g,'""')}"`).join(","))].join("\n");const blob=new Blob(["\uFEFF"+csv],{type:"text/csv;charset=utf-8"}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download="estateflow-audit-trail.csv";a.click();URL.revokeObjectURL(url);recordAudit({module:"administration",action:"export",entityType:"system",entityId:"AUDIT",entityLabel:"Audit Trail",route:"audit",field:"Export",oldValue:"—",newValue:`CSV · ${rows.length} rows`,note:"Audit Trail exported by authorized user.",severity:"warning"});toastLocalized(t("v55.audit.exported"))}
