import {clients,deals,contracts,paymentSchedule,powersOfAttorney,warrantyCases,handoverCases,mortgageApplications} from "../data/mock";
import {clientDocuments,relatedPeople,clientInterests,clientOffers,clientReservations,clientCommunications,clientKycProfiles,kycChecklist} from "../data/client360";
import type {KycChecklistItem,KycCheckStatus} from "../data/client360";
import {amd,badge,clientTypeLabel,escapeHtml,initials,paymentSourceLabel,priorityLabel,statusLabel} from "../utils";
import {navigate} from "../router";
import {closeModal,formValue,openLocalizedModal,toastLocalized} from "../components/layout";
import {bindTabs} from "../components/tabs";
import {t} from "../i18n";
import {demoText} from "../demo-i18n";
import{canAction}from"../services/permissions";
import{entityAuditPanel}from"../components/audit-panel";
import{recordAudit}from"../services/audit";

const clientDocumentTypeCode:Record<string,string>={
  idCard:"clientDetail.idCard",passport:"clientDetail.passport",incomeCertificate:"clientDetail.incomeCertificate",spouseConsent:"clientDetail.spouseConsent",corporateDocument:"clientDetail.corporateDocument",
  maritalCertificate:"v42.doc.maritalCertificate",stateRegistration:"v42.doc.stateRegistration",charter:"v42.doc.charter",majorTransactionApproval:"v42.doc.majorTransactionApproval",directorAppointment:"v42.doc.directorAppointment",soleProprietorRegistration:"v42.doc.soleProprietorRegistration",uboDeclaration:"v42.doc.uboDeclaration"
};
const relatedRoleCode:Record<string,string>={spouse:"clientDetail.spouse",coBorrower:"clientDetail.coBorrower",representative:"clientDetail.representative",beneficialOwner:"clientDetail.beneficialOwner",directorSignatory:"clientDetail.directorSignatory",founder:"v42.profile.founder",authorizedSignatory:"v42.profile.authorizedSignatory"};
const documentTypeLabel=(value:string)=>clientDocumentTypeCode[value]?t(clientDocumentTypeCode[value]):demoText(value);
const relatedRoleLabel=(value:string)=>relatedRoleCode[value]?t(relatedRoleCode[value]):demoText(value);
const kycLabel=(value:string)=>t(`v42.kyc.check.${value}`);

const tabs=[
  ["overview","clientDetail.tab.overview"],["profile","v42.tab.profile"],["kyc","v42.tab.kyc"],["documents","clientDetail.tab.documents"],["related","clientDetail.tab.related"],["interests","clientDetail.tab.interests"],["offers","clientDetail.tab.offers"],["reservations","clientDetail.tab.reservations"],
  ["deals","clientDetail.tab.deals"],["contracts","clientDetail.tab.contracts"],["payments","clientDetail.tab.payments"],["communications","clientDetail.tab.communications"],["service","clientDetail.tab.service"],["audit","v55.audit.nav"]
] as const;

export function clientDetailPage(id:string){
  const c=clients.find(x=>x.id===id);
  if(!c)return`<section class="page"><div class="card card-pad">${t("clientDetail.clientNotFound")}</div></section>`;
  const ds=deals.filter(d=>d.clientId===c.id),cs=contracts.filter(x=>x.clientId===c.id),schedules=paymentSchedule.filter(p=>ds.some(d=>d.id===p.dealId));
  const docs=clientDocuments.filter(x=>x.clientId===c.id),related=relatedPeople.filter(x=>x.clientId===c.id),interests=clientInterests.filter(x=>x.clientId===c.id),offers=clientOffers.filter(x=>x.clientId===c.id),reservations=clientReservations.filter(x=>x.clientId===c.id),comms=clientCommunications.filter(x=>x.clientId===c.id);
  const warranties=warrantyCases.filter((x:any)=>x.clientId===c.id),handovers=handoverCases.filter((x:any)=>x.clientId===c.id),poas=powersOfAttorney.filter((x:any)=>ds.some(d=>d.id===x.relatedDeal)||x.principal===c.name),mortgages=mortgageApplications.filter(x=>x.clientId===c.id);
  const checks=kycChecklist.filter(x=>x.clientId===c.id),kyc=clientKycProfiles.find(x=>x.clientId===c.id);
  const paid=schedules.reduce((s,p)=>s+p.paid,0),planned=schedules.reduce((s,p)=>s+p.amount,0);
  const counters={docs,related,interests,offers,reservations,ds,cs,schedules,comms,warranties,checks};
  const visibleTabs=tabs.filter(([key])=>key!=="payments"||canAction("client.financial"));
  return`<section class="page" id="client360">
    <div class="breadcrumbs"><span>CRM</span><span>›</span><span>${t("clientDetail.clients")}</span><span>›</span><span>${c.id}</span></div>
    <div class="detail-header"><div class="detail-title">
      <small>${c.id} · ${clientTypeLabel(c.type)}</small>
      <div class="u-inline-center-12"><div class="avatar accent u-avatar-lg">${initials(c.name)}</div><h1 class="u-m0">${c.name}</h1></div>
      <div class="toolbar u-mt-10">${badge(c.verification)}${kyc?riskChip(kyc.risk):""}<span class="chip">${c.manager}</span></div>
    </div><div class="toolbar"><button class="btn" id="backClients">${t("clientDetail.registry")}</button><button class="btn" id="headerKyc">${t("v42.kyc.open")}</button><button class="btn" id="headerDocuments">${t("clientDetail.documents")}</button><button class="btn btn-primary" id="newClientDeal">${t("clientDetail.newDeal")}</button></div></div>
    <div class="client-quick-stats">
      ${quickStat(t("clientDetail.activeDeals"),String(ds.length),"◇")}${quickStat(t("clientDetail.totalValue"),sensitive("financial",amd(ds.reduce((s,d)=>s+d.amount,0))),"₳")}${quickStat(t("clientDetail.paid"),sensitive("financial",amd(paid)),"✓")}${quickStat(t("clientDetail.openObligations"),sensitive("financial",planned?amd(Math.max(planned-paid,0)):amd(c.outstanding)),"!")}${quickStat(t("v42.kyc.readiness"),kyc?`${kyc.score}%`:"—","◎")}
    </div>
    <div class="tabs client-tabs">${visibleTabs.map(([key,labelKey],i)=>`<button class="tab ${i===0?"active":""}" data-tab-target="${key}">${t(labelKey)}${tabCounter(key,counters)}</button>`).join("")}</div>
    <div class="client-tab-content">
      <div data-tab-panel="overview">${overviewPanel(c,ds,cs,schedules,docs,poas,mortgages,handovers,warranties,kyc,checks)}</div>
      <div data-tab-panel="profile" hidden>${profilePanel(c,related,docs)}</div>
      <div data-tab-panel="kyc" hidden>${kycPanel(c,kyc,checks)}</div>
      <div data-tab-panel="documents" hidden>${documentsPanel(docs)}</div><div data-tab-panel="related" hidden>${relatedPanel(c,related,poas)}</div><div data-tab-panel="interests" hidden>${interestsPanel(interests)}</div><div data-tab-panel="offers" hidden>${offersPanel(offers)}</div><div data-tab-panel="reservations" hidden>${reservationsPanel(reservations)}</div><div data-tab-panel="deals" hidden>${dealsPanel(ds)}</div><div data-tab-panel="contracts" hidden>${contractsPanel(cs)}</div>${canAction("client.financial")?`<div data-tab-panel="payments" hidden>${paymentsPanel(schedules)}</div>`:""}<div data-tab-panel="communications" hidden>${communicationsPanel(comms)}</div><div data-tab-panel="service" hidden>${servicePanel(handovers,warranties)}</div><div data-tab-panel="audit" hidden>${entityAuditPanel("client",c.id)}</div>
    </div>
  </section>`;
}

function quickStat(label:string,value:string,icon:string){return`<div class="card client-quick-stat"><div class="metric-icon">${icon}</div><div><span>${label}</span><strong>${value}</strong></div></div>`}
function tabCounter(key:string,x:any){const map:Record<string,number>={kyc:x.checks.length,documents:x.docs.length,related:x.related.length,interests:x.interests.length,offers:x.offers.length,reservations:x.reservations.length,deals:x.ds.length,contracts:x.cs.length,payments:x.schedules.length,communications:x.comms.length,service:x.warranties.length};const n=map[key];return n?`<em>${n}</em>`:""}

function overviewPanel(c:any,ds:any[],cs:any[],schedules:any[],docs:any[],poas:any[],mortgages:any[],handovers:any[],warranties:any[],kyc:any,checks:KycChecklistItem[]){
  const due=schedules.filter(x=>["due","overdue","partial"].includes(x.status));
  const dealValue=ds.length?`${ds[0].id} · ${ds[0].propertyLabel}`:t("clientDetail.noActiveDeals");
  const dealNote=ds.length?demoText(ds[0].nextAction):"—";
  const contractValue=cs.length?`${cs[0].id} · ${demoText(cs[0].type)}`:t("clientDetail.noContractsYet");
  const contractNote=cs.length?clientStateText(cs[0].status):"—";
  const financeValue=due.length?t("clientDetail.obligationsNeedAttention",{count:due.length}):t("clientDetail.noCriticalPayments");
  const serviceValue=handovers.length?`${handovers[0].id} · ${clientStateText(handovers[0].status)}`:warranties.length?t("clientDetail.warrantyCaseCount",{count:warranties.length}):t("clientDetail.noPostSaleCases");
  const isCompany=["company","foreign-company"].includes(c.type);
  const identifier=isCompany?(c.taxId??c.registrationNumber):(c.personalNumber??"—");
  const country=isCompany?(c.countryOfRegistration??c.legalAddress?.country):(c.citizenship??c.taxResidency);
  const pendingChecks=checks.filter(x=>x.status!=="passed").length;
  return`<div class="client-summary"><div class="card card-pad">
    <div class="section-title"><div><h2>${t("clientDetail.client360Profile")}</h2><p>${t("v42.overview.subtitle")}</p></div><button class="btn btn-soft" data-open-client-tab="profile">${t("v42.profile.openFull")}</button></div>
    <div class="client-foundation-ribbon"><div><span>${t("v41.client.profileType")}</span><strong>${clientTypeLabel(c.type)}</strong></div><div><span>${t("v41.client.identifier")}</span><strong data-sensitive="personal">${identifier}</strong></div><div><span>${t("v41.client.language")}</span><strong>${c.preferredLanguage??"—"}</strong></div><div><span>${t("v41.client.country")}</span><strong>${country??"—"}</strong></div></div>
    <div class="profile-health-grid">
      ${profileHealthItem(t("v42.health.identity"),isCompany?(c.registrationNumber&&c.taxId):(c.personalNumber&&c.dateOfBirth),t("v42.health.identityNote"))}
      ${profileHealthItem(t("v42.health.address"),isCompany?c.legalAddress:c.registrationAddress,t("v42.health.addressNote"))}
      ${profileHealthItem(t("v42.health.bank"),(c.bankAccounts?.length??0)>0,t("v42.health.bankNote"))}
      ${profileHealthItem(t("v42.health.consent"),c.consentPersonalData,t("v42.health.consentNote"))}
    </div>
    <div class="section-title u-mt-22"><div><h2>${t("clientDetail.currentContext")}</h2><p>${t("clientDetail.whatIsHappeningWithTheClientNow")}</p></div></div>
    <div class="client-context-grid">${contextCard(t("clientDetail.deals"),dealValue,dealNote,"deals")}${contextCard(t("clientDetail.contracts"),contractValue,contractNote,"contracts")}${contextCard(t("clientDetail.finance"),financeValue,due.length?amd(due.reduce((sum,p)=>sum+(p.amount-p.paid),0)):"—","payments")}${contextCard(t("clientDetail.service"),serviceValue,warranties.length?demoText(warranties[0].title):"—","service")}</div>
  </div><div class="card card-pad kyc-overview-card">
    <div class="section-title"><div><h2>${t("client.kycCompliance")}</h2><p>${t("clientDetail.clientDealReadiness")}</p></div><div class="readiness-score ${kyc?.status==="review"?"warning":kyc?.status==="blocked"?"danger":""}">${kyc?.score??0}%</div></div>
    <div class="kyc-overview-meta"><div><span>${t("v42.kyc.decision")}</span>${kycStatusChip(kyc?.status??"review")}</div><div><span>${t("v42.kyc.risk")}</span>${riskChip(kyc?.risk??"medium")}</div><div><span>${t("v42.kyc.openChecks")}</span><strong>${pendingChecks}</strong></div></div>
    <div class="timeline">${checks.slice(0,5).map(x=>kycStep(kycLabel(x.code),x.note,x.status==="passed",x.status==="review"||x.status==="pending")).join("")}</div>
    <button class="btn btn-accent u-full u-mt-14" data-open-client-tab="kyc">${t("v42.kyc.openWorkspace")}</button>
    ${mortgages.length?`<div class="soft-callout"><span>${t("clientDetail.mortgage")}</span><strong>${mortgages[0].bank} · ${amd(mortgages[0].requestedAmount)}</strong><button class="btn btn-soft" data-mortgage-link="${mortgages[0].id}">${t("clientDetail.openApplication")}</button></div>`:""}
  </div></div>`;
}
function contextCard(title:string,value:string,note:string,tab:string){return`<button class="client-context-card" data-open-client-tab="${tab}"><span>${title}</span><strong>${value}</strong><small>${note}</small><b>${t("clientDetail.open")} →</b></button>`}
function kycStep(title:string,sub:string,done:boolean,current=false){return`<div class="timeline-item ${done?"done":current?"current":""}"><div class="timeline-dot"></div><div class="timeline-copy"><strong>${title}</strong><span>${sub}</span></div></div>`}
function profileHealthItem(title:string,ok:any,note:string){return`<div class="profile-health-item ${ok?"complete":"attention"}"><span>${ok?"✓":"!"}</span><div><strong>${title}</strong><small>${note}</small></div></div>`}

function profilePanel(c:any,related:any[],docs:any[]){
  const isCompany=["company","foreign-company"].includes(c.type);
  const primaryDoc=docs.find(x=>["idCard","passport","stateRegistration","soleProprietorRegistration"].includes(x.type));
  return`<div class="profile-workspace">
    <div class="profile-workspace-main">
      <div class="card card-pad profile-hero-card">
        <div class="section-title"><div><span class="section-eyebrow">${t("v42.profile.eyebrow")}</span><h2>${isCompany?t("v42.profile.companyProfile"):t("v42.profile.individualProfile")}</h2><p>${t("v42.profile.subtitle")}</p></div><button class="btn btn-primary" data-demo-action="edit-client">${t("clientDetail.edit")}</button></div>
        ${isCompany?companyProfile(c):individualProfile(c,primaryDoc)}
      </div>
      ${isCompany?corporateStructure(c):familyAndRelationships(c,related)}
      ${bankAccountsPanel(c)}
    </div>
    <div class="profile-workspace-side">
      ${addressPanel(c,isCompany)}
      ${consentsPanel(c)}
      <div class="card card-pad"><div class="section-title"><div><h2>${t("v42.profile.documentsReady")}</h2><p>${t("v42.profile.documentsReadySub")}</p></div><button class="btn btn-soft" data-open-client-tab="documents">${t("clientDetail.open")}</button></div><div class="profile-document-stat"><strong>${docs.filter(x=>x.status==="valid").length}</strong><span>${t("v42.profile.validDocs")}</span><b>${docs.filter(x=>x.status!=="valid").length}</b><span>${t("v42.profile.docsAttention")}</span></div></div>
    </div>
  </div>`;
}

function individualProfile(c:any,primaryDoc:any){return`<div class="profile-field-grid">
  ${field(t("v42.profile.lastName"),c.lastName)}${field(t("v42.profile.firstName"),c.firstName)}${field(t("v42.profile.middleName"),c.middleName)}${field(t("client.publicServiceNumber"),c.personalNumber,"personal")}
  ${field(t("v42.profile.birthDate"),c.dateOfBirth,"personal")}${field(t("v42.profile.birthPlace"),c.placeOfBirth,"personal")}${field(t("v42.profile.citizenship"),c.citizenship)}${field(t("v41.client.residency"),c.taxResidency)}
  ${field(t("v42.profile.maritalStatus"),c.maritalStatus?t(`v42.marital.${c.maritalStatus}`):"—")}${field(t("v42.profile.primaryDocument"),primaryDoc?`${documentTypeLabel(primaryDoc.type)} · ${primaryDoc.number}`:"—")}${field(t("clientDetail.phone"),c.phone,"personal")}${field(t("common.email"),c.email,"personal")}
</div>`}
function companyProfile(c:any){return`<div class="profile-field-grid">
  ${field(t("v42.profile.legalName"),c.name)}${field(t("v42.profile.shortName"),c.companyShortName)}${field(t("v42.profile.legalForm"),c.legalForm)}${field(t("client.taxId"),c.taxId,"personal")}
  ${field(t("v41.client.companyRegistration"),c.registrationNumber,"personal")}${field(t("v42.profile.registrationDate"),c.registrationDate)}${field(t("v42.profile.registrationCountry"),c.countryOfRegistration)}${field(t("v41.client.language"),c.preferredLanguage)}
  ${field(t("v42.profile.director"),c.director?.name)}${field(t("v42.profile.directorAuthority"),c.director?.authority)}${field(t("clientDetail.phone"),c.phone,"personal")}${field(t("common.email"),c.email,"personal")}
</div>`}
function field(label:string,value:any,sensitiveKind?:"personal"|"financial"){return`<div class="profile-field"><span>${label}</span><strong ${sensitiveKind?`data-sensitive="${sensitiveKind}"`:""}>${value||"—"}</strong></div>`}
function sensitive(kind:"personal"|"financial",value:string){return`<span data-sensitive="${kind}">${value}</span>`}

function familyAndRelationships(c:any,related:any[]){const family=related.filter(x=>["spouse","coBorrower"].includes(x.role));return`<div class="card card-pad"><div class="section-title"><div><h2>${t("v42.profile.family")}</h2><p>${t("v42.profile.familySub")}</p></div><button class="btn btn-soft" data-open-client-tab="related">${t("v42.profile.manage")}</button></div>${family.length?`<div class="profile-person-grid">${family.map(personCard).join("")}</div>`:`<div class="empty compact-empty">${t("v42.profile.noFamily")}</div>`}</div>`}
function corporateStructure(c:any){const people=[...(c.director?[{...c.director,role:"director"}]:[]),...(c.founders??[]),...(c.beneficialOwners??[]),...(c.authorizedSignatories??[])];return`<div class="card card-pad"><div class="section-title"><div><h2>${t("v42.profile.corporateStructure")}</h2><p>${t("v42.profile.corporateStructureSub")}</p></div><button class="btn btn-soft" data-open-client-tab="related">${t("v42.profile.manage")}</button></div><div class="profile-person-grid">${people.map((x:any)=>`<div class="profile-person-card"><div class="person"><div class="avatar">${initials(x.name)}</div><div><strong>${x.name}</strong><span>${personRoleLabel(x.role)}</span></div></div><div class="profile-person-meta">${x.sharePercent!=null?`<span>${t("v42.profile.share")}: <b>${x.sharePercent}%</b></span>`:""}${x.authority?`<span>${x.authority}</span>`:""}</div>${clientState(x.verification??"review")}</div>`).join("")}</div></div>`}
function personCard(x:any){return`<div class="profile-person-card"><div class="person"><div class="avatar">${initials(x.name)}</div><div><strong>${x.name}</strong><span>${relatedRoleLabel(x.role)}</span></div></div><div class="profile-person-meta"><span>${x.phone}</span><span>${demoText(x.note)}</span></div>${clientState(x.verification)}</div>`}
function personRoleLabel(role:string){const map:Record<string,string>={director:"v42.profile.director",founder:"v42.profile.founder","beneficial-owner":"clientDetail.beneficialOwner",signatory:"v42.profile.authorizedSignatory"};return map[role]?t(map[role]):role}

function addressPanel(c:any,isCompany:boolean){const a1=isCompany?c.legalAddress:c.registrationAddress,a2=isCompany?c.businessAddress:c.residenceAddress;return`<div class="card card-pad"><div class="section-title"><div><h2>${t("v42.profile.addresses")}</h2><p>${t("v42.profile.addressesSub")}</p></div></div><div class="address-stack">${addressCard(isCompany?t("v42.profile.legalAddress"):t("v42.profile.registrationAddress"),a1,true)}${addressCard(isCompany?t("v42.profile.businessAddress"):t("v42.profile.residenceAddress"),a2,false)}</div></div>`}
function addressCard(title:string,a:any,primary:boolean){return`<div class="address-card ${primary?"primary":""}" data-sensitive="personal"><div><span>${title}</span>${primary?`<b>${t("v42.profile.primary")}</b>`:""}</div><strong>${a?`${a.address}, ${a.city}`:"—"}</strong><small>${a?`${a.country}${a.postalCode?` · ${a.postalCode}`:""}`:"—"}</small></div>`}
function bankAccountsPanel(c:any){const rows=c.bankAccounts??[];return`<div class="card card-pad" data-sensitive="financial"><div class="section-title"><div><h2>${t("v42.profile.bankAccounts")}</h2><p>${t("v42.profile.bankAccountsSub")}</p></div><button class="btn btn-primary" data-demo-action="add-bank-account">${t("v42.profile.addAccount")}</button></div>${rows.length?`<div class="bank-account-grid">${rows.map((x:any)=>`<div class="bank-account-card"><div class="bank-account-head"><div><span>${x.bank}</span><strong>${x.currency}</strong></div>${x.isPrimary?`<b>${t("v42.profile.primary")}</b>`:""}</div><strong class="bank-iban">${x.iban}</strong><div class="bank-account-meta"><span>${x.accountName??c.name}</span><span>SWIFT ${x.swift??"—"}</span></div></div>`).join("")}</div>`:`<div class="empty compact-empty">${t("v42.profile.noAccounts")}</div>`}</div>`}
function consentsPanel(c:any){return`<div class="card card-pad"><div class="section-title"><div><h2>${t("v42.profile.consents")}</h2><p>${t("v42.profile.consentsSub")}</p></div></div><div class="consent-list">${consentRow(t("v42.profile.consentPersonal"),c.consentPersonalData,true)}${consentRow(t("v42.profile.consentElectronic"),c.consentElectronicCommunication,true)}${consentRow(t("v42.profile.consentDocuments"),c.consentDocumentDelivery,true)}${consentRow(t("v42.profile.consentMarketing"),c.consentMarketing,false)}</div></div>`}
function consentRow(label:string,value:boolean|undefined,required:boolean){return`<div class="consent-row"><span class="consent-check ${value?"on":"off"}">${value?"✓":"—"}</span><div><strong>${label}</strong><small>${required?t("v42.profile.requiredConsent"):t("v42.profile.optionalConsent")}</small></div><b>${value?t("v42.common.granted"):t("v42.common.notGranted")}</b></div>`}

function kycPanel(c:any,profile:any,checks:KycChecklistItem[]){
  const passed=checks.filter(x=>x.status==="passed").length,pending=checks.filter(x=>x.status==="pending"||x.status==="review").length,failed=checks.filter(x=>x.status==="failed").length;
  return`<div class="kyc-workspace">
    <div class="kyc-summary-card card"><div class="kyc-score-ring" style="--kyc-pct:${profile?.score??0}%"><div><strong>${profile?.score??0}%</strong><span>${t("v42.kyc.readiness")}</span></div></div><div class="kyc-summary-copy"><span class="section-eyebrow">${t("v42.kyc.eyebrow")}</span><h2>${t("v42.kyc.workspace")}</h2><p>${profile?.riskNote??t("v42.kyc.noProfile")}</p><div class="toolbar">${kycStatusChip(profile?.status??"review")}${riskChip(profile?.risk??"medium")}<span class="chip">${t("v42.kyc.lastReview")}: ${profile?.reviewedAt??"—"}</span></div></div><div class="kyc-summary-actions"><button class="btn btn-primary" data-demo-action="finalize-kyc">${t("v42.kyc.finalize")}</button><button class="btn" data-demo-action="edit-client">${t("v42.kyc.profileData")}</button></div></div>
    <div class="kyc-metrics">${kycMetric(t("v42.kyc.passed"),passed,"success")}${kycMetric(t("v42.kyc.inReview"),pending,"warning")}${kycMetric(t("v42.kyc.failed"),failed,"danger")}${kycMetric(t("v42.kyc.mandatory"),checks.filter(x=>x.mandatory).length,"neutral")}</div>
    <div class="grid grid-2 kyc-grid">
      <div class="card card-pad"><div class="section-title"><div><h2>${t("v42.kyc.checklist")}</h2><p>${t("v42.kyc.checklistSub")}</p></div></div><div class="kyc-check-list">${checks.map(kycCheckRow).join("")||`<div class="empty compact-empty">${t("v42.kyc.noChecks")}</div>`}</div></div>
      <div class="kyc-side-stack"><div class="card card-pad"><div class="section-title"><div><h2>${t("v42.kyc.riskAssessment")}</h2><p>${t("v42.kyc.riskAssessmentSub")}</p></div></div><div class="risk-brief"><div><span>${t("v42.kyc.risk")}</span>${riskChip(profile?.risk??"medium")}</div><div><span>${t("v42.kyc.decision")}</span>${kycStatusChip(profile?.status??"review")}</div><div><span>${t("v42.kyc.reviewer")}</span><strong>${profile?.reviewedBy??"—"}</strong></div></div><div class="risk-note"><span>${t("v42.kyc.riskNote")}</span><p>${profile?.riskNote??"—"}</p></div></div>
      <div class="card card-pad"><div class="section-title"><div><h2>${t("v42.kyc.sourceOfFunds")}</h2><p>${t("v42.kyc.sourceOfFundsSub")}</p></div></div><div class="source-funds-card"><span>₳</span><div><strong>${profile?.sourceOfFunds??"—"}</strong><small>${t("v42.kyc.sourceRecorded")}</small></div></div></div></div>
    </div>
  </div>`;
}
function kycMetric(label:string,value:number,tone:string){return`<div class="card kyc-metric ${tone}"><span>${label}</span><strong>${value}</strong></div>`}
function kycCheckRow(x:KycChecklistItem){return`<button class="kyc-check-row" data-kyc-check="${x.id}"><span class="kyc-check-icon ${x.status}">${x.status==="passed"?"✓":x.status==="failed"?"×":x.status==="review"?"!":"…"}</span><div><div><strong>${kycLabel(x.code)}</strong>${x.mandatory?`<em>${t("v42.kyc.required")}</em>`:""}</div><p>${x.note}</p><small>${x.owner} · ${x.updatedAt}${x.evidence&&x.evidence!=="—"?` · ${x.evidence}`:""}</small></div><span class="status ${kycTone(x.status)}">${t(`v42.kyc.status.${x.status}`)}</span></button>`}
function kycTone(status:string){return status==="passed"?"success":status==="failed"?"danger":status==="review"||status==="pending"?"warning":"neutral"}
function riskChip(risk:string){return`<span class="risk-chip ${risk}"><i></i>${t(`v42.risk.${risk}`)}</span>`}
function kycStatusChip(status:string){return`<span class="status ${status==="clear"?"success":status==="blocked"?"danger":"warning"}">${t(`v42.kyc.decision.${status}`)}</span>`}

function documentsPanel(rows:any[]){return sectionWrap(t("clientDetail.clientDocuments"),t("v42.documents.subtitle"),`<div class="toolbar"><button class="btn btn-primary" data-demo-action="upload-document">${t("clientDetail.uploadDocument")}</button><button class="btn" data-demo-action="scan-document">${t("client.ocrIdReader")}</button></div>`,rows.length?`<div class="table-wrap"><table class="table"><thead><tr><th>${t("clientDetail.document")}</th><th>${t("clientDetail.number")}</th><th>${t("v42.documents.issuer")}</th><th>${t("clientDetail.deadline")}</th><th>${t("clientDetail.source")}</th><th>${t("clientDetail.status")}</th><th></th></tr></thead><tbody>${rows.map(x=>`<tr><td><strong>${documentTypeLabel(x.type)}</strong><div class="table-sub">${x.fileName??x.id}</div></td><td>${x.number}</td><td>${x.issuer??"—"}<div class="table-sub">${x.issueCountry??""}</div></td><td>${x.expiresAt??"—"}</td><td>${x.source}</td><td>${clientState(x.status)}</td><td><button class="btn btn-soft" data-doc-preview="${x.id}">${t("clientDetail.open")}</button></td></tr>`).join("")}</tbody></table></div>`:empty(t("clientDetail.noDocumentsAddedYet")))}
function relatedPanel(c:any,rows:any[],poas:any[]){const corp=["company","foreign-company"].includes(c.type);return sectionWrap(t("clientDetail.relatedPartiesAndAuthorities"),corp?t("v42.related.companySub"):t("clientDetail.spousesCoBorrowersDirectorsBeneficiariesAndRepresentatives"),`<button class="btn btn-primary" data-demo-action="add-related">${t("clientDetail.linkPerson")}</button>`,rows.length?`<div class="related-grid">${rows.map(x=>`<div class="card related-person-card"><div class="person"><div class="avatar">${initials(x.name)}</div><div><strong>${x.name}</strong><span>${relatedRoleLabel(x.role)}</span></div></div><div class="related-details"><span>${x.phone}</span><span>${clientState(x.verification)}</span></div><p>${demoText(x.note)}</p></div>`).join("")}</div>${poas.length?`<div class="card card-pad u-mt-16"><div class="section-title"><div><h2>${t("clientDetail.powersOfAttorney")}</h2><p>${t("clientDetail.activeAuthoritiesForLinkedDeals")}</p></div><button class="btn" id="openClientPoa">${t("clientDetail.powerOfAttorneyRegistry")}</button></div>${poas.map((x:any)=>`<div class="attention-item"><div class="attention-badge">POA</div><div class="attention-copy"><strong>${x.documentNo} · ${x.representative}</strong><span>${demoText(x.scope)}</span></div>${clientState(x.status)}</div>`).join("")}</div>`:""}`:empty(t("clientDetail.noRelatedPartiesSpecified")))}
function interestsPanel(rows:any[]){return sectionWrap(t("clientDetail.interestsAndNeeds"),t("clientDetail.savedPropertySelectionCriteria"),`<button class="btn btn-primary" data-demo-action="add-interest">${t("clientDetail.newInterest")}</button>`,rows.length?`<div class="interest-grid">${rows.map(x=>`<div class="card card-pad interest-card"><div class="section-title"><div><span class="priority ${x.priority==='hot'?'high':x.priority==='warm'?'medium':'low'}">${priorityLabel(x.priority)}</span><h2 class="u-mt-8">${x.project}</h2><p>${demoText(x.type)}</p></div></div><div class="info-list"><div class="info-box"><span>${t("clientDetail.rooms")}</span><strong>${x.rooms}</strong></div><div class="info-box"><span>${t("clientDetail.budget")}</span><strong>${x.budget}</strong></div><div class="info-box"><span>${t("clientDetail.location")}</span><strong>${demoText(x.districts)}</strong></div><div class="info-box"><span>${t("clientDetail.financing")}</span><strong>${demoText(x.payment)}</strong></div></div><button class="btn btn-accent u-mt-14" data-property-search="1">${t("clientDetail.matchProperties")}</button></div>`).join("")}</div>`:empty(t("clientDetail.selectionCriteriaNotRecordedYet")))}
function offersPanel(rows:any[]){return sectionWrap(t("clientDetail.commercialOffers"),t("clientDetail.historyOfSentOptionsAndClientResponse"),`<button class="btn btn-primary" data-demo-action="create-offer">${t("clientDetail.newOffer")}</button>`,rows.length?`<div class="table-wrap"><table class="table"><thead><tr><th>${t("clientDetail.offer")}</th><th>${t("clientDetail.created")}</th><th>${t("clientDetail.properties")}</th><th>${t("clientDetail.amount")}</th><th>${t("clientDetail.validUntil")}</th><th>${t("clientDetail.status")}</th><th></th></tr></thead><tbody>${rows.map(x=>`<tr><td><strong>${x.id}</strong></td><td>${demoText(x.createdAt)}</td><td>${x.objects.join(", ")}</td><td>${amd(x.total)}</td><td>${x.validUntil}</td><td>${clientState(x.status)}</td><td><button class="btn btn-soft" data-demo-action="preview-offer">${t("clientDetail.preview")}</button></td></tr>`).join("")}</tbody></table></div>`:empty(t("clientDetail.noCommercialOffers")))}
function reservationsPanel(rows:any[]){return sectionWrap(t("clientDetail.reservations"),t("clientDetail.reservationHistoryDeadlinesPaymentsAndConversionToDeal"),"",rows.length?`<div class="table-wrap"><table class="table"><thead><tr><th>${t("clientDetail.reservation")}</th><th>${t("clientDetail.property")}</th><th>${t("clientDetail.period")}</th><th>${t("clientDetail.contribution")}</th><th>${t("clientDetail.payment")}</th><th>${t("clientDetail.status")}</th><th>${t("clientDetail.deal")}</th></tr></thead><tbody>${rows.map(x=>`<tr><td><strong>${x.id}</strong></td><td>${x.property}</td><td>${x.from}<br><span class="table-sub">${t("clientDetail.until")} ${x.until}</span></td><td>${amd(x.fee)}</td><td>${x.paid?clientState("paid"):clientState("due")}</td><td>${clientState(x.status)}</td><td>${x.dealId?`<button class="btn btn-soft" data-deal="${x.dealId}">${x.dealId}</button>`:"—"}</td></tr>`).join("")}</tbody></table></div>`:empty(t("clientDetail.noReservations")))}
function dealsPanel(rows:any[]){return sectionWrap(t("clientDetail.clientDeals"),t("clientDetail.allActiveAndCompletedPropertyDeals"),"",rows.length?`<div class="deal-cards">${rows.map(d=>`<button class="card client-deal-card" data-deal="${d.id}"><div><span>${d.id}</span><strong>${d.propertyLabel}</strong><small>${demoText(d.nextAction)}</small></div><div><b>${amd(d.amount)}</b>${badge(d.status)}</div></button>`).join("")}</div>`:empty(t("clientDetail.noDealsYet")))}
function contractsPanel(rows:any[]){return sectionWrap(t("clientDetail.contractsAndAgreements"),t("clientDetail.versionsStatusesAndLegalReadiness"),"",rows.length?`<div class="table-wrap"><table class="table"><thead><tr><th>${t("clientDetail.contract")}</th><th>${t("clientDetail.type")}</th><th>${t("clientDetail.property")}</th><th>${t("clientDetail.amount")}</th><th>${t("clientDetail.version")}</th><th>${t("clientDetail.deviations")}</th><th>${t("clientDetail.status")}</th><th></th></tr></thead><tbody>${rows.map(x=>`<tr><td><strong>${x.id}</strong></td><td>${demoText(x.type)}</td><td>${x.propertyLabel}</td><td>${amd(x.amount)}</td><td>${x.versions.at(-1)?.version??"—"}</td><td>${x.nonStandardClauses}</td><td>${clientState(x.status)}</td><td><button class="btn btn-soft" data-contract="${x.id}">${t("clientDetail.open")}</button></td></tr>`).join("")}</tbody></table></div>`:empty(t("clientDetail.noContracts")))}
function paymentsPanel(rows:any[]){const paid=rows.reduce((s,x)=>s+x.paid,0),total=rows.reduce((s,x)=>s+x.amount,0);return`<div data-sensitive="financial"><div class="grid grid-3 u-mb-16">${quickStat(t("clientDetail.scheduled"),amd(total),"₳")}${quickStat(t("clientDetail.paid"),sensitive("financial",amd(paid)),"✓")}${quickStat(t("clientDetail.balance"),amd(Math.max(total-paid,0)),"!")}</div>${sectionWrap(t("clientDetail.paymentSchedule"),t("clientDetail.buyerReservationAndBankFinancing"),`<button class="btn" data-global-route="payments">${t("clientDetail.openFinanceModule")}</button>`,rows.length?`<div class="table-wrap"><table class="table"><thead><tr><th>${t("clientDetail.stage")}</th><th>${t("clientDetail.deal")}</th><th>${t("clientDetail.deadline")}</th><th>${t("clientDetail.source")}</th><th>${t("clientDetail.plan")}</th><th>${t("clientDetail.paid")}</th><th>${t("clientDetail.balance")}</th><th>${t("clientDetail.status")}</th></tr></thead><tbody>${rows.map(x=>`<tr><td><strong>${demoText(x.title)}</strong></td><td><button class="link-button" data-deal="${x.dealId}">${x.dealId}</button></td><td>${x.dueDate}</td><td><span class="chip ${x.source==='mortgage'?'accent':''}">${paymentSourceLabel(x.source)}</span></td><td>${amd(x.amount)}</td><td>${amd(x.paid)}</td><td>${amd(x.amount-x.paid)}</td><td>${badge(x.status)}</td></tr>`).join("")}</tbody></table></div>`:empty(t("clientDetail.noPaymentSchedule")))}</div>`}
function communicationsPanel(rows:any[]){return sectionWrap(t("clientDetail.communicationHistory"),t("clientDetail.callsEmailsMeetingsSmsAndInternalNotes"),`<button class="btn btn-primary" data-demo-action="add-communication">${t("clientDetail.addInteraction")}</button>`,rows.length?`<div class="communication-timeline">${rows.map(x=>`<div class="communication-row"><div class="communication-icon">${commIcon(x.type)}</div><div class="communication-copy"><div><strong>${demoText(x.title)}</strong><span>${demoText(x.at)} · ${x.owner}</span></div><p>${demoText(x.text)}</p></div></div>`).join("")}</div>`:empty(t("clientDetail.noCommunicationsRecordedYet")))}
function servicePanel(handovers:any[],warranties:any[]){return`<div class="grid grid-2"><div class="card card-pad"><div class="section-title"><div><h2>${t("clientDetail.propertyHandover")}</h2><p>${t("clientDetail.inspectionDefectsActAndKeys")}</p></div></div>${handovers.length?handovers.map(x=>`<button class="service-link-card" data-handover="${x.id}"><div><strong>${x.propertyLabel}</strong><span>${x.id} · ${x.plannedAt}</span></div>${badge(x.status)}</button>`).join(""):empty(t("clientDetail.handoverProcessNotOpenedYet"))}</div><div class="card card-pad"><div class="section-title"><div><h2>${t("clientDetail.warrantyService")}</h2><p>${t("clientDetail.requestsAfterHandover")}</p></div><button class="btn" data-global-route="service">${t("clientDetail.allRequests")}</button></div>${warranties.length?warranties.map(x=>`<button class="service-link-card" data-warranty="${x.id}"><div><strong>${demoText(x.title)}</strong><span>${x.id} · ${x.propertyLabel}</span></div>${badge(x.status)}</button>`).join(""):empty(t("clientDetail.noWarrantyCases"))}</div></div>`}
function sectionWrap(title:string,sub:string,action:string,body:string){return`<div class="card card-pad"><div class="section-title"><div><h2>${title}</h2><p>${sub}</p></div>${action}</div>${body}</div>`}
function empty(text:string){return`<div class="empty compact-empty">${text}</div>`}
function commIcon(type:string){return({call:"☎",email:"✉",meeting:"◎",sms:"◫",note:"✎"} as Record<string,string>)[type]??"·"}
function clientStateText(state:string){return statusLabel(state)}
function clientState(state:string){const cls=(["valid","verified","accepted","converted","paid","signed","registered","handed-over"].includes(state)?"success":["expiring","review","active","due","legal-review","client-review","signature","notary","viewed","readiness","inspection","defects","reinspection","acceptance"].includes(state)?"warning":["missing","expired"].includes(state)?"danger":"neutral");return`<span class="status ${cls}">${clientStateText(state)}</span>`}

export function bindClientDetail(){
  bindTabs("#client360");
  document.querySelector("#backClients")?.addEventListener("click",()=>navigate("clients"));document.querySelector("#headerDocuments")?.addEventListener("click",()=>openTab("documents"));document.querySelector("#headerKyc")?.addEventListener("click",()=>openTab("kyc"));document.querySelector("#newClientDeal")?.addEventListener("click",()=>{const id=location.hash.split("/").pop()!;navigate("deals?client="+id)});document.querySelector("#openClientPoa")?.addEventListener("click",()=>navigate("legal/poa"));
  document.querySelectorAll<HTMLElement>("[data-open-client-tab]").forEach(el=>el.addEventListener("click",()=>openTab(el.dataset.openClientTab!)));document.querySelectorAll<HTMLElement>("[data-deal]").forEach(el=>el.addEventListener("click",()=>navigate("deal/"+el.dataset.deal)));document.querySelectorAll<HTMLElement>("[data-contract]").forEach(el=>el.addEventListener("click",()=>navigate("contract/"+el.dataset.contract)));document.querySelectorAll<HTMLElement>("[data-mortgage-link]").forEach(el=>el.addEventListener("click",()=>navigate("mortgage/"+el.dataset.mortgageLink)));document.querySelectorAll<HTMLElement>("[data-handover]").forEach(el=>el.addEventListener("click",()=>navigate("handover-case/"+el.dataset.handover)));document.querySelectorAll<HTMLElement>("[data-warranty]").forEach(el=>el.addEventListener("click",()=>navigate("warranty/"+el.dataset.warranty)));document.querySelectorAll<HTMLElement>("[data-global-route]").forEach(el=>el.addEventListener("click",()=>navigate(el.dataset.globalRoute!)));document.querySelectorAll<HTMLElement>("[data-property-search]").forEach(el=>el.addEventListener("click",()=>navigate("properties")));document.querySelectorAll<HTMLElement>("[data-demo-action]").forEach(el=>el.addEventListener("click",()=>handleClientAction(el.dataset.demoAction!)));document.querySelectorAll<HTMLElement>("[data-kyc-check]").forEach(el=>el.addEventListener("click",()=>openKycCheck(el.dataset.kycCheck!)));document.querySelectorAll<HTMLElement>("[data-doc-preview]").forEach(el=>el.addEventListener("click",()=>openDocument(el.dataset.docPreview!)));
}
function currentClient(){const id=location.hash.split("?")[0].split("/").pop()!;return clients.find(x=>x.id===id)}
function refreshClient(tab?:string){const c=currentClient();if(c){navigate("clients");setTimeout(()=>{navigate("client/"+c.id);if(tab)setTimeout(()=>openTab(tab),30)},20)}}

function handleClientAction(action:string){
  const c=currentClient();if(!c)return;
  if(action==="edit-client"){openClientEdit(c);return}
  if(action==="add-bank-account"){openBankAccount(c);return}
  if(action==="finalize-kyc"){openKycDecision(c);return}
  if(action==="upload-document"){
    openLocalizedModal(t("clientDetail.uploadDocument2"),`<form id="clientDocForm" class="form-grid"><div class="form-field"><label>${t("clientDetail.documentType")}</label><select name="type"><option value="idCard">${t("clientDetail.idCard")}</option><option value="passport">${t("clientDetail.passport")}</option><option value="incomeCertificate">${t("clientDetail.incomeCertificate")}</option><option value="spouseConsent">${t("clientDetail.spouseConsent")}</option><option value="stateRegistration">${t("v42.doc.stateRegistration")}</option><option value="charter">${t("v42.doc.charter")}</option><option value="majorTransactionApproval">${t("v42.doc.majorTransactionApproval")}</option></select></div><div class="form-field"><label>${t("clientDetail.number")}</label><input name="number" required value="DOC-${Date.now().toString().slice(-6)}"></div><div class="form-field"><label>${t("clientDetail.issueDate")}</label><input name="issuedAt" value="22.09.2026"></div><div class="form-field"><label>${t("clientDetail.validUntil")}</label><input name="expiresAt" placeholder="dd.MM.yyyy"></div><div class="form-field full"><label>${t("v42.documents.issuer")}</label><input name="issuer"></div><div class="form-field full"><label>${t("clientDetail.file")}</label><input type="file" name="file"></div></form>`,`<button class="btn" data-modal-close>${t("clientDetail.cancel")}</button><button class="btn btn-accent" id="saveClientDoc">${t("clientDetail.add")}</button>`);
    setTimeout(()=>document.querySelector("#saveClientDoc")?.addEventListener("click",()=>{const f=document.querySelector<HTMLFormElement>("#clientDocForm")!;if(!f.reportValidity())return;const file=(f.querySelector<HTMLInputElement>('input[name="file"]')?.files?.[0]?.name)||`document-${Date.now()}.pdf`;clientDocuments.push({id:`DOC-${c.id}-${clientDocuments.length+1}`,clientId:c.id,type:formValue(f,"type"),number:formValue(f,"number"),issuedAt:formValue(f,"issuedAt"),expiresAt:formValue(f,"expiresAt")||undefined,issuer:formValue(f,"issuer")||undefined,issueCountry:c.countryOfRegistration??c.citizenship,fileName:file,status:"review",source:"Manual upload"});closeModal();toastLocalized(t("clientDetail.documentAddedAndSentForReview"));refreshClient("documents")}),0);return;
  }
  if(action==="add-related"){
    openLocalizedModal(t("clientDetail.linkPerson2"),`<form id="relatedForm" class="form-grid"><div class="form-field full"><label>${t("clientDetail.fullName")}</label><input name="name" required></div><div class="form-field"><label>${t("clientDetail.role")}</label><select name="role"><option value="spouse">${t("clientDetail.spouse")}</option><option value="coBorrower">${t("clientDetail.coBorrower")}</option><option value="representative">${t("clientDetail.representative")}</option><option value="beneficialOwner">${t("clientDetail.beneficialOwner")}</option><option value="directorSignatory">${t("clientDetail.directorSignatory")}</option><option value="founder">${t("v42.profile.founder")}</option><option value="authorizedSignatory">${t("v42.profile.authorizedSignatory")}</option></select></div><div class="form-field"><label>${t("clientDetail.phone")}</label><input name="phone" value="+374 "></div><div class="form-field full"><label>${t("clientDetail.comment")}</label><textarea name="note"></textarea></div></form>`,`<button class="btn" data-modal-close>${t("clientDetail.cancel")}</button><button class="btn btn-accent" id="saveRelated">${t("clientDetail.link")}</button>`);
    setTimeout(()=>document.querySelector("#saveRelated")?.addEventListener("click",()=>{const f=document.querySelector<HTMLFormElement>("#relatedForm")!;if(!f.reportValidity())return;relatedPeople.push({id:`RP-${c.id}-${relatedPeople.length+1}`,clientId:c.id,name:formValue(f,"name"),role:formValue(f,"role"),phone:formValue(f,"phone"),verification:"review",note:formValue(f,"note")});closeModal();toastLocalized(t("clientDetail.relatedPersonAdded"));refreshClient("related")}),0);return;
  }
  if(action==="add-interest"){
    openLocalizedModal(t("clientDetail.newClientInterest"),`<form id="interestForm" class="form-grid"><div class="form-field"><label>${t("clientDetail.project")}</label><input name="project" value="Norq Residence" required></div><div class="form-field"><label>${t("clientDetail.propertyType")}</label><input name="type" value="${t("clientDetail.apartment")}" required></div><div class="form-field"><label>${t("clientDetail.roomCount")}</label><input name="rooms" value="2–3"></div><div class="form-field"><label>${t("clientDetail.budget")}</label><input name="budget" value="${t("clientDetail.defaultBudget50_75")}"></div><div class="form-field"><label>${t("clientDetail.location")}</label><input name="districts" value="${t("dashboard.city")}"></div><div class="form-field"><label>${t("clientDetail.financing")}</label><input name="payment" value="${t("clientDetail.text30Mortgage")}"></div><div class="form-field full"><label>${t("clientDetail.priority")}</label><select name="priority"><option value="hot">${t("clientDetail.hot")}</option><option value="warm">${t("clientDetail.warm")}</option><option value="cold">${t("clientDetail.cold")}</option></select></div></form>`,`<button class="btn" data-modal-close>${t("clientDetail.cancel")}</button><button class="btn btn-accent" id="saveInterest">${t("clientDetail.add")}</button>`);
    setTimeout(()=>document.querySelector("#saveInterest")?.addEventListener("click",()=>{const f=document.querySelector<HTMLFormElement>("#interestForm")!;if(!f.reportValidity())return;const typeValue=formValue(f,"type"),budgetValue=formValue(f,"budget"),districtValue=formValue(f,"districts"),paymentValue=formValue(f,"payment");clientInterests.push({id:`INT-${c.id}-${clientInterests.length+1}`,clientId:c.id,project:formValue(f,"project"),type:typeValue===t("clientDetail.apartment")?"i18n:clientDetail.apartment":typeValue,rooms:formValue(f,"rooms"),budget:budgetValue===t("clientDetail.defaultBudget50_75")?"i18n:clientDetail.defaultBudget50_75":budgetValue,districts:districtValue===t("dashboard.city")?"i18n:dashboard.city":districtValue,payment:paymentValue===t("clientDetail.text30Mortgage")?"i18n:clientDetail.text30Mortgage":paymentValue,priority:formValue(f,"priority") as any});closeModal();toastLocalized(t("clientDetail.interestAdded"));refreshClient("interests")}),0);return;
  }
  if(action==="create-offer"){
    openLocalizedModal(t("clientDetail.newCommercialOffer"),`<form id="clientOfferForm" class="form-grid"><div class="form-field full"><label>${t("clientDetail.propertiesSeparatedByCommas")}</label><input name="objects" value="B-1204, B-1301" required></div><div class="form-field"><label>${t("clientDetail.totalAmountAmd")}</label><input name="total" type="number" value="68376000" required></div><div class="form-field"><label>${t("clientDetail.validUntil")}</label><input name="validUntil" value="24.09.2026"></div></form>`,`<button class="btn" data-modal-close>${t("clientDetail.cancel")}</button><button class="btn btn-accent" id="saveClientOffer">${t("clientDetail.create")}</button>`);
    setTimeout(()=>document.querySelector("#saveClientOffer")?.addEventListener("click",()=>{const f=document.querySelector<HTMLFormElement>("#clientOfferForm")!;if(!f.reportValidity())return;clientOffers.push({id:`OF-2026-${220+clientOffers.length}`,clientId:c.id,createdAt:"22.09.2026 · 14:20",validUntil:formValue(f,"validUntil"),objects:formValue(f,"objects").split(",").map(x=>x.trim()).filter(Boolean),total:Number(formValue(f,"total")),status:"draft"});closeModal();toastLocalized(t("clientDetail.commercialOfferCreated"));refreshClient("offers")}),0);return;
  }
  if(action==="preview-offer"){
    const o=[...clientOffers].reverse().find(x=>x.clientId===c.id);if(!o){toastLocalized(t("clientDetail.offerNotFound"));return}
    openLocalizedModal(`${t("clientDetail.offer")} ${o.id}`,`<div class="info-list"><div class="info-box"><span>${t("clientDetail.client")}</span><strong>${c.name}</strong></div><div class="info-box"><span>${t("clientDetail.status")}</span><strong>${clientStateText(o.status)}</strong></div><div class="info-box"><span>${t("clientDetail.properties")}</span><strong>${o.objects.join(", ")}</strong></div><div class="info-box"><span>${t("clientDetail.value")}</span><strong>${amd(o.total)}</strong></div><div class="info-box"><span>${t("clientDetail.validUntil")}</span><strong>${o.validUntil}</strong></div></div>`);return;
  }
  if(action==="add-communication"){
    openLocalizedModal(t("clientDetail.addInteraction2"),`<form id="communicationForm" class="form-grid"><div class="form-field"><label>${t("clientDetail.type")}</label><select name="type"><option value="call">${t("clientDetail.call")}</option><option value="email">${t("common.email")}</option><option value="meeting">${t("clientDetail.meeting")}</option><option value="sms">SMS</option><option value="note">${t("clientDetail.note")}</option></select></div><div class="form-field"><label>${t("clientDetail.responsible")}</label><input name="owner" value="${c.manager}"></div><div class="form-field full"><label>${t("clientDetail.subject")}</label><input name="title" required></div><div class="form-field full"><label>${t("clientDetail.comment")}</label><textarea name="text" required></textarea></div></form>`,`<button class="btn" data-modal-close>${t("clientDetail.cancel")}</button><button class="btn btn-accent" id="saveCommunication">${t("clientDetail.add")}</button>`);
    setTimeout(()=>document.querySelector("#saveCommunication")?.addEventListener("click",()=>{const f=document.querySelector<HTMLFormElement>("#communicationForm")!;if(!f.reportValidity())return;clientCommunications.unshift({id:`COM-${Date.now()}`,clientId:c.id,type:formValue(f,"type") as any,at:"23.09.2026 · сейчас",title:formValue(f,"title"),text:formValue(f,"text"),owner:formValue(f,"owner")});closeModal();toastLocalized(t("clientDetail.interactionAdded"));refreshClient("communications")}),0);return;
  }
  if(action==="scan-document"){openLocalizedModal(t("client.ocrIdReader"),`<div class="modal-note">${t("v42.ocr.frontendNote")}</div><div class="ocr-preview u-mt-14"><div class="ocr-doc-visual"><span>ID</span><b>${c.name}</b><small>${c.personalNumber??c.taxId??"—"}</small></div><div class="ocr-fields"><div><span>${t("clientDetail.fullName")}</span><strong>${c.name}</strong></div><div><span>${t("clientDetail.document")}</span><strong>${t("client.idPassportDetected")}</strong></div><div><span>${t("client.confidence")}</span><strong>98.4%</strong></div><div><span>${t("clientDetail.status")}</span><strong>${t("clientDetail.requiresConfirmation")}</strong></div></div></div>`);return}
  toastLocalized(t("clientDetail.thereIsNoSeparateScenarioForThisActionYet"));
}

function openClientEdit(c:any){const company=["company","foreign-company"].includes(c.type);const body=company?companyEditForm(c):individualEditForm(c);openLocalizedModal(t("clientDetail.editClient"),`<form id="editClientForm" class="form-grid profile-edit-form">${body}<div class="form-field"><label>${t("clientDetail.responsible")}</label><select name="manager"><option ${c.manager==="Անի Հակոբյան"?"selected":""}>Անի Հակոբյան</option><option ${c.manager==="Նարեկ Կարապետյան"?"selected":""}>Նարեկ Կարապետյան</option><option ${c.manager==="Մարի Հովհաննիսյան"?"selected":""}>Մարի Հովհաննիսյան</option></select></div><div class="form-field"><label>${t("v41.client.language")}</label><select name="preferredLanguage"><option ${c.preferredLanguage==="HY"?"selected":""}>HY</option><option ${c.preferredLanguage==="RU"?"selected":""}>RU</option><option ${c.preferredLanguage==="EN"?"selected":""}>EN</option></select></div>${consentForm(c)}</form>`,`<button class="btn" data-modal-close>${t("clientDetail.cancel")}</button><button class="btn btn-accent" id="saveClientEdit">${t("clientDetail.save")}</button>`);
  setTimeout(()=>document.querySelector("#saveClientEdit")?.addEventListener("click",()=>{const f=document.querySelector<HTMLFormElement>("#editClientForm")!;if(!f.reportValidity())return;updateCommon(c,f);if(company)updateCompany(c,f);else updateIndividual(c,f);deals.filter(d=>d.clientId===c.id).forEach(d=>d.clientName=c.name);contracts.filter(x=>x.clientId===c.id).forEach(x=>x.clientName=c.name);closeModal();toastLocalized(t("clientDetail.clientRecordUpdated"));refreshClient("profile")}),0)}
function individualEditForm(c:any){return`<div class="form-section-title full">${t("v42.profile.identityData")}</div><div class="form-field"><label>${t("v42.profile.lastName")}</label><input name="lastName" value="${escapeHtml(c.lastName??"")}"></div><div class="form-field"><label>${t("v42.profile.firstName")}</label><input name="firstName" value="${escapeHtml(c.firstName??"")}"></div><div class="form-field"><label>${t("v42.profile.middleName")}</label><input name="middleName" value="${escapeHtml(c.middleName??"")}"></div><div class="form-field"><label>${t("client.publicServiceNumber")}</label><input name="personalNumber" value="${escapeHtml(c.personalNumber??"")}"></div><div class="form-field"><label>${t("v42.profile.birthDate")}</label><input name="dateOfBirth" value="${escapeHtml(c.dateOfBirth??"")}"></div><div class="form-field"><label>${t("v42.profile.birthPlace")}</label><input name="placeOfBirth" value="${escapeHtml(c.placeOfBirth??"")}"></div><div class="form-field"><label>${t("v42.profile.citizenship")}</label><input name="citizenship" value="${escapeHtml(c.citizenship??"")}"></div><div class="form-field"><label>${t("v41.client.residency")}</label><input name="taxResidency" value="${escapeHtml(c.taxResidency??"")}"></div><div class="form-field"><label>${t("v42.profile.maritalStatus")}</label><select name="maritalStatus">${["single","married","divorced","widowed"].map(x=>`<option value="${x}" ${c.maritalStatus===x?"selected":""}>${t(`v42.marital.${x}`)}</option>`).join("")}</select></div>${contactFields(c)}<div class="form-section-title full">${t("v42.profile.addresses")}</div>${addressFields("registration",c.registrationAddress,t("v42.profile.registrationAddress"))}${addressFields("residence",c.residenceAddress,t("v42.profile.residenceAddress"))}`}
function companyEditForm(c:any){return`<div class="form-section-title full">${t("v42.profile.companyData")}</div><div class="form-field full"><label>${t("v42.profile.legalName")}</label><input name="name" required value="${escapeHtml(c.name)}"></div><div class="form-field"><label>${t("v42.profile.shortName")}</label><input name="companyShortName" value="${escapeHtml(c.companyShortName??"")}"></div><div class="form-field"><label>${t("v42.profile.legalForm")}</label><input name="legalForm" value="${escapeHtml(c.legalForm??"")}"></div><div class="form-field"><label>${t("client.taxId")}</label><input name="taxId" value="${escapeHtml(c.taxId??"")}"></div><div class="form-field"><label>${t("v41.client.companyRegistration")}</label><input name="registrationNumber" value="${escapeHtml(c.registrationNumber??"")}"></div><div class="form-field"><label>${t("v42.profile.registrationDate")}</label><input name="registrationDate" value="${escapeHtml(c.registrationDate??"")}"></div><div class="form-field"><label>${t("v42.profile.registrationCountry")}</label><input name="countryOfRegistration" value="${escapeHtml(c.countryOfRegistration??"")}"></div>${contactFields(c)}<div class="form-section-title full">${t("v42.profile.addresses")}</div>${addressFields("legal",c.legalAddress,t("v42.profile.legalAddress"))}${addressFields("business",c.businessAddress,t("v42.profile.businessAddress"))}`}
function contactFields(c:any){return`<div class="form-section-title full">${t("v42.profile.contacts")}</div><div class="form-field"><label>${t("clientDetail.phone")}</label><input name="phone" required value="${escapeHtml(c.phone)}"></div><div class="form-field"><label>${t("common.email")}</label><input name="email" type="email" value="${escapeHtml(c.email)}"></div>`}
function addressFields(prefix:string,a:any,label:string){return`<div class="form-field full form-subheading">${label}</div><div class="form-field"><label>${t("v42.profile.country")}</label><input name="${prefix}Country" value="${escapeHtml(a?.country??"")}"></div><div class="form-field"><label>${t("v42.profile.city")}</label><input name="${prefix}City" value="${escapeHtml(a?.city??"")}"></div><div class="form-field full"><label>${t("v42.profile.streetAddress")}</label><input name="${prefix}Address" value="${escapeHtml(a?.address??"")}"></div><div class="form-field"><label>${t("v42.profile.postalCode")}</label><input name="${prefix}Postal" value="${escapeHtml(a?.postalCode??"")}"></div>`}
function consentForm(c:any){return`<div class="form-section-title full">${t("v42.profile.consents")}</div><label class="check-row full"><input type="checkbox" name="consentPersonalData" ${c.consentPersonalData?"checked":""}><span>${t("v42.profile.consentPersonal")}</span></label><label class="check-row full"><input type="checkbox" name="consentElectronicCommunication" ${c.consentElectronicCommunication?"checked":""}><span>${t("v42.profile.consentElectronic")}</span></label><label class="check-row full"><input type="checkbox" name="consentDocumentDelivery" ${c.consentDocumentDelivery?"checked":""}><span>${t("v42.profile.consentDocuments")}</span></label><label class="check-row full"><input type="checkbox" name="consentMarketing" ${c.consentMarketing?"checked":""}><span>${t("v42.profile.consentMarketing")}</span></label>`}
function updateCommon(c:any,f:HTMLFormElement){c.phone=formValue(f,"phone");c.email=formValue(f,"email");c.manager=formValue(f,"manager");c.preferredLanguage=formValue(f,"preferredLanguage");c.consentPersonalData=checked(f,"consentPersonalData");c.consentElectronicCommunication=checked(f,"consentElectronicCommunication");c.consentDocumentDelivery=checked(f,"consentDocumentDelivery");c.consentMarketing=checked(f,"consentMarketing")}
function updateIndividual(c:any,f:HTMLFormElement){c.lastName=formValue(f,"lastName");c.firstName=formValue(f,"firstName");c.middleName=formValue(f,"middleName");c.name=[c.firstName,c.lastName].filter(Boolean).join(" ")||c.name;c.personalNumber=formValue(f,"personalNumber");c.dateOfBirth=formValue(f,"dateOfBirth");c.placeOfBirth=formValue(f,"placeOfBirth");c.citizenship=formValue(f,"citizenship");c.taxResidency=formValue(f,"taxResidency");c.maritalStatus=formValue(f,"maritalStatus");c.registrationAddress=readAddress(f,"registration");c.residenceAddress=readAddress(f,"residence")}
function updateCompany(c:any,f:HTMLFormElement){c.name=formValue(f,"name");c.companyShortName=formValue(f,"companyShortName");c.legalForm=formValue(f,"legalForm");c.taxId=formValue(f,"taxId");c.registrationNumber=formValue(f,"registrationNumber");c.registrationDate=formValue(f,"registrationDate");c.countryOfRegistration=formValue(f,"countryOfRegistration");c.legalAddress=readAddress(f,"legal");c.businessAddress=readAddress(f,"business")}
function readAddress(f:HTMLFormElement,prefix:string){return{country:formValue(f,`${prefix}Country`),city:formValue(f,`${prefix}City`),address:formValue(f,`${prefix}Address`),postalCode:formValue(f,`${prefix}Postal`)||undefined}}
function checked(f:HTMLFormElement,name:string){return !!f.querySelector<HTMLInputElement>(`[name="${name}"]`)?.checked}

function openBankAccount(c:any){openLocalizedModal(t("v42.profile.addAccount"),`<form id="bankAccountForm" class="form-grid"><div class="form-field"><label>${t("v42.profile.bank")}</label><input name="bank" required></div><div class="form-field"><label>${t("v41.property.currency")}</label><select name="currency"><option>AMD</option><option>USD</option><option>EUR</option></select></div><div class="form-field full"><label>IBAN / ${t("v42.profile.accountNumber")}</label><input name="iban" required></div><div class="form-field"><label>SWIFT</label><input name="swift"></div><div class="form-field"><label>${t("v42.profile.accountHolder")}</label><input name="accountName" value="${escapeHtml(c.name)}"></div><label class="check-row full"><input type="checkbox" name="isPrimary"><span>${t("v42.profile.makePrimary")}</span></label></form>`,`<button class="btn" data-modal-close>${t("common.cancel")}</button><button class="btn btn-accent" id="saveBankAccount">${t("clientDetail.add")}</button>`);setTimeout(()=>document.querySelector("#saveBankAccount")?.addEventListener("click",()=>{const f=document.querySelector<HTMLFormElement>("#bankAccountForm")!;if(!f.reportValidity())return;const primary=checked(f,"isPrimary");if(primary)(c.bankAccounts??[]).forEach((x:any)=>x.isPrimary=false);c.bankAccounts??=[];c.bankAccounts.push({bank:formValue(f,"bank"),iban:formValue(f,"iban"),currency:formValue(f,"currency"),swift:formValue(f,"swift")||undefined,accountName:formValue(f,"accountName")||c.name,isPrimary:primary,status:"active"});closeModal();toastLocalized(t("v42.profile.accountAdded"));refreshClient("profile")}),0)}

function openKycCheck(id:string){const item=kycChecklist.find(x=>x.id===id),c=currentClient();if(!item||!c)return;openLocalizedModal(kycLabel(item.code),`<div class="kyc-modal-head">${item.mandatory?`<span class="chip accent">${t("v42.kyc.required")}</span>`:""}<span class="status ${kycTone(item.status)}">${t(`v42.kyc.status.${item.status}`)}</span></div><form id="kycCheckForm" class="form-grid u-mt-14"><div class="form-field"><label>${t("clientDetail.status")}</label><select name="status">${(["passed","review","pending","failed"] as KycCheckStatus[]).map(x=>`<option value="${x}" ${item.status===x?"selected":""}>${t(`v42.kyc.status.${x}`)}</option>`).join("")}</select></div><div class="form-field"><label>${t("v42.kyc.owner")}</label><input name="owner" value="${escapeHtml(item.owner)}"></div><div class="form-field full"><label>${t("v42.kyc.evidence")}</label><input name="evidence" value="${escapeHtml(item.evidence)}"></div><div class="form-field full"><label>${t("v42.kyc.note")}</label><textarea name="note">${escapeHtml(item.note)}</textarea></div></form>`,`<button class="btn" data-modal-close>${t("common.cancel")}</button><button class="btn btn-accent" id="saveKycCheck">${t("clientDetail.save")}</button>`);setTimeout(()=>document.querySelector("#saveKycCheck")?.addEventListener("click",()=>{const f=document.querySelector<HTMLFormElement>("#kycCheckForm")!;const oldStatus=item.status;item.status=formValue(f,"status") as KycCheckStatus;item.owner=formValue(f,"owner");item.evidence=formValue(f,"evidence");item.note=formValue(f,"note");item.updatedAt="23.09.2026";recordAudit({module:"clients",action:"update",entityType:"client",entityId:c.id,entityLabel:`${c.id} · ${c.name}`,route:`client/${c.id}`,field:`KYC · ${kycLabel(item.code)}`,oldValue:oldStatus,newValue:item.status,note:item.note,severity:item.status==="failed"?"critical":item.status==="review"?"warning":"info"});recalculateKyc(c.id);closeModal();toastLocalized(t("v42.kyc.checkUpdated"));refreshClient("kyc")}),0)}
function recalculateKyc(clientId:string){const items=kycChecklist.filter(x=>x.clientId===clientId),profile=clientKycProfiles.find(x=>x.clientId===clientId),c=clients.find(x=>x.id===clientId);if(!profile||!items.length)return;const mandatory=items.filter(x=>x.mandatory),passed=mandatory.filter(x=>x.status==="passed").length;profile.score=Math.round((passed/Math.max(mandatory.length,1))*100);profile.status=mandatory.some(x=>x.status==="failed")?"blocked":mandatory.some(x=>x.status!=="passed")?"review":"clear";profile.reviewedAt="22.09.2026 · 14:25";if(c)c.verification=profile.status==="clear"?"verified":"review"}
function openKycDecision(c:any){const p=clientKycProfiles.find(x=>x.clientId===c.id);if(!p)return;openLocalizedModal(t("v42.kyc.finalize"),`<div class="modal-note">${t("v42.kyc.finalizeNote")}</div><form id="kycDecisionForm" class="form-grid u-mt-14"><div class="form-field"><label>${t("v42.kyc.decision")}</label><select name="status"><option value="clear" ${p.status==="clear"?"selected":""}>${t("v42.kyc.decision.clear")}</option><option value="review" ${p.status==="review"?"selected":""}>${t("v42.kyc.decision.review")}</option><option value="blocked" ${p.status==="blocked"?"selected":""}>${t("v42.kyc.decision.blocked")}</option></select></div><div class="form-field"><label>${t("v42.kyc.risk")}</label><select name="risk"><option value="low" ${p.risk==="low"?"selected":""}>${t("v42.risk.low")}</option><option value="medium" ${p.risk==="medium"?"selected":""}>${t("v42.risk.medium")}</option><option value="high" ${p.risk==="high"?"selected":""}>${t("v42.risk.high")}</option></select></div><div class="form-field"><label>${t("v42.kyc.reviewer")}</label><input name="reviewedBy" value="${escapeHtml(p.reviewedBy)}"></div><div class="form-field full"><label>${t("v42.kyc.sourceOfFunds")}</label><input name="sourceOfFunds" value="${escapeHtml(p.sourceOfFunds)}"></div><div class="form-field full"><label>${t("v42.kyc.riskNote")}</label><textarea name="riskNote">${escapeHtml(p.riskNote)}</textarea></div></form>`,`<button class="btn" data-modal-close>${t("common.cancel")}</button><button class="btn btn-accent" id="saveKycDecision">${t("v42.kyc.saveDecision")}</button>`);setTimeout(()=>document.querySelector("#saveKycDecision")?.addEventListener("click",()=>{const f=document.querySelector<HTMLFormElement>("#kycDecisionForm")!;const oldDecision=p.status,oldRisk=p.risk;p.status=formValue(f,"status") as any;p.risk=formValue(f,"risk") as any;p.reviewedBy=formValue(f,"reviewedBy");p.sourceOfFunds=formValue(f,"sourceOfFunds");p.riskNote=formValue(f,"riskNote");p.reviewedAt="23.09.2026 · сейчас";c.verification=p.status==="clear"?"verified":"review";recordAudit({module:"clients",action:"status",entityType:"client",entityId:c.id,entityLabel:`${c.id} · ${c.name}`,route:`client/${c.id}`,field:"KYC decision / risk",oldValue:`${oldDecision} / ${oldRisk}`,newValue:`${p.status} / ${p.risk}`,note:p.riskNote,severity:p.status==="blocked"?"critical":p.status==="review"?"warning":"info"});closeModal();toastLocalized(t("v42.kyc.decisionSaved"));refreshClient("kyc")}),0)}

function openDocument(id:string){const x=clientDocuments.find(d=>d.id===id);if(!x)return;openLocalizedModal(documentTypeLabel(x.type),`<div class="document-detail-preview"><div class="document-sheet"><span>${x.issueCountry??"DOC"}</span><strong>${x.number}</strong><small>${x.fileName??x.id}</small></div><div class="document-meta-grid">${field(t("clientDetail.number"),x.number)}${field(t("clientDetail.issueDate"),x.issuedAt)}${field(t("clientDetail.validUntil"),x.expiresAt)}${field(t("v42.documents.issuer"),x.issuer)}${field(t("clientDetail.source"),x.source)}${field(t("clientDetail.status"),clientStateText(x.status))}</div></div>`)}
function openTab(key:string){(document.querySelector<HTMLElement>(`[data-tab-target="${key}"]`))?.click();document.querySelector(".client-tabs")?.scrollIntoView({behavior:"smooth",block:"start"})}
