import { approvals, clients, contracts, deals, powersOfAttorney, properties, registrationCases } from "../data/mock";
import { money,statusLabel } from "../utils";
import { navigate } from "../router";
import { closeModal,formValue,openLocalizedModal,toastLocalized } from "../components/layout";
import { contractDiffHtml, downloadContractDocx, downloadContractPdf } from "../services/documents";
import {t} from "../i18n";
import {demoText} from "../demo-i18n";
import {poaActionLabel,validateAuthority} from "../services/authority";
import {createWorkflowRoute,getWorkflowRoute,invalidateWorkflowRoute} from "../services/workflow";
import {ensureContractManagement,findTemplateVersion,requiredSignersComplete,signingProgress} from "../services/contract-management";
import type {ContractDeviation,ContractSigner} from "../models/types";
import{entityAuditPanel}from"../components/audit-panel";
import{recordAudit}from"../services/audit";

const statusClass:Record<string,string>={draft:"neutral","legal-review":"warning","client-review":"info",signature:"accent",signed:"success",notary:"warning",registered:"success"};
const lockedStatuses=["signed","notary","registered"];

export function contractDetailPage(id:string){
 const c=contracts.find(x=>x.id===id);
 if(!c)return `<section class="page"><div class="card card-pad empty">${t("common.recordNotFound")}</div></section>`;
 const client=clients.find(x=>x.id===c.clientId),deal=deals.find(x=>x.id===c.dealId);ensureContractManagement(c,deal,client);
 const contractPropertyIds=c.propertyIds?.length?c.propertyIds:[c.propertyId],contractProperties=contractPropertyIds.map(pid=>properties.find(x=>x.id===pid)).filter(Boolean) as typeof properties,poa=powersOfAttorney.find(x=>x.relatedDeal===c.dealId),registration=registrationCases.find(x=>x.contractId===c.id);
 const authority=validateAuthority(deal,poa,"sign-contract",contractPropertyIds),contractRoute=getWorkflowRoute("contract",c.id),deviationsReady=c.nonStandardClauses===0||contractRoute?.status==="approved",template=findTemplateVersion(c.template),signing=signingProgress(c),requiredClausesReady=(c.clauses??[]).filter(x=>x.required).every(x=>x.included);
 if(contractRoute?.status==="approved")c.deviations?.forEach(x=>x.status="approved");
 if(contractRoute?.status==="rejected")c.deviations?.forEach(x=>x.status="rejected");
 const signatureReady=!['signature','signed','notary','registered'].includes(c.status)||requiredSignersComplete(c);
 const readinessChecks=[Boolean(template),authority.ok,requiredClausesReady,deviationsReady,true,signatureReady],readiness=Math.round(readinessChecks.filter(Boolean).length/readinessChecks.length*100);
 const immutable=lockedStatuses.includes(c.status),nextSigner=(c.signers??[]).find(s=>s.required&&s.status!=="signed");
 return `<section class="page">
  <div class="breadcrumbs"><span>${t("contractDetail.operations")}</span><span>›</span><span>${t("contractDetail.contracts")}</span><span>›</span><span>${c.id}</span></div>
  <div class="detail-header">
    <div class="detail-title"><small>${c.id} · ${c.template}</small><h1>${c.clientName} · ${contractProperties.map(p=>p.unit).join(" + ")||c.propertyLabel}${contractProperties.length>1?` <span class="title-count">+${contractProperties.length-1}</span>`:""}</h1><div class="toolbar"><span class="status ${statusClass[c.status]}">${statusLabel(c.status)}</span>${contractProperties.length>1?`<span class="chip accent">${t("v45.package.bundleContract")}</span>`:""}${immutable?`<span class="chip contract-lock-chip">🔒 ${t("v49.contract.immutable")}</span>`:""}</div></div>
    <div class="toolbar"><button class="btn" id="backContracts">${t("contractDetail.registry")}</button><button class="btn" id="exportWord">Word</button><button class="btn" id="exportPdf">PDF</button><button class="btn btn-accent" id="contractPrimary">${primaryActionLabel(c.status)}</button></div>
  </div>

  <div class="contract-progress">
   ${progress("01",t("contractDetail.progress.draft"),true)}${progress("02",t("contractDetail.progress.legal"),c.status!=="draft",c.status==="legal-review")}${progress("03",t("contractDetail.progress.client"),["client-review","signature","signed","notary","registered"].includes(c.status),c.status==="client-review")}${progress("04",t("contractDetail.progress.signature"),["signature","signed","notary","registered"].includes(c.status),c.status==="signature")}${progress("05",t("contractDetail.progress.notary"),["notary","registered"].includes(c.status),c.status==="notary")}${progress("06",t("contractDetail.progress.registered"),c.status==="registered")}
  </div>
  ${immutable?`<div class="contract-immutable-banner"><b>🔒</b><div><strong>${t("v49.contract.immutableTitle")}</strong><span>${t("v49.contract.immutableText")}</span></div><span>${c.signedDocumentName??t("v49.contract.signedCopy")}</span></div>`:""}
  ${c.nonStandardClauses?`<div class="sales-flow-alert ${contractRoute?.status==="approved"?"success":"warning"}"><b>${contractRoute?.status==="approved"?"✓":"↗"}</b><div><strong>${contractRoute?.status==="approved"?t("v47.contract.approvedTitle"):t("v47.contract.routeTitle")}</strong><span>${contractRoute?`${contractRoute.id} · ${t(`status.${contractRoute.status}`)}`:t("v47.contract.routeMissing")}</span></div>${contractRoute?`<button class="btn" id="openContractWorkflow">${t("v47.common.openRoute")}</button>`:""}</div>`:""}

  <div class="contract-layout">
   <div class="contract-main">
    <div class="card card-pad">
      <div class="section-title"><div><h2>${t("contractDetail.contractRecord")}</h2><p>${t("contractDetail.unifiedDealContextWithoutSearchingAcrossMultipleSystems")}</p></div><span class="language-pill">${c.language}</span></div>
      <div class="contract-template-snapshot"><div><span>${t("v49.contract.templateSnapshot")}</span><strong>${c.template}</strong><small>${template?`${template.template.name} · ${template.version.version} · ${t(`v49.templateStatus.${template.version.status}`)}`:t("v49.contract.templateMissing")}</small></div><button class="btn btn-soft" id="openTemplateSource">${t("v49.contract.openTemplate")}</button></div>
      <div class="info-list">
       <div class="info-box"><span>${t("contractDetail.contractType")}</span><strong>${demoText(c.type)}</strong></div><div class="info-box"><span>${t("contractDetail.amount")}</span><strong>${money(c.amount,c.currency??"AMD")}</strong></div>
       <div class="info-box"><span>${t("contractDetail.buyer")}</span><strong>${client?.name??c.clientName}</strong></div><div class="info-box"><span>${t("v45.package.contractLogic")}</span><strong>${contractProperties.length>1?(c.packageMode==="separate"?t("v45.package.mixedContracts"):t("v45.package.sharedContract")):t("v45.package.singleAsset")}</strong></div>
       <div class="info-box"><span>${t("v45.package.assets")}</span><strong>${contractProperties.length}</strong></div><div class="info-box"><span>${t("contractDetail.area")}</span><strong>${contractProperties.reduce((sum,p)=>sum+p.area,0).toFixed(1)} m²</strong></div>
       <div class="info-box"><span>${t("contractDetail.responsibleLawyer")}</span><strong>${c.owner}</strong></div><div class="info-box"><span>${t("contractDetail.language")}</span><strong>${c.language}</strong></div>
      </div>
      ${contractProperties.length>1?`<div class="contract-package-assets"><div class="contract-package-head"><span>${t("v45.package.packageComposition")}</span><strong>${t("v45.package.allAssetsInOneLegalContext")}</strong></div>${contractProperties.map((p,i)=>`<button data-contract-property="${p.id}" class="contract-package-row"><span>${String(i+1).padStart(2,"0")}</span><div><strong>${p.unit}</strong><small>${p.project} · ${p.area} m²</small></div><b>${money(p.totalPrice,p.currency)}</b></button>`).join("")}</div>`:""}
    </div>

    <div class="card card-pad">
      <div class="section-title"><div><h2>${t("v49.contract.clauseSet")}</h2><p>${t("v49.contract.clauseSetSub")}</p></div><button class="btn" id="showClauseRules">${t("v49.contract.showRules")}</button></div>
      <div class="clause-engine-summary"><div><span>${t("v49.contract.includedClauses")}</span><strong>${(c.clauses??[]).filter(x=>x.included).length}</strong></div><div><span>${t("v49.contract.conditionalIncluded")}</span><strong>${(c.clauses??[]).filter(x=>x.included&&x.mode==="conditional").length}</strong></div><div><span>${t("v49.contract.notApplicable")}</span><strong>${(c.clauses??[]).filter(x=>!x.included).length}</strong></div><div><span>${t("v49.contract.deviations")}</span><strong>${c.nonStandardClauses}</strong></div></div>
      <div class="contract-clause-list">${(c.clauses??[]).filter(x=>x.included).map((clause,i)=>`<div class="contract-clause-row"><div class="clause-number">${String(i+1).padStart(2,"0")}</div><div><div class="contract-clause-top"><span>${clause.code} · ${clause.category}</span>${clause.mode==="conditional"?`<b>${t("v49.clauseMode.conditional")}</b>`:""}</div><strong>${clause.title}</strong><p>${clause.text}</p>${clause.mode==="conditional"?`<small>↳ ${t("v49.contract.includedBecause")}: ${t(`v49.condition.${clause.inclusionReason}`)}</small>`:""}</div></div>`).join("")}</div>
    </div>

    <div class="card card-pad">
      <div class="section-title"><div><h2>${t("contractDetail.templateDeviations")}</h2><p>${t("contractDetail.nonStandardTermsAreShownSeparatelyAndFollowTheirOwnApprovalFlow")}</p></div>${!immutable?`<button class="btn btn-soft" id="addDeviation">${t("contractDetail.addDeviation")}</button>`:""}</div>
      ${c.deviations?.length?`<div class="contract-deviation-list">${c.deviations.map((d,i)=>`<div class="deviation-card"><div class="deviation-index">${String(i+1).padStart(2,"0")}</div><div><div class="deviation-title">${d.title}</div><p>${d.reason}</p><div class="clause-compare"><div><span>${t("contractDetail.standard")}</span><strong>${d.standardText}</strong></div><div><span>${t("contractDetail.proposed")}</span><strong>${d.proposedText}</strong></div></div><small class="deviation-meta">${d.createdAt} · ${d.createdBy}</small></div><div><span class="status ${d.status==="approved"?"success":d.status==="rejected"?"danger":"warning"}">${t(`v49.deviation.${d.status}`)}</span></div></div>`).join("")}</div>`:`<div class="empty compact-empty">${t("contractDetail.noDeviationsFromTheApprovedTemplate")}</div>`}
    </div>

    <div class="card card-pad signing-workspace ${c.status==="signature"?"is-active":""}">
      <div class="section-title"><div><h2>${t("v49.signing.title")}</h2><p>${t("v49.signing.subtitle")}</p></div><div class="signing-score"><strong>${signing.signed}/${signing.total}</strong><span>${t("v49.signing.signed")}</span></div></div>
      <div class="signing-progress-bar"><i style="width:${signing.percent}%"></i></div>
      <div class="signer-list">${(c.signers??[]).map((s,i)=>signerRow(s,i,nextSigner?.id,c.status)).join("")}</div>
      <div class="signing-footer"><div><span>${t("v49.signing.signedCopy")}</span><strong>${c.signedDocumentName??t("v49.signing.notUploaded")}</strong><small>${c.status==="signature"?t("v49.signing.uploadHelp"):t("v49.signing.archiveHelp")}</small></div>${["signature","signed","notary","registered"].includes(c.status)?`<button class="btn" id="uploadSignedScan">${t("v49.signing.uploadScan")}</button><input type="file" id="signedScanInput" accept="application/pdf,image/*" hidden>`:""}</div>
    </div>

    <div class="card card-pad">
      <div class="section-title"><div><h2>${t("contractDetail.documentVersions")}</h2><p>${t("contractDetail.theSignedCopyBecomesImmutable")}</p></div><div class="toolbar">${!immutable?`<button class="btn btn-soft" id="newContractVersion">${t("v49.contract.newVersion")}</button>`:""}<button class="btn" id="compareVersions">${t("contractDetail.compareVersions")}</button></div></div>
      <div class="version-list">${c.versions.slice().reverse().map(v=>`<div class="version-row"><div class="version-mark ${v.status}"></div><div class="version-copy"><strong>${v.version} · ${demoText(v.note)}</strong><span>${demoText(v.createdAt)} · ${demoText(v.author)}</span></div><span class="version-state">${t(v.status==="current"?"contractDetail.versionState.current":v.status==="signed"?"contractDetail.versionState.signed":"contractDetail.versionState.archived")}</span></div>`).join("")}</div>
    </div>
   </div>

   <aside class="contract-side">
    <div class="card card-pad legal-health">
      <div class="section-title"><div><h2>${t("contractDetail.legalReadiness")}</h2><p>${t("contractDetail.beforeSigning")}</p></div><div class="readiness-score ${readiness===100?"":"warning"}">${readiness}%</div></div>
      ${check(t("v49.contract.check.template"),Boolean(template),template?`${template.version.code} · ${template.version.version}`:t("v49.contract.templateMissing"))}${check(t("contractDetail.check.kyc"),true,t("contractDetail.check.verified"))}${check(t("contractDetail.check.signerAuthority"),authority.ok,authority.message)}${check(t("contractDetail.check.propertyRestrictions"),true,t("contractDetail.check.notFound"))}${check(t("contractDetail.check.templateDeviations"),deviationsReady,c.nonStandardClauses?(contractRoute?.status==="approved"?t("v47.contract.routeApproved"):t("contractDetail.check.oneNeedsDecision")):t("contractDetail.check.none"))}${check(t("v49.contract.check.signatures"),signatureReady,signing.total?`${signing.signed}/${signing.total}`:t("v49.signing.notStarted"))}${check(t("contractDetail.check.financialTerms"),true,t("contractDetail.check.approved"))}
    </div>

    <div class="card card-pad">
      <div class="section-title"><div><h2>${t("contractDetail.representation")}</h2><p>${t("contractDetail.authorityAtSigning")}</p></div></div>
      ${poa?`<div class="poa-mini authority-contract-card ${authority.ok?"ok":"fail"}"><span>${t("contractDetail.powerOfAttorney")}</span><strong>${poa.documentNo} · ${poa.representative}</strong><p>${demoText(poa.scope)}</p><div class="authority-inline-result"><b>${authority.ok?"✓":"!"}</b><div><strong>${authority.title}</strong><span>${authority.message}</span></div></div><div class="toolbar"><button class="btn btn-soft" id="openPoa">${t("contractDetail.openPowerOfAttorney")}</button><button class="btn" id="verifyContractAuthority">${t("v43.authority.run")}</button></div></div>`:`<div class="empty compact-empty">${t("contractDetail.buyerActsInPerson")}</div>`}
    </div>

    <div class="card card-pad">
      <div class="section-title"><div><h2>${t("v49.contract.versionControl")}</h2><p>${t("v49.contract.versionControlSub")}</p></div></div>
      <div class="contract-control-list"><div><span>${t("v49.contract.templateVersion")}</span><strong>${template?.version.version??"—"}</strong></div><div><span>${t("v49.contract.transactionVersion")}</span><strong>${c.versions.at(-1)?.version??"—"}</strong></div><div><span>${t("v49.contract.signingProgress")}</span><strong>${signing.percent}%</strong></div><div><span>${t("v49.contract.lockState")}</span><strong>${immutable?t("v49.contract.locked"):t("v49.contract.editable")}</strong></div></div>
    </div>

    <div class="card card-pad">
      <div class="section-title"><div><h2>${t("contractDetail.nextStage")}</h2><p>${t("contractDetail.notaryRegistration")}</p></div></div>
      ${registration?`<div class="next-stage"><span>${registration.plannedAt}</span><strong>${registration.notary}</strong><p>${registration.applicationNo?`${t("contractDetail.application")}: ${registration.applicationNo}`:t("contractDetail.documentPackageIsBeingPrepared")}</p><button class="btn btn-primary" id="openRegistration">${t("contractDetail.openProcess")}</button></div>`:`<div class="next-stage"><span>${t("contractDetail.afterSigning")}</span><strong>${t("contractDetail.createRegistrationProcess")}</strong><p>${t("contractDetail.notaryStateFeeApplicationAndRegistrationResult")}</p><button class="btn" id="openRegistration">${t("contractDetail.prepare")}</button></div>`}
    </div>
   </aside>
  </div>
  ${entityAuditPanel("contract",c.id)}
 </section>`;
}
function progress(n:string,label:string,done:boolean,current=false){return `<div class="contract-step ${done?"done":""} ${current?"current":""}"><div>${done&&!current?"✓":n}</div><span>${label}</span></div>`}
function check(label:string,ok:boolean,note:string){return `<div class="legal-check"><div class="checkmark ${ok?"":"pending"}">${ok?"✓":"!"}</div><div><strong>${label}</strong><span>${note}</span></div></div>`}
function primaryActionLabel(status:string){return t(status==="legal-review"?"contractDetail.action.finishLegalReview":status==="client-review"?"v49.contract.startSigning":status==="signature"?"v49.contract.completeSigning":status==="signed"?"v49.contract.toNotary":status==="notary"?"v49.contract.markRegistered":"contractDetail.action.nextStage")}
function signerRole(role:string){return t(`v49.signerRole.${role}`)}
function signerRow(s:ContractSigner,index:number,nextId:string|undefined,status:string){const isNext=s.id===nextId&&status==="signature";return`<div class="signer-row ${s.status} ${isNext?"next":""}"><div class="signer-order">${s.status==="signed"?"✓":String(index+1).padStart(2,"0")}</div><div class="signer-person"><span>${s.side==="buyer"?t("v49.signing.buyerSide"):t("v49.signing.sellerSide")} · ${signerRole(s.role)}</span><strong>${s.name}</strong><small>${s.authority??t("v49.signing.authorityChecked")}</small></div><div class="signer-method"><span>${t("v49.signing.method")}</span><strong>${t(`v49.signatureMethod.${s.method}`)}</strong>${s.signedAt?`<small>${demoText(s.signedAt)}</small>`:""}</div><div class="signer-state"><span class="status ${s.status==="signed"?"success":s.status==="declined"?"danger":"warning"}">${t(`v49.signerStatus.${s.status}`)}</span>${isNext?`<button class="btn btn-accent" data-sign-signer="${s.id}">${t("v49.signing.sign")}</button>`:s.status==="pending"&&status==="signature"?`<small>${t("v49.signing.waitingPrevious")}</small>`:""}</div></div>`}

export function bindContractDetail(){
 document.querySelector("#backContracts")?.addEventListener("click",()=>navigate("contracts"));
 document.querySelector("#openTemplateSource")?.addEventListener("click",()=>{const c=currentContract();const found=c&&findTemplateVersion(c.template);navigate(found?`contract-templates?id=${found.template.id}`:"contract-templates")});
 document.querySelector("#openPoa")?.addEventListener("click",()=>{const c=currentContract();const p=c&&powersOfAttorney.find(x=>x.relatedDeal===c.dealId);navigate(p?"poa/"+p.id:"legal/poa")});
 document.querySelector("#verifyContractAuthority")?.addEventListener("click",()=>{const c=currentContract();if(!c)return;const d=deals.find(x=>x.id===c.dealId),p=powersOfAttorney.find(x=>x.relatedDeal===c.dealId),ids=c.propertyIds?.length?c.propertyIds:[c.propertyId],r=validateAuthority(d,p,"sign-contract",ids);openLocalizedModal(t("v43.authority.check"),`<div class="authority-modal-result ${r.ok?"ok":"fail"}"><strong>${r.ok?"✓":"!"} ${r.title}</strong><span>${r.message}</span></div>${p?`<div class="poa-action-preview u-mt-12">${p.allowedActions.map(a=>`<span>${poaActionLabel(a)}</span>`).join("")}</div>`:""}`,`<button class="btn" data-modal-close>${t("contractDetail.close")}</button>`)});
 document.querySelector("#openRegistration")?.addEventListener("click",()=>{const c=currentContract();if(!c)return;if(!["signed","notary","registered"].includes(c.status)){toastLocalized(t("v49.contract.registrationBlocked"));return}navigate("registration")});
 document.querySelector("#contractPrimary")?.addEventListener("click",()=>advanceContract());
 document.querySelector("#openContractWorkflow")?.addEventListener("click",()=>navigate("approvals?tab=routes"));
 document.querySelector("#addDeviation")?.addEventListener("click",()=>openDeviation());
 document.querySelector("#newContractVersion")?.addEventListener("click",()=>openNewVersion());
 document.querySelector("#showClauseRules")?.addEventListener("click",()=>showClauseRules());
 document.querySelectorAll<HTMLElement>("[data-sign-signer]").forEach(el=>el.addEventListener("click",()=>openSignerAction(el.dataset.signSigner!)));
 document.querySelector("#uploadSignedScan")?.addEventListener("click",()=>document.querySelector<HTMLInputElement>("#signedScanInput")?.click());
 document.querySelector<HTMLInputElement>("#signedScanInput")?.addEventListener("change",e=>{const input=e.currentTarget as HTMLInputElement;const file=(input.files??[])[0],c=currentContract();if(!file||!c)return;c.signedDocumentName=file.name;c.updatedAt="23.09.2026 · сейчас";toastLocalized(t("v49.signing.scanAttached",{name:file.name}));refreshContract()});
 document.querySelector("#exportWord")?.addEventListener("click",()=>{const c=currentContract();if(!c)return;recordAudit({module:"contracts",action:"export",entityType:"contract",entityId:c.id,entityLabel:`${c.id} · ${c.clientName}`,route:`contract/${c.id}`,field:"Export",oldValue:"—",newValue:"Word",note:"Contract document exported."});downloadContractDocx(c,clients.find(x=>x.id===c.clientId),(c.propertyIds?.length?c.propertyIds:[c.propertyId]).map(pid=>properties.find(x=>x.id===pid)).filter(Boolean) as typeof properties);toastLocalized(t("contractDetail.docxGeneratedAndDownloading"))});
 document.querySelector("#exportPdf")?.addEventListener("click",async()=>{const c=currentContract();if(!c)return;toastLocalized(t("contractDetail.generatingPdf"));recordAudit({module:"contracts",action:"export",entityType:"contract",entityId:c.id,entityLabel:`${c.id} · ${c.clientName}`,route:`contract/${c.id}`,field:"Export",oldValue:"—",newValue:"PDF",note:"Contract PDF exported."});await downloadContractPdf(c,clients.find(x=>x.id===c.clientId),(c.propertyIds?.length?c.propertyIds:[c.propertyId]).map(pid=>properties.find(x=>x.id===pid)).filter(Boolean) as typeof properties);toastLocalized(t("contractDetail.pdfGeneratedAndDownloading"))});
 document.querySelectorAll<HTMLElement>("[data-contract-property]").forEach(el=>el.addEventListener("click",()=>navigate("property/"+el.dataset.contractProperty)));
 document.querySelector("#compareVersions")?.addEventListener("click",()=>{const c=currentContract();if(!c)return;openLocalizedModal(t("contractDetail.contractVersionComparison"),contractDiffHtml(c),`<button class="btn" data-modal-close>${t("contractDetail.close")}</button>`)});
}
const contractFlow=["draft","legal-review","client-review","signature","signed","notary","registered"] as const;
function currentContract(){const id=location.hash.split("?")[0].split("/").pop()!;return contracts.find(x=>x.id===id)}
function refreshContract(){const c=currentContract();if(c){navigate("contracts");setTimeout(()=>navigate("contract/"+c.id),20)}}
function advanceContract(){const c=currentContract();if(!c)return;const d=deals.find(x=>x.id===c.dealId),client=clients.find(x=>x.id===c.clientId);ensureContractManagement(c,d,client);const idx=contractFlow.indexOf(c.status as any);if(idx===contractFlow.length-1){toastLocalized(t("contractDetail.contractIsAlreadyRegistered"));return}if(idx<0)return;if(c.status==="legal-review"){const route=getWorkflowRoute("contract",c.id);if(c.nonStandardClauses>0&&route?.status!=="approved"){toastLocalized(t("contractDetail.pendingApprovalBlock"));return}}const previous=c.status;const next=contractFlow[idx+1];if(next==="signature"||next==="signed"){const p=powersOfAttorney.find(x=>x.relatedDeal===c.dealId),authority=validateAuthority(d,p,"sign-contract",c.propertyIds?.length?c.propertyIds:[c.propertyId]);if(!authority.ok){toastLocalized(t("v43.authority.contractBlocked"));return}}if(c.status==="signature"&&!requiredSignersComplete(c)){const p=signingProgress(c);toastLocalized(t("v49.signing.incomplete",{signed:p.signed,total:p.total}));return}c.status=next;c.updatedAt="23.09.2026 · сейчас";recordAudit({module:"contracts",action:"status",entityType:"contract",entityId:c.id,entityLabel:`${c.id} · ${c.clientName}`,route:`contract/${c.id}`,field:"Contract status",oldValue:previous,newValue:next,note:`Contract moved to ${next}.`});if(next==="signature")c.signingStartedAt="23.09.2026 · сейчас";if(next==="signed"){c.versions.forEach(v=>v.status="archived");c.versions.push({id:c.id+`-V${c.versions.length+1}`,version:`v${c.versions.length+1}.0`,createdAt:"23.09.2026 · сейчас",author:c.owner,note:"i18n:contractDetail.signedCopy",status:"signed"});c.signedDocumentName??=`${c.id}-signed.pdf`}toastLocalized(`${t("contractDetail.contractMoved")}: ${statusLabel(next)}`);refreshContract()}
function openSignerAction(signerId:string){const c=currentContract();if(!c||c.status!=="signature")return;const deal=deals.find(x=>x.id===c.dealId),poa=powersOfAttorney.find(x=>x.relatedDeal===c.dealId),authority=validateAuthority(deal,poa,"sign-contract",c.propertyIds?.length?c.propertyIds:[c.propertyId]);if(!authority.ok){toastLocalized(t("v43.authority.contractBlocked"));return}const signer=c.signers?.find(x=>x.id===signerId);if(!signer)return;const firstPending=c.signers?.find(x=>x.required&&x.status!=="signed");if(firstPending?.id!==signer.id){toastLocalized(t("v49.signing.sequenceBlocked"));return}openLocalizedModal(t("v49.signing.signTitle"),`<div class="signer-modal-person"><span>${signerRole(signer.role)}</span><strong>${signer.name}</strong><small>${signer.authority??"—"}</small></div><form id="signerForm" class="form-grid"><div class="form-field full"><label>${t("v49.signing.method")}</label><select name="method"><option value="electronic">${t("v49.signatureMethod.electronic")}</option><option value="paper">${t("v49.signatureMethod.paper")}</option></select></div><div class="form-field full"><label>${t("v49.signing.note")}</label><input name="document" placeholder="${t("v49.signing.documentPlaceholder")}"></div></form>`,`<button class="btn" data-modal-close>${t("common.cancel")}</button><button class="btn btn-accent" id="confirmSigner">${t("v49.signing.confirm")}</button>`);setTimeout(()=>document.querySelector("#confirmSigner")?.addEventListener("click",()=>{const f=document.querySelector<HTMLFormElement>("#signerForm")!;const oldSigner=signer.status;signer.status="signed";signer.method=formValue(f,"method") as "electronic"|"paper";signer.signedAt="23.09.2026 · сейчас";recordAudit({module:"contracts",action:"signature",entityType:"contract",entityId:c.id,entityLabel:`${c.id} · ${c.clientName}`,route:`contract/${c.id}`,field:`Signature · ${signer.name}`,oldValue:oldSigner,newValue:"signed",note:`${signer.method} signature recorded.`});signer.documentName=formValue(f,"document")||undefined;c.updatedAt="23.09.2026 · сейчас";closeModal();toastLocalized(t("v49.signing.signedBy",{name:signer.name}));refreshContract()}),0)}
function showClauseRules(){const c=currentContract();if(!c)return;openLocalizedModal(t("v49.contract.clauseRules"),`<div class="clause-rule-modal">${(c.clauses??[]).map(x=>`<div class="clause-rule-row ${x.included?"included":"excluded"}"><div>${x.included?"✓":"—"}</div><div><span>${x.code} · ${x.category}</span><strong>${x.title}</strong><small>${x.mode==="standard"?t("v49.clauseMode.standard"):`${t("v49.condition.label")}: ${t(`v49.condition.${x.condition}`)}`}</small></div><b>${x.included?t("v49.contract.included"):t("v49.contract.notApplicable")}</b></div>`).join("")}</div>`,`<button class="btn" data-modal-close>${t("common.close")}</button>`)}
function openNewVersion(){const c=currentContract();if(!c||lockedStatuses.includes(c.status))return;const current=c.versions.at(-1)?.version??"v1.0",match=current.match(/v(\d+)\.(\d+)/),next=match?`v${match[1]}.${Number(match[2])+1}`:`v${c.versions.length+1}.0`;openLocalizedModal(t("v49.contract.newVersion"),`<form id="contractVersionForm" class="form-grid"><div class="form-field"><label>${t("v49.contract.version")}</label><input name="version" value="${next}" required></div><div class="form-field full"><label>${t("v49.contract.changeReason")}</label><textarea name="note" required placeholder="${t("v49.contract.changeReasonPlaceholder")}"></textarea></div></form>`,`<button class="btn" data-modal-close>${t("common.cancel")}</button><button class="btn btn-accent" id="saveContractVersion">${t("common.save")}</button>`);setTimeout(()=>document.querySelector("#saveContractVersion")?.addEventListener("click",()=>{const f=document.querySelector<HTMLFormElement>("#contractVersionForm")!;if(!f.reportValidity())return;c.versions.forEach(v=>{if(v.status==="current")v.status="archived"});c.versions.push({id:`${c.id}-V${c.versions.length+1}`,version:formValue(f,"version"),createdAt:"23.09.2026 · сейчас",author:c.owner,note:formValue(f,"note"),status:"current"});c.updatedAt="23.09.2026 · сейчас";closeModal();toastLocalized(t("v49.contract.versionCreated"));refreshContract()}),0)}
function openDeviation(){const c=currentContract();if(!c||lockedStatuses.includes(c.status))return;openLocalizedModal(t("contractDetail.templateDeviation"),`<form id="deviationForm" class="form-grid"><div class="form-field full"><label>${t("contractDetail.sectionTerm")}</label><input name="clause" required value="${t("contractDetail.propertyHandoverTerm")}"></div><div class="form-field full"><label>${t("contractDetail.standardTerm")}</label><textarea name="standard">${t("contractDetail.text30CalendarDaysAfterFullSettlement")}</textarea></div><div class="form-field full"><label>${t("contractDetail.proposedTerm")}</label><textarea name="proposed" required>${t("contractDetail.text15CalendarDaysAfterTitleRegistration")}</textarea></div><div class="form-field full"><label>${t("contractDetail.reason")}</label><textarea name="reason">${t("contractDetail.buyerRequest")}</textarea></div></form>`,`<button class="btn" data-modal-close>${t("contractDetail.cancel")}</button><button class="btn btn-accent" id="saveDeviation">${t("contractDetail.addAndSendForApproval")}</button>`);setTimeout(()=>document.querySelector("#saveDeviation")?.addEventListener("click",()=>{const f=document.querySelector<HTMLFormElement>("#deviationForm")!;if(!f.reportValidity())return;c.status="legal-review";c.updatedAt="23.09.2026 · сейчас";invalidateWorkflowRoute("contract",c.id,"Contract deviation changed");const d=deals.find(x=>x.id===c.dealId),client=clients.find(x=>x.id===c.clientId),poa=powersOfAttorney.find(x=>x.relatedDeal===c.dealId);const deviation:ContractDeviation={id:`${c.id}-DEV-${(c.deviations?.length??0)+1}`,clauseCode:"CUSTOM",title:formValue(f,"clause"),standardText:formValue(f,"standard"),proposedText:formValue(f,"proposed"),reason:formValue(f,"reason"),status:"approval",createdAt:"23.09.2026 · сейчас",createdBy:c.owner};c.deviations??=[];c.deviations.push(deviation);c.nonStandardClauses=c.deviations.length;const route=createWorkflowRoute({sourceType:"contract",subjectId:c.id,dealId:c.dealId,title:`${c.id} · ${deviation.title}`,clientName:c.clientName,propertyLabel:c.propertyLabel,requestedBy:c.owner,discountPercent:d?.discount,amount:c.amount,currency:c.currency,buyerType:client?.type,hasRepresentative:Boolean(poa||d?.participants.some(p=>p.role==="representative")),nonStandardClauses:c.nonStandardClauses,riskLevel:"medium",assetCount:c.propertyIds?.length??1});deviation.workflowRouteId=route.id;const current=approvals.find(a=>a.routeId===route.id&&a.status==="pending");if(current){current.requestedValue=deviation.proposedText;current.limitValue=deviation.standardText;current.reason=`${deviation.title}: ${deviation.reason}`}closeModal();toastLocalized(`${t("contractDetail.deviationAddedAndSentForLegalApproval")} · ${route.id}`);navigate("approvals?tab=inbox")}),0)}
