import {bankStatementLines,deals,exchangeRates,financialSecurities,mortgageApplications,paymentReceipts,paymentSchedule,restructureCases} from "../data/mock";
import {badge,compactAmd,money,paymentSourceLabel,statusLabel} from "../utils";
import {navigate} from "../router";
import {t} from "../i18n";
import {demoText} from "../demo-i18n";
import {activeExchangeRate,penaltyFor,portfolioFinanceSummary,scheduleCurrency,toAMD,updateExchangeRate} from "../services/finance-control";
import {closeModal,formValue,openLocalizedModal,toastLocalized} from "../components/layout";
import type {Currency} from "../models/types";

const monthKey:Record<string,string>={Sep:"finance.month.sep",Oct:"finance.month.oct",Nov:"finance.month.nov",Dec:"finance.month.dec",Jan:"finance.month.jan",Feb:"finance.month.feb"};
const monthLabel=(m:string)=>t(monthKey[m]??m);
const stat=(labelKey:string,value:string,note:string,tone="")=>`<div class="card finance-stat ${tone}"><div class="finance-stat-label">${t(labelKey)}</div><div class="finance-stat-value">${value}</div><div class="finance-stat-note">${note}</div></div>`;

export function financePage(){
  const summary=portfolioFinanceSummary(),unmatched=bankStatementLines.filter(x=>x.status==="unmatched").length;
  const pendingMortgage=mortgageApplications.filter(x=>!["funded","declined"].includes(x.status)).reduce((s,x)=>s+x.requestedAmount,0);
  const advances=paymentReceipts.filter(x=>x.unallocatedAmount>0&&x.accountingStatus==="confirmed"),expiringSecurities=financialSecurities.filter(x=>x.status==="expiring").length;
  const months:[[string,number,number],[string,number,number],[string,number,number],[string,number,number],[string,number,number],[string,number,number]]=[["Sep",32,18],["Oct",58,34],["Nov",74,49],["Dec",88,60],["Jan",64,52],["Feb",51,43]];
  const exposures=(['USD','EUR'] as Currency[]).map(currency=>{const open=paymentSchedule.filter(x=>scheduleCurrency(x)===currency).reduce((sum,x)=>sum+Math.max(0,x.amount-x.paid),0);return{currency,open,amd:toAMD(open,currency)}}).filter(x=>x.open>0);
  const overdueRows=paymentSchedule.filter(x=>penaltyFor(x).chargeableDays>0&&x.paid<x.amount);
  return `<section class="page">
    <div class="page-header"><div class="page-title"><div class="eyebrow">${t("finance.workspace")}</div><h1>${t("financePage.title")}</h1><p>${t("v50.finance.subtitle")}</p></div><div class="toolbar"><button class="btn" id="openRates">${t("v50.finance.fxRates")}</button><button class="btn" id="openSecurities">${t("v50.finance.securities")}</button><button class="btn" id="openReconciliation">${t("financePage.reconciliation")} <span class="count-pill">${unmatched}</span></button><button class="btn btn-primary" id="openMortgages">${t("financePage.mortgageApplications")}</button></div></div>
    <div class="finance-metrics finance-metrics-v50">
      ${stat("financePage.contractPlan",compactAmd(summary.scheduledAMD),t("v50.finance.baseCurrency"))}
      ${stat("financePage.confirmedReceipts",compactAmd(summary.paidAMD),t("financePage.currentPlanPercent",{percent:summary.completion}),"positive")}
      ${stat("v50.finance.penaltyExposure",compactAmd(summary.penaltyAMD),t("v50.finance.penaltyCases",{count:overdueRows.length}),summary.penaltyAMD?"negative":"positive")}
      ${stat("v50.finance.advances",compactAmd(summary.advancesAMD),t("v50.finance.advanceCases",{count:advances.length}),summary.advancesAMD?"accent":"")}
      ${stat("v50.finance.securityCoverage",compactAmd(summary.securityAMD),t("v50.finance.securityCount",{count:financialSecurities.filter(x=>["active","expiring"].includes(x.status)).length}),"accent")}
    </div>
    <div class="finance-grid-main">
      <div class="card card-pad cashflow-card"><div class="section-title"><div><h2>${t("financePage.cashflowForecast")}</h2><p>${t("finance.cashflowSourceNote")}</p></div><div class="chip">AMD · ${t("v50.finance.normalized")}</div></div><div class="cashflow-chart"><div class="cashflow-axis"><span>${t("financePage.axis100")}</span><span>${t("financePage.axis75")}</span><span>${t("financePage.axis50")}</span><span>${t("financePage.axis25")}</span><span>0</span></div><div class="cashflow-bars">${months.map(([m,buyer,bank])=>`<div class="cashflow-month"><div class="cashflow-stack"><span class="cashflow-bank" style="height:${bank}%"></span><span class="cashflow-buyer" style="height:${buyer}%"></span></div><strong>${monthLabel(m)}</strong></div>`).join("")}</div></div><div class="chart-legend"><span><i class="legend-dot buyer"></i> ${t("financePage.buyer")}</span><span><i class="legend-dot bank"></i> ${t("financePage.bankMortgage")}</span></div></div>
      <div class="card card-pad finance-alerts"><div class="section-title"><div><h2>${t("financePage.exceptions")}</h2><p>${t("financePage.needsDecisionToday")}</p></div></div>
        <button class="finance-alert danger" data-route-fin="payments"><span class="alert-icon">!</span><span><strong>${t("v50.finance.overdueWithPenalty",{amount:compactAmd(summary.openAMD),penalty:compactAmd(summary.penaltyAMD)})}</strong><small>${t("v50.finance.overdueWithPenaltySub")}</small></span><b>→</b></button>
        <button class="finance-alert warning" data-route-fin="reconciliation"><span class="alert-icon">≋</span><span><strong>${t("financePage.unmatchedPayments",{count:unmatched})}</strong><small>${t("financePage.manualDealMatchRequired")}</small></span><b>→</b></button>
        <button class="finance-alert accent" data-route-fin="payments"><span class="alert-icon">↗</span><span><strong>${t("v50.finance.advanceAlert",{count:advances.length})}</strong><small>${t("v50.finance.advanceAlertSub")}</small></span><b>→</b></button>
        <button class="finance-alert neutral" data-route-fin="securities"><span class="alert-icon">◇</span><span><strong>${t("v50.finance.expiringSecurity",{count:expiringSecurities})}</strong><small>${t("v50.finance.expiringSecuritySub")}</small></span><b>→</b></button>
      </div>
    </div>
    <div class="grid grid-2 u-mt-16">
      <div class="card card-pad"><div class="section-title"><div><h2>${t("v50.finance.fxBook")}</h2><p>${t("v50.finance.fxBookSub")}</p></div><button class="text-btn" id="editRates">${t("v50.finance.editRates")}</button></div><div class="fx-rate-grid">${exchangeRates.filter(x=>x.status==="active").map(r=>`<div class="fx-rate-card ${r.currency==='AMD'?'base':''}"><div><span>${r.currency}</span><strong>${r.currency==='AMD'?'1.0000':r.rateToAMD.toFixed(2)}</strong></div><small>${r.currency==='AMD'?t("v50.finance.base"):t("v50.finance.amdPerUnit")} · ${r.effectiveDate}</small><em>${r.source}</em></div>`).join("")}</div>${exposures.length?`<div class="fx-exposure"><span>${t("v50.finance.foreignExposure")}</span>${exposures.map(x=>`<div><strong>${money(x.open,x.currency)}</strong><small>≈ ${compactAmd(x.amd)}</small></div>`).join("")}</div>`:""}</div>
      <div class="card card-pad"><div class="section-title"><div><h2>${t("v50.finance.advancesTitle")}</h2><p>${t("v50.finance.advancesSub")}</p></div><button class="text-btn" data-route-fin="payments">${t("v50.finance.manageAdvances")}</button></div><div class="finance-list">${advances.length?advances.slice(0,4).map(r=>{const d=deals.find(x=>x.id===r.dealId);return`<div class="finance-list-row" data-deal-fin="${r.dealId}"><div class="bank-avatar">↗</div><div class="finance-list-copy"><strong>${r.payer}</strong><span>${r.reference} · ${d?.id??r.dealId}</span></div><div class="finance-list-value"><strong>${money(r.unallocatedAmount,r.dealCurrency)}</strong><span class="status warning">${statusLabel(r.status)}</span></div></div>`}).join(""):`<div class="empty compact-empty">${t("v50.finance.noAdvances")}</div>`}</div></div>
    </div>
    <div class="grid grid-2 u-mt-16">
      <div class="card card-pad"><div class="section-title"><div><h2>${t("financePage.upcomingPayments")}</h2><p>${t("financePage.activeDeals")}</p></div><button class="text-btn" data-route-fin="payments">${t("financePage.allPayments")}</button></div><div class="finance-list">${paymentSchedule.filter(p=>p.status!=="paid").slice(0,6).map(p=>`<div class="finance-list-row" data-deal-fin="${p.dealId}"><div class="finance-date"><strong>${p.dueDate.slice(0,5)}</strong><span>${paymentSourceLabel(p.source)}</span></div><div class="finance-list-copy"><strong>${demoText(p.title)}</strong><span>${p.dealId} · ${scheduleCurrency(p)}</span></div><div class="finance-list-value"><strong>${money(p.amount-p.paid,scheduleCurrency(p))}</strong>${badge(p.status)}</div></div>`).join("")}</div></div>
      <div class="card card-pad"><div class="section-title"><div><h2>${t("financePage.mortgagePortfolio")}</h2><p>${t("financePage.bankDealFinancing")}</p></div><button class="text-btn" data-route-fin="mortgages">${t("financePage.open")}</button></div><div class="finance-list">${mortgageApplications.map(m=>`<div class="finance-list-row" data-mortgage="${m.id}"><div class="bank-avatar">${m.bank.slice(0,2).toUpperCase()}</div><div class="finance-list-copy"><strong>${m.clientName}</strong><span>${m.bank} · ${m.propertyLabel.split(" · ").pop()}</span></div><div class="finance-list-value"><strong>${compactAmd(m.requestedAmount)}</strong>${badge(m.status)}</div></div>`).join("")}</div><div class="finance-total-note">${t("v50.finance.pendingMortgage")}: ${compactAmd(pendingMortgage)}</div></div>
    </div>
  </section>`;
}
export function bindFinance(){
  document.querySelector("#openReconciliation")?.addEventListener("click",()=>navigate("reconciliation"));document.querySelector("#openMortgages")?.addEventListener("click",()=>navigate("mortgages"));document.querySelector("#openSecurities")?.addEventListener("click",()=>navigate("securities"));document.querySelector("#openRates")?.addEventListener("click",openRateBook);document.querySelector("#editRates")?.addEventListener("click",openRateBook);
  document.querySelectorAll("[data-route-fin]").forEach(el=>el.addEventListener("click",()=>navigate((el as HTMLElement).dataset.routeFin!)));document.querySelectorAll("[data-deal-fin]").forEach(el=>el.addEventListener("click",()=>navigate("deal/"+(el as HTMLElement).dataset.dealFin)));document.querySelectorAll("[data-mortgage]").forEach(el=>el.addEventListener("click",()=>navigate("mortgage/"+(el as HTMLElement).dataset.mortgage)));
}
function openRateBook(){const currencies=(['USD','EUR'] as Currency[]);openLocalizedModal(t("v50.fx.title"),`<div class="modal-note">${t("v50.fx.note")}</div><form id="fxForm" class="form-grid u-mt-14">${currencies.map(c=>`<div class="form-field"><label>${c} · ${t("v50.finance.amdPerUnit")}</label><input name="rate-${c}" type="number" step="0.01" min="0.01" value="${activeExchangeRate(c)}"></div><div class="form-field"><label>${t("v50.fx.source")}</label><input name="source-${c}" value="${exchangeRates.find(x=>x.currency===c&&x.status==='active')?.source??''}"></div>`).join("")}</form>`,`<button class="btn" data-modal-close>${t("v50.common.cancel")}</button><button class="btn btn-primary" id="saveRates">${t("v50.common.save")}</button>`);setTimeout(()=>document.querySelector("#saveRates")?.addEventListener("click",()=>{const f=document.querySelector<HTMLFormElement>("#fxForm")!;currencies.forEach(c=>updateExchangeRate(c,Number(formValue(f,`rate-${c}`)),formValue(f,`source-${c}`)||"Finance manual rate"));closeModal();toastLocalized(t("v50.fx.saved"));navigate("dashboard");setTimeout(()=>navigate("finance"),20)}),0)}
