import {deals,financialSecurities} from "../data/mock";
import {closeModal,formValue,openLocalizedModal,toastLocalized} from "../components/layout";
import {navigate} from "../router";
import {money,statusLabel} from "../utils";
import {t} from "../i18n";
import {toAMD} from "../services/finance-control";
import type {Currency,FinancialSecurityStatus,FinancialSecurityType} from "../models/types";

const typeLabel=(type:FinancialSecurityType)=>t(`v50.securityType.${type}`);
const statusTone=(status:FinancialSecurityStatus)=>status==="active"?"success":status==="expiring"?"warning":status==="expired"?"danger":status==="released"?"neutral":"info";
const securityBadge=(status:FinancialSecurityStatus)=>`<span class="status ${statusTone(status)}">${statusLabel(status)}</span>`;
const coverage=(s:(typeof financialSecurities)[number])=>{const d=deals.find(x=>x.id===s.dealId);if(!d)return 0;const dealAMD=toAMD(d.amount,d.currency),securityAMD=toAMD(s.amount,s.currency);return dealAMD?Math.min(999,Math.round(securityAMD/dealAMD*100)):0};

export function financialSecuritiesPage(){
  const active=financialSecurities.filter(x=>["active","expiring"].includes(x.status)),expiring=financialSecurities.filter(x=>x.status==="expiring").length,totalAMD=active.reduce((sum,x)=>sum+toAMD(x.amount,x.currency),0),guarantees=active.filter(x=>["guarantee","bank-guarantee","surety"].includes(x.type)).length;
  return `<section class="page" id="securityRegistry">
    <div class="page-header"><div class="page-title"><div class="eyebrow">${t("v50.security.eyebrow")}</div><h1>${t("v50.security.title")}</h1><p>${t("v50.security.subtitle")}</p></div><div class="toolbar"><button class="btn" id="backFinanceSecurity">${t("v50.security.back")}</button><button class="btn btn-primary" id="newSecurity">${t("v50.security.new")}</button></div></div>
    <div class="grid grid-4 u-mb-16">
      ${metric(t("v50.security.kpi.active"),String(active.length),t("v50.security.kpi.activeNote"))}
      ${metric(t("v50.security.kpi.coverage"),`${new Intl.NumberFormat().format(totalAMD)} ֏`,t("v50.security.kpi.coverageNote"))}
      ${metric(t("v50.security.kpi.expiring"),String(expiring),t("v50.security.kpi.expiringNote"),expiring?"negative":"positive")}
      ${metric(t("v50.security.kpi.guarantees"),String(guarantees),t("v50.security.kpi.guaranteesNote"))}
    </div>
    <div class="card"><div class="card-pad table-toolbar"><div><strong>${t("v50.security.registry")}</strong><div class="subtle">${t("v50.security.registrySub")}</div></div><div class="toolbar"><select class="field" id="securityTypeFilter"><option value="">${t("v50.security.allTypes")}</option>${(["pledge","guarantee","bank-guarantee","insurance","surety","advance","other"] as FinancialSecurityType[]).map(x=>`<option value="${x}">${typeLabel(x)}</option>`).join("")}</select><select class="field" id="securityStatusFilter"><option value="">${t("v50.security.allStatuses")}</option>${(["draft","active","expiring","expired","released"] as FinancialSecurityStatus[]).map(x=>`<option value="${x}">${statusLabel(x)}</option>`).join("")}</select></div></div>
      <div class="table-wrap"><table class="table finance-security-table"><thead><tr><th>${t("v50.security.security")}</th><th>${t("v50.security.deal")}</th><th>${t("v50.security.provider")}</th><th>${t("v50.security.amount")}</th><th>${t("v50.security.coverage")}</th><th>${t("v50.security.validity")}</th><th>${t("v50.security.status")}</th></tr></thead><tbody>${financialSecurities.map(s=>row(s)).join("")}</tbody></table></div>
    </div>
  </section>`;
}
function metric(label:string,value:string,note:string,tone=""){return`<div class="card metric-card ${tone}"><div class="metric-top"><span>${label}</span></div><div class="metric-value u-fs-20">${value}</div><div class="metric-note">${note}</div></div>`}
function row(s:(typeof financialSecurities)[number]){const d=deals.find(x=>x.id===s.dealId);return`<tr data-security-row="${s.id}" data-security-type="${s.type}" data-security-status="${s.status}"><td><button class="link-button security-name" data-security-open="${s.id}">${typeLabel(s.type)}</button><div class="table-sub">${s.documentNo}</div></td><td><strong>${s.dealId}</strong><div class="table-sub">${d?.clientName??"—"}</div></td><td>${s.provider}<div class="table-sub">${s.beneficiary}</div></td><td><strong>${money(s.amount,s.currency)}</strong></td><td><div class="security-coverage"><strong>${coverage(s)}%</strong><span><i style="width:${Math.min(100,coverage(s))}%"></i></span></div></td><td>${s.validFrom}${s.validUntil?`<div class="table-sub">→ ${s.validUntil}</div>`:""}</td><td>${securityBadge(s.status)}</td></tr>`}

export function bindFinancialSecurities(){
  document.querySelector("#backFinanceSecurity")?.addEventListener("click",()=>navigate("finance"));
  document.querySelector("#newSecurity")?.addEventListener("click",()=>openSecurityForm());
  document.querySelectorAll<HTMLElement>("[data-security-open]").forEach(el=>el.addEventListener("click",()=>openSecurity(el.dataset.securityOpen!)));
  document.querySelector("#securityTypeFilter")?.addEventListener("change",filterRows);document.querySelector("#securityStatusFilter")?.addEventListener("change",filterRows);
}
function filterRows(){const type=(document.querySelector<HTMLSelectElement>("#securityTypeFilter")?.value??""),status=(document.querySelector<HTMLSelectElement>("#securityStatusFilter")?.value??"");document.querySelectorAll<HTMLElement>("[data-security-row]").forEach(row=>row.style.display=(!type||row.dataset.securityType===type)&&(!status||row.dataset.securityStatus===status)?"":"none")}
function openSecurity(id:string){const s=financialSecurities.find(x=>x.id===id);if(!s)return;const d=deals.find(x=>x.id===s.dealId);openLocalizedModal(`${typeLabel(s.type)} · ${s.id}`,`<div class="security-detail-hero"><div><span>${t("v50.security.coverage")}</span><strong>${coverage(s)}%</strong><small>${d?`${money(s.amount,s.currency)} / ${money(d.amount,d.currency)}`:""}</small></div>${securityBadge(s.status)}</div><div class="info-list"><div class="info-box"><span>${t("v50.security.deal")}</span><strong>${s.dealId}</strong></div><div class="info-box"><span>${t("v50.security.provider")}</span><strong>${s.provider}</strong></div><div class="info-box"><span>${t("v50.security.beneficiary")}</span><strong>${s.beneficiary}</strong></div><div class="info-box"><span>${t("v50.security.amount")}</span><strong>${money(s.amount,s.currency)}</strong></div><div class="info-box"><span>${t("v50.security.document")}</span><strong>${s.documentName??s.documentNo}</strong></div><div class="info-box"><span>${t("v50.security.owner")}</span><strong>${s.owner}</strong></div><div class="info-box"><span>${t("v50.security.validFrom")}</span><strong>${s.validFrom}</strong></div><div class="info-box"><span>${t("v50.security.validUntil")}</span><strong>${s.validUntil??"—"}</strong></div></div>${s.note?`<div class="modal-note u-mt-14">${s.note}</div>`:""}`,`<button class="btn" data-modal-close>${t("v50.common.close")}</button>${s.status!=="released"?`<button class="btn" id="releaseSecurity">${t("v50.security.release")}</button>`:""}<button class="btn btn-primary" id="openSecurityDeal">${t("v50.security.openDeal")}</button>`);setTimeout(()=>{document.querySelector("#openSecurityDeal")?.addEventListener("click",()=>{closeModal();navigate("deal/"+s.dealId)});document.querySelector("#releaseSecurity")?.addEventListener("click",()=>{s.status="released";closeModal();toastLocalized(t("v50.security.releasedToast"));refresh()})},0)}
function openSecurityForm(){openLocalizedModal(t("v50.security.newTitle"),`<form id="securityForm" class="form-grid"><div class="form-field full"><label>${t("v50.security.deal")}</label><select name="dealId" required><option value="">${t("v50.security.chooseDeal")}</option>${deals.map(d=>`<option value="${d.id}">${d.id} · ${d.clientName}</option>`).join("")}</select></div><div class="form-field"><label>${t("v50.security.type")}</label><select name="type">${(["pledge","guarantee","bank-guarantee","insurance","surety","advance","other"] as FinancialSecurityType[]).map(x=>`<option value="${x}">${typeLabel(x)}</option>`).join("")}</select></div><div class="form-field"><label>${t("v50.security.provider")}</label><input name="provider" required></div><div class="form-field"><label>${t("v50.security.amount")}</label><input name="amount" type="number" min="0" required></div><div class="form-field"><label>${t("v50.security.currency")}</label><select name="currency"><option>AMD</option><option>USD</option><option>EUR</option></select></div><div class="form-field"><label>${t("v50.security.validFrom")}</label><input name="validFrom" value="22.09.2026"></div><div class="form-field"><label>${t("v50.security.validUntil")}</label><input name="validUntil" placeholder="31.12.2026"></div><div class="form-field"><label>${t("v50.security.documentNo")}</label><input name="documentNo" required></div><div class="form-field"><label>${t("v50.security.beneficiary")}</label><input name="beneficiary" value="EstateFlow Developer"></div><div class="form-field full"><label>${t("v50.security.note")}</label><textarea name="note"></textarea></div></form>`,`<button class="btn" data-modal-close>${t("v50.common.cancel")}</button><button class="btn btn-primary" id="saveSecurity">${t("v50.common.save")}</button>`);setTimeout(()=>document.querySelector("#saveSecurity")?.addEventListener("click",()=>{const f=document.querySelector<HTMLFormElement>("#securityForm")!;if(!f.reportValidity())return;financialSecurities.unshift({id:`SEC-2026-${String(35+financialSecurities.length).padStart(3,"0")}`,dealId:formValue(f,"dealId"),type:formValue(f,"type") as FinancialSecurityType,provider:formValue(f,"provider"),amount:Number(formValue(f,"amount")),currency:formValue(f,"currency") as Currency,validFrom:formValue(f,"validFrom"),validUntil:formValue(f,"validUntil")||undefined,status:"active",documentNo:formValue(f,"documentNo"),beneficiary:formValue(f,"beneficiary"),owner:"Finance",note:formValue(f,"note")||undefined});closeModal();toastLocalized(t("v50.security.createdToast"));refresh()}),0)}
function refresh(){navigate("finance");setTimeout(()=>navigate("securities"),20)}
