import {deals,legalCases,powersOfAttorney,registrationCases} from "../data/mock";
import {badge,statusLabel} from "../utils";
import {navigate} from "../router";
import {closeModal,formValue,openLocalizedModal,toastLocalized} from "../components/layout";
import {demoText} from "../demo-i18n";
import {t} from "../i18n";
import type {LegalCase,LegalCheckItem,LegalCheckStatus} from "../models/types";
import {poaUsable} from "../services/authority";

const lClass:Record<string,string>={clear:"success",review:"warning",blocked:"danger"};
const legalCaseTypeLabel=(value:string)=>{const key=({"Standard KYC":"legalPage.caseType.standardKyc","standard-kyc":"legalPage.caseType.standardKyc","Authority / UBO review":"legalPage.caseType.authorityUbo","authority-ubo":"legalPage.caseType.authorityUbo","Contract deviation":"legalPage.caseType.contractDeviation","contract-deviation":"legalPage.caseType.contractDeviation","Property restrictions":"legalPage.caseType.propertyRestrictions","property-restrictions":"legalPage.caseType.propertyRestrictions","Payment / contract breach":"legalPage.caseType.paymentContractBreach"} as Record<string,string>)[value];return key?t(key):demoText(value)};
const riskLabel=(value:string)=>t(`enum.risk.${value.toLowerCase()}`);
const checkLabel=(value:string)=>value.startsWith("i18n:")?t(value.slice(5)):demoText(value);

export function legalPage(){
 const open=legalCases.filter(x=>x.status==="review").length,blocked=legalCases.filter(x=>x.status==="blocked").length,authorityAlerts=powersOfAttorney.filter(x=>!["revoked","expired"].includes(x.status)&&!poaUsable(x)||x.status==="expiring").length,clear=legalCases.filter(x=>x.status==="clear").length;
 return `<section class="page" id="legalWorkspace">
 <div class="page-header"><div class="page-title"><div class="eyebrow">${t("legal.workspace")}</div><h1>${t("legalPage.title")}</h1><p>${t("v43.legal.subtitle")}</p></div><div class="toolbar"><button class="btn" id="poaRegistry">${t("legalPage.poa")}</button><button class="btn btn-accent" id="newLegalCase">${t("legalPage.newReview")}</button></div></div>
 <div class="legal-hero v43-legal-hero"><div><span class="eyebrow light">${t("legal.today")}</span><h2>${t("v43.legal.attentionTitle",{count:open+blocked+authorityAlerts})}</h2><p>${t("v43.legal.attentionText")}</p></div><div class="legal-hero-kpis"><div><span>${t("legalPage.openReviews")}</span><strong>${open}</strong></div><div><span>${t("legalPage.blocked")}</span><strong>${blocked}</strong></div><div><span>${t("v43.legal.authorityAlerts")}</span><strong>${authorityAlerts}</strong></div></div></div>
 <div class="grid grid-4 u-mt-16 legal-summary-grid">
  ${summary(t("v43.legal.metric.clear"),clear,t("v43.legal.metric.clearNote"),"success")}${summary(t("v43.legal.metric.review"),open,t("v43.legal.metric.reviewNote"),"warning")}${summary(t("v43.legal.metric.blocked"),blocked,t("v43.legal.metric.blockedNote"),"danger")}${summary(t("v43.legal.metric.poa"),powersOfAttorney.length,t("v43.legal.metric.poaNote"),"accent")}
 </div>
 <div class="grid grid-2 u-mt-16">
  <div class="card card-pad"><div class="section-title"><div><h2>${t("legalPage.reviewQueue")}</h2><p>${t("v43.legal.reviewQueueSubtitle")}</p></div><button class="btn btn-soft" id="allLegalCases">${t("legalPage.allReviews")}</button></div>
   <div class="legal-case-list">${legalCases.map(x=>legalCaseRow(x)).join("")}</div>
  </div>
  <div class="card card-pad"><div class="section-title"><div><h2>${t("v43.legal.authorityDesk")}</h2><p>${t("v43.legal.authorityDeskSub")}</p></div><button class="btn btn-soft" id="openPoaDesk">${t("v43.legal.openPoaDesk")}</button></div>
   <div class="authority-alert-list">${powersOfAttorney.filter(p=>p.status!=="active"||p.verificationStatus!=="verified").slice(0,4).map(p=>`<button class="authority-alert-row" data-poa-link="${p.id}"><div class="authority-alert-icon ${["revoked","expired","suspended"].includes(p.status)?"danger":"warning"}">§</div><div><strong>${p.representative}</strong><span>${p.documentNo} · ${p.relatedDeal??t("poaPage.noRelation")}</span></div>${badge(p.status)}</button>`).join("")}</div>
  </div>
 </div>
 <div class="grid grid-3 u-mt-16">
  <div class="card card-pad legal-module-card" id="moduleKyc"><div class="module-icon">ID</div><h3>${t("legalPage.kycCompliance")}</h3><p>${t("legalPage.kycText")}</p><span>${t("legalPage.kycNeedsReview")}</span></div>
  <div class="card card-pad legal-module-card" id="modulePoa"><div class="module-icon">POA</div><h3>${t("legalPage.poa")}</h3><p>${t("v43.legal.poaModuleText")}</p><span>${t("legalPage.registryCount",{count:powersOfAttorney.length})}</span></div>
  <div class="card card-pad legal-module-card" id="moduleRegistration"><div class="module-icon">REG</div><h3>${t("legalPage.notaryRegistration")}</h3><p>${t("v43.legal.registrationModuleText")}</p><span>${t("v43.legal.registrationCount",{count:registrationCases.length})}</span></div>
 </div>
 </section>`;
}
function summary(label:string,value:number,note:string,tone:string){return `<div class="card metric-card legal-summary ${tone}"><div class="metric-top"><span>${label}</span></div><div class="metric-value">${value}</div><div class="metric-foot">${note}</div></div>`}
function legalCaseRow(x:LegalCase){const checks=x.checklist??[],complete=checks.filter(c=>c.status==="clear").length;return `<button class="legal-case legal-case-v43" data-legal-case="${x.id}"><div class="risk-dot ${x.risk.toLowerCase()}"></div><div><strong>${x.clientName}</strong><span>${legalCaseTypeLabel(x.type)} · ${x.dealId}</span><small>${t("v43.legal.checksProgress",{done:complete,total:checks.length})}</small></div><div class="case-owner"><span>${x.owner}</span><small>${demoText(x.updatedAt)}</small></div><span class="status ${lClass[x.status]}">${statusLabel(x.status)}</span></button>`}

export function bindLegal(){
 document.querySelector("#poaRegistry")?.addEventListener("click",()=>navigate("legal/poa"));document.querySelector("#modulePoa")?.addEventListener("click",()=>navigate("legal/poa"));document.querySelector("#openPoaDesk")?.addEventListener("click",()=>navigate("legal/poa"));document.querySelector("#moduleRegistration")?.addEventListener("click",()=>navigate("registration"));document.querySelector("#moduleKyc")?.addEventListener("click",openKycQueue);document.querySelector("#newLegalCase")?.addEventListener("click",openLegalCase);document.querySelector("#allLegalCases")?.addEventListener("click",openAllLegalCases);
 document.querySelectorAll<HTMLElement>("[data-legal-case]").forEach(el=>el.addEventListener("click",()=>el.dataset.legalCase&&openLegalReview(el.dataset.legalCase)));
 document.querySelectorAll<HTMLElement>("[data-poa-link]").forEach(el=>el.addEventListener("click",()=>el.dataset.poaLink&&navigate("poa/"+el.dataset.poaLink)));
}
function openAllLegalCases(){openLocalizedModal(t("legalPage.allReviews"),`<div class="legal-case-list">${legalCases.map(x=>legalCaseRow(x)).join("")}</div>`);setTimeout(()=>document.querySelectorAll<HTMLElement>("[data-legal-case]").forEach(el=>el.addEventListener("click",()=>{const id=el.dataset.legalCase;if(!id)return;closeModal();setTimeout(()=>openLegalReview(id),20)})),0)}
function openKycQueue(){const items=legalCases.filter(x=>["Standard KYC","standard-kyc","Authority / UBO review","authority-ubo"].includes(x.type));openLocalizedModal(t("legalPage.kycQueueTitle"),`<div class="legal-case-list">${items.length?items.map(x=>legalCaseRow(x)).join(""):`<div class="empty compact-empty">${t("legalPage.kycQueueEmpty")}</div>`}</div>`);setTimeout(()=>document.querySelectorAll<HTMLElement>("[data-legal-case]").forEach(el=>el.addEventListener("click",()=>{const id=el.dataset.legalCase;if(!id)return;closeModal();setTimeout(()=>openLegalReview(id),20)})),0)}

function openLegalReview(id:string){const item=legalCases.find(x=>x.id===id);if(!item)return;const checks=item.checklist??[];openLocalizedModal(`${item.id} · ${item.clientName}`,`<div class="legal-review-workspace"><div class="legal-review-head"><div><span>${legalCaseTypeLabel(item.type)}</span><strong>${riskLabel(item.risk)} · ${item.dealId}</strong><small>${item.owner} · ${demoText(item.updatedAt)}</small></div>${badge(item.status)}</div><div class="legal-review-progress"><div><span>${t("v43.legal.checks")}</span><strong>${checks.filter(c=>c.status==="clear").length}/${checks.length}</strong></div><div><span>${t("v43.legal.evidence")}</span><strong>${item.evidenceCount??checks.length}</strong></div><div><span>${t("v43.legal.decision")}</span><strong>${statusLabel(item.status)}</strong></div></div><div class="legal-checklist-v43">${checks.map(c=>`<div class="legal-check-v43"><div class="checkmark ${c.status==="clear"?"":"pending"}">${c.status==="clear"?"✓":c.status==="blocked"?"×":"!"}</div><div><strong>${checkLabel(c.label)}${c.required?` <em>${t("v43.legal.required")}</em>`:""}</strong><span>${c.evidence}</span>${c.note?`<small>${c.note}</small>`:""}<small>${c.owner}</small></div><button class="btn btn-soft" data-edit-legal-check="${c.id}">${t("v43.legal.update")}</button></div>`).join("")||`<div class="empty compact-empty">${t("v43.legal.noChecks")}</div>`}</div><div class="modal-note u-mt-14"><strong>${t("v43.legal.decisionNote")}</strong><br>${item.decisionNote??"—"}</div></div>`,`<button class="btn" id="openLegalDeal">${t("v43.legal.openDeal")}</button><button class="btn" data-modal-close>${t("contractDetail.close")}</button><button class="btn btn-accent" id="finalizeLegalReview">${t("v43.legal.finalize")}</button>`);setTimeout(()=>{document.querySelector("#openLegalDeal")?.addEventListener("click",()=>{closeModal();navigate("deal/"+item.dealId)});document.querySelectorAll<HTMLElement>("[data-edit-legal-check]").forEach(el=>el.addEventListener("click",()=>{const check=checks.find(c=>c.id===el.dataset.editLegalCheck);if(check)openCheckEditor(item,check)}));document.querySelector("#finalizeLegalReview")?.addEventListener("click",()=>finalizeLegal(item))},0)}
function openCheckEditor(item:LegalCase,check:LegalCheckItem){openLocalizedModal(checkLabel(check.label),`<form id="legalCheckForm" class="form-grid"><div class="form-field"><label>${t("v43.legal.status")}</label><select name="status"><option value="clear" ${check.status==="clear"?"selected":""}>${statusLabel("clear")}</option><option value="review" ${check.status==="review"?"selected":""}>${statusLabel("review")}</option><option value="blocked" ${check.status==="blocked"?"selected":""}>${statusLabel("blocked")}</option></select></div><div class="form-field"><label>${t("v43.legal.owner")}</label><input name="owner" value="${check.owner}"></div><div class="form-field full"><label>${t("v43.legal.evidence")}</label><textarea name="evidence" required>${check.evidence}</textarea></div><div class="form-field full"><label>${t("v43.legal.note")}</label><textarea name="note">${check.note??""}</textarea></div></form>`,`<button class="btn" data-modal-close>${t("poaPage.cancel")}</button><button class="btn btn-accent" id="saveLegalCheck">${t("v43.common.save")}</button>`);setTimeout(()=>document.querySelector("#saveLegalCheck")?.addEventListener("click",()=>{const f=document.querySelector<HTMLFormElement>("#legalCheckForm")!;if(!f.reportValidity())return;check.status=formValue(f,"status") as LegalCheckStatus;check.owner=formValue(f,"owner");check.evidence=formValue(f,"evidence");check.note=formValue(f,"note")||undefined;item.updatedAt="22.09 · сейчас";item.status=(item.checklist??[]).some(c=>c.status==="blocked")?"blocked":(item.checklist??[]).some(c=>c.status==="review")?"review":"clear";closeModal();toastLocalized(t("v43.legal.checkUpdated"));setTimeout(()=>openLegalReview(item.id),20)}),0)}
function finalizeLegal(item:LegalCase){const blocked=(item.checklist??[]).some(c=>c.required&&c.status==="blocked"),pending=(item.checklist??[]).some(c=>c.required&&c.status!=="clear");if(blocked){item.status="blocked";toastLocalized(t("v43.legal.finalizeBlocked"))}else if(pending){item.status="review";toastLocalized(t("v43.legal.finalizePending"))}else{item.status="clear";item.decisionNote=t("v43.legal.clearDecision");toastLocalized(t("v43.legal.finalizeClear"))}item.updatedAt="22.09 · сейчас";closeModal();navigate("contracts");setTimeout(()=>navigate("legal"),20)}

function openLegalCase(){openLocalizedModal(t("legalPage.modal.title"),`<form id="legalCaseForm" class="form-grid"><div class="form-field full"><label>${t("legalPage.modal.deal")}</label><select name="dealId" required><option value="">${t("legalPage.modal.chooseDeal")}</option>${deals.map(d=>`<option value="${d.id}">${d.id} · ${d.clientName}</option>`).join("")}</select></div><div class="form-field"><label>${t("legalPage.modal.reviewType")}</label><select name="type"><option value="standard-kyc">${t("legalPage.caseType.standardKyc")}</option><option value="authority-ubo">${t("legalPage.caseType.authorityUbo")}</option><option value="contract-deviation">${t("legalPage.caseType.contractDeviation")}</option><option value="property-restrictions">${t("legalPage.caseType.propertyRestrictions")}</option></select></div><div class="form-field"><label>${t("legalPage.modal.risk")}</label><select name="risk"><option value="low">${t("enum.risk.low")}</option><option value="medium">${t("enum.risk.medium")}</option><option value="high">${t("enum.risk.high")}</option></select></div><div class="form-field"><label>${t("legalPage.modal.owner")}</label><select name="owner"><option>Անահիտ Մարտիրոսյան</option><option>Վահե Խաչատրյան</option></select></div></form>`,`<button class="btn" data-modal-close>${t("legalPage.cancel")}</button><button class="btn btn-accent" id="saveLegalCase">${t("legalPage.create")}</button>`);setTimeout(()=>document.querySelector("#saveLegalCase")?.addEventListener("click",()=>{const f=document.querySelector<HTMLFormElement>("#legalCaseForm")!;if(!f.reportValidity())return;const d=deals.find(x=>x.id===formValue(f,"dealId"))!,type=formValue(f,"type"),id=`LG-${90+legalCases.length+1}`,checklist=defaultChecklist(type,formValue(f,"owner"));legalCases.push({id,clientId:d.clientId,clientName:d.clientName,dealId:d.id,type,risk:formValue(f,"risk"),status:"review",owner:formValue(f,"owner"),updatedAt:"22.09 · сейчас",evidenceCount:0,decisionNote:t("v43.legal.newReviewDecision"),checklist});closeModal();toastLocalized(t("legalPage.toast.created"));navigate("contracts");setTimeout(()=>navigate("legal"),20)}),0)}
function defaultChecklist(type:string,owner:string):LegalCheckItem[]{const base:LegalCheckItem[]=[{id:`LC-${Date.now()}-1`,label:"i18n:v43.legal.check.identity",status:"review",required:true,owner,evidence:t("v43.legal.evidencePending")},{id:`LC-${Date.now()}-2`,label:"i18n:v43.legal.check.property",status:"review",required:true,owner,evidence:t("v43.legal.evidencePending")},{id:`LC-${Date.now()}-3`,label:"i18n:v43.legal.check.risk",status:"review",required:false,owner,evidence:t("v43.legal.evidencePending")}];if(type==="authority-ubo")base.splice(1,0,{id:`LC-${Date.now()}-4`,label:"i18n:v43.legal.check.signatory",status:"review",required:true,owner,evidence:t("v43.legal.evidencePending")},{id:`LC-${Date.now()}-5`,label:"i18n:v43.legal.check.ubo",status:"review",required:true,owner,evidence:t("v43.legal.evidencePending")});if(type==="contract-deviation")base.push({id:`LC-${Date.now()}-6`,label:"i18n:v43.legal.check.contract",status:"review",required:true,owner,evidence:t("v43.legal.evidencePending")});return base}
