import { deals, mortgageApplications, paymentSchedule } from "../data/mock";
import { amd, badge, paymentSourceLabel, statusLabel } from "../utils";
import { navigate } from "../router";
import { closeModal, formValue, openLocalizedModal, toastLocalized } from "../components/layout";
import { bindTabs } from "../components/tabs";
import { t } from "../i18n";
import { demoText } from "../demo-i18n";

const documentKeys=[
  "mortgageDetail.doc.passport","mortgageDetail.doc.income","mortgageDetail.doc.employment","mortgageDetail.doc.property","mortgageDetail.doc.preliminaryContract","mortgageDetail.doc.valuation","mortgageDetail.doc.insuranceApplication","mortgageDetail.doc.bankStatement","mortgageDetail.doc.coBorrowerConsent","mortgageDetail.doc.bankApplication"
] as const;

export function mortgageDetailPage(id:string){
  const m=mortgageApplications.find(x=>x.id===id);if(!m)return`<section class="page"><div class="card card-pad">${t("mortgageDetail.notFound")}</div></section>`;
  const deal=deals.find(x=>x.id===m.dealId),ltv=Math.round(m.requestedAmount/m.propertyPrice*100),schedule=paymentSchedule.filter(x=>x.dealId===m.dealId);
  return `<section class="page" id="mortgage360">
    <div class="breadcrumbs"><span>${t("mortgageDetail.finance")}</span><span>›</span><span>${t("mortgageDetail.mortgage")}</span><span>›</span><span>${m.id}</span></div>
    <div class="detail-header"><div class="detail-title"><small>${m.id} · ${m.dealId}</small><h1>${m.clientName}</h1><div class="toolbar">${badge(m.status)}<span class="chip">${m.bank}</span></div></div><div class="toolbar"><button class="btn" id="backMortgages">${t("mortgageDetail.registry")}</button><button class="btn" id="openDealMortgage">${t("mortgageDetail.deal")}</button><button class="btn btn-primary" id="advanceMortgage">${t("mortgageDetail.nextStage")}</button></div></div>
    <div class="mortgage-hero card"><div class="mortgage-hero-main"><div class="eyebrow">${t("mortgageDetail.financingStructure")}</div><h2>${m.propertyLabel}</h2><p>${demoText(m.program)}</p><div class="mortgage-amount-grid"><div><span>${t("mortgageDetail.propertyPrice")}</span><strong>${amd(m.propertyPrice)}</strong></div><div><span>${t("mortgageDetail.ownContribution")}</span><strong>${amd(m.downPayment)}</strong></div><div><span>${t("mortgageDetail.requestedFromBank")}</span><strong>${amd(m.requestedAmount)}</strong></div><div><span>${t("mortgageDetail.approved")}</span><strong>${m.approvedAmount?amd(m.approvedAmount):"—"}</strong></div></div></div><div class="ltv-ring" style="--pct:${ltv*3.6}deg"><div><strong>${ltv}%</strong><span>LTV</span></div></div></div>
    <div class="tabs">${[["overview","mortgageDetail.tab.overview"],["documents","mortgageDetail.tab.documents"],["decision","mortgageDetail.tab.decision"],["schedule","mortgageDetail.tab.schedule"],["collateral","mortgageDetail.tab.collateral"],["history","mortgageDetail.tab.history"]].map(([k,key],i)=>`<button class="tab ${i===0?"active":""}" data-tab-target="${k}">${t(key)}</button>`).join("")}</div>
    <div class="detail-tab-content"><div data-tab-panel="overview">${overview(m)}</div><div data-tab-panel="documents" hidden>${documents(m)}</div><div data-tab-panel="decision" hidden>${decision(m,ltv)}</div><div data-tab-panel="schedule" hidden>${schedulePanel(schedule)}</div><div data-tab-panel="collateral" hidden>${collateral(m)}</div><div data-tab-panel="history" hidden>${history(m,deal)}</div></div>
  </section>`;
}
function overview(m:any){return`<div class="finance-grid-main"><div class="card card-pad"><div class="section-title"><div><h2>${t("mortgageDetail.applicationStatus")}</h2><p>${t("mortgageDetail.workflowSubtitle")}</p></div></div><div class="mortgage-steps">${step("01",t("mortgageDetail.step.created"),m.submittedAt,"done")}${step("02",t("mortgageDetail.step.documents"),t("mortgageDetail.documentsCount",{done:m.documentsDone,total:m.documentsTotal}),m.documentsDone===m.documentsTotal?"done":"current")}${step("03",t("mortgageDetail.step.bankReview"),m.status==="bank-review"?t("mortgageDetail.inProgress"):m.approvedAmount?t("mortgageDetail.decisionReceived"):t("mortgageDetail.waiting"),m.status==="bank-review"?"current":m.approvedAmount?"done":"")}${step("04",t("mortgageDetail.step.creditContract"),m.status==="contracting"?t("mortgageDetail.inProgress"):t("mortgageDetail.afterApproval"),m.status==="contracting"?"current":"")}${step("05",t("mortgageDetail.step.disbursement"),t("mortgageDetail.toSellerAccount"),m.status==="funded"?"done":"")}</div></div><div class="card card-pad"><div class="section-title"><div><h2>${t("mortgageDetail.parameters")}</h2><p>${t("mortgageDetail.keyTerms")}</p></div></div><div class="info-list"><div class="info-box"><span>${t("mortgageDetail.bank")}</span><strong>${m.bank}</strong></div><div class="info-box"><span>${t("mortgageDetail.program")}</span><strong>${demoText(m.program)}</strong></div><div class="info-box"><span>${t("mortgageDetail.loanTerm")}</span><strong>${t("mortgageDetail.months",{count:m.termMonths})}</strong></div><div class="info-box"><span>${t("mortgageDetail.decisionDue")}</span><strong>${m.decisionDue}</strong></div><div class="info-box"><span>${t("mortgageDetail.coordinator")}</span><strong>${m.manager}</strong></div><div class="info-box"><span>${t("mortgageDetail.comment")}</span><strong>${demoText(m.note)}</strong></div></div></div></div>`}
function documents(m:any){return`<div class="card card-pad"><div class="section-title"><div><h2>${t("mortgageDetail.documentPackage")}</h2><p>${t("mortgageDetail.documentsReady",{done:m.documentsDone,total:m.documentsTotal})}</p></div><button class="btn btn-primary" data-demo-action="mortgage-upload">${t("mortgageDetail.addDocument")}</button></div><div class="check-list">${documentKeys.slice(0,m.documentsTotal).map((key,i)=>check(t(key),i<m.documentsDone)).join("")}</div></div>`}
function decision(m:any,ltv:number){return`<div class="grid grid-2"><div class="card card-pad"><div class="section-title"><div><h2>${t("mortgageDetail.bankDecision")}</h2><p>${t("mortgageDetail.decisionCapture")}</p></div>${badge(m.status)}</div><div class="info-list"><div class="info-box"><span>${t("mortgageDetail.requested")}</span><strong>${amd(m.requestedAmount)}</strong></div><div class="info-box"><span>${t("mortgageDetail.approved")}</span><strong>${m.approvedAmount?amd(m.approvedAmount):t("mortgageDetail.expected")}</strong></div><div class="info-box"><span>LTV</span><strong>${ltv}%</strong></div><div class="info-box"><span>${t("mortgageDetail.decisionDue")}</span><strong>${m.decisionDue}</strong></div></div></div><div class="card card-pad"><div class="section-title"><div><h2>${t("mortgageDetail.termsComments")}</h2></div></div><div class="soft-callout"><span>${t("mortgageDetail.bankNote")}</span><strong>${demoText(m.note)}</strong><button class="btn btn-soft" data-demo-action="bank-decision">${t("mortgageDetail.update")}</button></div></div></div>`}
function schedulePanel(rows:any[]){return`<div class="card card-pad"><div class="section-title"><div><h2>${t("mortgageDetail.dealFinancingSchedule")}</h2><p>${t("mortgageDetail.ownFundsPlusMortgage")}</p></div></div>${rows.map(s=>`<div class="schedule-row"><div class="schedule-index">${String(s.sequence).padStart(2,"0")}</div><div><strong>${demoText(s.title)}</strong><span>${s.dueDate} · ${paymentSourceLabel(s.source)}</span></div><div class="schedule-value"><strong>${amd(s.amount)}</strong>${badge(s.status)}</div></div>`).join("")||`<div class="empty compact-empty">${t("mortgageDetail.scheduleNotFormed")}</div>`}</div>`}
function collateral(m:any){return`<div class="grid grid-2"><div class="card card-pad"><div class="section-title"><div><h2>${t("mortgageDetail.collateral")}</h2><p>${t("mortgageDetail.financingSecurity")}</p></div></div><div class="info-list"><div class="info-box"><span>${t("mortgageDetail.collateralProperty")}</span><strong>${m.propertyLabel}</strong></div><div class="info-box"><span>${t("mortgageDetail.appraisedValue")}</span><strong>${amd(m.propertyPrice)}</strong></div><div class="info-box"><span>${t("mortgageDetail.collateralRegistration")}</span><strong>${m.approvedAmount?t("mortgageDetail.afterCreditContract"):t("mortgageDetail.awaitingDecision")}</strong></div><div class="info-box"><span>${t("mortgageDetail.pledgeeBank")}</span><strong>${m.bank}</strong></div></div></div><div class="card card-pad"><div class="section-title"><div><h2>${t("mortgageDetail.insurance")}</h2><p>${t("mortgageDetail.documentsBeforeFunding")}</p></div></div>${check(t("mortgageDetail.propertyInsurance"),m.documentsDone===m.documentsTotal)}${check(t("mortgageDetail.borrowerInsurance"),m.documentsDone>=m.documentsTotal-1)}${check(t("mortgageDetail.bankBeneficiary"),m.approvedAmount>0)}</div></div>`}
function history(m:any,deal:any){return`<div class="card card-pad"><div class="section-title"><div><h2>${t("mortgageDetail.historyTitle")}</h2><p>${t("mortgageDetail.historySubtitle")}</p></div></div><div class="timeline">${timeline(t("mortgageDetail.history.created"),`${m.submittedAt} · ${m.manager}`,"done")}${timeline(t("mortgageDetail.history.linkedDeal"),`${deal?.id??m.dealId} · ${m.propertyLabel}`,"done")}${timeline(t("mortgageDetail.history.documentPackage"),t("mortgageDetail.readyCount",{done:m.documentsDone,total:m.documentsTotal}),m.documentsDone===m.documentsTotal?"done":"current")}${timeline(t("mortgageDetail.history.currentStage"),`${statusLabel(m.status)} · ${t("mortgageDetail.decisionBy")} ${m.decisionDue}`,"current")}</div></div>`}
function step(n:string,title:string,sub:string,state:string){return`<div class="mortgage-step ${state}"><div class="mortgage-step-no">${n}</div><div><strong>${title}</strong><span>${sub}</span></div></div>`}
function check(label:string,ok:boolean){return`<div class="check-row ${ok?"done":"missing"}"><span class="check-box">${ok?"✓":"·"}</span><strong>${label}</strong><span>${ok?t("mortgageDetail.ready"):t("mortgageDetail.expected")}</span></div>`}
function timeline(title:string,sub:string,state:string){return`<div class="timeline-item ${state}"><div class="timeline-dot"></div><div class="timeline-copy"><strong>${title}</strong><span>${sub}</span></div></div>`}
const mortgageFlow=["draft","documents","bank-review","approved","contracting","funded"] as const;
function reloadMortgage(id:string){navigate("mortgages");setTimeout(()=>navigate("mortgage/"+id),20)}
function advanceMortgage(id:string){const m=mortgageApplications.find(x=>x.id===id);if(!m)return;if(m.status==="declined"){toastLocalized(t("mortgageDetail.rejectedByBank"));return}if(m.status==="documents"&&m.documentsDone<m.documentsTotal){toastLocalized(t("mortgageDetail.completeDocumentsFirst",{done:m.documentsDone,total:m.documentsTotal}));return}if(m.status==="bank-review"){openBankDecision(id);return}const idx=mortgageFlow.indexOf(m.status as any);if(idx<0||idx===mortgageFlow.length-1){toastLocalized(t("mortgageDetail.processCompleted"));return}m.status=mortgageFlow[idx+1];if(m.status==="funded"){const bankStage=paymentSchedule.find(x=>x.dealId===m.dealId&&x.source==="mortgage");if(bankStage){bankStage.paid=bankStage.amount;bankStage.status="paid"}}toastLocalized(t("mortgageDetail.movedTo",{status:statusLabel(m.status)}));reloadMortgage(id)}
function uploadMortgageDocument(id:string){const m=mortgageApplications.find(x=>x.id===id);if(!m)return;if(m.documentsDone>=m.documentsTotal){toastLocalized(t("mortgageDetail.packageComplete"));return}openLocalizedModal(t("mortgageDetail.addDocumentTitle"),`<form id="mortgageDocForm" class="form-grid"><div class="form-field full"><label>${t("mortgageDetail.document")}</label><select name="document">${documentKeys.map(key=>`<option value="${key}">${t(key)}</option>`).join("")}</select></div><div class="form-field full"><label>${t("mortgageDetail.file")}</label><input type="file" name="file"></div></form>`,`<button class="btn" data-modal-close>${t("mortgageDetail.cancel")}</button><button class="btn btn-accent" id="saveMortgageDoc">${t("mortgageDetail.add")}</button>`);setTimeout(()=>document.querySelector("#saveMortgageDoc")?.addEventListener("click",()=>{m.documentsDone=Math.min(m.documentsTotal,m.documentsDone+1);if(m.status==="draft")m.status="documents";closeModal();toastLocalized(t("mortgageDetail.documentAdded",{done:m.documentsDone,total:m.documentsTotal}));reloadMortgage(id)}),0)}
function openBankDecision(id:string){const m=mortgageApplications.find(x=>x.id===id);if(!m)return;openLocalizedModal(t("mortgageDetail.bankDecision"),`<form id="bankDecisionForm" class="form-grid"><div class="form-field"><label>${t("mortgageDetail.result")}</label><select name="result"><option value="approved">${t("mortgageDetail.resultApproved")}</option><option value="declined">${t("mortgageDetail.resultDeclined")}</option><option value="bank-review">${t("mortgageDetail.resultKeepReview")}</option></select></div><div class="form-field"><label>${t("mortgageDetail.approvedAmount")}</label><input name="approvedAmount" type="number" min="0" value="${m.approvedAmount||m.requestedAmount}"></div><div class="form-field full"><label>${t("mortgageDetail.bankComment")}</label><textarea name="note">${demoText(m.note)}</textarea></div></form>`,`<button class="btn" data-modal-close>${t("mortgageDetail.cancel")}</button><button class="btn btn-accent" id="saveBankDecision">${t("mortgageDetail.saveDecision")}</button>`);setTimeout(()=>document.querySelector("#saveBankDecision")?.addEventListener("click",()=>{const f=document.querySelector<HTMLFormElement>("#bankDecisionForm")!;const result=formValue(f,"result") as any;m.status=result;m.approvedAmount=result==="approved"?Number(formValue(f,"approvedAmount")):0;m.note=formValue(f,"note");closeModal();toastLocalized(t(result==="approved"?"mortgageDetail.decisionRecorded":"mortgageDetail.bankStatusUpdated"));reloadMortgage(id)}),0)}
export function bindMortgageDetail(){bindTabs("#mortgage360");const id=location.hash.split("?")[0].split("/").pop()!,m=mortgageApplications.find(x=>x.id===id);document.querySelector("#backMortgages")?.addEventListener("click",()=>navigate("mortgages"));document.querySelector("#openDealMortgage")?.addEventListener("click",()=>m&&navigate("deal/"+m.dealId));document.querySelector("#advanceMortgage")?.addEventListener("click",()=>advanceMortgage(id));document.querySelectorAll<HTMLElement>("[data-demo-action]").forEach(x=>x.addEventListener("click",()=>{const action=x.dataset.demoAction;if(action==="mortgage-upload")uploadMortgageDocument(id);else if(action==="bank-decision")openBankDecision(id)}))}
