import{closeModal,openLocalizedModal,toastLocalized}from"../components/layout";
import{locale,t}from"../i18n";
import type{NotificationCategory,NotificationSeverity,PlatformNotification}from"../models/types";
import{navigate}from"../router";
import{archiveNotification,clearNotificationSnooze,ensureNotificationsInitialized,isNotificationSnoozed,markAllNotificationsRead,markNotificationRead,notificationCategoryStats,notificationsForRole,notificationStats,restoreNotification,snoozeNotification}from"../services/notifications";
import{currentRole,roleLabelKey,type PlatformRole}from"../services/permissions";

const roleLabel=(role:string)=>{try{return t(roleLabelKey(role as PlatformRole))}catch{return role}};
const categories:NotificationCategory[]=["approval","payment","legal","registration","handover","service","sla"];
const severities:NotificationSeverity[]=["critical","warning","info","success"];
const categoryLabel=(c:NotificationCategory)=>t(`v53.category.${c}`);
const severityLabel=(s:NotificationSeverity)=>t(`v53.severity.${s}`);
const iconFor=(c:NotificationCategory)=>({approval:"✓",payment:"֏",legal:"§",registration:"R",handover:"⌂",service:"◇",sla:"!",general:"•"}[c]);
const dt=(iso:string)=>new Intl.DateTimeFormat(locale(),{day:"2-digit",month:"short",hour:"2-digit",minute:"2-digit"}).format(new Date(iso));
const refresh=()=>window.dispatchEvent(new HashChangeEvent("hashchange"));
const visibleInbox=(rows:PlatformNotification[])=>rows.filter(n=>!n.archivedAt&&!n.resolvedAt&&!isNotificationSnoozed(n));

export function notificationsPage(){ensureNotificationsInitialized();const role=currentRole(),rows=notificationsForRole(role,true),stats=notificationStats(role),catStats=notificationCategoryStats(role);return`<section class="page notification-page">
 <div class="page-header"><div class="page-title"><div class="eyebrow">${t("v53.eyebrow")}</div><h1>${t("v53.title")}</h1><p>${t("v53.subtitle")}</p></div><div class="toolbar"><span class="notification-role-chip"><small>${t("v53.forRole")}</small><strong>${roleLabel(role)}</strong></span><button class="btn" id="notificationRules">${t("v53.rules")}</button><button class="btn btn-accent" id="markAllNotifications">${t("v53.markAllRead")}</button></div></div>
 <div class="notification-kpis"><div class="card notification-kpi accent"><span>${t("v53.kpi.unread")}</span><strong>${stats.unread}</strong><small>${t("v53.kpi.unreadNote")}</small></div><div class="card notification-kpi danger"><span>${t("v53.kpi.critical")}</span><strong>${stats.critical}</strong><small>${t("v53.kpi.criticalNote")}</small></div><div class="card notification-kpi"><span>${t("v53.kpi.active")}</span><strong>${stats.total}</strong><small>${t("v53.kpi.activeNote")}</small></div><div class="card notification-kpi muted"><span>${t("v53.kpi.snoozed")}</span><strong>${stats.snoozed}</strong><small>${t("v53.kpi.snoozedNote")}</small></div></div>
 <div class="notification-tabs" role="tablist"><button class="active" data-notification-tab="inbox"><span>${t("v53.tab.inbox")}</span><b>${visibleInbox(rows).length}</b></button><button data-notification-tab="unread"><span>${t("v53.tab.unread")}</span><b>${stats.unread}</b></button><button data-notification-tab="critical"><span>${t("v53.tab.critical")}</span><b>${stats.critical}</b></button><button data-notification-tab="snoozed"><span>${t("v53.tab.snoozed")}</span><b>${stats.snoozed}</b></button><button data-notification-tab="archive"><span>${t("v53.tab.archive")}</span><b>${stats.archived}</b></button></div>
 <div class="notification-workspace"><aside class="card card-pad notification-sidebar"><div class="section-title"><div><h2>${t("v53.filters")}</h2><p>${t("v53.filtersSub")}</p></div></div><label>${t("v53.search")}</label><input id="notificationSearch" class="field" placeholder="${t("v53.searchPlaceholder")}"><label>${t("v53.filter.category")}</label><select id="notificationCategory" class="field"><option value="">${t("v53.filter.allCategories")}</option>${categories.map(c=>`<option value="${c}">${categoryLabel(c)}</option>`).join("")}</select><label>${t("v53.filter.severity")}</label><select id="notificationSeverity" class="field"><option value="">${t("v53.filter.allSeverities")}</option>${severities.map(s=>`<option value="${s}">${severityLabel(s)}</option>`).join("")}</select><div class="notification-policy-note"><span>●</span><div><strong>${t("v53.internalOnly")}</strong><p>${t("v53.internalOnlySub")}</p></div></div></aside>
 <main class="notification-feed"><div class="notification-feed-head"><div><span>${t("v53.feed")}</span><strong id="notificationVisibleCount">${visibleInbox(rows).length}</strong></div><div class="notification-legend"><span><i class="critical"></i>${t("v53.severity.critical")}</span><span><i class="warning"></i>${t("v53.severity.warning")}</span><span><i class="info"></i>${t("v53.severity.info")}</span></div></div><div id="notificationList" class="notification-list">${rows.map(notificationCard).join("")}<div id="notificationEmpty" class="notification-empty"><div>✓</div><h3>${t("v53.empty.title")}</h3><p>${t("v53.empty.text")}</p></div></div></main>
 <aside class="notification-insights"><section class="card card-pad"><div class="section-title"><div><h2>${t("v53.attentionMap")}</h2><p>${t("v53.attentionMapSub")}</p></div></div><div class="notification-category-map">${catStats.filter(x=>x.count).map(x=>`<button data-category-jump="${x.category}"><span class="notification-category-icon ${x.category}">${iconFor(x.category)}</span><div><strong>${categoryLabel(x.category)}</strong><small>${x.unread} ${t("v53.unreadShort")}${x.critical?` · ${x.critical} ${t("v53.criticalShort")}`:""}</small></div><b>${x.count}</b></button>`).join("")}</div></section><section class="card card-pad notification-focus-card"><div class="eyebrow">${t("v53.focus.eyebrow")}</div><h3>${t("v53.focus.title")}</h3><p>${t("v53.focus.text")}</p><button class="btn btn-primary" id="openTasksFromNotifications">${t("v53.focus.openTasks")}</button></section></aside></div>
 </section>`}

function notificationCard(n:PlatformNotification){const snoozed=isNotificationSnoozed(n),state=n.archivedAt?"archive":snoozed?"snoozed":!n.readAt?"unread":"read";const search=[n.title,n.description,n.sourceLabel,n.dealId,n.clientName,n.propertyLabel,n.category,n.severity].filter(Boolean).join(" ").toLowerCase();return`<article class="card notification-card ${state} ${n.severity}" data-notification-card="${n.id}" data-category="${n.category}" data-severity="${n.severity}" data-state="${state}" data-search="${search}"><button class="notification-card-main" data-notification-detail="${n.id}"><span class="notification-card-icon ${n.category}">${iconFor(n.category)}</span><span class="notification-unread-dot" aria-hidden="true"></span><div class="notification-card-copy"><div class="notification-card-top"><span class="notification-category-tag ${n.category}">${categoryLabel(n.category)}</span><span class="notification-severity ${n.severity}">${severityLabel(n.severity)}</span><span>${dt(n.createdAt)}</span></div><h3>${n.title}</h3><p>${n.description}</p><div class="notification-context">${n.clientName?`<span>${t("v53.client")}: <b>${n.clientName}</b></span>`:""}${n.dealId?`<span>${t("v53.deal")}: <b>${n.dealId}</b></span>`:""}${n.propertyLabel?`<span>${t("v53.property")}: <b>${n.propertyLabel}</b></span>`:""}${n.sourceLabel?`<span>${t("v53.source")}: <b>${n.sourceLabel}</b></span>`:""}</div>${snoozed?`<div class="notification-snooze-note">⏱ ${t("v53.snoozedUntil",{time:dt(n.snoozedUntil!)})}</div>`:""}${n.resolvedAt?`<div class="notification-resolved-note">✓ ${t("v53.resolved")}</div>`:""}</div></button><div class="notification-card-actions">${n.sourceRoute?`<button class="btn btn-primary" data-notification-source="${n.id}">${t("v53.open")}</button>`:""}${!n.archivedAt?`<button class="btn" data-notification-read="${n.id}">${n.readAt?t("v53.markUnread"):t("v53.markRead")}</button><button class="btn" data-notification-snooze="${n.id}">${snoozed?t("v53.unsnooze"):t("v53.snooze")}</button><button class="icon-btn notification-archive-btn" data-notification-archive="${n.id}" aria-label="${t("v53.archive")}" title="${t("v53.archive")}">×</button>`:`<button class="btn" data-notification-restore="${n.id}">${t("v53.restore")}</button>`}</div></article>`}

function findNotification(id:string){return notificationsForRole(currentRole(),true).find(x=>x.id===id)}
function openNotificationDetail(id:string){const n=findNotification(id);if(!n)return;markNotificationRead(id,true);const card=document.querySelector<HTMLElement>(`[data-notification-card="${id}"]`);if(card){card.classList.remove("unread");card.classList.add("read");card.dataset.state="read"}const badge=document.querySelector<HTMLElement>(".topbar-notification-badge");const unread=notificationStats(currentRole()).unread;if(badge){if(unread)badge.textContent=unread>99?"99+":String(unread);else badge.remove()}openLocalizedModal(n.title,`<div class="notification-detail"><div class="notification-detail-head"><span class="notification-card-icon ${n.category}">${iconFor(n.category)}</span><div><span class="notification-category-tag ${n.category}">${categoryLabel(n.category)}</span><span class="notification-severity ${n.severity}">${severityLabel(n.severity)}</span></div></div><p class="notification-detail-text">${n.description}</p><div class="notification-detail-grid"><div><span>${t("v53.created")}</span><strong>${dt(n.createdAt)}</strong></div><div><span>${t("v53.source")}</span><strong>${n.sourceLabel??"—"}</strong></div>${n.clientName?`<div><span>${t("v53.client")}</span><strong>${n.clientName}</strong></div>`:""}${n.dealId?`<div><span>${t("v53.deal")}</span><strong>${n.dealId}</strong></div>`:""}${n.propertyLabel?`<div class="wide"><span>${t("v53.property")}</span><strong>${n.propertyLabel}</strong></div>`:""}</div>${n.meta?.length?`<div class="notification-meta-list">${n.meta.map(x=>`<div><span>•</span><p>${x}</p></div>`).join("")}</div>`:""}<div class="notification-detail-status"><span>${n.readAt?t("v53.read"):t("v53.unread")}</span>${isNotificationSnoozed(n)?`<span>${t("v53.snoozedUntil",{time:dt(n.snoozedUntil!)})}</span>`:""}</div></div>`,`${n.sourceRoute?`<button class="btn btn-primary" id="notificationModalOpen">${t("v53.openProcess")}</button>`:""}<button class="btn" id="notificationModalSnooze">${isNotificationSnoozed(n)?t("v53.unsnooze"):t("v53.snooze")}</button><button class="btn" data-modal-close>${t("common.close")}</button>`);setTimeout(()=>{document.querySelector("#notificationModalOpen")?.addEventListener("click",()=>{closeModal();if(n.sourceRoute)navigate(n.sourceRoute)});document.querySelector("#notificationModalSnooze")?.addEventListener("click",()=>{if(isNotificationSnoozed(n))clearNotificationSnooze(n.id);else snoozeNotification(n.id,"2026-09-24T09:00:00+04:00");closeModal();refresh()})},0)}
function openSnooze(id:string){const n=findNotification(id);if(!n)return;if(isNotificationSnoozed(n)){clearNotificationSnooze(id);toastLocalized(t("v53.toast.unsnoozed"));refresh();return}openLocalizedModal(t("v53.snoozeTitle"),`<div class="notification-snooze-options"><button data-snooze-option="2026-09-23T19:00:00+04:00"><strong>${t("v53.snoozeLater")}</strong><span>${t("v53.snoozeLaterSub")}</span></button><button data-snooze-option="2026-09-24T09:00:00+04:00"><strong>${t("v53.snoozeTomorrow")}</strong><span>${t("v53.snoozeTomorrowSub")}</span></button><button data-snooze-option="2026-09-25T09:00:00+04:00"><strong>${t("v53.snoozeTwoDays")}</strong><span>${t("v53.snoozeTwoDaysSub")}</span></button></div>`);setTimeout(()=>document.querySelectorAll<HTMLElement>("[data-snooze-option]").forEach(btn=>btn.addEventListener("click",()=>{snoozeNotification(id,btn.dataset.snoozeOption!);closeModal();toastLocalized(t("v53.toast.snoozed"));refresh()})),0)}
function openRules(){openLocalizedModal(t("v53.rulesTitle"),`<div class="notification-rules"><div class="notification-rule-row"><span class="notification-category-icon approval">✓</span><div><strong>${t("v53.rule.approvals")}</strong><p>${t("v53.rule.approvalsSub")}</p></div><b>${t("v53.rule.immediate")}</b></div><div class="notification-rule-row"><span class="notification-category-icon payment">֏</span><div><strong>${t("v53.rule.payments")}</strong><p>${t("v53.rule.paymentsSub")}</p></div><b>${t("v53.rule.immediate")}</b></div><div class="notification-rule-row"><span class="notification-category-icon legal">§</span><div><strong>${t("v53.rule.legal")}</strong><p>${t("v53.rule.legalSub")}</p></div><b>${t("v53.rule.immediate")}</b></div><div class="notification-rule-row"><span class="notification-category-icon registration">R</span><div><strong>${t("v53.rule.registration")}</strong><p>${t("v53.rule.registrationSub")}</p></div><b>${t("v53.rule.immediate")}</b></div><div class="notification-rule-row"><span class="notification-category-icon sla">!</span><div><strong>${t("v53.rule.sla")}</strong><p>${t("v53.rule.slaSub")}</p></div><b>${t("v53.rule.immediate")}</b></div><div class="notification-rule-note">${t("v53.rule.note")}</div></div>`)}
function applyFilters(){const tab=document.querySelector<HTMLElement>("[data-notification-tab].active")?.dataset.notificationTab??"inbox",q=(document.querySelector<HTMLInputElement>("#notificationSearch")?.value??"").trim().toLowerCase(),cat=document.querySelector<HTMLSelectElement>("#notificationCategory")?.value??"",severity=document.querySelector<HTMLSelectElement>("#notificationSeverity")?.value??"";let count=0;document.querySelectorAll<HTMLElement>("[data-notification-card]").forEach(el=>{const state=el.dataset.state??"",tabOk=tab==="inbox"?(state==="read"||state==="unread"):tab==="unread"?state==="unread":tab==="critical"?(el.dataset.severity==="critical"&&(state==="read"||state==="unread")):tab==="snoozed"?state==="snoozed":state==="archive";const show=tabOk&&(!q||(el.dataset.search??"").includes(q))&&(!cat||el.dataset.category===cat)&&(!severity||el.dataset.severity===severity);el.style.display=show?"":"none";if(show)count++});const visible=document.querySelector<HTMLElement>("#notificationVisibleCount");if(visible)visible.textContent=String(count);const empty=document.querySelector<HTMLElement>("#notificationEmpty");if(empty)empty.style.display=count===0?"grid":"none"}
export function bindNotifications(){document.querySelectorAll<HTMLElement>("[data-notification-tab]").forEach(btn=>btn.addEventListener("click",()=>{document.querySelectorAll("[data-notification-tab]").forEach(x=>x.classList.remove("active"));btn.classList.add("active");applyFilters()}));["notificationSearch","notificationCategory","notificationSeverity"].forEach(id=>document.querySelector(`#${id}`)?.addEventListener(id==="notificationSearch"?"input":"change",applyFilters));document.querySelectorAll<HTMLElement>("[data-notification-detail]").forEach(btn=>btn.addEventListener("click",()=>openNotificationDetail(btn.dataset.notificationDetail!)));document.querySelectorAll<HTMLElement>("[data-notification-source]").forEach(btn=>btn.addEventListener("click",e=>{e.stopPropagation();const n=findNotification(btn.dataset.notificationSource!);if(n){markNotificationRead(n.id,true);if(n.sourceRoute)navigate(n.sourceRoute)}}));document.querySelectorAll<HTMLElement>("[data-notification-read]").forEach(btn=>btn.addEventListener("click",e=>{e.stopPropagation();const n=findNotification(btn.dataset.notificationRead!);if(!n)return;markNotificationRead(n.id,!n.readAt);refresh()}));document.querySelectorAll<HTMLElement>("[data-notification-snooze]").forEach(btn=>btn.addEventListener("click",e=>{e.stopPropagation();openSnooze(btn.dataset.notificationSnooze!)}));document.querySelectorAll<HTMLElement>("[data-notification-archive]").forEach(btn=>btn.addEventListener("click",e=>{e.stopPropagation();archiveNotification(btn.dataset.notificationArchive!);toastLocalized(t("v53.toast.archived"));refresh()}));document.querySelectorAll<HTMLElement>("[data-notification-restore]").forEach(btn=>btn.addEventListener("click",e=>{e.stopPropagation();restoreNotification(btn.dataset.notificationRestore!);toastLocalized(t("v53.toast.restored"));refresh()}));document.querySelector("#markAllNotifications")?.addEventListener("click",()=>{markAllNotificationsRead(currentRole());toastLocalized(t("v53.toast.allRead"));refresh()});document.querySelector("#notificationRules")?.addEventListener("click",openRules);document.querySelector("#openTasksFromNotifications")?.addEventListener("click",()=>navigate("tasks?tab=overdue"));document.querySelectorAll<HTMLElement>("[data-category-jump]").forEach(btn=>btn.addEventListener("click",()=>{const select=document.querySelector<HTMLSelectElement>("#notificationCategory");if(select){select.value=btn.dataset.categoryJump!;document.querySelector<HTMLElement>('[data-notification-tab="inbox"]')?.click();applyFilters()}}));applyFilters()}
