import {deals,financialSecurities,paymentReceipts,paymentSchedule,properties} from"../data/mock";
import {t} from "../i18n";
import{badge,compactAmd,money,paymentSourceLabel,statusLabel}from"../utils";
import{navigate}from"../router";
import{demoText}from"../demo-i18n";
import {allocateAdvance,candidateSchedulesForAdvance,dealFinancialSummary,penaltyFor,refundAdvance,scheduleCurrency,toAMD} from "../services/finance-control";
import {closeModal,formValue,openLocalizedModal,toastLocalized} from "../components/layout";
import{recordAudit}from"../services/audit";

export function paymentsPage(){
  const totalAMD=paymentSchedule.reduce((s,p)=>s+toAMD(p.amount,scheduleCurrency(p)),0),paidAMD=paymentSchedule.reduce((s,p)=>s+toAMD(p.paid,scheduleCurrency(p)),0),penaltyAMD=paymentSchedule.reduce((s,p)=>s+toAMD(penaltyFor(p).amount,scheduleCurrency(p)),0),advancesAMD=paymentReceipts.reduce((s,r)=>s+toAMD(r.unallocatedAmount,r.dealCurrency),0);
  const penaltyRows=paymentSchedule.filter(x=>penaltyFor(x).chargeableDays>0&&x.paid<x.amount),advanceRows=paymentReceipts.filter(x=>x.unallocatedAmount>0&&x.accountingStatus==="confirmed");
  return`<section class="page" id="paymentsWorkspace"><div class="page-header"><div class="page-title"><div class="eyebrow">${t("payments.control")}</div><h1>${t("paymentsPage.title")}</h1><p>${t("v50.payments.subtitle")}</p></div><div class="toolbar"><button class="btn" id="goFinance">${t("paymentsPage.financeCenter")}</button><button class="btn" id="goSecurities">${t("v50.finance.securities")}</button><button class="btn" id="goReconciliation">${t("paymentsPage.bankReconciliation")}</button><button class="btn" id="goPaymentAudit">${t("v55.audit.nav")}</button><button class="btn btn-primary" id="goMortgage">${t("paymentsPage.mortgage")}</button></div></div>
  <div class="finance-metrics finance-metrics-v50 u-mb-16"><div class="card metric-card"><div class="metric-top"><span>${t("paymentsPage.scheduled")}</span></div><div class="metric-value u-fs-20">${compactAmd(totalAMD)}</div><div class="metric-note">${t("v50.finance.normalized")}</div></div><div class="card metric-card positive"><div class="metric-top"><span>${t("paymentsPage.received")}</span></div><div class="metric-value u-fs-20">${compactAmd(paidAMD)}</div></div><div class="card metric-card"><div class="metric-top"><span>${t("paymentsPage.open")}</span></div><div class="metric-value u-fs-20">${compactAmd(Math.max(0,totalAMD-paidAMD))}</div></div><div class="card metric-card negative"><div class="metric-top"><span>${t("v50.finance.penaltyExposure")}</span></div><div class="metric-value u-fs-20">${compactAmd(penaltyAMD)}</div><div class="metric-note">${t("v50.finance.penaltyCases",{count:penaltyRows.length})}</div></div><div class="card metric-card accent"><div class="metric-top"><span>${t("v50.finance.advances")}</span></div><div class="metric-value u-fs-20">${compactAmd(advancesAMD)}</div><div class="metric-note">${t("v50.finance.advanceCases",{count:advanceRows.length})}</div></div></div>
  <div class="card"><div class="card-pad table-toolbar"><div><strong>${t("paymentsPage.schedules")}</strong><div class="subtle">${t("v50.payments.scheduleSub")}</div></div><div class="toolbar"><select class="field" id="paymentCurrency"><option value="">${t("v50.payments.allCurrencies")}</option><option>AMD</option><option>USD</option><option>EUR</option></select><select class="field" id="paymentSource"><option value="">${t("paymentsPage.allSources")}</option><option value="buyer">${paymentSourceLabel("buyer")}</option><option value="mortgage">${paymentSourceLabel("mortgage")}</option><option value="reservation">${paymentSourceLabel("reservation")}</option></select><select class="field" id="paymentStatus"><option value="">${t("paymentsPage.allStatuses")}</option><option value="overdue">${statusLabel("overdue")}</option><option value="due">${statusLabel("due")}</option><option value="partial">${statusLabel("partial")}</option><option value="future">${statusLabel("future")}</option><option value="paid">${statusLabel("paid")}</option></select></div></div><div class="table-wrap"><table class="table finance-schedule-table"><thead><tr><th>${t("paymentsPage.stage")}</th><th>${t("paymentsPage.deal")}</th><th>${t("paymentsPage.dueDate")}</th><th>${t("paymentsPage.source")}</th><th>${t("v50.payments.currencyRate")}</th><th>${t("paymentsPage.plan")}</th><th>${t("paymentsPage.paid")}</th><th>${t("paymentsPage.balance")}</th><th>${t("v50.payments.penalty")}</th><th>${t("paymentsPage.status")}</th></tr></thead><tbody>${paymentSchedule.map(p=>scheduleRow(p)).join("")}</tbody></table></div></div>
  <div class="grid grid-2 u-mt-16">
    <div class="card card-pad"><div class="section-title"><div><h2>${t("v50.payments.receiptsAdvances")}</h2><p>${t("v50.payments.receiptsAdvancesSub")}</p></div></div><div class="receipt-ledger">${paymentReceipts.slice().reverse().map(r=>receiptRow(r)).join("")}</div></div>
    <div class="card card-pad"><div class="section-title"><div><h2>${t("v50.payments.penaltyControl")}</h2><p>${t("v50.payments.penaltyControlSub")}</p></div></div>${penaltyRows.length?`<div class="penalty-list">${penaltyRows.map(p=>penaltyRow(p)).join("")}</div>`:`<div class="empty compact-empty">${t("v50.payments.noPenalties")}</div>`}</div>
  </div>
  </section>`}

function scheduleRow(p:(typeof paymentSchedule)[number]){const currency=scheduleCurrency(p),pen=penaltyFor(p);return`<tr data-payment-row="${p.id}" data-deal="${p.dealId}" data-source="${p.source}" data-status="${p.status}" data-currency="${currency}"><td><strong>${demoText(p.title)}</strong><div class="table-sub">#${String(p.sequence).padStart(2,"0")}</div></td><td>${p.dealId}</td><td>${p.dueDate}</td><td><span class="chip ${p.source==="mortgage"?"accent":""}">${paymentSourceLabel(p.source)}</span></td><td><strong>${currency}</strong><div class="table-sub">${currency==="AMD"?"1.00":t("v50.payments.fxRuleShort")}</div></td><td>${money(p.amount,currency)}${p.allocations?.length?`<div class="payment-allocation-list compact u-mt-7">${p.allocations.map(a=>{const asset=properties.find(x=>x.id===a.propertyId);return`<span><b>${asset?.unit??a.propertyId}</b>${money(a.amount,currency)}</span>`}).join("")}</div>`:""}</td><td>${money(p.paid,currency)}</td><td><strong>${money(Math.max(0,p.amount-p.paid),currency)}</strong></td><td>${pen.amount?`<strong class="penalty-value">${money(pen.amount,currency)}</strong><div class="table-sub">${pen.chargeableDays} ${t("v50.payments.days")} · ${pen.rate}%/${t("v50.payments.day")}</div>`:`<span class="subtle">—</span>`}</td><td>${badge(p.status)}</td></tr>`}
function receiptRow(r:(typeof paymentReceipts)[number]){const d=deals.find(x=>x.id===r.dealId);return`<div class="receipt-row"><div class="receipt-main"><div class="receipt-icon ${r.unallocatedAmount>0?'warning':'success'}">${r.unallocatedAmount>0?'↗':'✓'}</div><div><strong>${r.payer}</strong><span>${r.reference} · ${r.receivedAt}</span><small>${r.bank} · ${r.dealId}${d?` · ${d.propertyLabel}`:""}</small></div></div><div class="receipt-money"><strong>${money(r.sourceAmount,r.sourceCurrency)}</strong>${r.sourceCurrency!==r.dealCurrency?`<span>${t("v50.payments.dealAmount")}: ${money(r.dealAmount,r.dealCurrency)}</span>`:""}<small>${t("v50.payments.allocated")}: ${money(r.allocatedAmount,r.dealCurrency)}</small>${r.unallocatedAmount>0?`<em>${t("v50.payments.advance")}: ${money(r.unallocatedAmount,r.dealCurrency)}</em>`:""}${r.refundedAmount?`<small>${t("v50.payments.refunded")}: ${money(r.refundedAmount,r.dealCurrency)}</small>`:""}</div><div class="receipt-actions"><span class="status ${r.unallocatedAmount>0?'warning':'success'}">${statusLabel(r.status)}</span>${r.unallocatedAmount>0?`<button class="btn btn-soft" data-allocate-advance="${r.id}">${t("v50.payments.allocate")}</button><button class="text-btn danger-text" data-refund-advance="${r.id}">${t("v50.payments.refund")}</button>`:""}</div></div>`}
function penaltyRow(p:(typeof paymentSchedule)[number]){const d=deals.find(x=>x.id===p.dealId),currency=scheduleCurrency(p),x=penaltyFor(p),completion=dealFinancialSummary(p.dealId).completion;return`<button class="penalty-row" data-open-penalty-deal="${p.dealId}"><div><strong>${p.dealId} · ${d?.clientName??""}</strong><span>${demoText(p.title)} · ${p.dueDate}</span></div><div class="penalty-calc"><span>${money(x.principal,currency)} × ${x.rate}% × ${x.chargeableDays}</span><strong>${money(x.amount,currency)}</strong></div><div class="penalty-progress"><span>${t("v50.payments.completion")}</span><strong>${completion}%</strong></div></button>`}

export function bindPayments(){document.querySelectorAll("tr[data-deal]").forEach(el=>el.addEventListener("click",()=>navigate("deal/"+(el as HTMLElement).dataset.deal)));document.querySelector("#paymentCurrency")?.addEventListener("change",filterPayments);document.querySelector("#paymentSource")?.addEventListener("change",filterPayments);document.querySelector("#paymentStatus")?.addEventListener("change",filterPayments);document.querySelector("#goFinance")?.addEventListener("click",()=>navigate("finance"));document.querySelector("#goSecurities")?.addEventListener("click",()=>navigate("securities"));document.querySelector("#goReconciliation")?.addEventListener("click",()=>navigate("reconciliation"));document.querySelector("#goPaymentAudit")?.addEventListener("click",()=>navigate("audit?module=payments"));document.querySelector("#goMortgage")?.addEventListener("click",()=>navigate("mortgages"));document.querySelectorAll<HTMLElement>("[data-allocate-advance]").forEach(el=>el.addEventListener("click",e=>{e.stopPropagation();openAdvanceAllocation(el.dataset.allocateAdvance!)}));document.querySelectorAll<HTMLElement>("[data-refund-advance]").forEach(el=>el.addEventListener("click",e=>{e.stopPropagation();openAdvanceRefund(el.dataset.refundAdvance!)}));document.querySelectorAll<HTMLElement>("[data-open-penalty-deal]").forEach(el=>el.addEventListener("click",()=>navigate("deal/"+el.dataset.openPenaltyDeal)))}
function filterPayments(){const currency=document.querySelector<HTMLSelectElement>("#paymentCurrency")?.value??"",src=document.querySelector<HTMLSelectElement>("#paymentSource")?.value??"",st=document.querySelector<HTMLSelectElement>("#paymentStatus")?.value??"";document.querySelectorAll<HTMLTableRowElement>("tr[data-payment-row]").forEach(r=>r.style.display=(!currency||r.dataset.currency===currency)&&(!src||r.dataset.source===src)&&(!st||r.dataset.status===st)?"":"none")}
function openAdvanceAllocation(id:string){const receipt=paymentReceipts.find(x=>x.id===id);if(!receipt)return;const candidates=candidateSchedulesForAdvance(id);if(!candidates.length){toastLocalized(t("v50.payments.noOpenSchedule"));return}openLocalizedModal(t("v50.payments.allocateAdvanceTitle"),`<div class="advance-balance"><span>${t("v50.payments.availableAdvance")}</span><strong>${money(receipt.unallocatedAmount,receipt.dealCurrency)}</strong></div><form id="advanceAllocateForm" class="form-grid u-mt-14"><div class="form-field full"><label>${t("v50.payments.targetStage")}</label><select name="schedule" required>${candidates.map(p=>{const d=deals.find(x=>x.id===p.dealId),currency=scheduleCurrency(p);return`<option value="${p.id}">${p.dealId} · ${d?.propertyLabel??''} · ${demoText(p.title)} · ${money(p.amount-p.paid,currency)}</option>`}).join("")}</select></div><div class="form-field"><label>${t("v50.payments.amount")}</label><input name="amount" type="number" min="0.01" step="0.01" value="${Math.min(receipt.unallocatedAmount,candidates[0].amount-candidates[0].paid)}" required></div><div class="form-field"><label>${t("v50.payments.reason")}</label><input name="reason" value="${t("v50.payments.reallocationReason")}"></div></form>`,`<button class="btn" data-modal-close>${t("v50.common.cancel")}</button><button class="btn btn-primary" id="saveAdvanceAllocation">${t("v50.payments.allocate")}</button>`);setTimeout(()=>document.querySelector("#saveAdvanceAllocation")?.addEventListener("click",()=>{const f=document.querySelector<HTMLFormElement>("#advanceAllocateForm")!;if(!f.reportValidity())return;const target=paymentSchedule.find(x=>x.id===formValue(f,"schedule"));if(!target)return;const amount=Number(formValue(f,"amount"));if(!allocateAdvance(id,target.id,amount)){toastLocalized(t("v50.payments.allocationFailed"));return}receipt.note=`${receipt.note??""}${receipt.note?" · ":""}${formValue(f,"reason")}`;recordAudit({module:"payments",action:"payment",entityType:"payment",entityId:receipt.id,entityLabel:`${receipt.reference} · ${receipt.payer}`,route:"payments",field:"Unallocated advance",oldValue:`${receipt.unallocatedAmount+amount} ${receipt.dealCurrency}`,newValue:`${receipt.unallocatedAmount} ${receipt.dealCurrency}`,note:`Allocated to ${target.id}: ${amount} ${receipt.dealCurrency}.`});closeModal();toastLocalized(t("v50.payments.allocatedToast"));refresh()}),0)}
function openAdvanceRefund(id:string){const receipt=paymentReceipts.find(x=>x.id===id);if(!receipt)return;openLocalizedModal(t("v50.payments.refundTitle"),`<div class="advance-balance"><span>${t("v50.payments.availableAdvance")}</span><strong>${money(receipt.unallocatedAmount,receipt.dealCurrency)}</strong></div><form id="advanceRefundForm" class="form-grid u-mt-14"><div class="form-field"><label>${t("v50.payments.amount")}</label><input name="amount" type="number" min="0.01" max="${receipt.unallocatedAmount}" step="0.01" value="${receipt.unallocatedAmount}" required></div><div class="form-field"><label>${t("v50.payments.refundMethod")}</label><select name="method"><option>${t("v50.payments.bankTransfer")}</option><option>${t("v50.payments.cash")}</option></select></div><div class="form-field full"><label>${t("v50.payments.reason")}</label><textarea name="reason">${t("v50.payments.refundReason")}</textarea></div></form>`,`<button class="btn" data-modal-close>${t("v50.common.cancel")}</button><button class="btn btn-primary" id="saveAdvanceRefund">${t("v50.payments.confirmRefund")}</button>`);setTimeout(()=>document.querySelector("#saveAdvanceRefund")?.addEventListener("click",()=>{const f=document.querySelector<HTMLFormElement>("#advanceRefundForm")!;if(!f.reportValidity())return;const refundAmount=Number(formValue(f,"amount"));const before=receipt.unallocatedAmount;if(!refundAdvance(id,refundAmount)){toastLocalized(t("v50.payments.refundFailed"));return}receipt.note=`${receipt.note??""}${receipt.note?" · ":""}${formValue(f,"reason")}`;recordAudit({module:"payments",action:"payment",entityType:"payment",entityId:receipt.id,entityLabel:`${receipt.reference} · ${receipt.payer}`,route:"payments",field:"Advance refund",oldValue:`${before} ${receipt.dealCurrency}`,newValue:`${receipt.unallocatedAmount} ${receipt.dealCurrency}`,note:`Refunded ${refundAmount} ${receipt.dealCurrency}. ${formValue(f,"reason")}`,severity:"warning"});closeModal();toastLocalized(t("v50.payments.refundToast"));refresh()}),0)}
function refresh(){navigate("finance");setTimeout(()=>navigate("payments"),20)}
