import {deals,powersOfAttorney,properties} from "../data/mock";
import {navigate} from "../router";
import {badge} from "../utils";
import {closeModal,openLocalizedModal,toastLocalized} from "../components/layout";
import {t} from "../i18n";
import {POA_ACTIONS,authorityCoverage,poaActionLabel,validateAuthority} from "../services/authority";
import type {PowerOfAttorneyAction,PowerOfAttorneyStatus} from "../models/types";

export function powerAttorneyDetailPage(id:string){
 const p=powersOfAttorney.find(x=>x.id===id);if(!p)return`<section class="page"><div class="card card-pad empty">${t("common.recordNotFound")}</div></section>`;
 const deal=deals.find(d=>d.id===p.relatedDeal),covered=authorityCoverage(p,properties),defaultCheck=validateAuthority(deal,p,"sign-contract");
 return `<section class="page" id="poaDetailPage">
  <div class="breadcrumbs"><span>${t("legal")}</span><span>›</span><button class="crumb-button" id="poaRegistryBack">${t("poaPage.title")}</button><span>›</span><span>${p.id}</span></div>
  <div class="detail-header poa-detail-header"><div class="detail-title"><small>${p.id} · ${p.documentNo}</small><h1>${p.representative}</h1><div class="toolbar">${badge(p.status)}<span class="chip">${p.principal}</span></div></div><div class="toolbar"><button class="btn" id="poaBack">${t("v43.poa.backRegistry")}</button>${p.status==="suspended"?`<button class="btn btn-soft" id="poaReactivate">${t("v43.poa.reactivate")}</button>`:!["revoked","expired"].includes(p.status)?`<button class="btn" id="poaSuspend">${t("v43.poa.suspend")}</button>`:""}${!["revoked","expired"].includes(p.status)?`<button class="btn btn-danger-soft" id="poaRevoke">${t("v43.poa.revoke")}</button>`:""}</div></div>
  <div class="poa-hero card">
   <div><span>${t("v43.poa.principal")}</span><strong>${p.principal}</strong><small>${p.authorityBasis??"—"}</small></div>
   <div><span>${t("v43.poa.validity")}</span><strong>${p.issuedAt} → ${p.expiresAt}</strong><small>${p.notary}</small></div>
   <div><span>${t("v43.poa.linkedDeal")}</span><strong>${p.relatedDeal??"—"}</strong><small>${deal?.propertyLabel??t("poaPage.noRelation")}</small></div>
   <div><span>${t("v43.poa.subdelegation")}</span><strong>${p.canSubdelegate?t("v43.poa.allowed"):t("v43.poa.notAllowed")}</strong><small>${t("v43.poa.verification")}: ${p.verificationStatus==="verified"?t("v43.poa.verified"):t("v43.poa.review")}</small></div>
  </div>
  <div class="grid poa-detail-grid u-mt-16">
   <div class="poa-main-column">
    <div class="card card-pad"><div class="section-title"><div><h2>${t("v43.poa.authorityMatrix")}</h2><p>${t("v43.poa.authorityMatrixSub")}</p></div><button class="btn btn-soft" id="editPoaActions">${t("v43.poa.editAuthority")}</button></div><div class="poa-authority-matrix">${POA_ACTIONS.map(a=>`<div class="poa-authority-row ${p.allowedActions.includes(a)?"allowed":"blocked"}"><div class="authority-icon">${p.allowedActions.includes(a)?"✓":"×"}</div><div><strong>${poaActionLabel(a)}</strong><span>${p.allowedActions.includes(a)?t("v43.poa.actionAllowed"):t("v43.poa.actionNotAllowed")}</span></div></div>`).join("")}</div></div>
    <div class="card card-pad"><div class="section-title"><div><h2>${t("v43.poa.propertyScope")}</h2><p>${t("v43.poa.propertyScopeSub")}</p></div><span class="chip accent">${covered.length}</span></div>${covered.length?`<div class="poa-property-list">${covered.map(x=>`<button class="poa-property-card" data-property="${x.id}"><div><span>${x.project} · ${x.phase}</span><strong>${x.unit}</strong><small>${x.building} · ${x.area} m²</small></div>${badge(x.status)}</button>`).join("")}</div>`:`<div class="empty compact-empty">${t("v43.poa.noPropertyScope")}</div>`}</div>
    <div class="card card-pad"><div class="section-title"><div><h2>${t("v43.poa.lifecycle")}</h2><p>${t("v43.poa.lifecycleSub")}</p></div></div><div class="poa-history">${p.history.slice().reverse().map((h,i)=>`<div class="poa-history-row"><div class="poa-history-dot ${i===0?"current":""}"></div><div><strong>${h.action}</strong><span>${h.at} · ${h.actor}</span>${h.note?`<p>${h.note}</p>`:""}</div></div>`).join("")}</div></div>
   </div>
   <aside class="poa-side-column">
    <div class="card card-pad"><div class="section-title"><div><h2>${t("v43.authority.check")}</h2><p>${t("v43.authority.checkSub")}</p></div></div><div class="authority-result ${defaultCheck.ok?"ok":"fail"}"><span>${defaultCheck.ok?"✓":"!"}</span><div><strong>${defaultCheck.title}</strong><p>${defaultCheck.message}</p></div></div><button class="btn btn-primary u-w-100" id="runAuthorityCheck">${t("v43.authority.run")}</button></div>
    <div class="card card-pad"><div class="section-title"><div><h2>${t("v43.poa.documentCard")}</h2><p>${t("v43.poa.documentCardSub")}</p></div></div><div class="poa-document"><div class="document-icon">PDF</div><div><strong>${p.documentFile??t("v43.poa.noFile")}</strong><span>${p.documentNo}</span></div><button class="btn btn-soft" id="viewPoaDocument">${t("v43.poa.view")}</button></div><div class="info-list u-mt-12"><div class="info-box"><span>${t("poaPage.notary")}</span><strong>${p.notary}</strong></div><div class="info-box"><span>${t("poaPage.scope")}</span><strong>${p.scope.startsWith("i18n:")?t(p.scope.slice(5)):p.scope}</strong></div></div></div>
    ${deal?`<div class="card card-pad"><div class="section-title"><div><h2>${t("v43.poa.dealContext")}</h2><p>${t("v43.poa.dealContextSub")}</p></div></div><div class="next-stage"><span>${deal.id}</span><strong>${deal.clientName}</strong><p>${deal.propertyLabel}</p><button class="btn" id="openPoaDeal">${t("v43.poa.openDeal")}</button></div></div>`:""}
   </aside>
  </div>
 </section>`;
}

export function bindPowerAttorneyDetail(){
 const id=location.hash.split("?")[0].split("/").pop()!,p=powersOfAttorney.find(x=>x.id===id);if(!p)return;
 const refresh=()=>{navigate("legal/poa");setTimeout(()=>navigate("poa/"+p.id),20)};
 document.querySelector("#poaRegistryBack")?.addEventListener("click",()=>navigate("legal/poa"));document.querySelector("#poaBack")?.addEventListener("click",()=>navigate("legal/poa"));
 document.querySelector("#openPoaDeal")?.addEventListener("click",()=>p.relatedDeal&&navigate("deal/"+p.relatedDeal));
 document.querySelectorAll<HTMLElement>("[data-property]").forEach(x=>x.addEventListener("click",()=>navigate("property/"+x.dataset.property)));
 document.querySelector("#viewPoaDocument")?.addEventListener("click",()=>openLocalizedModal(t("v43.poa.documentCard"),`<div class="poa-document-preview"><div class="document-icon large">PDF</div><h3>${p.documentFile??t("v43.poa.noFile")}</h3><p>${t("v43.poa.documentDemoNote")}</p><div class="info-list"><div class="info-box"><span>${t("poaPage.number")}</span><strong>${p.documentNo}</strong></div><div class="info-box"><span>${t("poaPage.issuedAt")}</span><strong>${p.issuedAt}</strong></div><div class="info-box"><span>${t("poaPage.expiresAt")}</span><strong>${p.expiresAt}</strong></div><div class="info-box"><span>${t("v43.poa.verification")}</span><strong>${p.verificationStatus}</strong></div></div></div>`));
 document.querySelector("#poaSuspend")?.addEventListener("click",()=>changeStatus(p.id,"suspended",t("v43.poa.event.suspended"),refresh));
 document.querySelector("#poaReactivate")?.addEventListener("click",()=>changeStatus(p.id,"active",t("v43.poa.event.reactivated"),refresh));
 document.querySelector("#poaRevoke")?.addEventListener("click",()=>openRevoke(p.id,refresh));
 document.querySelector("#editPoaActions")?.addEventListener("click",()=>openActions(p.id,refresh));
 document.querySelector("#runAuthorityCheck")?.addEventListener("click",()=>openAuthorityCheck(p.id));
}
function changeStatus(id:string,status:PowerOfAttorneyStatus,event:string,done:()=>void){const p=powersOfAttorney.find(x=>x.id===id);if(!p)return;p.status=status;p.updatedAt="23.09.2026 · сейчас";p.history.push({id:`${p.id}-H${p.history.length+1}`,at:p.updatedAt,actor:"Անահիտ Մարտիրոսյան",action:event});toastLocalized(event);done()}
function openRevoke(id:string,done:()=>void){const p=powersOfAttorney.find(x=>x.id===id);if(!p)return;openLocalizedModal(t("v43.poa.revokeTitle"),`<div class="modal-note danger-note">${t("v43.poa.revokeWarning")}</div><form id="revokePoaForm" class="form-grid u-mt-12"><div class="form-field full"><label>${t("v43.poa.reason")}</label><textarea name="reason" required>${t("v43.poa.defaultRevokeReason")}</textarea></div></form>`,`<button class="btn" data-modal-close>${t("poaPage.cancel")}</button><button class="btn btn-danger" id="confirmRevoke">${t("v43.poa.confirmRevoke")}</button>`);setTimeout(()=>document.querySelector("#confirmRevoke")?.addEventListener("click",()=>{const f=document.querySelector<HTMLFormElement>("#revokePoaForm")!;if(!f.reportValidity())return;p.status="revoked";p.updatedAt="23.09.2026 · сейчас";p.history.push({id:`${p.id}-H${p.history.length+1}`,at:p.updatedAt,actor:"Անահիտ Մարտիրոսյան",action:t("v43.poa.event.revoked"),note:String(new FormData(f).get("reason")??"")});closeModal();toastLocalized(t("v43.poa.event.revoked"));done()}),0)}
function openActions(id:string,done:()=>void){const p=powersOfAttorney.find(x=>x.id===id);if(!p)return;openLocalizedModal(t("v43.poa.editAuthority"),`<form id="poaActionForm"><div class="poa-action-picker">${POA_ACTIONS.map(a=>`<label><input type="checkbox" name="actions" value="${a}" ${p.allowedActions.includes(a)?"checked":""}><span>${poaActionLabel(a)}</span></label>`).join("")}</div></form>`,`<button class="btn" data-modal-close>${t("poaPage.cancel")}</button><button class="btn btn-accent" id="savePoaActions">${t("v43.common.save")}</button>`);setTimeout(()=>document.querySelector("#savePoaActions")?.addEventListener("click",()=>{const f=document.querySelector<HTMLFormElement>("#poaActionForm")!,actions=new FormData(f).getAll("actions").map(String) as PowerOfAttorneyAction[];if(!actions.length){toastLocalized(t("v43.poa.chooseAction"));return}p.allowedActions=actions;p.updatedAt="23.09.2026 · сейчас";p.history.push({id:`${p.id}-H${p.history.length+1}`,at:p.updatedAt,actor:"Անահիտ Մարտիրոսյան",action:t("v43.poa.event.scopeChanged")});closeModal();toastLocalized(t("v43.poa.scopeSaved"));done()}),0)}
function openAuthorityCheck(id:string){const p=powersOfAttorney.find(x=>x.id===id);if(!p)return;const deal=deals.find(d=>d.id===p.relatedDeal);openLocalizedModal(t("v43.authority.check"),`<form id="authorityCheckForm" class="form-grid"><div class="form-field full"><label>${t("v43.authority.operation")}</label><select name="action">${POA_ACTIONS.map(a=>`<option value="${a}">${poaActionLabel(a)}</option>`).join("")}</select></div><div class="form-field full"><label>${t("v43.authority.property")}</label><select name="propertyId">${(deal?.propertyIds?.length?deal.propertyIds:[deal?.propertyId]).filter(Boolean).map(pid=>{const x=properties.find(q=>q.id===pid);return`<option value="${pid}">${x?.project??""} · ${x?.unit??pid}</option>`}).join("")}</select></div><div id="authorityCheckResult" class="authority-modal-result">${t("v43.authority.chooseAndRun")}</div></form>`,`<button class="btn" data-modal-close>${t("contractDetail.close")}</button><button class="btn btn-accent" id="executeAuthorityCheck">${t("v43.authority.run")}</button>`);setTimeout(()=>document.querySelector("#executeAuthorityCheck")?.addEventListener("click",()=>{const f=document.querySelector<HTMLFormElement>("#authorityCheckForm")!,fd=new FormData(f),result=validateAuthority(deal,p,String(fd.get("action")) as PowerOfAttorneyAction,[String(fd.get("propertyId"))]);const el=document.querySelector<HTMLElement>("#authorityCheckResult");if(el){el.className=`authority-modal-result ${result.ok?"ok":"fail"}`;el.innerHTML=`<strong>${result.ok?"✓":"!"} ${result.title}</strong><span>${result.message}</span>`}}),0)}
