import { contracts,deals,registrationCases,handoverCases,properties } from "../data/mock";
import type { RegistrationCase,RegistrationDocument,RegistrationStatus } from "../models/types";
import { amd,badge,escapeHtml,statusLabel } from "../utils";
import { navigate } from "../router";
import { closeModal,formValue,openLocalizedModal,toastLocalized } from "../components/layout";
import { t } from "../i18n";
import { recordAudit } from "../services/audit";
import { entityAuditPanel } from "../components/audit-panel";

const requiredDocumentSeed=():RegistrationDocument[]=>[
 {id:`RD-${Date.now()}-1`,type:"signed-contract",title:t("registrationPage.docs.signedContract"),required:true,status:"verified",fileName:"signed_contract.pdf",uploadedAt:"23.09.2026 · 09:14",verifiedAt:"23.09.2026 · 09:14",verifiedBy:"Անահիտ Մարտիրոսյան"},
 {id:`RD-${Date.now()}-2`,type:"party-documents",title:t("registrationPage.docs.partyDocuments"),required:true,status:"verified",fileName:"party_documents.pdf",uploadedAt:"23.09.2026 · 09:14",verifiedAt:"23.09.2026 · 09:14",verifiedBy:"Անահիտ Մարտիրոսյան"},
 {id:`RD-${Date.now()}-3`,type:"cadastral",title:t("registrationPage.docs.cadastral"),required:true,status:"verified",fileName:"cadastral_package.pdf",uploadedAt:"23.09.2026 · 09:14",verifiedAt:"23.09.2026 · 09:14",verifiedBy:"Անահիտ Մարտիրոսյան"},
 {id:`RD-${Date.now()}-4`,type:"fee-receipt",title:t("registrationPage.docs.feeReceipt"),required:true,status:"missing"},
 {id:`RD-${Date.now()}-5`,type:"notary-act",title:t("v51.registration.doc.notaryAct"),required:false,status:"missing"}
];

function ensureRegistrationData(r:RegistrationCase){
 if(!r.owner)r.owner="Անահիտ Մարտիրոսյան";
 if(!r.authority)r.authority=t("v51.registration.defaultAuthority");
 if(!r.submissionRound)r.submissionRound=r.applicationNo?1:0;
 if(!r.documents){
   const docs=requiredDocumentSeed();
   if(r.status!=="preparation"){
     const fee=docs.find(x=>x.type==="fee-receipt");if(fee){fee.status="verified";fee.fileName=`${r.id}_fee_receipt.pdf`;fee.uploadedAt="18.09.2026 · 14:10";fee.verifiedAt="18.09.2026 · 14:16";fee.verifiedBy="Անահիտ Մարտիրոսյան"}
   }
   if(["submitted","additional-documents","registered"].includes(r.status)){
     const notary=docs.find(x=>x.type==="notary-act");if(notary){notary.status="verified";notary.fileName=`${r.id}_notary_act.pdf`;notary.uploadedAt="18.09.2026 · 16:00";notary.verifiedAt="18.09.2026 · 16:08";notary.verifiedBy="Անահիտ Մարտիրոսյան"}
   }
   r.documents=docs;
 }
 if(!r.additionalRequests)r.additionalRequests=[];
 if(!r.history)r.history=[{id:`RE-${r.id}-1`,at:r.plannedAt,actor:r.owner,action:t("v51.registration.event.created"),note:t("v51.registration.event.createdNote")}];
 if(r.status==="submitted"&&!r.submittedAt)r.submittedAt="17.09.2026 · 10:20";
}
registrationCases.forEach(ensureRegistrationData);

const isAttention=(r:RegistrationCase)=>r.status==="additional-documents"||r.status==="rejected"||requiredDocs(r).some(x=>x.status!=="verified");
const requiredDocs=(r:RegistrationCase)=>(r.documents??[]).filter(x=>x.required);
const documentReadiness=(r:RegistrationCase)=>{const docs=requiredDocs(r),ok=docs.filter(x=>x.status==="verified").length;return{ok,total:docs.length,pct:docs.length?Math.round(ok/docs.length*100):100}};
const openRequest=(r:RegistrationCase)=>[...(r.additionalRequests??[])].reverse().find(x=>x.status==="open");
const at=()=>new Intl.DateTimeFormat("ru-RU",{day:"2-digit",month:"2-digit",year:"numeric",hour:"2-digit",minute:"2-digit",hour12:false}).format(new Date()).replace(","," ·");
const event=(r:RegistrationCase,action:string,note:string,actor="Անահիտ Մարտիրոսյան")=>{
 r.history??=[];r.history.push({id:`RE-${r.id}-${r.history.length+1}`,at:at(),actor,action,note});
 const warning=/request|reject|additional|document/i.test(`${action} ${note}`);
 recordAudit({module:"registration",action:"update",entityType:"registration",entityId:r.id,entityLabel:`${r.id} · ${r.clientName}`,route:`registration/${r.id}`,field:"Registration process",newValue:action,note,actor,actorRole:actor==="System"?"System Administrator":"Legal",source:actor==="System"?"system":"user",severity:warning?"warning":"info"});
};
const refresh=(id?:string)=>{navigate("legal");setTimeout(()=>navigate(id?`registration/${id}`:"registration"),20)};

function statusHint(r:RegistrationCase){
 const readiness=documentReadiness(r);
 if(r.status==="preparation")return readiness.ok<readiness.total?t("v51.registration.hint.completeDocs",{count:String(readiness.total-readiness.ok)}):t("v51.registration.hint.readyNotary");
 if(r.status==="notary")return t("v51.registration.hint.notary");
 if(r.status==="submitted")return t("v51.registration.hint.submitted");
 if(r.status==="additional-documents")return openRequest(r)?.status==="open"?t("v51.registration.hint.additional"):t("v51.registration.hint.resubmit");
 if(r.status==="rejected")return t("v51.registration.hint.rejected");
 return t("v51.registration.hint.registered");
}

function progressStep(label:string,done:boolean,current:boolean,warning=false){return `<div class="reg-lifecycle-step ${done?"done":""} ${current?"current":""} ${warning?"warning":""}"><span class="reg-lifecycle-dot">${done?"✓":""}</span><span>${label}</span></div>`}
function lifecycle(r:RegistrationCase){
 const index=r.status==="preparation"?0:r.status==="notary"?1:["submitted","additional-documents","rejected"].includes(r.status)?2:3;
 return `<div class="reg-lifecycle">${progressStep(t("registrationPage.track.package"),index>0,index===0)}${progressStep(t("registrationPage.track.notary"),index>1,index===1)}${progressStep(t("registrationPage.track.application"),index>2,index===2,["additional-documents","rejected"].includes(r.status))}${progressStep(t("registrationPage.track.result"),r.status==="registered",index===3)}</div>`;
}

export function registrationPage(id?:string){
 if(id){const r=registrationCases.find(x=>x.id===id);return r?registrationDetail(r):`<section class="page"><div class="empty">${t("common.recordNotFound")}</div></section>`}
 const active=registrationCases.filter(x=>x.status!=="registered").length,attention=registrationCases.filter(isAttention).length,submitted=registrationCases.filter(x=>["submitted","additional-documents","rejected"].includes(x.status)).length,done=registrationCases.filter(x=>x.status==="registered").length;
 return `<section class="page registration-page">
 <div class="breadcrumbs"><span>${t("legal")}</span><span>›</span><span>${t("registrationPage.breadcrumb")}</span></div>
 <div class="page-header"><div class="page-title"><div class="eyebrow">${t("registrationPage.eyebrow")}</div><h1>${t("registrationPage.title")}</h1><p>${t("v51.registration.subtitle")}</p></div><div class="toolbar"><button class="btn" id="backLegal">${t("registrationPage.backLegal")}</button><button class="btn btn-accent" id="newRegistration">${t("registrationPage.new")}</button></div></div>
 <div class="reg-kpis"><div class="card reg-kpi"><span>${t("v51.registration.kpi.active")}</span><strong>${active}</strong><small>${t("v51.registration.kpi.activeNote")}</small></div><div class="card reg-kpi ${attention?"warning":""}"><span>${t("v51.registration.kpi.attention")}</span><strong>${attention}</strong><small>${t("v51.registration.kpi.attentionNote")}</small></div><div class="card reg-kpi"><span>${t("v51.registration.kpi.submitted")}</span><strong>${submitted}</strong><small>${t("v51.registration.kpi.submittedNote")}</small></div><div class="card reg-kpi success"><span>${t("v51.registration.kpi.done")}</span><strong>${done}</strong><small>${t("v51.registration.kpi.doneNote")}</small></div></div>
 <div class="card reg-command"><div><div class="eyebrow">${t("v51.registration.command.eyebrow")}</div><h2>${t("v51.registration.command.title")}</h2><p>${t("v51.registration.command.text")}</p></div><div class="reg-filter" role="group" aria-label="${t("v51.registration.filter.label")}"><button class="active" data-reg-filter="all">${t("v51.registration.filter.all")}</button><button data-reg-filter="attention">${t("v51.registration.filter.attention")}</button><button data-reg-filter="active">${t("v51.registration.filter.active")}</button><button data-reg-filter="done">${t("v51.registration.filter.done")}</button></div></div>
 <div class="registration-board">${registrationCases.map(registrationCard).join("")}</div>
 </section>`}

function registrationCard(r:RegistrationCase){const ready=documentReadiness(r),req=openRequest(r);const filter=r.status==="registered"?"done":isAttention(r)?"attention active":"active";return `<article class="card registration-process" data-registration-card="${r.id}" data-filter-group="${filter}" tabindex="0">
 <div class="registration-process-head"><div><span>${r.id} · ${r.contractId}</span><h3>${escapeHtml(r.clientName)}</h3><p>${escapeHtml(r.propertyLabel)}</p></div>${badge(r.status)}</div>
 ${lifecycle(r)}
 <div class="reg-card-callout ${isAttention(r)?"warning":""}"><span>${t("v51.registration.currentAction")}</span><strong>${statusHint(r)}</strong></div>
 <div class="reg-card-grid"><div><span>${t("registrationPage.applicationNo")}</span><strong>${r.applicationNo??t("registrationPage.notAssigned")}</strong></div><div><span>${t("v51.registration.documentsReady")}</span><strong>${ready.ok}/${ready.total}</strong></div><div><span>${t("v51.registration.submissionRound")}</span><strong>${r.submissionRound||"—"}</strong></div><div><span>${t("registrationPage.stateFee")}</span><strong>${amd(r.stateFee)}</strong></div></div>
 <div class="reg-mini-progress"><span style="width:${ready.pct}%"></span></div>${req?`<div class="reg-request-inline"><strong>${t("v51.registration.additionalRequest")}</strong><span>${req.items.join(" · ")}</span></div>`:""}
 <div class="registration-card-foot"><span>${r.owner} · ${r.plannedAt}</span><button class="btn btn-primary" data-open-registration="${r.id}">${t("v51.registration.openCase")}</button></div></article>`}

function registrationDetail(r:RegistrationCase){const ready=documentReadiness(r),req=openRequest(r),contract=contracts.find(x=>x.id===r.contractId),deal=deals.find(x=>x.id===r.dealId);return `<section class="page registration-detail-page">
 <div class="breadcrumbs"><button class="link-button" id="backRegistration">${t("registrationPage.breadcrumb")}</button><span>›</span><span>${r.id}</span></div>
 <div class="page-header reg-detail-header"><div class="page-title"><div class="eyebrow">${t("v51.registration.caseEyebrow")}</div><div class="reg-title-row"><h1>${r.id}</h1>${badge(r.status)}</div><p>${escapeHtml(r.clientName)} · ${escapeHtml(r.propertyLabel)} · ${r.contractId}</p></div><div class="toolbar"><button class="btn" data-open-deal="${r.dealId}">${t("v51.registration.openDeal")}</button><button class="btn" data-open-contract="${r.contractId}">${t("v51.registration.openContract")}</button></div></div>
 <div class="card reg-overview"><div><span>${t("v51.registration.currentAction")}</span><strong>${statusHint(r)}</strong></div>${lifecycle(r)}</div>
 <div class="reg-detail-layout"><div class="reg-detail-main">
   <section class="card card-pad"><div class="section-head"><div><div class="eyebrow">${t("v51.registration.docs.eyebrow")}</div><h2>${t("v51.registration.docs.title")}</h2><p>${t("v51.registration.docs.subtitle")}</p></div><div class="reg-readiness-ring" style="--pct:${ready.pct}"><strong>${ready.pct}%</strong><span>${ready.ok}/${ready.total}</span></div></div><div class="registration-doc-grid">${(r.documents??[]).map(d=>documentCard(r,d)).join("")}</div><div class="toolbar u-mt-14"><button class="btn" id="addRegistrationDoc">+ ${t("v51.registration.addDocument")}</button></div></section>
   <section class="card card-pad"><div class="section-head"><div><div class="eyebrow">${t("v51.registration.requests.eyebrow")}</div><h2>${t("v51.registration.requests.title")}</h2><p>${t("v51.registration.requests.subtitle")}</p></div>${r.status==="submitted"?`<button class="btn" id="requestMoreDocs">+ ${t("v51.registration.requestDocs")}</button>`:""}</div>${(r.additionalRequests??[]).length?`<div class="reg-request-list">${[...(r.additionalRequests??[])].reverse().map(q=>`<article class="reg-request-card ${q.status}"><div class="reg-request-head"><div><strong>${q.id}</strong><span>${q.requestedAt} · ${q.requestedBy}</span></div><span class="chip ${q.status==="open"?"warning":"success"}">${q.status==="open"?t("v51.registration.requestOpen"):t("v51.registration.requestFulfilled")}</span></div><div class="reg-request-items">${q.items.map(x=>`<span>${escapeHtml(x)}</span>`).join("")}</div>${q.note?`<p>${escapeHtml(q.note)}</p>`:""}${q.dueAt?`<small>${t("v51.registration.due")}: ${q.dueAt}</small>`:""}${q.status==="open"?`<button class="btn btn-primary" data-fulfill-request="${q.id}">${t("v51.registration.fulfillRequest")}</button>`:""}</article>`).join("")}</div>`:`<div class="empty compact-empty">${t("v51.registration.noRequests")}</div>`}</section>
   <section class="card card-pad"><div class="section-head"><div><div class="eyebrow">${t("v51.registration.history.eyebrow")}</div><h2>${t("v51.registration.history.title")}</h2></div></div><div class="reg-history">${[...(r.history??[])].reverse().map(h=>`<div class="reg-history-row"><span class="reg-history-dot"></span><div><strong>${escapeHtml(h.action)}</strong><p>${escapeHtml(h.note)}</p><small>${h.at} · ${escapeHtml(h.actor)}</small></div></div>`).join("")}</div></section>
   ${entityAuditPanel("registration",r.id)}
 </div><aside class="reg-detail-side">
   <section class="card card-pad reg-summary"><div class="eyebrow">${t("v51.registration.caseSummary")}</div><div class="info-list"><div class="info-box"><span>${t("registrationPage.notary")}</span><strong>${escapeHtml(r.notary)}</strong></div><div class="info-box"><span>${t("v51.registration.authority")}</span><strong>${escapeHtml(r.authority??"—")}</strong></div><div class="info-box"><span>${t("registrationPage.plan")}</span><strong>${r.plannedAt}</strong></div><div class="info-box"><span>${t("registrationPage.applicationNo")}</span><strong>${r.applicationNo??"—"}</strong></div><div class="info-box"><span>${t("v51.registration.notaryAction")}</span><strong>${r.notaryActionNo??"—"}</strong></div><div class="info-box"><span>${t("v51.registration.submittedAt")}</span><strong>${r.submittedAt??"—"}</strong></div></div></section>
   <section class="card card-pad reg-fee-card"><div class="eyebrow">${t("v51.registration.fee.eyebrow")}</div><h3>${amd(r.stateFee)}</h3><p>${r.feeReceiptNo?t("v51.registration.fee.paid",{receipt:r.feeReceiptNo}):t("v51.registration.fee.notRecorded")}</p>${r.feePaidAt?`<small>${r.feePaidAt}</small>`:""}${!r.feeReceiptNo?`<button class="btn btn-primary u-mt-14" id="recordFee">${t("v51.registration.fee.record")}</button>`:""}</section>
   ${r.status==="rejected"?`<section class="card card-pad reg-alert danger"><div class="eyebrow">${t("v51.registration.rejection.eyebrow")}</div><h3>${t("v51.registration.rejection.title")}</h3><p>${escapeHtml(r.rejectionReason??"—")}</p><small>${r.rejectedAt??""}</small></section>`:""}
   <section class="card card-pad reg-result-card"><div class="eyebrow">${t("v51.registration.result.eyebrow")}</div><h3>${r.status==="registered"?t("v51.registration.result.done"):t("v51.registration.result.waiting")}</h3><p>${r.resultDocumentNo?`${r.resultDocumentNo} · ${r.resultDocumentName??""}`:t("v51.registration.result.note")}</p>${r.registeredAt?`<small>${r.registeredAt}</small>`:""}${r.status==="registered"?`<button class="btn u-mt-14" id="openResultDoc">${t("v51.registration.result.open")}</button>`:""}</section>
   <section class="card card-pad"><div class="eyebrow">${t("v51.registration.actions.eyebrow")}</div><div class="reg-action-stack">${actionButtons(r,ready.ok===ready.total,req)}</div></section>
   <section class="card card-pad reg-context"><div class="eyebrow">${t("v51.registration.context")}</div><p><strong>${contract?.type??r.contractId}</strong><br>${statusLabel(contract?.status??"—")}</p><p><strong>${deal?.id??r.dealId}</strong><br>${statusLabel(deal?.status??"—")}</p></section>
 </aside></div></section>`}

function documentCard(r:RegistrationCase,d:RegistrationDocument){const state=d.status==="verified"?"success":d.status==="rejected"?"danger":d.status==="uploaded"?"info":"warning";return `<article class="reg-doc-card ${state}"><div class="reg-doc-icon">${d.status==="verified"?"✓":d.status==="rejected"?"!":"DOC"}</div><div class="reg-doc-copy"><div class="reg-doc-title"><strong>${escapeHtml(d.title)}</strong>${d.required?`<span>${t("v51.registration.required")}</span>`:""}</div><p>${d.fileName?escapeHtml(d.fileName):t("v51.registration.docMissing")}</p><small>${d.verifiedBy?`${t("v51.registration.verifiedBy")}: ${escapeHtml(d.verifiedBy)}`:d.uploadedAt??""}</small></div><div class="reg-doc-actions">${badge(d.status)}${d.status==="missing"||d.status==="rejected"?`<button class="btn btn-small" data-upload-reg-doc="${d.id}">${t("v51.registration.upload")}</button>`:""}${d.status==="uploaded"?`<button class="btn btn-small btn-primary" data-verify-reg-doc="${d.id}">${t("v51.registration.verify")}</button>`:""}</div></article>`}

function actionButtons(r:RegistrationCase,docsReady:boolean,req?:ReturnType<typeof openRequest>){
 if(r.status==="registered")return `<button class="btn btn-primary" id="goHandover">${t("v51.registration.action.handover")}</button>`;
 if(r.status==="preparation")return `<button class="btn btn-primary" id="advanceRegistration" ${!docsReady||!r.feeReceiptNo?"disabled":""}>${t("v51.registration.action.toNotary")}</button><small>${!docsReady||!r.feeReceiptNo?t("v51.registration.action.blockedDocs"):t("v51.registration.action.ready")}</small>`;
 if(r.status==="notary")return `<button class="btn btn-primary" id="advanceRegistration">${t("v51.registration.action.submit")}</button>`;
 if(r.status==="submitted")return `<button class="btn btn-primary" id="registerSuccess">${t("v51.registration.action.register")}</button><button class="btn" id="requestMoreDocsSide">${t("v51.registration.requestDocs")}</button><button class="btn danger-outline" id="rejectRegistration">${t("v51.registration.action.reject")}</button>`;
 if(r.status==="additional-documents")return req?.status==="open"?`<div class="reg-action-note">${t("v51.registration.action.fulfillFirst")}</div>`:`<button class="btn btn-primary" id="resubmitRegistration">${t("v51.registration.action.resubmit")}</button>`;
 if(r.status==="rejected")return `<button class="btn btn-primary" id="resubmitRegistration">${t("v51.registration.action.resubmit")}</button><small>${t("v51.registration.action.resubmitNote")}</small>`;
 return "";
}

export function bindRegistration(){
 document.querySelector("#backLegal")?.addEventListener("click",()=>navigate("legal"));document.querySelector("#newRegistration")?.addEventListener("click",openRegistrationForm);
 document.querySelector("#backRegistration")?.addEventListener("click",()=>navigate("registration"));
 document.querySelectorAll<HTMLElement>("[data-open-registration]").forEach(el=>el.addEventListener("click",e=>{e.stopPropagation();navigate(`registration/${el.dataset.openRegistration}`)}));
 document.querySelectorAll<HTMLElement>("[data-registration-card]").forEach(el=>{el.addEventListener("click",()=>navigate(`registration/${el.dataset.registrationCard}`));el.addEventListener("keydown",e=>{if(e.key==="Enter"||e.key===" "){e.preventDefault();navigate(`registration/${el.dataset.registrationCard}`)}})});
 document.querySelectorAll<HTMLButtonElement>("[data-reg-filter]").forEach(btn=>btn.addEventListener("click",()=>{document.querySelectorAll("[data-reg-filter]").forEach(x=>x.classList.remove("active"));btn.classList.add("active");const f=btn.dataset.regFilter!;document.querySelectorAll<HTMLElement>("[data-registration-card]").forEach(card=>card.hidden=f!=="all"&&!card.dataset.filterGroup?.split(" ").includes(f))}));
 document.querySelector<HTMLElement>("[data-open-deal]")?.addEventListener("click",e=>navigate(`deal/${(e.currentTarget as HTMLElement).dataset.openDeal}`));
 document.querySelector<HTMLElement>("[data-open-contract]")?.addEventListener("click",e=>navigate(`contract/${(e.currentTarget as HTMLElement).dataset.openContract}`));
 const id=location.hash.match(/registration\/([^?]+)/)?.[1],r=id?registrationCases.find(x=>x.id===id):undefined;if(!r)return;
 document.querySelector("#recordFee")?.addEventListener("click",()=>recordFee(r));document.querySelector("#addRegistrationDoc")?.addEventListener("click",()=>addDocument(r));
 document.querySelectorAll<HTMLElement>("[data-upload-reg-doc]").forEach(el=>el.addEventListener("click",()=>uploadDocument(r,el.dataset.uploadRegDoc!)));
 document.querySelectorAll<HTMLElement>("[data-verify-reg-doc]").forEach(el=>el.addEventListener("click",()=>verifyDocument(r,el.dataset.verifyRegDoc!)));
 document.querySelector("#advanceRegistration")?.addEventListener("click",()=>advanceRegistration(r));
 document.querySelector("#requestMoreDocs")?.addEventListener("click",()=>requestDocuments(r));document.querySelector("#requestMoreDocsSide")?.addEventListener("click",()=>requestDocuments(r));
 document.querySelectorAll<HTMLElement>("[data-fulfill-request]").forEach(el=>el.addEventListener("click",()=>fulfillRequest(r,el.dataset.fulfillRequest!)));
 document.querySelector("#resubmitRegistration")?.addEventListener("click",()=>resubmit(r));document.querySelector("#rejectRegistration")?.addEventListener("click",()=>rejectRegistration(r));document.querySelector("#registerSuccess")?.addEventListener("click",()=>completeRegistration(r));
 document.querySelector("#openResultDoc")?.addEventListener("click",()=>toastLocalized(t("v51.registration.result.previewToast",{name:r.resultDocumentName??"PDF"})));
 document.querySelector("#goHandover")?.addEventListener("click",()=>navigate("handover"));
}

function contractReady(r:RegistrationCase){const c=contracts.find(x=>x.id===r.contractId);return !!c&&["signed","notary","registered"].includes(c.status)}
function advanceRegistration(r:RegistrationCase){
 if(!contractReady(r)){toastLocalized(t("registrationPage.contractNotReady"));return}
 if(r.status==="preparation"){
   const ready=documentReadiness(r);if(ready.ok!==ready.total||!r.feeReceiptNo){toastLocalized(t("v51.registration.toast.docsNotReady"));return}
   r.status="notary";event(r,t("v51.registration.event.notary"),t("v51.registration.event.notaryNote"));const c=contracts.find(x=>x.id===r.contractId);if(c)c.status="notary";toastLocalized(t("v51.registration.toast.notary"));refresh(r.id);return;
 }
 if(r.status==="notary"){
   r.notaryActionNo=r.notaryActionNo??`NT-${String(8100+registrationCases.indexOf(r)).padStart(5,"0")}`;r.notaryCompletedAt=at();r.status="submitted";r.applicationNo=r.applicationNo??`REG-2026-${550200+registrationCases.length+registrationCases.indexOf(r)}`;r.submissionRound=(r.submissionRound??0)+1;r.submittedAt=at();
   const n=r.documents?.find(x=>x.type==="notary-act");if(n){n.status="verified";n.fileName=`${r.id}_notary_act.pdf`;n.uploadedAt=at();n.verifiedAt=at();n.verifiedBy=r.owner}
   event(r,t("v51.registration.event.submitted"),t("v51.registration.event.submittedNote",{number:r.applicationNo}));toastLocalized(t("v51.registration.toast.submitted"));refresh(r.id);
 }
}
function recordFee(r:RegistrationCase){openLocalizedModal(t("v51.registration.fee.modalTitle"),`<form id="feeForm" class="form-grid"><div class="form-field"><label>${t("v51.registration.fee.receipt")}</label><input name="receipt" value="SF-${r.id.replace("RG-","")}-2026" required></div><div class="form-field"><label>${t("v51.registration.fee.amount")}</label><input value="${r.stateFee}" disabled></div><div class="form-field full"><label>${t("v51.registration.fee.file")}</label><input name="file" value="${r.id}_state_fee_receipt.pdf" required></div></form>`,`<button class="btn" data-modal-close>${t("registrationPage.cancel")}</button><button class="btn btn-primary" id="saveFee">${t("v51.registration.save")}</button>`);setTimeout(()=>document.querySelector("#saveFee")?.addEventListener("click",()=>{const f=document.querySelector<HTMLFormElement>("#feeForm")!;if(!f.reportValidity())return;r.feeReceiptNo=formValue(f,"receipt");r.feePaidAt=at();const d=r.documents?.find(x=>x.type==="fee-receipt");if(d){d.status="verified";d.fileName=formValue(f,"file");d.uploadedAt=at();d.verifiedAt=at();d.verifiedBy=r.owner}event(r,t("v51.registration.event.fee"),t("v51.registration.event.feeNote",{receipt:r.feeReceiptNo}));closeModal();toastLocalized(t("v51.registration.toast.fee"));refresh(r.id)}),0)}
function uploadDocument(r:RegistrationCase,docId:string){const d=r.documents?.find(x=>x.id===docId);if(!d)return;openLocalizedModal(t("v51.registration.uploadTitle"),`<form id="regUploadForm" class="form-grid"><div class="form-field full"><label>${t("v51.registration.fileName")}</label><input name="file" value="${r.id}_${d.type}.pdf" required></div><div class="form-field full"><label>${t("v51.registration.note")}</label><textarea name="note" rows="3"></textarea></div></form>`,`<button class="btn" data-modal-close>${t("registrationPage.cancel")}</button><button class="btn btn-primary" id="saveRegUpload">${t("v51.registration.upload")}</button>`);setTimeout(()=>document.querySelector("#saveRegUpload")?.addEventListener("click",()=>{const f=document.querySelector<HTMLFormElement>("#regUploadForm")!;if(!f.reportValidity())return;d.fileName=formValue(f,"file");d.note=formValue(f,"note");d.uploadedAt=at();d.status="uploaded";event(r,t("v51.registration.event.documentUploaded"),d.title);closeModal();toastLocalized(t("v51.registration.toast.uploaded"));refresh(r.id)}),0)}
function verifyDocument(r:RegistrationCase,docId:string){const d=r.documents?.find(x=>x.id===docId);if(!d)return;d.status="verified";d.verifiedAt=at();d.verifiedBy=r.owner;event(r,t("v51.registration.event.documentVerified"),d.title);toastLocalized(t("v51.registration.toast.verified"));refresh(r.id)}
function addDocument(r:RegistrationCase){openLocalizedModal(t("v51.registration.addDocument"),`<form id="addRegDocForm" class="form-grid"><div class="form-field full"><label>${t("v51.registration.documentTitle")}</label><input name="title" required></div><div class="form-field full"><label>${t("v51.registration.fileName")}</label><input name="file" value="additional_document.pdf" required></div></form>`,`<button class="btn" data-modal-close>${t("registrationPage.cancel")}</button><button class="btn btn-primary" id="saveAddedRegDoc">${t("v51.registration.add")}</button>`);setTimeout(()=>document.querySelector("#saveAddedRegDoc")?.addEventListener("click",()=>{const f=document.querySelector<HTMLFormElement>("#addRegDocForm")!;if(!f.reportValidity())return;r.documents??=[];r.documents.push({id:`RD-${r.id}-${r.documents.length+1}`,type:"additional",title:formValue(f,"title"),required:false,status:"uploaded",fileName:formValue(f,"file"),uploadedAt:at()});event(r,t("v51.registration.event.documentUploaded"),formValue(f,"title"));closeModal();refresh(r.id)}),0)}
function requestDocuments(r:RegistrationCase){openLocalizedModal(t("v51.registration.requestModal.title"),`<form id="requestDocsForm" class="form-grid"><div class="form-field full"><label>${t("v51.registration.requestModal.items")}</label><textarea name="items" rows="4" placeholder="${t("v51.registration.requestModal.placeholder")}" required></textarea></div><div class="form-field"><label>${t("v51.registration.requestModal.due")}</label><input type="date" name="due" value="2026-09-29"></div><div class="form-field full"><label>${t("v51.registration.note")}</label><textarea name="note" rows="3"></textarea></div></form>`,`<button class="btn" data-modal-close>${t("registrationPage.cancel")}</button><button class="btn btn-primary" id="saveDocRequest">${t("v51.registration.requestDocs")}</button>`);setTimeout(()=>document.querySelector("#saveDocRequest")?.addEventListener("click",()=>{const f=document.querySelector<HTMLFormElement>("#requestDocsForm")!;if(!f.reportValidity())return;const items=formValue(f,"items").split(/\n|,/).map(x=>x.trim()).filter(Boolean);r.additionalRequests??=[];const q={id:`RQ-${r.id}-${r.additionalRequests.length+1}`,requestedAt:at(),requestedBy:r.authority??t("v51.registration.defaultAuthority"),dueAt:formValue(f,"due"),items,note:formValue(f,"note"),status:"open" as const};r.additionalRequests.push(q);r.status="additional-documents";event(r,t("v51.registration.event.additionalRequested"),items.join("; "));closeModal();toastLocalized(t("v51.registration.toast.additionalRequested"));refresh(r.id)}),0)}
function fulfillRequest(r:RegistrationCase,id:string){const q=r.additionalRequests?.find(x=>x.id===id);if(!q)return;q.status="fulfilled";q.fulfilledAt=at();q.items.forEach((item,i)=>{r.documents??=[];r.documents.push({id:`RD-${r.id}-REQ${r.documents.length+i}`,type:"additional",title:item,required:false,status:"verified",fileName:`${r.id}_additional_${i+1}.pdf`,uploadedAt:at(),verifiedAt:at(),verifiedBy:r.owner})});event(r,t("v51.registration.event.requestFulfilled"),q.items.join("; "));toastLocalized(t("v51.registration.toast.requestFulfilled"));refresh(r.id)}
function resubmit(r:RegistrationCase){if(openRequest(r)){toastLocalized(t("v51.registration.toast.openRequest"));return}r.status="submitted";r.submissionRound=(r.submissionRound??1)+1;r.applicationNo=`${(r.applicationNo??`REG-2026-${550200+registrationCases.length}` ).split("/R")[0]}/R${r.submissionRound}`;r.submittedAt=at();event(r,t("v51.registration.event.resubmitted"),t("v51.registration.event.resubmittedNote",{round:String(r.submissionRound)}));toastLocalized(t("v51.registration.toast.resubmitted"));refresh(r.id)}
function rejectRegistration(r:RegistrationCase){openLocalizedModal(t("v51.registration.rejectModal.title"),`<form id="rejectRegForm" class="form-grid"><div class="form-field full"><label>${t("v51.registration.rejectModal.reason")}</label><textarea name="reason" rows="5" required placeholder="${t("v51.registration.rejectModal.placeholder")}"></textarea></div></form>`,`<button class="btn" data-modal-close>${t("registrationPage.cancel")}</button><button class="btn danger" id="confirmRegReject">${t("v51.registration.action.reject")}</button>`);setTimeout(()=>document.querySelector("#confirmRegReject")?.addEventListener("click",()=>{const f=document.querySelector<HTMLFormElement>("#rejectRegForm")!;if(!f.reportValidity())return;r.status="rejected";r.rejectionReason=formValue(f,"reason");r.rejectedAt=at();event(r,t("v51.registration.event.rejected"),r.rejectionReason);closeModal();toastLocalized(t("v51.registration.toast.rejected"));refresh(r.id)}),0)}
function completeRegistration(r:RegistrationCase){const ready=documentReadiness(r);if(ready.ok!==ready.total){toastLocalized(t("v51.registration.toast.docsNotReady"));return}openLocalizedModal(t("v51.registration.completeModal.title"),`<form id="completeRegForm" class="form-grid"><div class="form-field"><label>${t("v51.registration.completeModal.number")}</label><input name="number" value="CERT-${r.id.replace("RG-","")}-2026" required></div><div class="form-field"><label>${t("v51.registration.completeModal.file")}</label><input name="file" value="${r.id}_final_extract.pdf" required></div><div class="form-field full"><label>${t("v51.registration.note")}</label><textarea name="note" rows="3">${t("v51.registration.completeModal.defaultNote")}</textarea></div></form>`,`<button class="btn" data-modal-close>${t("registrationPage.cancel")}</button><button class="btn btn-primary" id="confirmRegistrationDone">${t("v51.registration.completeModal.confirm")}</button>`);setTimeout(()=>document.querySelector("#confirmRegistrationDone")?.addEventListener("click",()=>{const f=document.querySelector<HTMLFormElement>("#completeRegForm")!;if(!f.reportValidity())return;r.status="registered";r.resultDocumentNo=formValue(f,"number");r.resultDocumentName=formValue(f,"file");r.registeredAt=at();r.documents??=[];r.documents.push({id:`RD-${r.id}-FINAL`,type:"final-extract",title:t("v51.registration.finalExtract"),required:false,status:"verified",fileName:r.resultDocumentName,uploadedAt:at(),verifiedAt:at(),verifiedBy:r.owner});const c=contracts.find(x=>x.id===r.contractId);if(c)c.status="registered";const d=deals.find(x=>x.id===r.dealId);if(d){d.status="registration";d.nextAction="i18n:registration.next.prepareHandover";d.propertyIds.forEach(pid=>{const p=properties.find(x=>x.id===pid);if(p){p.status="sold";p.legalStatus="registered";p.statusHistory??=[];p.statusHistory.push({id:`PSE-${p.id}-${p.statusHistory.length+1}`,status:"sold",at:at(),actor:r.owner??"Legal",note:t("v51.registration.propertyRegistered")})}})}const h=handoverCases.find((x:any)=>x.dealId===r.dealId);if(h)h.registrationClearance=true;event(r,t("v51.registration.event.registered"),formValue(f,"note"));closeModal();toastLocalized(t("v51.registration.toast.registered"));refresh(r.id)}),0)}

function openRegistrationForm(){
 const eligibleContracts=contracts.filter(c=>["signed","notary"].includes(c.status)&&!registrationCases.some(r=>r.contractId===c.id));
 openLocalizedModal(t("registrationPage.modal.title"),`<form id="regForm" class="form-grid"><div class="form-field full"><label>${t("registrationPage.contract")}</label><select name="contractId" required ${eligibleContracts.length?"":"disabled"}><option value="">${eligibleContracts.length?t("registrationPage.chooseContract"):t("registrationPage.noEligibleContracts")}</option>${eligibleContracts.map(c=>`<option value="${c.id}">${c.id} · ${c.clientName} · ${c.propertyLabel}</option>`).join("")}</select></div><div class="form-field"><label>${t("registrationPage.notary")}</label><input name="notary" value="Ա. Սահակյան"></div><div class="form-field"><label>${t("v51.registration.authority")}</label><input name="authority" value="${t("v51.registration.defaultAuthority")}"></div><div class="form-field"><label>${t("registrationPage.stateFee")}</label><input name="stateFee" type="number" min="0" value="25000"></div><div class="form-field"><label>${t("v51.registration.owner")}</label><input name="owner" value="Անահիտ Մարտիրոսյան"></div><div class="form-field full"><label>${t("registrationPage.plannedDate")}</label><input name="plannedAt" value="24.09.2026 · 11:00"></div></form>`,`<button class="btn" data-modal-close>${t("registrationPage.cancel")}</button><button class="btn btn-accent" id="saveRegistration" ${eligibleContracts.length?"":"disabled"}>${t("registrationPage.create")}</button>`);
 setTimeout(()=>document.querySelector("#saveRegistration")?.addEventListener("click",()=>{const f=document.querySelector<HTMLFormElement>("#regForm")!;if(!f.reportValidity())return;const contractId=formValue(f,"contractId");if(registrationCases.some(r=>r.contractId===contractId)){toastLocalized(t("registrationPage.toast.duplicate"));return}const c=contracts.find(x=>x.id===contractId);if(!c){toastLocalized(t("common.recordNotFound"));return}const d=deals.find(x=>x.id===c.dealId);if(!d){toastLocalized(t("common.recordNotFound"));return}const id=`RG-${String(265+registrationCases.length).padStart(4,"0")}`;const r:RegistrationCase={id,dealId:d.id,contractId:c.id,clientName:c.clientName,propertyLabel:c.propertyLabel.split("·").pop()?.trim()??c.propertyLabel,status:"preparation",notary:formValue(f,"notary"),authority:formValue(f,"authority"),stateFee:Number(formValue(f,"stateFee")),plannedAt:formValue(f,"plannedAt"),owner:formValue(f,"owner"),submissionRound:0,documents:requiredDocumentSeed(),additionalRequests:[],history:[]};event(r,t("v51.registration.event.created"),t("v51.registration.event.createdNote"),r.owner);registrationCases.push(r);closeModal();toastLocalized(t("registrationPage.toast.created"));navigate(`registration/${id}`)}),0)
}
