import { approvals, deals, paymentSchedule, paymentScheduleVersions, restructureCases } from "../data/mock";
import { amd, badge, paymentSourceLabel, statusLabel } from "../utils";
import { navigate } from "../router";
import { openLocalizedModal,toastLocalized } from "../components/layout";
import { applyRestructure } from "../services/payments";
import {t} from "../i18n";
import {demoText} from "../demo-i18n";
import {createManualWorkflowRoute,getRouteApprovals,getWorkflowRoute} from "../services/workflow";

export function restructurePage(){return`<section class="page"><div class="page-header"><div class="page-title"><div class="eyebrow">${t("restructure.terms")}</div><h1>${t("restructurePage.title")}</h1><p>${t("restructurePage.subtitle")}</p></div><button class="btn" id="backFinanceRes">${t("restructurePage.backFinance")}</button></div><div class="card card-pad">${restructureCases.map(r=>card(r)).join("")}</div></section>`}
function card(r:(typeof restructureCases)[number]){const versions=paymentScheduleVersions.filter(v=>v.dealId===r.dealId).sort((a,b)=>a.version-b.version),route=getWorkflowRoute("payment-plan",r.id),approval=r.approvalId?approvals.find(a=>a.id===r.approvalId):route?getRouteApprovals(route)[0]:approvals.find(a=>a.dealId===r.dealId&&a.type==="payment-plan"&&a.reason.includes(r.id)),current=paymentSchedule.filter(x=>x.dealId===r.dealId);if(approval&&!r.approvalId)r.approvalId=approval.id;return`<div class="restructure-card"><div class="restructure-head"><div><strong>${r.id} · ${r.clientName}</strong><span>${r.dealId} · ${demoText(r.reason)}</span></div>${badge(r.status)}</div><div class="restructure-compare"><div><span>${t("restructurePage.beforeChange")}</span><strong>${demoText(r.oldTerms)}</strong></div><div class="change-arrow">→</div><div><span>${t("restructurePage.proposedSchedule")}</span><strong>${demoText(r.newTerms)}</strong></div></div>${r.proposedSchedule?.length?`<div class="schedule-preview"><div><span>${t("restructurePage.proposedVersion")}</span>${r.proposedSchedule.map((x,i)=>`<p><b>${i+1}. ${x.dueDate}</b><strong>${demoText(x.title)}</strong><em>${amd(x.amount)} · ${paymentSourceLabel(x.source)}</em></p>`).join("")}</div><div><span>${t("restructurePage.currentSchedule")}</span>${current.map(x=>`<p><b>${x.dueDate}</b><strong>${demoText(x.title)}</strong><em>${amd(x.amount)} · ${statusLabel("paid")} ${amd(x.paid)}</em></p>`).join("")}</div></div>`:""}<div class="restructure-meta"><span>${t("restructurePage.scheduleVersions")} <strong>${Math.max(versions.length,r.appliedVersion?2:1)}</strong></span>${r.appliedVersion?`<span>${t("restructurePage.applied")} <strong>${r.appliedVersion}</strong></span>`:""}${approval?`<span>${t("restructurePage.approval")} <strong>${approval.id} · ${statusLabel(approval.status)}</strong></span>`:""}</div><div class="toolbar"><button class="btn" data-res-deal="${r.dealId}">${t("restructurePage.openDeal")}</button><button class="btn" data-res-history="${r.dealId}">${t("restructurePage.versionHistory")}</button>${r.status==="approval"&&!approval?`<button class="btn btn-primary" data-res-send="${r.id}">${t("restructurePage.sendForApproval")}</button>`:""}${r.status==="approval"&&approval?.status==="pending"?`<button class="btn btn-primary" data-res-center="1">${t("restructurePage.openApprovalCenter")}</button>`:""}${r.status==="approval"&&approval?.status==="approved"?`<button class="btn btn-success" data-res-apply="${r.id}">${t("restructurePage.applyApprovedSchedule")}</button>`:""}${r.status==="approved"?`<button class="btn btn-soft" disabled>${t("restructurePage.scheduleApplied")}</button>`:""}</div></div>`}
export function bindRestructure(){document.querySelector("#backFinanceRes")?.addEventListener("click",()=>navigate("finance"));document.querySelectorAll<HTMLElement>("[data-res-deal]").forEach(el=>el.addEventListener("click",()=>navigate("deal/"+el.dataset.resDeal)));document.querySelectorAll<HTMLElement>("[data-res-center]").forEach(el=>el.addEventListener("click",()=>navigate("approvals")));document.querySelectorAll<HTMLElement>("[data-res-send]").forEach(el=>el.addEventListener("click",()=>sendApproval(el.dataset.resSend!)));document.querySelectorAll<HTMLElement>("[data-res-apply]").forEach(el=>el.addEventListener("click",()=>applyNow(el.dataset.resApply!)));document.querySelectorAll<HTMLElement>("[data-res-history]").forEach(el=>el.addEventListener("click",()=>showHistory(el.dataset.resHistory!)))}
function sendApproval(id:string){const r=restructureCases.find(x=>x.id===id);if(!r)return;const existing=getWorkflowRoute("payment-plan",r.id);if(existing){r.approvalId=getRouteApprovals(existing)[0]?.id;navigate("approvals?tab=inbox");return}const d=deals.find(x=>x.id===r.dealId);const route=createManualWorkflowRoute({sourceType:"payment-plan",subjectId:r.id,dealId:r.dealId,title:r.id,clientName:r.clientName,propertyLabel:d?.propertyLabel??"Payment schedule",requestedBy:r.owner,amount:d?.amount,currency:d?.currency,installmentMonths:24},{type:"payment-plan",role:"Finance",priority:"high",slaHours:12,requestedValue:r.newTerms,limitValue:r.oldTerms,reason:`${r.id}: ${r.reason}`});r.approvalId=getRouteApprovals(route)[0]?.id;r.updatedAt="17.09 · сейчас";toastLocalized(t("restructurePage.sentForApproval"));navigate("approvals?tab=inbox")}
function applyNow(id:string){const version=applyRestructure(id);toastLocalized(version?t("restructurePage.appliedAsVersion",{version:version.version}):t("restructurePage.applyFailed"));refresh()}
function showHistory(dealId:string){const versions=paymentScheduleVersions.filter(v=>v.dealId===dealId).sort((a,b)=>b.version-a.version);if(!versions.length){toastLocalized(t("restructurePage.noSavedVersions"));return}openLocalizedModal(`${t("restructurePage.historyTitle")} · ${dealId}`,`<div class="version-list">${versions.map(v=>`<div class="version-row"><div class="version-mark ${v.version===versions[0].version?"current":"archived"}"></div><div class="version-copy"><strong>v${v.version} · ${demoText(v.reason)}</strong><span>${demoText(v.createdAt)}${v.sourceCaseId?` · ${v.sourceCaseId}`:""}</span>${v.rows.map(r=>`<small class="u-block-muted-mt4">${r.dueDate} · ${demoText(r.title)} · ${amd(r.amount)} · ${paymentSourceLabel(r.source)}</small>`).join("")}</div><span class="version-state">${v.version===versions[0].version?t("restructurePage.current"):t("restructurePage.archived")}</span></div>`).join("")}</div>`)}
function refresh(){navigate("finance");setTimeout(()=>navigate("restructure"),20)}
