import { t } from "../i18n";
import { clients, properties, warrantyCases } from "../data/mock";
import { badge, channelLabel, priorityLabel } from "../utils";
import { navigate } from "../router";
import { closeModal, formValue, openLocalizedModal, toastLocalized } from "../components/layout";
import { warrantyCategoryLabel } from "./service-i18n";

const serviceNow=new Date("2026-09-23T09:14:00+04:00");
function parseLegacy(v:string){const [date,time="23:59"]=v.split(" · ");const [d,m,y]=date.split(".");return new Date(`${y}-${m}-${d}T${time}:00`)}
function slaState(w:any){if(["resolved","closed"].includes(w.status))return "done";const diff=parseLegacy(w.dueAt).getTime()-serviceNow.getTime();if(diff<0)return "overdue";if(diff<=12*3600000)return "risk";return "ok"}
function slaLabel(w:any){const state=slaState(w);if(state==="done")return t("v52.service.sla.done");const hours=Math.ceil(Math.abs(parseLegacy(w.dueAt).getTime()-serviceNow.getTime())/3600000);return state==="overdue"?t("v52.service.sla.overdue",{count:hours}):state==="risk"?t("v52.service.sla.risk",{count:hours}):t("v52.service.sla.remaining",{count:hours})}

export function servicePage() {
  const open=warrantyCases.filter((x:any)=>!["resolved","closed"].includes(x.status));
  const atRisk=open.filter((w:any)=>["overdue","risk"].includes(slaState(w))).length;
  const escalated=open.filter((w:any)=>(w.escalationLevel??0)>0).length;
  const rated=warrantyCases.filter((w:any)=>typeof w.csat==="number");
  const rating=rated.length?(rated.reduce((s:number,w:any)=>s+w.csat,0)/rated.length).toFixed(1):"—";
  const waiting=warrantyCases.filter((w:any)=>w.status==="waiting-client").length;
  return `<section class="page">
    <div class="page-header"><div class="page-title"><h1>${t("servicePage.title")}</h1><p>${t("v52.service.subtitle")}</p></div><div class="toolbar"><button class="btn" id="contractors">${t("servicePage.contractors")}</button><button class="btn btn-primary" id="newWarranty">${t("servicePage.newRequest")}</button></div></div>
    <div class="grid grid-4 u-mb-16">
      ${metric(t("servicePage.metric.open"), open.length, t("servicePage.metric.openNote"))}
      ${metric(t("v52.service.metric.sla"), atRisk, t("v52.service.metric.slaNote",{count:escalated}))}
      ${metric(t("v52.service.metric.waiting"), waiting, t("v52.service.metric.waitingNote"))}
      ${metric(t("servicePage.metric.rating"), `${rating}/5`, t("v52.service.metric.ratingNote",{count:rated.length}))}
    </div>

    <div class="v52-service-control card card-pad u-mb-16"><div><span class="eyebrow">${t("v52.service.commandEyebrow")}</span><strong>${t("v52.service.commandTitle")}</strong><p>${t("v52.service.commandSub")}</p></div><div class="toolbar"><select class="field compact" id="serviceStatusFilter"><option value="">${t("v52.service.filter.all")}</option><option value="attention">${t("v52.service.filter.attention")}</option><option value="waiting-client">${t("v52.service.filter.waiting")}</option><option value="closed">${t("v52.service.filter.closed")}</option></select><select class="field compact" id="serviceCategoryFilter"><option value="">${t("v52.service.filter.allCategories")}</option>${["Electrical","Plumbing","HVAC","Windows","Finishing"].map(x=>`<option value="${x}">${warrantyCategoryLabel(x)}</option>`).join("")}</select></div></div>

    <div class="service-board"><div class="card card-pad service-kpis"><div class="section-title"><div><h2>${t("servicePage.load.title")}</h2><p>${t("v52.service.loadSub")}</p></div></div>
      ${lane(t("servicePage.lane.new"), warrantyCases.filter((x: any) => x.status === "new").length, 18)}
      ${lane(t("servicePage.lane.assigned"), warrantyCases.filter((x: any) => x.status === "assigned").length, 36)}
      ${lane(t("servicePage.lane.inProgress"), warrantyCases.filter((x: any) => x.status === "in-progress").length, 62)}
      ${lane(t("servicePage.lane.waitingClient"), waiting, 44)}
      ${lane(t("servicePage.lane.completed"), warrantyCases.filter((x:any)=>["resolved","closed"].includes(x.status)).length, 86)}
      <div class="v52-service-legend"><span class="ok">● ${t("v52.service.legend.onTime")}</span><span class="risk">● ${t("v52.service.legend.atRisk")}</span><span class="late">● ${t("v52.service.legend.overdue")}</span></div>
    </div>
    <div class="card"><div class="table-wrap"><table class="table v52-service-table"><thead><tr><th>${t("servicePage.col.request")}</th><th>${t("servicePage.col.clientProperty")}</th><th>${t("servicePage.col.category")}</th><th>${t("servicePage.col.priority")}</th><th>SLA</th><th>${t("servicePage.col.contractor")}</th><th>${t("v52.service.evidence")}</th><th>${t("servicePage.col.status")}</th></tr></thead><tbody>${warrantyCases.map((w: any) => row(w)).join("")}</tbody></table></div></div></div>
  </section>`;
}

function metric(label: string, value: number | string, note: string) {return `<div class="card metric-card"><div class="metric-top"><span>${label}</span></div><div><div class="metric-value">${value}</div><div class="metric-note">${note}</div></div></div>`;}
function lane(label: string, value: number, percent: number) {return `<div class="service-lane"><div><strong>${label}</strong><span>${t("servicePage.cases", { count: value })}</span></div><div class="progress"><span style="width:${percent}%"></span></div></div>`;}
function row(w:any){const s=slaState(w),attention=s==="overdue"||s==="risk"||(w.escalationLevel??0)>0;const evidence=`${w.beforeEvidence??0}/${w.afterEvidence??0}`;return `<tr data-warranty="${w.id}" data-service-status="${w.status}" data-service-attention="${attention?"1":"0"}" data-service-category="${w.category}"><td><strong>${w.id}</strong><div class="u-meta-105 u-mt-3">${channelLabel(w.channel)}${w.escalationLevel?` · <span class="v52-escalation-inline">L${w.escalationLevel}</span>`:""}</div></td><td><div class="person"><div class="avatar">${w.propertyLabel.split("-").pop()}</div><div><strong>${w.clientName}</strong><span>${w.propertyLabel}</span></div></div></td><td>${warrantyCategoryLabel(w.category)}</td><td><span class="priority ${w.priority}">${priorityLabel(w.priority)}</span></td><td><span class="v52-sla-pill ${s}">${slaLabel(w)}</span><small class="v52-table-sub">${w.dueAt}</small></td><td>${w.contractor}<small class="v52-table-sub">${w.owner}</small></td><td><span class="v52-evidence-ratio"><b>${evidence}</b><small>${t("v52.service.beforeAfter")}</small></span></td><td>${badge(w.status)}${w.csat?`<div class="v52-stars-mini">${"★".repeat(w.csat)}${"☆".repeat(5-w.csat)}</div>`:""}</td></tr>`}

export function bindService() {
  document.querySelectorAll("[data-warranty]").forEach(el => el.addEventListener("click", () => navigate("warranty/" + (el as HTMLElement).dataset.warranty)));
  document.querySelector("#newWarranty")?.addEventListener("click", openWarrantyForm);
  document.querySelector("#contractors")?.addEventListener("click", openContractorPerformance);
  document.querySelector("#serviceStatusFilter")?.addEventListener("change",filterRows);document.querySelector("#serviceCategoryFilter")?.addEventListener("change",filterRows);
}
function filterRows(){const st=document.querySelector<HTMLSelectElement>("#serviceStatusFilter")?.value??"",cat=document.querySelector<HTMLSelectElement>("#serviceCategoryFilter")?.value??"";document.querySelectorAll<HTMLTableRowElement>("[data-warranty]").forEach(r=>{const statusOk=!st||(st==="attention"?r.dataset.serviceAttention==="1":st==="closed"?["closed","resolved"].includes(r.dataset.serviceStatus??""):r.dataset.serviceStatus===st);const catOk=!cat||r.dataset.serviceCategory===cat;r.style.display=statusOk&&catOk?"":"none"})}
function openContractorPerformance(){const names=[...new Set(warrantyCases.map((w:any)=>w.contractor))];openLocalizedModal(t("v52.service.contractorsTitle"),`<div class="v52-contractor-grid">${names.map(name=>{const rows=warrantyCases.filter((w:any)=>w.contractor===name),active=rows.filter((w:any)=>!["resolved","closed"].includes(w.status)).length,closed=rows.filter((w:any)=>w.status==="closed"),ratings=closed.filter((w:any)=>w.csat),score=ratings.length?(ratings.reduce((s:number,w:any)=>s+w.csat,0)/ratings.length).toFixed(1):"—";return `<div class="v52-contractor-card"><div><span>${t("v52.service.contractor")}</span><strong>${name}</strong></div><div class="v52-contractor-metrics"><div><b>${active}</b><span>${t("v52.service.active")}</span></div><div><b>${score}</b><span>CSAT</span></div><div><b>${rows.filter((w:any)=>slaState(w)==="overdue").length}</b><span>${t("v52.service.overdue")}</span></div></div></div>`}).join("")}</div>`)}

function openWarrantyForm() {
  openLocalizedModal(t("servicePage.modal.title"), `<form id="warrantyCreateForm" class="form-grid"><div class="form-field"><label>${t("servicePage.modal.client")}</label><select name="clientId" required><option value="">${t("servicePage.choose")}</option>${clients.map(c => `<option value="${c.id}">${c.name}</option>`).join("")}</select></div><div class="form-field"><label>${t("servicePage.modal.property")}</label><select name="propertyId" required><option value="">${t("servicePage.choose")}</option>${properties.filter(p => ["sold","contract","handed-over","handover"].includes(p.status)).map(p => `<option value="${p.id}">${p.project} · ${p.unit}</option>`).join("")}</select></div><div class="form-field"><label>${t("servicePage.modal.category")}</label><select name="category"><option value="Electrical">${t("servicePage.category.electrical")}</option><option value="Plumbing">${t("servicePage.category.plumbing")}</option><option value="HVAC">${t("servicePage.category.hvac")}</option><option value="Windows">${t("servicePage.category.windows")}</option><option value="Finishing">${t("servicePage.category.finishing")}</option></select></div><div class="form-field"><label>${t("servicePage.modal.priority")}</label><select name="priority"><option value="low">${priorityLabel("low")}</option><option value="medium">${priorityLabel("medium")}</option><option value="high">${priorityLabel("high")}</option><option value="urgent">${priorityLabel("urgent")}</option></select></div><div class="form-field full"><label>${t("servicePage.modal.subject")}</label><input name="title" required placeholder="${t("servicePage.modal.subjectPlaceholder")}"></div><div class="form-field full"><label>${t("servicePage.modal.description")}</label><textarea name="description" required></textarea></div><div class="form-field"><label>${t("servicePage.modal.contractor")}</label><select name="contractor"><option>ElectroBuild LLC</option><option>Aqua Systems LLC</option><option>Facade Pro Armenia</option><option>Climate Systems AM</option><option>Interior Works CJSC</option></select></div><div class="form-field"><label>${t("servicePage.modal.slaHours")}</label><input name="sla" type="number" value="48"></div><div class="form-field full"><label>${t("v52.service.beforeEvidence")}</label><select name="beforeEvidence"><option value="0">0</option><option value="1">1</option><option value="2">2</option><option value="3">3</option></select></div></form>`, `<button class="btn" data-modal-close>${t("servicePage.cancel")}</button><button class="btn btn-accent" id="saveWarranty">${t("servicePage.modal.create")}</button>`);
  setTimeout(() => document.querySelector("#saveWarranty")?.addEventListener("click", () => {const f = document.querySelector<HTMLFormElement>("#warrantyCreateForm")!;if (!f.reportValidity()) return;const c = clients.find(x => x.id === formValue(f, "clientId"))!,p = properties.find(x => x.id === formValue(f, "propertyId"))!,id = `WR-2026-${String(42 + warrantyCases.length).padStart(4, "0")}`,contractor=formValue(f,"contractor"),before=Number(formValue(f,"beforeEvidence")||0);warrantyCases.push({ id, clientId: c.id, clientName: c.name, propertyId: p.id, propertyLabel: `${p.project} · ${p.unit}`, category: formValue(f, "category"), title: formValue(f, "title"), description: formValue(f, "description"), priority: formValue(f, "priority") as any, status: "new", createdAt: "23.09.2026 · 09:14", dueAt: "24.09.2026 · 18:00", owner: "i18n:servicePage.owner.serviceTeam", contractor, channel: "manager", attachments: before, slaHours: Number(formValue(f, "sla")),beforeEvidence:before,afterEvidence:0,clientConfirmation:"pending",assignmentHistory:[],history:[{id:`WE-${Date.now()}`,at:"23.09.2026 · 09:14",actor:"Sales Manager",action:"created",note:"Гарантийное обращение зарегистрировано."}] });closeModal();toastLocalized(t("servicePage.toast.created"));navigate("warranty/" + id);}), 0);
}
