import {closeModal,formValue,openLocalizedModal,toastLocalized}from"../components/layout";
import {currentRoute,navigate}from"../router";
import {locale,t}from"../i18n";
import type{TaskCategory,TaskPriority,TaskStatus,WorkTask}from"../models/types";
import {addTask,deferTask,ensureTasksInitialized,escalateTask,getTask,reassignTask,setTaskReminder,setTaskStatus,TASK_REFERENCE_NOW,taskNow,taskOwnerForRole,tasks,taskStats}from"../services/tasks";
import{currentRole,platformRoles,roleLabelKey,type PlatformRole}from"../services/permissions";

const roles=[...platformRoles];
const currentUser=()=>taskOwnerForRole(currentRole());
const roleLabel=(role:string)=>{try{return t(roleLabelKey(role as PlatformRole))}catch{return role}};
const priorityLabel=(p:TaskPriority)=>t(`v48.priority.${p}`);
const statusLabel=(s:TaskStatus)=>t(`v48.status.${s}`);
const categoryLabel=(c:TaskCategory)=>t(`v48.category.${c}`);
const tabFromRoute=()=>currentRoute().match(/[?&]tab=([^&]+)/)?.[1]??"my";
const dt=(iso:string)=>new Intl.DateTimeFormat(locale(),{day:"2-digit",month:"2-digit",hour:"2-digit",minute:"2-digit"}).format(new Date(iso));
const dayLabel=(iso:string)=>new Intl.DateTimeFormat(locale(),{day:"2-digit",month:"short"}).format(new Date(iso));
const isClosed=(x:WorkTask)=>x.status==="done"||x.status==="cancelled";
const isOverdue=(x:WorkTask)=>!isClosed(x)&&new Date(x.dueAt).getTime()<taskNow().getTime();
const dueToday=(x:WorkTask)=>!isClosed(x)&&x.dueAt.slice(0,10)===TASK_REFERENCE_NOW.slice(0,10);
const isUpcoming=(x:WorkTask)=>!isClosed(x)&&new Date(x.dueAt).getTime()>new Date(TASK_REFERENCE_NOW.slice(0,10)+"T23:59:59").getTime();
const priorityRank:Record<TaskPriority,number>={critical:4,high:3,normal:2,low:1};
const statusRank:Record<TaskStatus,number>={"in-progress":1,open:2,waiting:3,done:4,cancelled:5};
function taskTone(x:WorkTask){return isOverdue(x)?"overdue":x.escalated?"escalated":x.status}
function slaText(x:WorkTask){if(isClosed(x))return t("v48.sla.closed");const diff=new Date(x.dueAt).getTime()-taskNow().getTime(),mins=Math.round(Math.abs(diff)/60000),h=Math.floor(mins/60),m=mins%60;if(diff<0)return t("v48.sla.overdueBy",{time:h?`${h}${t("v48.h.short")} ${m}${t("v48.m.short")}`:`${m}${t("v48.m.short")}`});if(mins<60)return t("v48.sla.left",{time:`${mins}${t("v48.m.short")}`});return t("v48.sla.left",{time:`${h}${t("v48.h.short")} ${m}${t("v48.m.short")}`})}

export function tasksPage(){ensureTasksInitialized();const tab=tabFromRoute(),stats=taskStats(),rows=filteredByTab(tab).sort((a,b)=>Number(isOverdue(b))-Number(isOverdue(a))||Number(b.escalated)-Number(a.escalated)||priorityRank[b.priority]-priorityRank[a.priority]||new Date(a.dueAt).getTime()-new Date(b.dueAt).getTime());
 return`<section class="page task-page">
  <div class="page-header"><div class="page-title"><div class="eyebrow">${t("v48.eyebrow")}</div><h1>${t("v48.title")}</h1><p>${t("v48.subtitle")}</p></div><div class="toolbar"><span class="task-role-chip"><small>${t("v48.workingAs")}</small><strong>${roleLabel(currentRole())}</strong></span><button class="btn" id="taskTeamLoad">${t("v48.teamCapacity")}</button><button class="btn btn-accent" id="newTask">+ ${t("v48.newTask")}</button></div></div>
  <div class="task-control-strip"><div><span>${t("v48.control.active")}</span><strong>${stats.active}</strong><small>${t("v48.control.activeNote")}</small></div><div class="warn"><span>${t("v48.control.today")}</span><strong>${stats.today}</strong><small>${t("v48.control.todayNote")}</small></div><div class="danger"><span>${t("v48.control.overdue")}</span><strong>${stats.overdue}</strong><small>${t("v48.control.overdueNote")}</small></div><div class="accent"><span>${t("v48.control.escalated")}</span><strong>${stats.escalated}</strong><small>${t("v48.control.escalatedNote")}</small></div></div>
  <div class="task-tabs" role="tablist">${tabButton("my",t("v48.tab.my"),tab,filteredByTab("my").length)}${tabButton("team",t("v48.tab.team"),tab,filteredByTab("team").length)}${tabButton("today",t("v48.tab.today"),tab,filteredByTab("today").length)}${tabButton("overdue",t("v48.tab.overdue"),tab,filteredByTab("overdue").length)}${tabButton("upcoming",t("v48.tab.upcoming"),tab,filteredByTab("upcoming").length)}${tabButton("escalated",t("v48.tab.escalated"),tab,filteredByTab("escalated").length)}</div>
  ${tab==="team"?teamView(rows):taskWorkView(rows,tab)}
 </section>`}
function tabButton(id:string,label:string,current:string,count:number){return`<button class="task-tab ${id===current?"active":""}" data-task-tab="${id}" role="tab" aria-selected="${id===current}"><span>${label}</span><b>${count}</b></button>`}
function filteredByTab(tab:string){const active=tasks.filter(x=>!isClosed(x));if(tab==="my")return active.filter(x=>x.assignedRole===currentRole());if(tab==="today")return active.filter(dueToday);if(tab==="overdue")return active.filter(isOverdue);if(tab==="upcoming")return active.filter(isUpcoming);if(tab==="escalated")return active.filter(x=>x.escalated);return active}
function taskWorkView(rows:WorkTask[],tab:string){return`<div class="task-workspace"><aside class="card card-pad task-filter-panel"><div class="section-title"><div><h2>${t("v48.filters")}</h2><p>${t("v48.filtersSub")}</p></div></div><label>${t("v48.search")}</label><input class="field" id="taskSearch" placeholder="${t("v48.searchPlaceholder")}"><label>${t("v48.filter.category")}</label><select class="field" id="taskCategory"><option value="">${t("v48.allCategories")}</option>${(["sales","approval","contract","payment","legal","registration","handover","service","mortgage","general"] as TaskCategory[]).map(c=>`<option value="${c}">${categoryLabel(c)}</option>`).join("")}</select><label>${t("v48.filter.priority")}</label><select class="field" id="taskPriority"><option value="">${t("v48.allPriorities")}</option>${(["critical","high","normal","low"] as TaskPriority[]).map(p=>`<option value="${p}">${priorityLabel(p)}</option>`).join("")}</select><label>${t("v48.filter.status")}</label><select class="field" id="taskStatus"><option value="">${t("v48.allStatuses")}</option>${(["open","in-progress","waiting"] as TaskStatus[]).map(s=>`<option value="${s}">${statusLabel(s)}</option>`).join("")}</select><div class="task-filter-callout"><b>${tab==="my"?filteredByTab("my").filter(isOverdue).length:rows.filter(isOverdue).length}</b><span>${t("v48.filter.focusText")}</span></div></aside><div class="task-list-panel"><div class="task-list-head"><div><span>${t("v48.list.showing")}</span><strong id="taskVisibleCount">${rows.length}</strong></div><div class="task-legend"><span><i class="dot overdue"></i>${t("v48.tab.overdue")}</span><span><i class="dot escalated"></i>${t("v48.tab.escalated")}</span><span><i class="dot today"></i>${t("v48.tab.today")}</span></div></div><div class="task-list" id="taskList">${rows.length?rows.map(taskCard).join(""):emptyState()}</div></div></div>`}
function taskCard(x:WorkTask){return`<article class="card work-task ${taskTone(x)}" data-task-card="${x.id}" data-category="${x.category}" data-priority="${x.priority}" data-status="${x.status}" data-search="${[x.title,x.description,x.clientName,x.dealId,x.sourceLabel,x.assignedTo].filter(Boolean).join(" ").toLowerCase()}"><button class="task-card-main" data-open-task="${x.id}"><span class="task-priority-bar ${x.priority}"></span><div class="task-card-copy"><div class="task-card-overline"><span class="task-category ${x.category}">${categoryLabel(x.category)}</span>${x.escalated?`<span class="task-escalation">↗ ${t("v48.escalation.level",{level:x.escalationLevel??1})}</span>`:""}<span>${x.id}</span></div><h3>${x.title}</h3><p>${x.description}</p><div class="task-context">${x.clientName?`<span>${t("v48.client")}: <b>${x.clientName}</b></span>`:""}${x.dealId?`<span>${t("v48.deal")}: <b>${x.dealId}</b></span>`:""}${x.propertyLabel?`<span>${t("v48.property")}: <b>${x.propertyLabel}</b></span>`:""}</div></div><div class="task-card-meta"><span class="task-state ${x.status}">${statusLabel(x.status)}</span><div><small>${t("v48.owner")}</small><strong>${x.assignedTo}</strong><em>${roleLabel(x.assignedRole)}</em></div><div class="task-due ${isOverdue(x)?"late":dueToday(x)?"today":""}"><small>${t("v48.deadline")}</small><strong>${dt(x.dueAt)}</strong><em>${slaText(x)}</em></div></div></button><div class="task-card-actions">${x.status==="open"?`<button class="btn btn-soft" data-task-start="${x.id}">${t("v48.action.start")}</button>`:""}${x.sourceRoute?`<button class="btn" data-task-source="${x.id}">${t("v48.action.openSource")}</button>`:""}<button class="btn" data-open-task="${x.id}">${t("v48.action.details")}</button></div></article>`}
function emptyState(){return`<div class="task-empty"><div>✓</div><h3>${t("v48.empty.title")}</h3><p>${t("v48.empty.text")}</p></div>`}

function teamView(rows:WorkTask[]){const active=rows.filter(x=>!isClosed(x)),groups=[...new Set(active.map(x=>`${x.assignedTo}|||${x.assignedRole}`))].map(key=>{const [name,role]=key.split("|||"),list=active.filter(x=>x.assignedTo===name&&x.assignedRole===role),over=list.filter(isOverdue).length,critical=list.filter(x=>x.priority==="critical").length;return{name,role,list,over,critical}}).sort((a,b)=>b.list.length-a.list.length);const max=Math.max(1,...groups.map(g=>g.list.length));return`<div class="team-workload-grid">${groups.map(g=>`<div class="card team-workload-card"><div class="team-person"><div class="task-avatar">${g.name.split(/\s+/).slice(0,2).map(v=>v[0]??"").join("")}</div><div><strong>${g.name}</strong><span>${roleLabel(g.role)}</span></div><b>${g.list.length}</b></div><div class="workload-meter"><span style="width:${Math.round(g.list.length/max*100)}%"></span></div><div class="team-load-stats"><span>${t("v48.team.open")} <b>${g.list.length}</b></span><span class="${g.over?"danger-text":""}">${t("v48.team.overdue")} <b>${g.over}</b></span><span>${t("v48.team.critical")} <b>${g.critical}</b></span></div><div class="team-task-preview">${g.list.slice(0,3).map(x=>`<button data-open-task="${x.id}"><i class="priority-mini ${x.priority}"></i><span><strong>${x.title}</strong><small>${dayLabel(x.dueAt)} · ${slaText(x)}</small></span></button>`).join("")}</div>${g.list.length>3?`<button class="link-button team-show-tasks" data-team-owner="${g.name}">${t("v48.team.more",{count:g.list.length-3})}</button>`:""}</div>`).join("")}</div>`}

function openTask(id:string){const x=getTask(id);if(!x)return;openLocalizedModal(`${x.id} · ${t("v48.task")}`,`<div class="task-detail"><div class="task-detail-hero"><div><div class="task-card-overline"><span class="task-category ${x.category}">${categoryLabel(x.category)}</span><span class="priority-label ${x.priority}">${priorityLabel(x.priority)}</span>${x.escalated?`<span class="task-escalation">↗ ${t("v48.escalation.level",{level:x.escalationLevel??1})}</span>`:""}</div><h3>${x.title}</h3><p>${x.description}</p></div><span class="task-state ${x.status}">${statusLabel(x.status)}</span></div><div class="task-detail-grid"><div><span>${t("v48.owner")}</span><strong>${x.assignedTo}</strong><small>${roleLabel(x.assignedRole)}</small></div><div><span>${t("v48.backup")}</span><strong>${x.backupOwner??"—"}</strong><small>${t("v48.backupNote")}</small></div><div><span>${t("v48.deadline")}</span><strong>${dt(x.dueAt)}</strong><small class="${isOverdue(x)?"danger-text":""}">${slaText(x)}</small></div><div><span>${t("v48.reminder")}</span><strong>${x.reminderAt?dt(x.reminderAt):t("v48.notSet")}</strong><small>${x.slaHours?`SLA ${x.slaHours}${t("v48.h.short")}`:"—"}</small></div></div>${x.sourceLabel?`<div class="task-source-box"><div><span>${t("v48.source")}</span><strong>${x.sourceLabel}</strong><small>${categoryLabel(x.category)}${x.dealId?` · ${x.dealId}`:""}</small></div>${x.sourceRoute?`<button class="btn" id="taskOpenSource">${t("v48.action.openSource")}</button>`:""}</div>`:""}<div class="task-history"><div class="section-title"><div><h3>${t("v48.history")}</h3><p>${t("v48.historySub")}</p></div></div>${x.history.map(h=>`<div class="task-history-row"><span class="task-history-mark ${h.action}"></span><div><strong>${actionLabel(h.action)}</strong><p>${h.note}</p><small>${dt(h.at)} · ${h.actor}</small></div></div>`).join("")}</div></div>`,`<button class="btn" data-modal-close>${t("common.cancel")}</button>${x.status==="open"?`<button class="btn" id="taskStart">${t("v48.action.start")}</button>`:""}<button class="btn" id="taskReassign">${t("v48.action.reassign")}</button><button class="btn" id="taskDefer">${t("v48.action.defer")}</button><button class="btn" id="taskReminder">${t("v48.action.reminder")}</button>${!x.escalated?`<button class="btn btn-danger-soft" id="taskEscalate">${t("v48.action.escalate")}</button>`:""}${!isClosed(x)?`<button class="btn btn-success" id="taskComplete">${t("v48.action.complete")}</button>`:""}`);setTimeout(()=>bindTaskModal(x),0)}
function actionLabel(action:string){return t(`v48.event.${action}`)}
function bindTaskModal(x:WorkTask){document.querySelector("#taskOpenSource")?.addEventListener("click",()=>{closeModal();if(x.sourceRoute)navigate(x.sourceRoute)});document.querySelector("#taskStart")?.addEventListener("click",()=>{setTaskStatus(x.id,"in-progress",currentUser(),t("v48.note.started"));closeModal();refresh()});document.querySelector("#taskComplete")?.addEventListener("click",()=>completeTask(x));document.querySelector("#taskReassign")?.addEventListener("click",()=>openReassign(x));document.querySelector("#taskDefer")?.addEventListener("click",()=>openDefer(x));document.querySelector("#taskReminder")?.addEventListener("click",()=>openReminder(x));document.querySelector("#taskEscalate")?.addEventListener("click",()=>openEscalate(x))}
function completeTask(x:WorkTask){openLocalizedModal(t("v48.complete.title"),`<form id="taskCompleteForm" class="form-grid"><div class="form-field full"><label>${t("v48.complete.result")}</label><textarea name="note" rows="4" required placeholder="${t("v48.complete.placeholder")}"></textarea></div></form>`,`<button class="btn" data-modal-close>${t("common.cancel")}</button><button class="btn btn-success" id="taskCompleteSave">${t("v48.action.complete")}</button>`);setTimeout(()=>document.querySelector("#taskCompleteSave")?.addEventListener("click",()=>{const f=document.querySelector<HTMLFormElement>("#taskCompleteForm")!;if(!f.reportValidity())return;setTaskStatus(x.id,"done",currentUser(),formValue(f,"note"));closeModal();toastLocalized(t("v48.toast.completed"));refresh()}),0)}
function openReassign(x:WorkTask){openLocalizedModal(t("v48.reassign.title"),`<form id="taskReassignForm" class="form-grid"><div class="form-field"><label>${t("v48.reassign.role")}</label><select name="role">${roles.map(r=>`<option value="${r}" ${x.assignedRole===r?"selected":""}>${roleLabel(r)}</option>`).join("")}</select></div><div class="form-field"><label>${t("v48.reassign.owner")}</label><input name="owner" value="${x.assignedTo}" required></div><div class="form-field"><label>${t("v48.backup")}</label><input name="backup" value="${x.backupOwner??""}"></div><div class="form-field full"><label>${t("v48.reassign.note")}</label><textarea name="note" rows="3" placeholder="${t("v48.reassign.placeholder")}"></textarea></div></form>`,`<button class="btn" data-modal-close>${t("common.cancel")}</button><button class="btn btn-accent" id="taskReassignSave">${t("v48.reassign.save")}</button>`);setTimeout(()=>{const role=document.querySelector<HTMLSelectElement>('#taskReassignForm [name="role"]'),owner=document.querySelector<HTMLInputElement>('#taskReassignForm [name="owner"]');role?.addEventListener("change",()=>{if(owner)owner.value=taskOwnerForRole(role.value)});document.querySelector("#taskReassignSave")?.addEventListener("click",()=>{const f=document.querySelector<HTMLFormElement>("#taskReassignForm")!;if(!f.reportValidity())return;reassignTask(x.id,formValue(f,"owner"),formValue(f,"role"),currentUser(),formValue(f,"note"),formValue(f,"backup"));closeModal();toastLocalized(t("v48.toast.reassigned"));refresh()})},0)}
function openDefer(x:WorkTask){openLocalizedModal(t("v48.defer.title"),`<form id="taskDeferForm" class="form-grid"><div class="form-field"><label>${t("v48.defer.deadline")}</label><input name="due" type="datetime-local" value="${x.dueAt.slice(0,16)}" required></div><div class="form-field full"><label>${t("v48.defer.reason")}</label><textarea name="note" rows="3" required placeholder="${t("v48.defer.placeholder")}"></textarea></div></form>`,`<button class="btn" data-modal-close>${t("common.cancel")}</button><button class="btn btn-accent" id="taskDeferSave">${t("v48.defer.save")}</button>`);setTimeout(()=>document.querySelector("#taskDeferSave")?.addEventListener("click",()=>{const f=document.querySelector<HTMLFormElement>("#taskDeferForm")!;if(!f.reportValidity())return;deferTask(x.id,formValue(f,"due")+":00",currentUser(),formValue(f,"note"));closeModal();toastLocalized(t("v48.toast.deferred"));refresh()}),0)}
function openReminder(x:WorkTask){openLocalizedModal(t("v48.reminder.title"),`<form id="taskReminderForm" class="form-grid"><div class="form-field full"><label>${t("v48.reminder.when")}</label><input name="when" type="datetime-local" value="${(x.reminderAt??x.dueAt).slice(0,16)}" required></div><div class="notice-box">${t("v48.reminder.help")}</div></form>`,`<button class="btn" data-modal-close>${t("common.cancel")}</button><button class="btn btn-accent" id="taskReminderSave">${t("v48.reminder.save")}</button>`);setTimeout(()=>document.querySelector("#taskReminderSave")?.addEventListener("click",()=>{const f=document.querySelector<HTMLFormElement>("#taskReminderForm")!;if(!f.reportValidity())return;setTaskReminder(x.id,formValue(f,"when")+":00",currentUser());closeModal();toastLocalized(t("v48.toast.reminder"));refresh()}),0)}
function openEscalate(x:WorkTask){openLocalizedModal(t("v48.escalate.title"),`<form id="taskEscalateForm" class="form-grid"><div class="notice-box danger full">${t("v48.escalate.help")}</div><div class="form-field full"><label>${t("v48.escalate.reason")}</label><textarea name="note" rows="3" required placeholder="${t("v48.escalate.placeholder")}"></textarea></div></form>`,`<button class="btn" data-modal-close>${t("common.cancel")}</button><button class="btn btn-danger" id="taskEscalateSave">${t("v48.action.escalate")}</button>`);setTimeout(()=>document.querySelector("#taskEscalateSave")?.addEventListener("click",()=>{const f=document.querySelector<HTMLFormElement>("#taskEscalateForm")!;if(!f.reportValidity())return;escalateTask(x.id,currentUser(),formValue(f,"note"));closeModal();toastLocalized(t("v48.toast.escalated"));refresh()}),0)}
function openNewTask(){openLocalizedModal(t("v48.new.title"),`<form id="newTaskForm" class="form-grid"><div class="form-field full"><label>${t("v48.new.subject")}</label><input name="title" required placeholder="${t("v48.new.subjectPlaceholder")}"></div><div class="form-field full"><label>${t("v48.new.description")}</label><textarea name="description" rows="3" required></textarea></div><div class="form-field"><label>${t("v48.filter.category")}</label><select name="category">${(["sales","contract","payment","legal","registration","handover","service","general"] as TaskCategory[]).map(c=>`<option value="${c}">${categoryLabel(c)}</option>`).join("")}</select></div><div class="form-field"><label>${t("v48.filter.priority")}</label><select name="priority"><option value="normal">${priorityLabel("normal")}</option><option value="high">${priorityLabel("high")}</option><option value="critical">${priorityLabel("critical")}</option><option value="low">${priorityLabel("low")}</option></select></div><div class="form-field"><label>${t("v48.reassign.role")}</label><select name="role">${roles.map(r=>`<option value="${r}" ${currentRole()===r?"selected":""}>${roleLabel(r)}</option>`).join("")}</select></div><div class="form-field"><label>${t("v48.reassign.owner")}</label><input name="owner" value="${currentUser()}" required></div><div class="form-field"><label>${t("v48.deadline")}</label><input name="due" type="datetime-local" value="2026-09-23T12:00" required></div><div class="form-field"><label>${t("v48.backup")}</label><input name="backup" placeholder="${t("v48.new.backupPlaceholder")}"></div></form>`,`<button class="btn" data-modal-close>${t("common.cancel")}</button><button class="btn btn-accent" id="newTaskSave">${t("v48.new.create")}</button>`);setTimeout(()=>{const role=document.querySelector<HTMLSelectElement>('#newTaskForm [name="role"]'),owner=document.querySelector<HTMLInputElement>('#newTaskForm [name="owner"]');role?.addEventListener("change",()=>{if(owner)owner.value=taskOwnerForRole(role.value)});document.querySelector("#newTaskSave")?.addEventListener("click",()=>{const f=document.querySelector<HTMLFormElement>("#newTaskForm")!;if(!f.reportValidity())return;addTask({title:formValue(f,"title"),description:formValue(f,"description"),category:formValue(f,"category") as TaskCategory,dueAt:formValue(f,"due")+":00",priority:formValue(f,"priority") as TaskPriority,assignedTo:formValue(f,"owner"),assignedRole:formValue(f,"role"),backupOwner:formValue(f,"backup")});closeModal();toastLocalized(t("v48.toast.created"));refresh()})},0)}
function openTeamCapacity(){const active=tasks.filter(x=>!isClosed(x)),byRole=roles.map(role=>({role,count:active.filter(x=>x.assignedRole===role).length,over:active.filter(x=>x.assignedRole===role&&isOverdue(x)).length})).filter(x=>x.count);openLocalizedModal(t("v48.capacity.title"),`<div class="capacity-list">${byRole.map(x=>`<div><span>${roleLabel(x.role)}</span><div class="capacity-bar"><i style="width:${Math.min(100,x.count*12)}%"></i></div><strong>${x.count}</strong><small class="${x.over?"danger-text":""}">${x.over?`${x.over} ${t("v48.team.overdue").toLowerCase()}`:t("v48.capacity.ok")}</small></div>`).join("")}</div>`)}
function filterCards(){const q=(document.querySelector<HTMLInputElement>("#taskSearch")?.value??"").trim().toLowerCase(),cat=document.querySelector<HTMLSelectElement>("#taskCategory")?.value??"",pr=document.querySelector<HTMLSelectElement>("#taskPriority")?.value??"",st=document.querySelector<HTMLSelectElement>("#taskStatus")?.value??"";let count=0;document.querySelectorAll<HTMLElement>("[data-task-card]").forEach(el=>{const show=(!q||(el.dataset.search??"").includes(q))&&(!cat||el.dataset.category===cat)&&(!pr||el.dataset.priority===pr)&&(!st||el.dataset.status===st);el.style.display=show?"":"none";if(show)count++});const n=document.querySelector<HTMLElement>("#taskVisibleCount");if(n)n.textContent=String(count)}
function refresh(){window.dispatchEvent(new HashChangeEvent("hashchange"))}
export function bindTasks(){document.querySelectorAll("[data-task-tab]").forEach(el=>el.addEventListener("click",()=>navigate(`tasks?tab=${(el as HTMLElement).dataset.taskTab}`)));document.querySelectorAll("[data-open-task]").forEach(el=>el.addEventListener("click",e=>{e.stopPropagation();openTask((el as HTMLElement).dataset.openTask!)}));document.querySelectorAll("[data-task-start]").forEach(el=>el.addEventListener("click",e=>{e.stopPropagation();const id=(el as HTMLElement).dataset.taskStart!;setTaskStatus(id,"in-progress",currentUser(),t("v48.note.started"));toastLocalized(t("v48.toast.started"));refresh()}));document.querySelectorAll("[data-task-source]").forEach(el=>el.addEventListener("click",e=>{e.stopPropagation();const x=getTask((el as HTMLElement).dataset.taskSource!);if(x?.sourceRoute)navigate(x.sourceRoute)}));["taskSearch","taskCategory","taskPriority","taskStatus"].forEach(id=>document.querySelector(`#${id}`)?.addEventListener(id==="taskSearch"?"input":"change",filterCards));document.querySelector("#newTask")?.addEventListener("click",openNewTask);document.querySelector("#taskTeamLoad")?.addEventListener("click",openTeamCapacity);document.querySelectorAll("[data-team-owner]").forEach(el=>el.addEventListener("click",()=>{const owner=(el as HTMLElement).dataset.teamOwner!;openLocalizedModal(owner,`<div class="task-mini-list">${tasks.filter(x=>!isClosed(x)&&x.assignedTo===owner).map(x=>`<button data-team-task="${x.id}"><span class="priority-mini ${x.priority}"></span><div><strong>${x.title}</strong><small>${dt(x.dueAt)} · ${slaText(x)}</small></div></button>`).join("")}</div>`);setTimeout(()=>document.querySelectorAll("[data-team-task]").forEach(btn=>btn.addEventListener("click",()=>{closeModal();openTask((btn as HTMLElement).dataset.teamTask!)})),0)}))}
