import { t } from "../i18n";
import { demoText } from "../demo-i18n";
import { warrantyCases } from "../data/mock";
import { badge, channelLabel, priorityLabel } from "../utils";
import { navigate } from "../router";
import { closeModal, formValue, openLocalizedModal, toastLocalized } from "../components/layout";
import { warrantyCategoryLabel } from "./service-i18n";
import { entityAuditPanel } from "../components/audit-panel";
import { recordAudit } from "../services/audit";

const serviceNow=new Date("2026-09-23T09:14:00+04:00");
const contractors=["ElectroBuild LLC","Aqua Systems LLC","Facade Pro Armenia","Climate Systems AM","Interior Works CJSC","Stone & Tile AM"];
function parseLegacy(v:string){const [date,time="23:59"]=v.split(" · ");const [d,m,y]=date.split(".");return new Date(`${y}-${m}-${d}T${time}:00`)}
function slaInfo(w:any){if(["resolved","closed"].includes(w.status))return{state:"done",hours:0,label:t("v52.service.sla.done")};const diff=parseLegacy(w.dueAt).getTime()-serviceNow.getTime(),hours=Math.ceil(Math.abs(diff)/3600000);if(diff<0)return{state:"overdue",hours,label:t("v52.service.sla.overdue",{count:hours})};if(diff<=12*3600000)return{state:"risk",hours,label:t("v52.service.sla.risk",{count:hours})};return{state:"ok",hours,label:t("v52.service.sla.remaining",{count:hours})}}

export function warrantyDetailPage(id: string) {
  const w = warrantyCases.find((x: any) => x.id === id);
  if (!w) return `<section class="page"><div class="card card-pad">${t("warrantyDetail.notFound")}</div></section>`;
  const sla=slaInfo(w),before=w.beforeEvidence??w.attachments??0,after=w.afterEvidence??0,confirmed=w.clientConfirmation==="confirmed";
  const canCompleteWork=["assigned","in-progress"].includes(w.status),canConfirm=w.status==="waiting-client",canRate=["resolved","closed"].includes(w.status)&&confirmed;
  return `<section class="page">
    <button class="btn btn-soft u-mb-16" id="backService">${t("warrantyDetail.back")}</button>
    <div class="detail-header"><div class="detail-title"><small>${w.id} · ${warrantyCategoryLabel(w.category)}</small><h1>${demoText(w.title)}</h1>${badge(w.status)} <span class="priority ${w.priority}">${priorityLabel(w.priority)}</span>${w.escalationLevel?` <span class="chip danger">${t("v52.warranty.escalationLevel",{count:w.escalationLevel})}</span>`:""}</div><div class="toolbar"><button class="btn" id="contactWarrantyClient">${t("warrantyDetail.contactClient")}</button><button class="btn btn-primary" id="updateWarranty">${t("v52.warranty.manage")}</button></div></div>

    <div class="grid grid-4 u-mb-16">
      ${metric(t("v52.warranty.kpi.sla"),sla.label,t("v52.warranty.kpi.slaNote"),sla.state)}
      ${metric(t("v52.warranty.kpi.evidence"),`${before}/${after}`,t("v52.warranty.kpi.evidenceNote"))}
      ${metric(t("v52.warranty.kpi.client"),w.clientConfirmation==="confirmed"?t("v52.acceptance.confirmed"):w.clientConfirmation==="declined"?t("v52.acceptance.declined"):t("v52.acceptance.pending"),t("v52.warranty.kpi.clientNote"),w.clientConfirmation==="declined"?"danger":confirmed?"success":"warning")}
      ${metric("CSAT",w.csat?`${w.csat}/5`:"—",w.csat?t("v52.warranty.kpi.csatDone"):t("v52.warranty.kpi.csatPending"),w.csat?"success":"")}
    </div>

    <div class="warranty-hero"><div class="card card-pad"><div class="section-title"><div><h2>${t("warrantyDetail.request.title")}</h2><p>${channelLabel(w.channel)} · ${demoText(w.createdAt)}</p></div><span class="v52-sla-pill ${sla.state}">${sla.label}</span></div><p class="case-description">${demoText(w.description)}</p><div class="info-list">
      <div class="info-box"><span>${t("warrantyDetail.client")}</span><strong>${w.clientName}</strong></div><div class="info-box"><span>${t("warrantyDetail.property")}</span><strong>${w.propertyLabel}</strong></div><div class="info-box"><span>${t("warrantyDetail.owner")}</span><strong>${demoText(w.owner)}</strong></div><div class="info-box"><span>${t("warrantyDetail.contractor")}</span><strong>${w.contractor}</strong></div><div class="info-box"><span>SLA</span><strong>${t("warrantyDetail.hours", { count: w.slaHours })}</strong></div><div class="info-box"><span>${t("warrantyDetail.deadline")}</span><strong>${w.dueAt}</strong></div>
    </div>${w.escalationReason?`<div class="v52-escalation-note"><strong>${t("v52.warranty.escalation")}</strong><p>${demoText(w.escalationReason)}</p><span>${w.escalatedAt??""}</span></div>`:""}</div>

    <div class="card card-pad"><div class="section-title"><div><h2>${t("v52.warranty.lifecycle")}</h2><p>${t("v52.warranty.lifecycleSub")}</p></div></div><div class="timeline">
      ${timeline(t("warrantyDetail.timeline.created"), demoText(w.createdAt), "done")}
      ${timeline(t("warrantyDetail.timeline.triage"), t("warrantyDetail.timeline.owner", { owner: demoText(w.owner) }), w.status==="new"?"current":"done")}
      ${timeline(t("warrantyDetail.timeline.contractorNotified"), w.contractor, ["assigned","in-progress","waiting-client","resolved","closed"].includes(w.status)?"done":"")}
      ${timeline(t("warrantyDetail.timeline.work"), w.resolutionNote?demoText(w.resolutionNote):t("warrantyDetail.timeline.currentStage"), ["assigned","in-progress"].includes(w.status)?"current":["waiting-client","resolved","closed"].includes(w.status)?"done":"")}
      ${timeline(t("warrantyDetail.timeline.clientConfirmation"), confirmed?`${w.clientConfirmedAt??""} · ${demoText(w.clientComment??"")}`:w.clientConfirmation==="declined"?t("v52.warranty.clientRejected"):t("warrantyDetail.timeline.waitAfterWork"), w.status==="waiting-client"?"current":confirmed?"done":"")}
      ${timeline(t("warrantyDetail.timeline.closeRating"), w.csat?`${"★".repeat(w.csat)}${"☆".repeat(5-w.csat)} · ${demoText(w.csatComment??"")}`:t("warrantyDetail.timeline.csatAfterClose"), w.status==="closed"?"done":w.status==="resolved"?"current":"")}
    </div></div></div>

    <div class="v52-warranty-grid u-mt-16">
      <div class="card card-pad"><div class="section-title"><div><span class="eyebrow">${t("v52.warranty.evidenceEyebrow")}</span><h2>${t("v52.warranty.evidenceTitle")}</h2><p>${t("v52.warranty.evidenceSub")}</p></div></div><div class="v52-before-after large"><button class="v52-evidence-box before" id="openBefore"><span>${t("v52.common.before")}</span><strong>${before}</strong><small>${t("v52.common.files")}</small></button><div class="evidence-arrow">→</div><button class="v52-evidence-box after" id="openAfter"><span>${t("v52.common.after")}</span><strong>${after}</strong><small>${after?t("v52.warranty.afterReady"):t("v52.warranty.afterMissing")}</small></button></div>${w.resolutionNote?`<div class="v52-resolution-note"><strong>${t("v52.warranty.workResult")}</strong><p>${demoText(w.resolutionNote)}</p></div>`:""}${canCompleteWork?`<button class="btn btn-primary u-mt-14" id="completeWarrantyWork">${t("v52.warranty.completeWork")}</button>`:""}</div>

      <div class="card card-pad"><div class="section-title"><div><span class="eyebrow">${t("v52.warranty.assignmentEyebrow")}</span><h2>${t("v52.warranty.assignmentTitle")}</h2><p>${t("v52.warranty.assignmentSub")}</p></div></div><div class="v52-assignment-current"><span>${t("warrantyDetail.contractor")}</span><strong>${w.contractor}</strong><small>${demoText(w.owner)}</small></div><div class="v52-assignment-history">${(w.assignmentHistory??[]).slice(0,3).map((a:any)=>`<div><i></i><p><strong>${a.from} → ${a.to}</strong><span>${a.at} · ${a.actor}</span><small>${demoText(a.note)}</small></p></div>`).join("")||`<div class="empty">${t("v52.warranty.noAssignments")}</div>`}</div><div class="toolbar u-mt-14"><button class="btn btn-soft" id="reassignWarranty">${t("v52.warranty.reassign")}</button><button class="btn btn-soft" id="escalateWarranty">${t("v52.warranty.escalate")}</button></div></div>
    </div>

    <div class="v52-warranty-grid u-mt-16">
      <div class="card card-pad"><div class="section-title"><div><span class="eyebrow">${t("v52.warranty.clientEyebrow")}</span><h2>${t("v52.warranty.clientTitle")}</h2><p>${t("v52.warranty.clientSub")}</p></div>${acceptanceBadge(w.clientConfirmation??"pending")}</div><div class="v52-client-confirmation"><div><span>${t("v52.warranty.notifiedAt")}</span><strong>${w.clientNotifiedAt??"—"}</strong></div><div><span>${t("v52.warranty.confirmedAt")}</span><strong>${w.clientConfirmedAt??"—"}</strong></div><div class="full"><span>${t("v52.handover.comment")}</span><strong>${demoText(w.clientComment??t("v52.common.notRecorded"))}</strong></div></div>${canConfirm?`<button class="btn btn-primary" id="confirmWarrantyClient">${t("v52.warranty.recordClientDecision")}</button>`:""}</div>
      <div class="card card-pad"><div class="section-title"><div><span class="eyebrow">CSAT</span><h2>${t("v52.warranty.csatTitle")}</h2><p>${t("v52.warranty.csatSub")}</p></div></div>${w.csat?`<div class="v52-csat-result"><strong>${w.csat}/5</strong><div>${"★".repeat(w.csat)}${"☆".repeat(5-w.csat)}</div><p>${demoText(w.csatComment??"")}</p></div>`:`<div class="v52-csat-empty"><span>☆</span><p>${t("v52.warranty.csatEmpty")}</p></div>`}${canRate&&w.status!=="closed"?`<button class="btn btn-primary" id="rateWarranty">${t("v52.warranty.rateClose")}</button>`:""}</div>
    </div>

    <div class="card card-pad u-mt-16"><div class="section-title"><div><h2>${t("v52.warranty.historyTitle")}</h2><p>${t("v52.warranty.historySub")}</p></div></div><div class="v52-service-history">${(w.history??[]).map((e:any)=>`<div class="v52-history-row"><div class="timeline-dot"></div><div><strong>${demoText(e.action)}</strong><span>${e.at} · ${e.actor}</span><p>${demoText(e.note)}</p></div></div>`).join("")}</div></div>

    <div class="card card-pad u-mt-16"><div class="section-title"><div><h2>${t("warrantyDetail.closeChecklist.title")}</h2><p>${t("warrantyDetail.closeChecklist.subtitle")}</p></div></div><div class="readiness-grid">
      ${check(t("warrantyDetail.closeChecklist.workDone"), ["waiting-client","resolved","closed"].includes(w.status))}
      ${check(t("warrantyDetail.closeChecklist.afterPhoto"), after>0)}
      ${check(t("warrantyDetail.closeChecklist.clientNotified"), Boolean(w.clientNotifiedAt))}
      ${check(t("warrantyDetail.closeChecklist.clientConfirmed"), confirmed)}
      ${check(t("v52.warranty.closeChecklist.csat"), Boolean(w.csat))}
    </div></div>
    ${entityAuditPanel("warranty",w.id)}
  </section>`;
}

function metric(label:string,value:string|number,note:string,cls=""){return `<div class="card metric-card ${cls}"><div class="metric-top"><span>${label}</span></div><div><div class="metric-value v52-metric-compact">${value}</div><div class="metric-note">${note}</div></div></div>`}
function timeline(title: string, subtitle: string, cls: string) {return `<div class="timeline-item ${cls}"><div class="timeline-dot"></div><div class="timeline-copy"><strong>${title}</strong><span>${subtitle}</span></div></div>`;}
function check(title: string, ok: boolean) {return `<div class="readiness-item ${ok ? "ok" : "wait"}"><div class="readiness-icon">${ok ? "✓" : "○"}</div><div><strong>${title}</strong><span>${ok ? t("warrantyDetail.confirmed") : t("warrantyDetail.pending")}</span></div></div>`;}
function acceptanceBadge(status:string){const cls=status==="confirmed"?"success":status==="declined"?"danger":"warning";return `<span class="chip ${cls}">${t(`v52.acceptance.${status}`)}</span>`}
function reloadWarranty(id: string) { navigate("service"); setTimeout(() => navigate("warranty/" + id), 20); }
function addHistory(w:any,action:string,note:string,actor="Սերվիս թիմ"){w.history=w.history??[];w.history.unshift({id:`WE-${Date.now()}-${Math.random().toString(36).slice(2,5)}`,at:"23.09.2026 · 09:14",actor,action,note});const critical=action==="escalated",warning=critical||action==="client-declined"||action==="reassigned";recordAudit({module:"service",action:critical?"status":"update",entityType:"warranty",entityId:w.id,entityLabel:`${w.id} · ${w.propertyLabel}`,route:`warranty/${w.id}`,field:"Service event",newValue:action,note,actor,actorRole:"Service",severity:critical?"critical":warning?"warning":"info"})}

export function bindWarrantyDetail() {
  const id = location.hash.split("?")[0].split("/").pop()!;
  document.querySelector("#backService")?.addEventListener("click", () => navigate("service"));
  document.querySelector("#contactWarrantyClient")?.addEventListener("click",()=>contactClient(id));
  document.querySelector("#updateWarranty")?.addEventListener("click",()=>manageWarranty(id));
  document.querySelector("#completeWarrantyWork")?.addEventListener("click",()=>completeWork(id));
  document.querySelector("#confirmWarrantyClient")?.addEventListener("click",()=>clientDecision(id));
  document.querySelector("#rateWarranty")?.addEventListener("click",()=>rateAndClose(id));
  document.querySelector("#reassignWarranty")?.addEventListener("click",()=>reassign(id));
  document.querySelector("#escalateWarranty")?.addEventListener("click",()=>escalate(id));
  document.querySelector("#openBefore")?.addEventListener("click",()=>evidenceGallery(id,"before"));
  document.querySelector("#openAfter")?.addEventListener("click",()=>evidenceGallery(id,"after"));
}

function contactClient(id:string){const w=warrantyCases.find((x:any)=>x.id===id);if(!w)return;openLocalizedModal(t("warrantyDetail.contact.title"), `<form id="warrantyContactForm" class="form-grid"><div class="form-field"><label>${t("warrantyDetail.contact.channel")}</label><select name="channel"><option>${t("warrantyDetail.contact.phone")}</option><option>${t("common.email")}</option><option>SMS</option></select></div><div class="form-field full"><label>${t("warrantyDetail.contact.comment")}</label><textarea name="note">${t("warrantyDetail.contact.defaultNote")}</textarea></div></form>`, `<button class="btn" data-modal-close>${t("warrantyDetail.cancel")}</button><button class="btn btn-accent" id="saveWarrantyContact">${t("warrantyDetail.contact.register")}</button>`);setTimeout(()=>document.querySelector("#saveWarrantyContact")?.addEventListener("click",()=>{const f=document.querySelector<HTMLFormElement>("#warrantyContactForm")!;w.clientNotifiedAt="23.09.2026 · 09:14";addHistory(w,"client-contact",formValue(f,"note"));closeModal();toastLocalized(t("warrantyDetail.toast.contactRegistered"));reloadWarranty(id)}),0)}

function manageWarranty(id:string){const w=warrantyCases.find((x:any)=>x.id===id);if(!w)return;openLocalizedModal(t("v52.warranty.manageTitle"),`<div class="v52-action-grid"><button class="entity-card" data-w-action="start"><span>${t("v52.warranty.action.startOverline")}</span><strong>${t("v52.warranty.action.start")}</strong><small>${t("v52.warranty.action.startNote")}</small></button><button class="entity-card" data-w-action="reassign"><span>${t("v52.warranty.assignmentEyebrow")}</span><strong>${t("v52.warranty.reassign")}</strong><small>${t("v52.warranty.assignmentSub")}</small></button><button class="entity-card" data-w-action="escalate"><span>SLA</span><strong>${t("v52.warranty.escalate")}</strong><small>${t("v52.warranty.escalateNote")}</small></button><button class="entity-card" data-w-action="complete"><span>${t("v52.warranty.evidenceEyebrow")}</span><strong>${t("v52.warranty.completeWork")}</strong><small>${t("v52.warranty.completeWorkNote")}</small></button></div>`);setTimeout(()=>document.querySelectorAll<HTMLElement>("[data-w-action]").forEach(el=>el.addEventListener("click",()=>{closeModal();const action=el.dataset.wAction;if(action==="start"){w.status="in-progress";addHistory(w,"work-started",t("v52.warranty.startedNote"));toastLocalized(t("v52.warranty.started"));reloadWarranty(id)}if(action==="reassign")reassign(id);if(action==="escalate")escalate(id);if(action==="complete")completeWork(id)})),0)}

function completeWork(id:string){const w=warrantyCases.find((x:any)=>x.id===id);if(!w)return;openLocalizedModal(t("v52.warranty.completeWork"),`<form id="completeWorkForm" class="form-grid"><div class="form-field full"><label>${t("v52.warranty.workResult")}</label><textarea name="note" required>${w.resolutionNote??""}</textarea></div><div class="form-field"><label>${t("v52.warranty.afterFiles")}</label><select name="files"><option value="1">1</option><option value="2" selected>2</option><option value="3">3</option><option value="4">4</option></select></div><div class="form-field"><label>${t("v52.warranty.notifyClient")}</label><select name="notify"><option value="yes">${t("v52.common.yes")}</option><option value="no">${t("v52.common.no")}</option></select></div></form>`,`<button class="btn" data-modal-close>${t("common.cancel")}</button><button class="btn btn-accent" id="saveWorkCompletion">${t("v52.warranty.markCompleted")}</button>`);setTimeout(()=>document.querySelector("#saveWorkCompletion")?.addEventListener("click",()=>{const f=document.querySelector<HTMLFormElement>("#completeWorkForm")!;if(!f.reportValidity())return;const add=Number(formValue(f,"files"));w.afterEvidence=(w.afterEvidence??0)+add;w.attachments=(w.beforeEvidence??0)+(w.afterEvidence??0);w.resolutionNote=formValue(f,"note");w.status="waiting-client";w.clientConfirmation="pending";if(formValue(f,"notify")==="yes")w.clientNotifiedAt="23.09.2026 · 09:14";addHistory(w,"work-completed",`${w.resolutionNote} · +${add} after evidence` ,w.contractor);closeModal();toastLocalized(t("v52.warranty.workCompleted"));reloadWarranty(id)}),0)}

function clientDecision(id:string){const w=warrantyCases.find((x:any)=>x.id===id);if(!w)return;openLocalizedModal(t("v52.warranty.clientDecisionTitle"),`<form id="clientDecisionForm" class="form-grid"><div class="form-field full"><label>${t("v52.handover.acceptanceDecision")}</label><select name="decision"><option value="confirmed">${t("v52.acceptance.confirmed")}</option><option value="declined">${t("v52.acceptance.declined")}</option></select></div><div class="form-field full"><label>${t("v52.handover.comment")}</label><textarea name="comment" required></textarea></div></form>`,`<button class="btn" data-modal-close>${t("common.cancel")}</button><button class="btn btn-accent" id="saveClientDecision">${t("common.save")}</button>`);setTimeout(()=>document.querySelector("#saveClientDecision")?.addEventListener("click",()=>{const f=document.querySelector<HTMLFormElement>("#clientDecisionForm")!;if(!f.reportValidity())return;const decision=formValue(f,"decision") as "confirmed"|"declined";w.clientConfirmation=decision;w.clientConfirmedAt="23.09.2026 · 09:14";w.clientComment=formValue(f,"comment");if(decision==="confirmed"){w.status="resolved";w.resolvedAt="23.09.2026 · 09:14";addHistory(w,"client-confirmed",w.clientComment,w.clientName)}else{w.status="in-progress";addHistory(w,"client-declined",w.clientComment,w.clientName)}closeModal();toastLocalized(decision==="confirmed"?t("v52.warranty.clientConfirmed"):t("v52.warranty.clientReturned"));reloadWarranty(id)}),0)}

function rateAndClose(id:string){const w=warrantyCases.find((x:any)=>x.id===id);if(!w)return;openLocalizedModal(t("v52.warranty.csatTitle"),`<form id="csatForm" class="form-grid"><div class="form-field full"><label>${t("v52.warranty.rating")}</label><select name="rating"><option value="5">★★★★★ · 5</option><option value="4">★★★★☆ · 4</option><option value="3">★★★☆☆ · 3</option><option value="2">★★☆☆☆ · 2</option><option value="1">★☆☆☆☆ · 1</option></select></div><div class="form-field full"><label>${t("v52.warranty.csatComment")}</label><textarea name="comment"></textarea></div></form>`,`<button class="btn" data-modal-close>${t("common.cancel")}</button><button class="btn btn-accent" id="saveCsat">${t("v52.warranty.closeCase")}</button>`);setTimeout(()=>document.querySelector("#saveCsat")?.addEventListener("click",()=>{const f=document.querySelector<HTMLFormElement>("#csatForm")!;w.csat=Number(formValue(f,"rating"));w.csatComment=formValue(f,"comment");w.status="closed";w.closedAt="23.09.2026 · 09:14";addHistory(w,"closed",`CSAT ${w.csat}/5${w.csatComment?` · ${w.csatComment}`:""}`);closeModal();toastLocalized(t("v52.warranty.closed"));reloadWarranty(id)}),0)}

function reassign(id:string){const w=warrantyCases.find((x:any)=>x.id===id);if(!w)return;openLocalizedModal(t("v52.warranty.reassign"),`<form id="reassignForm" class="form-grid"><div class="form-field full"><label>${t("warrantyDetail.contractor")}</label><select name="contractor">${contractors.map(x=>`<option ${x===w.contractor?"selected":""}>${x}</option>`).join("")}</select></div><div class="form-field"><label>${t("warrantyDetail.owner")}</label><input name="owner" value="${demoText(w.owner)}"></div><div class="form-field full"><label>${t("v52.warranty.reassignReason")}</label><textarea name="note" required></textarea></div></form>`,`<button class="btn" data-modal-close>${t("common.cancel")}</button><button class="btn btn-accent" id="saveReassign">${t("common.save")}</button>`);setTimeout(()=>document.querySelector("#saveReassign")?.addEventListener("click",()=>{const f=document.querySelector<HTMLFormElement>("#reassignForm")!;if(!f.reportValidity())return;const old=w.contractor,next=formValue(f,"contractor");w.contractor=next;w.owner=formValue(f,"owner");w.status="assigned";w.assignmentHistory=w.assignmentHistory??[];w.assignmentHistory.unshift({id:`WA-${Date.now()}`,at:"23.09.2026 · 09:14",actor:"Սերվիս թիմ",from:old,to:next,note:formValue(f,"note")});addHistory(w,"reassigned",`${old} → ${next} · ${formValue(f,"note")}`);closeModal();toastLocalized(t("v52.warranty.reassigned"));reloadWarranty(id)}),0)}

function escalate(id:string){const w=warrantyCases.find((x:any)=>x.id===id);if(!w)return;openLocalizedModal(t("v52.warranty.escalate"),`<form id="escalateForm" class="form-grid"><div class="form-field full"><label>${t("v52.warranty.escalateReason")}</label><textarea name="reason" required>${w.escalationReason??t("v52.warranty.defaultEscalation")}</textarea></div></form>`,`<button class="btn" data-modal-close>${t("common.cancel")}</button><button class="btn btn-accent" id="saveEscalation">${t("v52.warranty.escalate")}</button>`);setTimeout(()=>document.querySelector("#saveEscalation")?.addEventListener("click",()=>{const f=document.querySelector<HTMLFormElement>("#escalateForm")!;if(!f.reportValidity())return;w.escalationLevel=(w.escalationLevel??0)+1;w.escalatedAt="23.09.2026 · 09:14";w.escalationReason=formValue(f,"reason");w.priority=w.escalationLevel>=2?"urgent":"high";addHistory(w,"escalated",`L${w.escalationLevel} · ${w.escalationReason}`);closeModal();toastLocalized(t("v52.warranty.escalated",{count:w.escalationLevel}));reloadWarranty(id)}),0)}

function evidenceGallery(id:string,kind:"before"|"after"){const w=warrantyCases.find((x:any)=>x.id===id);if(!w)return;const count=kind==="before"?(w.beforeEvidence??0):(w.afterEvidence??0);openLocalizedModal(kind==="before"?t("v52.warranty.beforeGallery"):t("v52.warranty.afterGallery"),`<div class="media-gallery">${Array.from({length:count},(_,i)=>`<div class="media-tile ${kind}"><div class="media-preview"><span>${kind==="before"?t("v52.common.before"):t("v52.common.after")}</span><b>${w.propertyLabel}</b></div><strong>${demoText(w.title)}</strong><small>${t("v52.common.fileNumber",{count:i+1})}</small></div>`).join("")||`<div class="empty">${t("inspectionPage.noMedia")}</div>`}</div>`)}
