import"./styles/app.css";
import{layout,bindLayoutEvents,bindUiEnhancements,cleanupTransientUi}from"./components/layout";import{currentRoute}from"./router";import{loginPage,bindLogin}from"./pages/login";
import{adminRolesPage,bindAdminRoles}from"./pages/admin-roles";import{auditPage,bindAudit}from"./pages/audit";import{accessDeniedPage,bindAccessDenied}from"./pages/access-denied";import{canAccessRoute}from"./services/permissions";
import{dashboardPage,bindDashboard}from"./pages/dashboard";import{tasksPage,bindTasks}from"./pages/tasks";import{notificationsPage,bindNotifications}from"./pages/notifications";import{leadsPage,bindLeads}from"./pages/leads";import{leadDetailPage,bindLeadDetail}from"./pages/lead-detail";import{offerPage,bindOffer}from"./pages/offer";import{reservationPage,bindReservation}from"./pages/reservation";import{applicationPage,bindApplication}from"./pages/application";
import{clientsPage,bindClients}from"./pages/clients";import{contractTemplatesPage,bindContractTemplates}from"./pages/contract-templates";import{clientDetailPage,bindClientDetail}from"./pages/client-detail";import{propertiesPage,bindProperties}from"./pages/properties";import{propertyDetailPage,bindPropertyDetail}from"./pages/property-detail";import{dealsPage,bindDeals}from"./pages/deals";import{dealDetailPage,bindDealDetail}from"./pages/deal-detail";import{paymentsPage,bindPayments}from"./pages/payments";import{approvalsPage,bindApprovals}from"./pages/approvals";import{contractsPage,bindContracts}from"./pages/contracts";import{contractDetailPage,bindContractDetail}from"./pages/contract-detail";import{legalPage,bindLegal}from"./pages/legal";import{powerAttorneyPage,bindPowerAttorney}from"./pages/power-attorney";import{powerAttorneyDetailPage,bindPowerAttorneyDetail}from"./pages/power-attorney-detail";import{registrationPage,bindRegistration}from"./pages/registration";
import{ensureAuditInitialized}from"./services/audit";import{financePage,bindFinance}from"./pages/finance";import{financialSecuritiesPage,bindFinancialSecurities}from"./pages/financial-securities";import{ensureWorkflowInitialized}from"./services/workflow";import{ensureTasksInitialized}from"./services/tasks";import{ensureNotificationsInitialized}from"./services/notifications";import{mortgagesPage,bindMortgages}from"./pages/mortgages";import{mortgageDetailPage,bindMortgageDetail}from"./pages/mortgage-detail";import{reconciliationPage,bindReconciliation}from"./pages/reconciliation";import{restructurePage,bindRestructure}from"./pages/restructure";import{handoverPage,bindHandover}from"./pages/handover";import{handoverDetailPage,bindHandoverDetail}from"./pages/handover-detail";import{inspectionPage,bindInspection}from"./pages/inspection";import{servicePage,bindService}from"./pages/service";import{warrantyDetailPage,bindWarrantyDetail}from"./pages/warranty-detail";import{reportsPage,bindReports}from"./pages/reports";import{searchPage,bindSearch}from"./pages/search";import{priceListsPage,bindPriceLists}from"./pages/price-lists";
const app=document.querySelector<HTMLDivElement>("#app")!;
const isAuthenticated=()=>sessionStorage.getItem("estateflowAuthenticated")==="1";
export function renderApp(){
  if(!isAuthenticated()){cleanupTransientUi();app.innerHTML=loginPage();bindLogin(renderApp,renderApp);return}
  ensureWorkflowInitialized();ensureTasksInitialized();ensureNotificationsInitialized();ensureAuditInitialized();
  const route=currentRoute(),routePath=route.split("?")[0],[path,rest]=routePath.split("/");let page="",bind=()=>{};if(!canAccessRoute(route)){page=accessDeniedPage(route);bind=bindAccessDenied}else switch(path){
case"dashboard":page=dashboardPage();bind=bindDashboard;break;case"search":page=searchPage(route);bind=bindSearch;break;case"price-lists":page=priceListsPage();bind=bindPriceLists;break;case"leads":page=leadsPage();bind=bindLeads;break;case"lead":page=leadDetailPage(rest);bind=bindLeadDetail;break;case"offer":page=offerPage(rest);bind=bindOffer;break;case"reservation":page=reservationPage(rest);bind=bindReservation;break;case"application":page=applicationPage(rest);bind=bindApplication;break;
case"tasks":page=tasksPage();bind=bindTasks;break;case"notifications":page=notificationsPage();bind=bindNotifications;break;case"clients":page=clientsPage(route);bind=bindClients;break;case"client":page=clientDetailPage(rest);bind=bindClientDetail;break;case"properties":page=propertiesPage();bind=bindProperties;break;case"property":page=propertyDetailPage(rest);bind=bindPropertyDetail;break;case"deals":page=dealsPage();bind=bindDeals;break;case"deal":page=dealDetailPage(rest);bind=bindDealDetail;break;case"payments":page=paymentsPage();bind=bindPayments;break;case"approvals":page=approvalsPage();bind=bindApprovals;break;
case"contracts":page=contractsPage();bind=bindContracts;break;case"contract-templates":page=contractTemplatesPage();bind=bindContractTemplates;break;case"contract":page=contractDetailPage(rest);bind=bindContractDetail;break;case"legal":if(rest==="poa"){page=powerAttorneyPage();bind=bindPowerAttorney}else{page=legalPage();bind=bindLegal}break;case"poa":page=powerAttorneyDetailPage(rest);bind=bindPowerAttorneyDetail;break;case"registration":page=registrationPage(rest);bind=bindRegistration;break;
case"finance":page=financePage();bind=bindFinance;break;case"securities":page=financialSecuritiesPage();bind=bindFinancialSecurities;break;case"mortgages":page=mortgagesPage();bind=bindMortgages;break;case"mortgage":page=mortgageDetailPage(rest);bind=bindMortgageDetail;break;case"reconciliation":page=reconciliationPage();bind=bindReconciliation;break;case"restructure":page=restructurePage();bind=bindRestructure;break;
case"handover":page=handoverPage();bind=bindHandover;break;case"handover-case":page=handoverDetailPage(rest);bind=bindHandoverDetail;break;case"inspection":page=inspectionPage(rest);bind=bindInspection;break;case"service":page=servicePage();bind=bindService;break;case"warranty":page=warrantyDetailPage(rest);bind=bindWarrantyDetail;break;case"reports":page=reportsPage(route);bind=bindReports;break;case"audit":page=auditPage();bind=bindAudit;break;case"admin":page=adminRolesPage();bind=bindAdminRoles;break;default:page=dashboardPage();bind=bindDashboard}
  cleanupTransientUi();app.innerHTML=layout(page);bindLayoutEvents();bind();bindUiEnhancements()
}
window.addEventListener("hashchange",renderApp);if(!location.hash)location.hash="#/dashboard";renderApp();
